### ISSUE TITLE
Static pages accessibility in theme (inconsistency)

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10042]
With [dynamic routing](https://github.com/TryGhost/Ghost/issues/9601) you can do the following:

```
routes:
  /about/:
    data: page.about
```

A static page with the slug `about` exists and you want this page to live on `/about/`. 
You can access the data with `{{#page}}...{{/page}}` in your template. This is because Ghost automatically takes the resource type (=== page) as target template name.

**But** any other static route, which is not mapped in `routes`, needs to use `{{#post}}` in the template, this is because the rendering formatter always returns `{post: Object}`, [see](https://github.com/TryGhost/Ghost/blob/2.2.4/core/server/services/routing/helpers/format-response.js#L38).

This is a little inconsistent. IMO we should return `{page: Object}` if the resource is a page.
**But to avoid breaking themes**, we should return both keys if the resource is a page?

Needs confirmation from @ErisDS 👍

**Comment by ErisDS** [comment]
It's a bit weird and inconsistent, but not _really_. What was really weird was that by default pages were returned as posts :)

Need to review what the get helper does as well here - although for both the get helper and the data key you _have_ the option to override the name of the data key that's returned, i.e. these should both work:

```
{{get "pages" slug="about" as |post|}}
    {{#post}}...{{/post}}
{{/get}}
```

and

```
routes:
  /about/:
    data: 
      post: page.about
```

It's only the default data that you can't override, which is _currently_ post, but should be page? I think this is the one case where we possibly ought to start returning both, and using `{{page}}` by default.

What's the actual case you're referring to where we need to avoid breaking themes?

Note: We have a similar inconsistency around users/authors which we possibly also need to think about more.

**Comment by kirrg001** [comment]
> It's only the default data that you can't override, which is currently post, but should be page? I think this is the one case where we possibly ought to start returning both, and using {{page}} by default.

Yeah this is exactly what i mean to avoid breaking themes, because any `page.hbs` is using `{{#post}}` right now. I agree, we should return both keys and update our docs to use `{{#page}}` if this improvement was applied. We could even deprecate the usage of `{{#post}}` in `page.hbs`.

The only thing we have to double check is our context usages/comparisons e.g. [see body class helper](https://github.com/TryGhost/Ghost/blob/2.3.0/core/server/helpers/body_class.js#L17).

**Comment by kirrg001** [comment]
> Note: We have a similar inconsistency around users/authors which we possibly also need to think about more.

https://github.com/TryGhost/Ghost/issues/10061 takes care of this on the Content API level. 

We probably need another issue for the "inconsistency" on the routing level e.g. 

```
routes:
  /about/:
    data: user.tim
```

vs.

```
routes:
  /about/:
    data: author.tim
```

**Comment by ErisDS** [comment]
All issues tagged with `routing` have been tagged with `later` and closed until we prioritise working on the Routing feature again.

**Comment by JohnONolan** [comment]
Would like to re-open this because I tried to make a theme w/ dynamic routing this weekend and this utterly ruined me. Lost hours trying to figure it out

**Comment by JohnONolan** [comment]
not stale

**Comment by gnimmelf** [comment]
This is maybe a bit on the side, but I'd expect 
```
{{get "pages" as |post|}}
    {{#post}}...{{/post}}
{{/get}}
```
To work as well, even without the `slug` specified. I know the rationale is for pages to be out of any loop, but this is just limiting the imagination of developers.

Cheers!

**Comment by ErisDS** [comment]
@gnimmelf Please use the forum for support - you're missing a foreach loop.

**Comment by gnimmelf** [comment]
@ErisDS I was missing a lot. Somehow I traced it to `findOne`  in the codebase, and I clearly must have misread the documentation as well. Pages are loopable 💚 !

**Comment by gargol** [comment]
This issue came up while investigating the reason behind [missing page title bug](https://github.com/TryGhost/Ghost/issues/11357). The cause was a mislabeled v0.1 piece of code that didn't give enough context about it not being an API issue but rather frontend data format quirk. 

To avoid keeping legacy format like that around and finally get rid of it,  we could start from removing places in our internal code (metadata-layer, helpers) where we are using syntax like:
```
if (_.includes(context, 'page') && data.post) {
```

The goal would be to not have `post` property in page context at all in the internals. 

To have back compatibility with current themes where `{{#post}}` is used in `page` context we could modify the [formatter](https://github.com/TryGhost/Ghost/blob/3.0.1/core/frontend/services/routing/helpers/format-response.js#L47) to look something like this:
```javascript
// pass `type` available on `res.routerOptions.resourceType` to formatter and
// possibly later down to setTemplate?
function formatResponse(entry, type) {
    let singular = type.replace(/s$/i, '');
    let response = {
        post: entry
    };

    response[singular] = entry;

    return response;
}
```

To smooth out the change, we'd want to detect the use of `{{#post}}` by gscan to stop using this syntax in `page.hbs` files (might need to push forward [context-aware AST](https://github.com/TryGhost/gscan/pull/241) to have this check working properly in all situations)

This is just a quick braindump and would need some more context loading to spot more issues that might come out of such change, but in general, think it would be a good idea to get us closer to cleaner format by next major version :)

**Comment by sampumon** [comment]
I'm experiencing this inconsistency when setting up simple(?) multilang page routes. Example:

```
/en/about → page.about
/fi/about → page.tietoa
```

Then trying some routes…

```routes.yml
  /en/about/: page.about
```
  → error `template "page.about.hbs" not found` (but this is not supposed to work)

```routes.yml
  /en/about/:
    data: page.about
    template: post
```
  → rendered page has empty contents, because post.hbs has `{{#post}}`, not `{{#page}}`

```routes.yml
  /en/about/:
    data: page.about
    template: page
```
  → works but need to create page.hbs, which is copy of post.hbs but has `{{#page}}` instead of `{{#post}}`

```routes.yml
  /en/about/:
    data: 
      post: page.about
    template: post
```
  → works and this is what I'm using, but starts to get bit verbose for multiple routes… (and isn't documented on the main [routing reference](https://ghost.org/docs/api/v3/handlebars-themes/routing/routes/))

I wonder why `page` and `post` are internally different at all?
