### ISSUE TITLE
Building from source wrong documented also keeps failing 

### ISSUE THREAD

**Issue by msacar** [TryGhost/Ghost#10176]
I trying to build ghost from source

i followed steps https://docs.ghost.org/install/source/

```
git clone git@github.com:TryGhost/Ghost.git && cd Ghost
git remote rename origin upstream
git remote set-url upstream git@github.com:TryGhost/Ghost.git
git remote add origin git@github.com:<YourUsername>/Ghost.git

git submodule update --init

```
also did it same things for casper and admin

then i install yarn setup

[BABEL] ember-component-inbound-actions/helpers/send.js: Unknown option: /home/mstk/Desktop/.babelrc.presets

![screenshot from 2018-11-18 13-36-49](https://user-images.githubusercontent.com/22613730/48672647-a816b300-eb49-11e8-89ff-e182cbe5de04.png)

i guess this error caused from ghost-admin , but in the ghost-admin repository doesnt have issue  report area thats why i report here

**Comment by gargol** [comment]
@msacar the problem seems to be within the `ember-component-inbound-actions` and it's babel preset options. I'd suggest having a look into linked `Stack Trace and Error Report` log, that might provide more insight into what's causing the issue exactly. Would appreciate if you could post it here. Did you try building on a newer version of node?

**Comment by kevinansfield** [comment]
`ember-component-inbound-actions` doesn't have any specific babel presets so I think that may be leading you down the wrong path in that it just happens to be the first entry point that triggers an error.

@msacar does this file exist `/home/mstk/Desktop/.babelrc.presets`? If so can you try renaming it so that it doesn't get picked up by babel then re-running `yarn setup`?

**Comment by msacar** [comment]
i pulled master up to date and tried again  and then error gone :+1:
