### ISSUE TITLE
Cannot find partials

### ISSUE THREAD

**Issue by pkail** [TryGhost/Ghost#10170]
### Issue Summary
{{> header}} doesn't work, even after restart.  I have header.hbs in /partials/ directory.
I get error 500 The partial header could not be found.
I have tried files with multiple different types of content.  Nothing works.
Windows 10.  Node 10.13.0 Ghost 2.5.0 

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:

**Comment by allouis** [comment]
Hello @pkail :sun_with_face: 

I think you might have missed some information from our bug report template..

> To Reproduce

>    This is the first step
>    This is the second step, etc.

Could you help us help you, by including some more information? What theme is it, did you upload a new theme, or change it locally on the server etc...?

Just a list of steps you took to find this bug, would be really helpful!

Thanks :relaxed:

**Comment by pkail** [comment]
I'm not sure what else you need: I've mentioned the operating system and the versions of Node and Ghost.  As I said, I get the same error regardless of the contents of the handlebars file.  The handlebars file is in the /partials directory, which is a subdirectory of my theme name.

>>What theme is it, did you upload a new theme, or change it locally on the server etc...?
This is a theme I am writing myself.  The error comes either when I try to activate it in the Ghost control panel or when I try to access a page which uses it.

**Comment by notanengineercom** [comment]
Hey @pkail 
It would be helpful if you shared maybe a bit of the code. Just with OS and versions no one can really help you!

**Comment by allouis** [comment]
Hey sorry if I wasn't clear enough @pkail, what we're looking for is a way to easily reproduce this, or some more information so that we can help you fix this issue.

Maybe sharing some of the code as @notanengineercom says would be the most useful right now!

Locally I've created a `header.hbs` file in the partial directory and successfully imported it using both
`{{> header}}` and `{{> "header"}}` syntax.

Have you taken a look at [our docs for theme development](https://docs.ghost.org/api/handlebars-themes/)?  - They're really good, and they suggest using a tool we've created called [gscan](https://github.com/TryGhost/gscan) - theres an [online version](https://gscan.ghost.org) too! If you ran your theme through that, it could help diagnose the problem :crossed_fingers: 

Thanks for your patience [:fist_oncoming:](https://en.wikipedia.org/wiki/Fist_bump)

**Comment by kevinansfield** [comment]
Hey @pkail 👋 All community support is handled on [our forum](https://forum.ghost.org) rather than on Github so I would suggest moving this discussion there - if there's a genuine, reproducible bug found then we can re-open this or open a new issue with proper details of the problem.

When creating your forum topic I would suggest providing sufficient information for someone to be able to help you such as:
- full example code or a zip of a theme that is causing you problems
- how you installed Ghost
- details of the permissions of your theme directories/files
