### ISSUE TITLE
Pretty URL middleware should be more specific.

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10216]
Currently the pretty url middleware can do some pretty crazy things - when registering a static file router with `registerRouter` you will get `/file.ext/` which results in unexpected result - not good! It is also applied to the api urls, which means that when testing api locally, it's very easy to run into a redirect rather than the correct response.

We should update the middleware so that
- it does not apply to any path which looks like it has a file extension
- it doesn't mess with API urls? maybe?

AFAIK the _only_ urls it should be applied to are those that are rendered documents of the publication @JohnONolan can you confirm?

**Comment by ErisDS** [comment]
@allouis our URLs have _always_ forced trailing slashes absolutely everywhere, for consistency. This behaviour is deliberate and spec'd by John since day -100.

> when registering a static file router with registerRouter you will get /file.ext/ which results in unexpected result 

When registering a static file router that you don't want to fallback to trailing, the fallback false option should be specified.

There is already an open issue here: https://github.com/TryGhost/Ghost/issues/8868 to fix some of the remaining places where fallbacks aren't used correctly. It might be useful to look at automatically not-falling-back for extensions and to add that to that issue.

IMO changing the API is something that should only be done with strong ref material.

**Comment by allouis** [comment]
> @allouis our URLs have always forced trailing slashes absolutely everywhere, for consistency. This behaviour is deliberate and spec'd by John since day -100.

Ah okay - I didn't realise it was necessary/specced outside of the actual pages like the api for example. 

> When registering a static file router that you don't want to fallback to trailing, the fallback false option should be specified.

So this is fine if the router _only_ has static files on it, but then you would lose the pretty urls for other stuff - I still think it would be useful for the middleware to not redirect if this url ends with `something.ext` - happy to close this if you think neither case is relevant tho

**Comment by JohnONolan** [comment]
Very in favour of trailing slashes on pages/routes

I have seen/tripped over trailing slashes on resources 100000x and would love to see that die. It's very safe to spot a handful of extensions and never add a slash to then, like images, css, and svg in particular

I have no strong opinion on how this applies to API routes

**Comment by kirrg001** [comment]
@allouis I'd suggest closing this issue, as mentioned, it's covered in #8868. Feel free to extend the issue or leave a comment?

> it doesn't mess with API urls? maybe?

I have not understood from this issue what the problem with API urls and traiing slahes is.

> IMO changing the API is something that should only be done with strong ref material.

Agree.
