### ISSUE TITLE
Content API returns `page` when `fields` query param is used

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#10351]
When making a request to the `/posts/:id` or `/pages/:id` endpoint and you request specific fields, e.g. `title` you will also get back the `page` boolean.

### To replicate
  - start ghost
  - create an integration
  - copy content key
  - curl http://localhost:2368/ghost/api/v2/posts/?key=$key | jq .posts[0].id
  - copy the id
  - curl "http://localhost:2368/ghost/api/v2/posts/$id/?key=$key&fields=title"  | jq .

### Desired behaviour

The `page` param should not be sent back!

**Comment by rishabhgrg** [comment]
The root cause was logic in input serializers which we were using to filter out `page` and `post` results in respective APIs. 

While the `browse` endpoints were correctly using `filter` property on `page` field in options to filter out page/post results, the `read` endpoints were setup differently to achieve the same result by passing `page` field as data option to query-
`frame.data.page = true/false`

Passing `page` as data field to model query was bypassing `fields` array passed in options, and query returned all results along with `page` field in response. 

*Fix*: Updating `read` endpoints to correctly use the same `filter` logic for `page`

**Comment by rishabhgrg** [comment]
Update: I overlooked the fact that `read` endpoints _can't_ use `filter` property as its not a valid bookshelf option for `fetch` calls which is used for `read`. 🙈So to filter out data based on `page` property, we will need to pass it as a data attribute, and data attributes are set by `forge` [call](https://bookshelfjs.org/api.html#Model-static-forge) as initial values on model and don't seem to be filtered by `columns` option.

Alternate fix is to update v2 output serializers to filter out extra properties from model if `columns` is set in the call.
