### ISSUE TITLE
Post URL is returning 404 after publishing

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10356]
### Issue Summary

The issue occurs after publishing a post. After clicking on "Published! *View post*" link it leads to 404 page.

### To Reproduce

1. Create a post
2. Publish the post
3. Click on the link in 'Published' popup in down left corner
4. Link opens a page with 404

Clicking on the link should lead to published post instead. 

Additionally the response that comes back from the server when publishing a post contains a field with wrong URL:
```
url: "http://ghost.local/404/"
```

### Technical details:

* Ghost Version: 2.10.1
* Node Version: 8.11.4
* Browser/OS: Chrome 71 / Ubuntu 18.04
* Database: MySQL 5.7.24

**Comment by gargol** [comment]
The issue has been prioritized and is being worked on asap.

**Comment by kirrg001** [comment]
The underlying problem:

1. PUT request to publish a post comes in
2. on saving method in model is being executed
3. on saving triggers Ghost events
  3.1. saving of the post finishes and the response is handed back (without finding url in url cache)
  3.2. url service repopulates the cache with new values
4. at this point 3.1 is done as we don't have anything listening to url cache updates. ideally we'd want to be notified or be sure that 3.2 is finished before 3.1

**Comment by pascalandy** [comment]
Hi, with this bug, should we wait before upgrading to 2.10.1? I think we should. If so here is my question:

Is there an official communication channel to let people know about the fact we should wait before upgrading to X version?

Thanks!

**Comment by kevinansfield** [comment]
@pascalandy the only practical problem arising from this bug is that the "View post" link in the "Published post" popup in the bottom left of the screen after publishing points at a 404. There are only a few milliseconds where an API request for a recently published post could have the wrong `url` field and it doesn't affect the front-end at all so the issue is not considered critical but is high-priority.

Whether you upgrade or not is up to you. If we discover a truly critical bug then a followup release will usually be made very quickly and the release notes will call out any problematic versions.

**Comment by gargol** [comment]
Closed via https://github.com/TryGhost/Ghost/pull/10361

**Comment by pascalandy** [comment]
Thank for the answer, this is where it was not clear not me:

> so the issue is not considered critical but is high-priority.

**Comment by bershatsky** [comment]
I too have this issue.

**Comment by bershatsky** [comment]
If you hit publish a second time, it goes away.

**Comment by smorele** [comment]
Hi,
I'm still having this bug with this configuration:
```
Debug Information:
    OS: Mac OS X, v10.14.4
    Node Version: v10.15.2
    Ghost-CLI Version: 1.9.9
    Environment: production
```

After publishing my page, I can find it in blog post but when trying to access it, it returns a 404.
From the blog list, the url is: `http://localhost:2368/p/f3e44130-b8cb-45fa-b90d-0d4e38e7515f/` instead of `http://localhost:2368/test-de-post`

Any idea ?

**Comment by jesobreira** [comment]
I still had this issue after deleting a tag. All the posts containing such tag (although never as primary and never alone) had their links set to /404.

Republishing a second time didn't help. Republishing after removing every tag and adding again also didn't. What worked was:

1. Open the post in the editor
2. Remove every tag
3. Publish. The link remains /404.
4. Re-add the tags.
5. Publish. Now the link works.

**Comment by JAKAMI99** [comment]
I have this exact issue after messing around with tags :/

**Comment by Sheepeer** [comment]
Met this issue with ghost5.22 too. I think  this is related to nginx, because the issue only occurs when deploying with nginx. But I have no idea how to fix this :(

**Comment by Sheepeer** [comment]
are U using k8s to deploy ghost and created several pods?

**Comment by sronald01** [comment]
The issue still persists

**Comment by naz** [comment]
@sronald01 yes it does.
