### ISSUE TITLE
Bug with `prev_post` and `next_post` helpers

### ISSUE THREAD

**Issue by zce** [TryGhost/Ghost#10389]
### Issue Summary

`prev_post` and `next_post` helpers not working

![image](https://user-images.githubusercontent.com/6166576/51292940-94070900-1a47-11e9-9ea5-00d8d855f4d8.png)

> - https://github.com/TryGhost/Ghost/commit/5548bbb2c - Removed post.status from Content API v2 response
> - https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/prev_next.js#L90 - Use `post.status`

### Technical details:

* Ghost Version: 2.11.1

**Comment by kirrg001** [comment]
Hey 👋

Thanks for the report. You found a bug 🕵🏽‍♂️

---

After we have removed `post.status`, we discovered some problems. One of the problem was `this.status` in the [prev_next](https://github.com/TryGhost/Ghost/blob/2.11.1/core/server/helpers/prev_next.js#L90) helper, which was mentioned [here](https://github.com/TryGhost/Ghost/issues/10335#issuecomment-451653233).

Content API V2 no longer returns the status. We have to extract the fix for it out of https://github.com/TryGhost/Ghost/pull/10338 or solve it differently for now.

**Comment by kirrg001** [comment]
We will fix this bug on Monday and ship it on Tuesday morning 🙂
