### ISSUE TITLE
[Regression] OG and Twitter description uses wrong order

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#10387]
1 - `manifest.json` (For Push Notifications) not loading gives `HTTP/1.1 422 Unprocessable Entity` and In Error page, it has shown `422 Validation (isSlug) failed for slug` Me add the Header tag via Code Injection ` <link rel="manifest" href="/manifest.json">`
2 - Casper theme Related post and Next and Previous Post is not Working in APIv2
3 - Meta OG description fetch the description from the post content previously I add the description on SEO Meta Boxes it fetches the same one for OG description too  

How to Get the Public API Key for v2?

I `Rollback` to the Previous version everything working fine

### Technical details:

* Ghost Version: 2.11.0
* Node Version: v6.16.0

**Comment by allouis** [comment]
Hey @mskian!

1. Could you describe more about where your manifest.json is located? and give some steps for replication?

2. This is being tracked here https://github.com/TryGhost/Ghost/issues/10389 :)

3. I really didn't understand this, could you please include some more information for replication, preferably step-by-step :relaxed:

Thanks!

**Comment by mskian** [comment]
1 - `manifest.json` file returns `422 Validation (isSlug) failed for slug` (HTTP/1.1 422 Unprocessable Entity)
2 - `og:description` and `twitter:description` not updated it was taken from post content previously I add the description on SEO Meta Boxes it fetches the same one for Social `OG` description too

**Comment by mskian** [comment]
@ErisDS I add Manifest File for Push Notification

**Comment by mskian** [comment]
@ErisDS  og:description and twitter:description not updated it was taken from Post content previously I add the Custom description on SEO Meta Boxes it fetches the same one for Social OG description too

**Comment by AileenCGN** [comment]
I was able to reproduce and understand the issue that is described here, due to the latest forum post [here](https://forum.ghost.org/t/social-meta-description-issue/5230/4)

This is indeed a regression bug, due to the `excerpt` property which messes the conditional up that determines the og and twitter description [here](https://github.com/tryghost/ghost/blob/30a0b1794a565263d0de9399c300b3fcde23b0b7/core/server/data/meta/index.js#L88-L89). `post.excerpt` was not populated by default before, so that conditional made sense. It's now *always* populated (when v2 is used) and makes the next conditional redundant: 

https://github.com/tryghost/ghost/blob/30a0b1794a565263d0de9399c300b3fcde23b0b7/core/server/data/meta/index.js#L92-L93

To visualise:

![image](https://user-images.githubusercontent.com/8037602/52331137-f1c8b880-2a29-11e9-8179-b34920b2384b.png)
☝️ v.2.13.0

![image](https://user-images.githubusercontent.com/8037602/52331153-02792e80-2a2a-11e9-9f2c-2570f620602d.png)
☝️ v2.5.0
