### ISSUE TITLE
Issue with {{get}} and `filter` for pages

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#10390]
### Issue Summary

Issue in rendering pages with API v2 using {{get}} and filtering.
___
I'm using this in my theme to get posts and pages marked as "featured":

{{#get "posts" filter="featured:true+page:[true,false]" include="authors,tags"}}

For API v0.1 everything works fine. For API v2 it return only posts. 
After changing to "featured:true,page:true" works fine, but it looks incorrect.

### Technical details:

* Ghost Version: 2.11.1
* Node Version: 8.12.0
* Browser/OS: Safari / macOS 10.14.2
* Database: SQLite

**Comment by gargol** [comment]
Hey :wave: @fueko! With API v2 we separated `posts` and  `pages` resources into 2 different endpoints, so you should [only be able](https://github.com/TryGhost/Ghost/blob/master/core/server/api/v2/utils/serializers/input/pages.js#L29-L41) to fetch posts with `{{#get "posts"}}` and pages with `{{#get pages}}`.

The filter `featured:true,page:true` is a hacky workaround and is considered a bug :smiley: I will be working on fixing it, so please don't rely on this filter and refactor your theme to use separate `get` helpers for each kind of resource :smiley:

**Comment by gargol** [comment]
@fueko the fix for this bug has landed in master and will be released tomorrow :smiley:  

As for combined `{{#get "posts,pages"}}` helper, we don't support such grouping at the moment but this use case could definitely be raised on our [forum](https://forum.ghost.org/) to discuss possible solutions.

To merge posts and pages you would need to nest {{#get}} helpers inside of each other and then merge them together probably using a custom helper. Would reach out on the forum, maybe somebody has solved this specific problem already :wink:

**Comment by fueko** [comment]
I understand. It is a great pity that there is no production alternative for: "featured:true+page:[true,false]" it was a great feature. Thank you for your help!
