### ISSUE TITLE
Trailing Slash for JSON files in Asset Directories

### ISSUE THREAD

**Issue by whyelse** [TryGhost/Ghost#10439]
### Issue Summary

I'm trying to set up Bodymovin and Lottie for website animation. As part of this software a json file is needed to be loaded. Unfortunately this is being 301 redirected to a trailing slash by ghost producing a 404 error. 

Mac OS 10.14.3
Chrome 71.0.3578.98
Safari 12.0.3

### To Reproduce

1. Add a json file under /assets/ in your theme
Upload and activate the theme and try to access the file under that directory.

### Technical details:

* Ghost Version: 2.13.1
* Node Version: 10.14.1
* Browser/OS: Chrome/Mac
* Database: MYSQL

**Comment by kevinansfield** [comment]
The trailing-slash redirect is because the asset isn't found then Ghost auto-redirects to to a trailing-slash url as that's required for all page and API requests.

As for why the asset isn't found, the `.json` filetype is [explicitly blacklisted](https://github.com/TryGhost/Ghost/blob/master/core/server/web/shared/middlewares/static-theme.js#L8) in the static file middleware for security. I would suggest uploading the file to an external host or in an area of your server that is served directly by the web/proxy server.
