### ISSUE TITLE
Unable to filter Stories in admin by a single-letter tag

### ISSUE THREAD

**Issue by justmarkham** [TryGhost/Ghost#10469]
### Issue Summary

On the Stories page of admin, I'm unable to filter by the tag "R".

### To Reproduce

1. Open my admin and click on Stories.
2. Click on the "all tags" dropdown.
3. Click on the tag "R".
4. The top of the page says "The request failed validation" and the error code is 422.

The problem only occurs for that tag, so I'm guessing it's because the tag is a single letter. That is a valid tag, as you can see [here](https://www.dataschool.io/tag/r/).

I have not tested creating other single letter tags to see if they also cause errors when filtering.

### Technical details:

* Ghost Version: 2.6.0
* Browser/OS: Chrome on Mac

I'm a Ghost Pro customer.

**Comment by gargol** [comment]
Hey :wave: @justmarkham! Thanks for reporting. This bug is caused by a filtering language and is being tracked here - https://github.com/NexesJS/NQL-Lang/issues/2 . For now, the workaround would be changing the tag 'URL' in tags editing screen to something that contains more than one letter e.g.: `r_` :+1:
