### ISSUE TITLE
Cannot read property match of undefined

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10496]
This is a known error message. It occurs when you mis-use something.

Every time I see this report somewhere, people have no idea what to do.

e.g. Forum: https://forum.ghost.org/t/static-home-page-routes-yaml-formatting-error/5649/6

I'd like to figure out if there is a way to catch this error and return a human-readable error message with hints what to do (and docs link).

Steps to reproduce:

- put {{asset css/styles.min.css}} into your theme

Ghost: master

**Comment by kirrg001** [comment]
Is that error only thrown if you misuse the asset helper? 🤔

**Comment by vikaspotluri123** [comment]
I don't think the root cause of this is the asset helper because the `page.hbs` template which was supposed to be cloned + changed doesn't contain the asset helper. I asked for the contents of the `homepage.hbs` helper so we can hopefully figure out what happened 😄

**Comment by MaluNoPeleke** [comment]
I updated from 2.11 to 2.14.3 and got this error as well:

```
@400000005c6d115c19072484 [2019-02-20 08:35:30] [31mERROR[39m
@400000005c6d115c19072c54 [31m
@400000005c6d115c19072c54 [31mNAME: InternalServerError[39m
@400000005c6d115c1907303c [31mMESSAGE: Cannot read property 'close' of undefined[39m
@400000005c6d115c19073424 
@400000005c6d115c1907380c [37mlevel:[39m[37mnormal[39m
@400000005c6d115c19073bf4 
@400000005c6d115c19073bf4 [37mInternalServerError: Cannot read property 'close' of undefined
@400000005c6d115c19073fdc     at new GhostError (/home/peleke/node_apps/ghost/core/server/lib/common/errors.js:10:26)
@400000005c6d115c1907a56c     at server.catch (/home/peleke/node_apps/ghost/core/index.js:16:23)
@400000005c6d115c1907a954     at tryCatcher (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/util.js:16:23)
@400000005c6d115c1907ad3c     at Promise._settlePromiseFromHandler (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/promise.js:512:31)
@400000005c6d115c1907b124     at Promise._settlePromise (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/promise.js:569:18)
@400000005c6d115c1907c4ac     at Promise._settlePromise0 (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/promise.js:614:10)
@400000005c6d115c1907c894     at Promise._settlePromises (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/promise.js:690:18)
@400000005c6d115c1907d064     at _drainQueueStep (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/async.js:138:12)
@400000005c6d115c190812cc     at _drainQueue (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/async.js:131:9)
@400000005c6d115c190816b4     at Async._drainQueues (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/async.js:147:5)
@400000005c6d115c19081a9c     at Immediate.Async.drainQueues [as _onImmediate] (/home/peleke/node_apps/ghost/node_modules/bluebird/js/release/async.js:17:14)
@400000005c6d115c19082e24     at runCallback (timers.js:696:18)
@400000005c6d115c19082e24     at tryOnImmediate (timers.js:667:5)
@400000005c6d115c1908320c     at processImmediate (timers.js:649:5)
@400000005c6d115c190835f4 
@400000005c6d115c190839dc TypeError: Cannot read property 'close' of undefined
@400000005c6d115c19083dc4     at Object.<anonymous> (/home/peleke/node_apps/ghost/node_modules/chalk/index.js:72:75)
@400000005c6d115c19084d64     at Module._compile (internal/modules/cjs/loader.js:689:30)
@400000005c6d115c1908514c     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
@400000005c6d115c19085534     at Module.load (internal/modules/cjs/loader.js:599:32)
@400000005c6d115c1908591c     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
@400000005c6d115c19085d04     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
@400000005c6d115c19086ca4     at Module.require (internal/modules/cjs/loader.js:637:17)
@400000005c6d115c19088be4     at require (internal/modules/cjs/helpers.js:20:18)
@400000005c6d115c19088fcc     at Object.<anonymous> (/home/peleke/node_apps/ghost/core/server/lib/common/i18n.js:4:13)
@400000005c6d115c190893b4     at Module._compile (internal/modules/cjs/loader.js:689:30)
@400000005c6d115c1908979c     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
@400000005c6d115c19089b84     at Module.load (internal/modules/cjs/loader.js:599:32)
@400000005c6d115c1908ab24     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
@400000005c6d115c1908af0c     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
@400000005c6d115c1908b2f4     at Module.require (internal/modules/cjs/loader.js:637:17)
@400000005c6d115c1908b6dc     at require (internal/modules/cjs/helpers.js:20:18)[39m
@400000005c6d115c1908bac4 [39m
```

**Comment by kirrg001** [comment]
@MaluNoPeleke This is a different error message. Looks like a bug in chalk or dependencies were not installed correctly. I'd suggest to ask for help in the forum.

**Comment by MaluNoPeleke** [comment]
Okay, done: https://forum.ghost.org/t/cannot-read-property-close-of-undefined/5779

**Comment by gargol** [comment]
Not stale

**Comment by ErisDS** [comment]
A very similar bug happens with `Cannot read property 'includeZero' of undefined`

It's documented on a Ghost blog! https://peterdaugaardrasmussen.com/2018/03/11/ghostblog-cannot-read-property-includezero-of-undefined/

I've noticed it a few times in our logs.

**Comment by gargol** [comment]
@ErisDS had a look at the errors you have mentioned. Have the following findings:

1. `IncludeZero` error happens when following handlebars syntax is used:
```handlebars
{{#if anything_goes_here 1}}
```
2. `Cannot read property 'hash' of undefined` happens for the following:
```handlebars
{{#if anything_goes_here undefined}}
```
3. `Cannot read property 'hash' of null` happens for the following:
```handlebars
{{#if anything_goes_here null}}
```

On a tangent to the `{{if}}` helper, similar error messages are being thrown by `{{unless}}` helper, e.g.: `Cannot read property 'inverse' of undefined` when using following way
```handlebars
{{#unless anything_goes_here undefined}}
```

Think the issues above are plain misuse of built-in handlebars helpers and as they expect [specific value](https://github.com/wycats/handlebars.js/blob/148b19182d70278237a62d8293db540483a0c46c/lib/handlebars/helpers/if.js#L10) in options. 

Was thinking if there's something we can do to improve current messaging and give more details about where it happens but there's not much in the [context](https://github.com/barc/express-hbs/blob/067dd6d/lib/hbs.js#L492) to add anything but the template file we already show.

When we use `options` object in Ghost custom helpers we usually have safety checks like the [following](https://github.com/TryGhost/Ghost/blob/b0efad7/core/frontend/helpers/img_url.js#L68):
```
const absoluteOption = options && options.hash && options.hash.absolute;
```
which prevents us from throwing like handlebars built in ones do.

I see a couple of possible ways to go about this error to become a little more helpful:
1. Check error stack in Ghost with something like `err.stack.includes('/helpers/if.js')` and add a hint about `"possible {{if}} helper misuse"`. The downside is this error handling becomes dependent on handlebars folder structure :grimacing:
2. Add additional checks for {{if}} usage in gscan based on [AST linter](https://github.com/TryGhost/gscan/pull/218)
3. Propose safer `options` parameter treatment in Handlebars?
 
As for error reported by Kate initially, wasn't able to reproduce it by following the instructions. It's unclear when exactly the error happens.

Sidenote:
We might want to go through our helpers and unify how `options` parameter is used throughout as it's very inconsistent and possibly could be causing similar vague runtime errors. 

For example in [content helper](https://github.com/TryGhost/Ghost/blob/df7e64f/core/frontend/helpers/content.js#L12) options is assigned as a default function parameter: `module.exports = function content(options = {}) {` but the [date helper](https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/frontend/helpers/date.js#L9-L12) has the following:
```
module.exports = function (date, options) {
    let timezone;

    if (!options && date.hasOwnProperty('hash')) {
```
`{{ghost_foot}}` helper on the other side [doesn't protect](https://github.com/TryGhost/Ghost/blob/df7e64fafa122ec5d461c4772eca86d21938046b/core/frontend/helpers/ghost_foot.js#L14) itself from empty options object at all.

**Comment by ErisDS** [comment]
Kevin's AST changes to gscan should be merged in and this should be dealt with by using the AST linter to add new checks  - until last week I thought those changes had already gone in. 

I feel very strongly that this work should be merged ASAP now and that everyone needs to be on the same page that AST-based rules are how we should be doing things in gscan.

**Comment by ErisDS** [comment]
Short term, have added some guards and error handling to try to cover off these cases.

Also raised an issue in handlebars: https://github.com/wycats/handlebars.js/issues/1548

This is part of ongoing work to reduce the amount of 500 errors generated by Ghost down to real, unexpected, unhandled errors.
