### ISSUE TITLE
Add validation for adding webhooks

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10567]
We currently have no webhook event name validation on the server side.

The admin client has a dropdown to choose an event from a list. It's impossible to add events which do not exist via the admin client. Lower priority, help wanted 👻

### Steps to reproduce
- use the Admin API v2 with an admin key
- add a webhook with any event name (e.g. with Postman)
- it will pass and return a 200

Ghost: master

**Comment by gargol** [comment]
Not stale

**Comment by lunaticmonk** [comment]
What kind of validation is required here? Pardon me, but, I could get only a vague idea from the description. @kirrg001 Can you elaborate it a bit? If possible, I will give it a try.

**Comment by gargol** [comment]
Hey @lunaticmonk! This issue was meant to add validations to the input that comes into Admin API's `POST /webhooks` and `PUT /webhooks/:id` endpoints. The only values that should be accepted by the controller are listed in [webhooks service](https://github.com/TryGhost/Ghost/blob/b83232b/core/server/services/webhooks/listen.js#L5-L38). Ideally this validation would happen in a similar manner to how [post validation](https://github.com/TryGhost/Ghost/blob/master/core/server/api/v2/utils/validators/input/posts.js) is done using [JSON Schema](https://github.com/TryGhost/Ghost/blob/34fad7e/core/server/api/v2/utils/validators/input/schemas/posts.json#L37-L38).

**Comment by lunaticmonk** [comment]
@gargol I added the validation. Wanted to know if there is need to add tests? The current tests fail when the validation was added.

**Comment by naz** [comment]
Just came across this issue when doing research. It was addressed with these changes - https://github.com/TryGhost/Ghost/commit/a520cdad0b3aa36a5a2e0a2dcf69a3e2d9e0bcdc when working on https://github.com/TryGhost/Ghost/issues/12033
