### ISSUE TITLE
Edit redirect for pages causes 404 with v0.1 API instances

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost#10649]
### Issue Summary

Ghost instances that internally use the v0.1 API no longer correctly redirect `/edit` requests for pages. This issue affects users whose instance's theme service returns `v0.1` as the API version.

### To Reproduce

1. Create a theme that does not specify the `engines` property in the package.json
2. Upload the theme and create a page in the admin interface
3. Visit the page
4. Append `/edit` to the url and get redirected to `/ghost/editor/post/{id}` which yields a 404

### Technical Information

This issue stems from the user being redirected to a post editor (e.g. `/ghost/editor/post/{id}/`) instead of a page editor (`/ghost/editor/page/{id}/`).

The act of redirecting is done here:

https://github.com/TryGhost/Ghost/blob/a532e35dc4eee04ae345833a72c5ccd8475c7fa4/core/server/services/routing/controllers/entry.js#L32-L35

However, the context of `res.routerOptions` changes between the v0.1 and v2 API:

```js
// v0.1 context
{ type: 'entry',
  filter: undefined,
  limit: undefined,
  order: undefined,
  permalinks: '/:slug/:options(edit)?/',
  resourceType: 'posts',
  query:
   { controller: 'posts',
     type: 'read',
     resource: 'posts',
     options: { slug: '%s', status: 'published', page: 0 } },
  context: [ 'post' ],
  frontPageTemplate: 'home',
  templates: [ 'index' ],
  identifier: 'blahblah',
  name: 'index',
  data: {} }
```

```js
// v2 context
{ type: 'entry',
  filter: undefined,
  permalinks: '/:slug/:options(edit)?/',
  resourceType: 'pages',
  query:
   { controller: 'pagesPublic',
     type: 'read',
     resource: 'pages',
     options: { slug: '%s' } },
  context: [ 'page' ] }
```

Ghost Version: master

**Comment by kevinansfield** [comment]
Thanks for the report @vikaspotluri123!

@gargol can you think of a way to get the correct resource type in the router?

If it's not possible we probably want to modify Ghost-Admin so that if `/#/editor/{objectId}` is hit then it can attempt to fetch both a post and page with the ID and do an internal redirect to the correct route. Feel free to re-assign to me if that's the case 🙂

I imagine any workaround needed would be temporary anyway seeing as the v0.1 API will be going away in 3.0.
