### ISSUE TITLE
Trailing Slash Redirect Ignoring Subdirectory in URL

### ISSUE THREAD

**Issue by cancan101** [TryGhost/Ghost#10687]
### Issue Summary

I have my `url` set to a path with a subdirectory (e.g. `https://my-app.herokuapp.com/blog`). When I attempt to visit a page without the trailing (e.g. `https://my-app.herokuapp.com/blog/ghost`) I get redirected to `https://my-app.herokuapp.com/ghost/` rather than `https://my-app.herokuapp.com/blog/ghost/`

This seems to be due to a redirect (`301`) with a relative path: `Location: /ghost/`.

### To Reproduce

1. Set url in config to include subdir
2. visit sub page (eg ghost admin) w/o training slash (`/`)

### Technical details:

* Ghost Version: 2.9.1
* Node Version: 10.15.X
* Browser/OS: Heroku
* Database: mysql

**Comment by cancan101** [comment]
This seems to be fixed by the suggestion in: https://github.com/TryGhost/Ghost/issues/9982#issuecomment-451363325:
```
var ghost = require('ghost');
var express = require('express');
var urlService = require('./node_modules/ghost/core/server/services/url');
var parentApp = express();

ghost()
  .then(function (ghostServer) {
    ////////////////////////////////////////////////////////////////
    // this is what you need to get subdirectories working properly!
    // e.g. https://www.website.com/blog
    parentApp.use(urlService.utils.getSubdir(), ghostServer.rootApp);
    ghostServer.start(parentApp);
    ////////////////////////////////////////////////////////////////
  });
```

**Comment by bdentino** [comment]
I ran into this issue as well. I'm using an old version of ghost where urlService is not available, so I needed my own workaround. I actually think the true root cause of this is related to not passing the subdir path as the `base` option to `connect-slashes` in the `pretty-urls.js` middleware. Is there a reason not to pass this option (e.g. would break other valid configurations)? If it's safe, fixing the issue here might be preferable to using workarounds that require digging private components out of node_modules.

```
var slashes = require('connect-slashes'),
    utils = require('../utils');

module.exports = [
    slashes(true, {
        base: urlService.utils.getSubdir(), // Adding the correct base here fixes the redirect problem
        headers: {
            'Cache-Control': 'public, max-age=' + utils.ONE_YEAR_S
        }
    }),
    require('./uncapitalise')
];
```
