### ISSUE TITLE
Unable to add language hint in code blocks for syntax highlighting

### ISSUE THREAD

**Issue by aliakhtar** [TryGhost/Ghost#10716]
When adding a code block, you should be able to provide the language so syntax highlighting can be done properly for that language.

This could be done by doing: 
`   ```scala`

Which would produce `<code language="java">`

However this cannot be achieved in the editor - as soon as you type ` ``` ` the whole thing disappears and you can't get to typing a language. Even copy / pasting the markup doesn't work.

Gif: 
![image](https://discourse-cdn-sjc1.com/business4/uploads/ghost2/original/2X/7/76fab26f5de098143ab5537e9b1b1c08f8655325.gif)

Any ideas?

**Comment by kevinansfield** [comment]
@aliakhtar this is expected at the moment because there is no language switcher for the basic code card. As you have demonstrated, the workaround is to use a markdown card, or alternatively you can use a html card where you have further control over how the language CSS is output in the rendered content.

If you want to propose it as a feature please use [our forum](https://forum.ghost.org) - there is an Ideas topic where features can be proposed and voted on.
