### ISSUE TITLE
Image resizing ignores dynamic content/images structure

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#10949]
When images are imported into the `/content/images/` directory, but below that, have their own structure of 

`/downloaded_images/dir-name/filename.jpg`

our resizing image feature doesn't work and creates URLs like this:

`https://domain.com/downloaded_images/filename.jpg/content/images/size/w1000/ `

This should not be hardcoded and work no matter if the underlying structure is following the `/yyyy/mm/` pattern or not.

**Comment by allouis** [comment]
After some digging (and a little more confusion) I've narrowed this issue down to our handling of relative URL's - _thankfully_ it has nothing to do with the directory structure of the `/content/images` directory.

The problem lies in the `img_url` helper, which does not work correctly for relative urls which do not have a leading slash ("/").

e.g.

```
content/images/whatever/you/want.jpg  # works correctly,
/content/images/whatever/you/want.jpg # does not.
```

We probably wanna fix imports so that we have consistent style of relative urls in the database. But the `img_url` helper should also be fixed to work for all kinds of urls from all different walks of life :relaxed:
