### ISSUE TITLE
Dynamic Routing Static Routes: Weird behaviour when template missing

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10990]
If you're using dynamic routing, define a static route, and don't include the template

### To Reproduce

This is weird and fiddly. It requires having a broken site setup. Reproducing also depends on development vs production mode and the order in which pages are loaded!

**Setup:**

1. Create a routes file that looks something like this:

routes:
  /: home
  /about/: about

2. Use the casper theme, but add a template called "about.hbs" that contains this:

```
{{!< default}}

<header class="site-header outer">
    <div class="inner">{{> "site-nav"}}</div>
</header>

<main id="site-main" class="site-main outer">
    <div class="inner"><div class="post-feed"><h2>About page</h2></div></div>
</main>
```

This means we have a routes file that references a `home.hbs` template, but that template doesn't exist.

**Reproduce**

- Start Ghost in development mode:
- Open the home route: `/` and see just a footer - the home template is missing, and so the default.hbs is rendered on it's own.
- Open the `/about/` route and see a header, footer and the words "About page"

Everything seems OK.

- Start Ghost in production mode:
- Open the home route: `/` and see just a footer  - exactly the same as last time.
- Open the `/about/` route, and you'll see a page with no CSS!

Last one...

- Stop Ghost & Start it in production mode again (stop-start is important):
- This time, visit `/about/` first, it'll look as it did in dev mode
- Then visit `/` and you'll see "500 Cannot read property 'match' of undefined"

I setup my routes.yaml, and I forgot to make a home.hbs template. I'm expecting my about page to work correctly, and I expect something sensible like a fallback or an error to happen on the home template.

### Technical details:

* Ghost Version: master

**Comment by ErisDS** [comment]
It took me a really long time to figure out the repro case for this one, but now that I have it makes some sense. Here's what's happening:

Originally, the default fallback template was always index.hbs, but for static routes that almost always results in Ghost throwing the following unhelpful error:

> 400 [index.hbs] The {{pagination}} helper was used outside of a paginated context. See https://ghost.org/docs/api/handlebars-themes/helpers/pagination/.

(this doesn't happen on casper, because casper doesn't use {{pagination}}, but it does on most themes).

index.hbs is meant to be a listing page, and static routes are never going to have lists of posts associated with them (that would be a channel) so, it makes no sense to fallback to index.

In https://github.com/TryGhost/Ghost/commit/07c72d735e8326be8aa633239b7fb782dba17ba6#diff-475c1d14a4a529809113e36dd6e3bf48, the default fallback was changed to default.hbs, as this would render a header and footer, and nothing else, be a fairly obvious problem etc etc. It seemed like a sensible solution.

However, although this is fine in development mode where templates don't get cached, in production mode it causes the 2 problems seen above. In the case that you load default.hbs as a template (e.g. load it as a fallback template for / in the repo cases) before loading it as a layout, it breaks the layout of all other pages that use default.hbs.

In the case that you load a page that uses default.hbs as a layout first, (e.g. the correct /about/ route in the repro cases) when you come to try to use it as a template file, it throws a weird "Cannot read property 'match' of undefined" error.

This is probably, technically, a bug in express-hbs, that template files can't be used interchangeably as templates as layouts.

However, it's also weird behaviour on our part, IMO. If I setup a static route, which is a 1:1 mapping between a route, and a template, and I load that route but the template is missing, rather than falling back or trying to do something semi-ok, we should just output a simple error!

**Comment by ErisDS** [comment]
I have a fix for this ready for once the v3 branch is cut.

**Comment by ErisDS** [comment]
Assume you have a route.yaml file something like:

```
    routes:
      /: home    
```

In Ghost v2, if you don't have a home.hbs template, Ghost falls back to using the default.hbs file if it's available. Most themes have a default.hbs, so this mostly works.

However this file is a layout file, depended on by other templates, not a template file itself. In production mode, using the default.hbs as a template causes weird, intermittent layout issues depending on which order pages are loaded. Due to the caching in [express-hbs](https://github.com/barc/express-hbs/issues/161). 

In Ghost v3, we will throw a 400 error for missing template files instead of having a fallback. 

E.g. for the example above, if there is no `home.hbs` file, navigating to '/' would throw the error 'Missing template home.hbs for route "/".'

![image](https://user-images.githubusercontent.com/101513/64437082-7f9e7c00-d0bd-11e9-8ed6-4d87936aee21.png)

This bug is fixed in the v3 branch, closing.

**Comment by matthieubulte** [comment]
Hi, so I came across this issue while looking for an issue which I think is very similar -- and actually causes the same issue and is reproducible the same way as your "last one..." -- but didn't get really resolved by your commit, which is expected.

So basically, the exact same exception (for similar reasons I believe) is thrown if an `.hbs` file is being used both as a template and as a layout. The reason why I had this situation is that I was using a single `.hbs` file as a base template for both a full page but also included it in another page, this was done to avoid duplicating code.

The solution was to replace the template usage (in my routes file) by a new template file which only includes my base `.hbs` file. However, it was really hard to figure out the reason for this issue and it took me a while and a lot of exploration of the source code to understand this issue.

Since I don't think my use case is really unreasonable, I would really advice to throw some more helpful message if this "class" of errors happen rather than fixing each possible cause (seems to be many way to trigger this same problem).

Otherwise, thanks for making this great project open source, it rocks!

**Comment by ErisDS** [comment]
This is a really interesting report, thanks!
The underlying issue was reported here: https://github.com/TryGhost/express-hbs/issues/161

Will have a think about where the best place to fix it would be so that, as you say, there's a better error.

**Comment by MarkErik** [comment]
Hello, I came across this thread searching for the {{pagination}} helper error which I see in the console when I navigate to my homepage which I have set up as a static route.

[2020-07-17 12:43:12] ERROR "GET /" 400 426ms
[home.hbs] The {{pagination}} helper was used outside of a paginated context. See https://ghost.org/docs/api/handlebars-themes/helpers/pagination/.

I am also getting a 404 Page Not Found in the body area of my homepage.

I followed the tutorial and the examples from the forums and ended up with a routes file:
```
routes:

  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /blog/topic/{slug}/
  author: /blog/author/{slug}/
```
I have to admit that I am an absolute novice with hbs, and don't fully understand the difference between templates and layouts.

From this thread I gather that I am doing something wrong.

I'm running the docker ghost image with:
`docker run -d --name some-ghost -e url=http://localhost:3001 -p 3001:2368 ghost
`
(So that likely is in development mode)

My plan was to create a homepage for the site. And as a starting point, to check that it worked I just duplicated the index.hbs -> home.hbs . I was happy with replicating the landing/ blog index page of the site on the homepage as well, as the first step.

This is what both of them look like. I see the pagination there, but I am not sure why it wouldn't work just like it does on the blog index page.
```
{{!< default}}

{{> loop }}

{{ pagination }}
```

The default.hbs looks like:
```
<!doctype html>
<html lang='{{ @site.lang }}'>

{{> head }}

<body class='{{ body_class }}'>
  <div class='c-site-container'>

    {{> header }}

    <div class='o-wrapper'>
      <div class='o-grid'>
        <div class='o-grid__col o-grid__col o-grid__col--center o-grid__col--9-10-m o-grid__col--2-3-l'>
          {{{ body }}}
        </div>
        <div class='o-grid__col o-grid__col o-grid__col--center o-grid__col--9-10-m o-grid__col--1-3-l'>
          {{> sidebar }}
        </div>
      </div>
    </div>

    {{> footer}}
  </div>

  <script src='{{ asset 'js/app.min.js' }}'></script>
  {{ ghost_foot }}
</body>
</html>
```

Is the issue that I am pulling in the default.hbs into the homepage?

This has been a tough issue to deal with, because from the tutorials/forum postings, I've seen a few solutions where some people have solved this with creating a /home Page in the admin panel. (I tried with and without, still same problem).

I've also tried the above combinations with removing the data: page.home from the routes file as some people mentioned that fixes their 404 issues. (From my understanding, if you specify only the template, the entire page must be created via code as part of the theme, whereas using the data: page.home allows you to create the page in the admin panel, and use the home template from the theme to style it).

**Comment by MarkErik** [comment]
Quick update:
With the following routes file (same as above, but reposting here for reference):
```
routes:

  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /blog/topic/{slug}/
  author: /blog/author/{slug}/
```

And the same default.hbs as my previous post.

But by changing my home.hbs to (removed the loop and pagination):
`{{!< default}}`

The result is that I no longer get the 404 error in the body (not sure why), or the pagination error in the console (which is expected since I've removed that from the hbs).

I also have a published /home Page created in the admin panel.

However, I do not see the contents of the page. (I see the header, footer and sidebar, but the main content area is blank).

My apologies if this is entirely because I am a novice and everything is working as expected, and this is something I need to figure out be learning more about hbs.

I thought it would work because the default.hbs contains the {{{ body }}}

**Comment by MarkErik** [comment]
@ErisDS Apologies, my hope was to add additional context to what appeared to be the similar issue.
