### ISSUE TITLE
Posts in dashboard ordering is wrong and shows non-published first

### ISSUE THREAD

**Issue by levelsio** [TryGhost/Ghost#11088]
Not sure why, but here's how my posts should be ordered:
<img width="1202" alt="Screen Shot 2019-09-08 at 5 22 01 PM" src="https://user-images.githubusercontent.com/7150848/64485542-43098680-d25d-11e9-8372-ee432f6b5efb.png">

Here's how they are ordered:
<img width="1214" alt="Screen Shot 2019-09-08 at 5 21 52 PM" src="https://user-images.githubusercontent.com/7150848/64485543-43a21d00-d25d-11e9-901c-c288c8070a5b.png">

Logically when ALL POSTS is selected (the default), it should just order all posts by last edited date. It's not logical to me to show me drafts I wrote years ago but haven't published yet, if I'd want to see those first I'd select DRAFT POSTS.

Thanks!

**Comment by kevinansfield** [comment]
@levelsio this is the expected behaviour. The posts list shows drafts first when ordered by "newest" because they have no published date and are likely the things that a writer will be working on now/soon.

If you want to list posts by the last edited date you can change the `Sort by:` column to `Sort by: Recently updated`.
