### ISSUE TITLE
bookmark card has problem get full of the canonical URL from a page

### ISSUE THREAD

**Issue by huangyuzhang** [TryGhost/Ghost#11209]
### Issue Summary

When Insert a deep path URL from GitHub, even though the canonical URL is defined, the bookmark card will only get part of the URL.

### To Reproduce

1. go to this page: [https://github.com/splitbrain/rpibplusleaf/blob/master/rpiblusleaf.pdf](https://github.com/splitbrain/rpibplusleaf/blob/master/rpiblusleaf.pdf)
2. Copy the URL and insert it as a bookmark card in Ghost editor
3. visit the bookmark card after publishing or viewing the draft, the URL stops at his GitHub repo, i.e. "https://github.com/splitbrain/rpibplusleaf".

Further, it seems that we cannot use bookmark card for those pages didn't set their canonical URL correctly. For example, when I add [https://www.raspberrypi.org/documentation/remote-access/ssh/](https://www.raspberrypi.org/documentation/remote-access/ssh/) as a bookmark card, but its canonical is "https://www.raspberrypi.org/". Is there a way that I can define the URL of a bookmark card manually or something like that?

Any help would be appreciated!

### Technical details:

* Ghost Version: v2.31
* Node Version: v8.15.1
* Browser/OS: Chrome 77 / MacOS  Mojave
* Database: SQLite3

**Comment by kevinansfield** [comment]
The bookmark card currently gives preference to the Twitter Card / Open Graph data that the page includes for sharing across sites before falling back to the canonical URL.

In the GitHub case it does not provide page-specific data but links to a generic project page:

<img width="890" alt="Screenshot 2019-10-08 at 08 46 37" src="https://user-images.githubusercontent.com/415/66377179-f4105780-e9a8-11e9-990e-c8ca82caa02f.png">

For the raspberrypi.org case for some reason they have their canonical URL set to the homepage:

<img width="1031" alt="Screenshot 2019-10-08 at 08 56 41" src="https://user-images.githubusercontent.com/415/66377456-92042200-e9a9-11e9-9b40-9a4a403de099.png">

These seem like problems with how those sites are coded because it's "breaking the web" to a certain extent. However, we can improve our handling of this by storing the url that is pasted in rather than one that is grabbed from the page.

**Comment by huangyuzhang** [comment]
Storing the pasted URL sounds like a perfect solution for this!
Thank you!

**Comment by rishabhgrg** [comment]
Closing in favor of https://github.com/TryGhost/Ghost/issues/11212
