### ISSUE TITLE
Bookmark card fails to parse dev.to link

### ISSUE THREAD

**Issue by jessehouwing** [TryGhost/Ghost#11201]
### Issue Summary

When I try to embed a `dev.to` link, I get an error the link can't be parsed.

### To Reproduce

Paste one of these links in a bookmark embed:

https://dev.to/lostintangent/visual-studio-live-share-in-pursuit-of-enjoyable-developer-collaboration-2nko
https://dev.to/lostintangent/collaboration-doesn-t-come-in-one-size-fits-all-33ai

![image](https://user-images.githubusercontent.com/4173387/66256806-09f7ff80-e792-11e9-9025-8c6272511b43.png)

### Technical details:

* Ghost Version: ghost.io
* Node Version: n/a
* Browser/OS: edge chromium /  Chrome latest
* Database: n/a

**Comment by rishabhgrg** [comment]
👋 Hey @jessehouwing, did some quick digging into the metadata for `dev.to` links and it looks like `dev.to` articles are creating empty `description` meta tags in html -
```
<meta name="description" content="">
<meta property="og:description" content="">
...
```

Bookmark card currently expects minimum of `title` and `description` in metadata for any url to show it as bookmark embed, and since above `dev.to` links don't have any `description` metadata it fails to load as bookmark card.

**Comment by jessehouwing** [comment]
Better error message would help... Cause it doesn't seem to have issues passing the url then.

**Comment by rishabhgrg** [comment]
Noted 👍 Meanwhile closing the issue here as we use GitHub solely for bug-tracking and on-going feature development.
