### ISSUE TITLE
SQLITE_ERROR: too many SQL variables (Upgrade 2.35.0 to 3.0.0)

### ISSUE THREAD

**Issue by gierschv** [TryGhost/Ghost#11263]
Hi there,

### Issue Summary

When I tried to upgrade my Ghost from 2.35.0 to 3.0.0, the process crashes in loop with when the database is being migrated:

`SQLITE_ERROR: too many variables` / `Error occurred while executing the following migration: 05-populate-posts-meta-table.js`

### To Reproduce

The full logs are available on this gist: https://gist.github.com/gierschv/71429b07b81cedc4bcdb95310c28c521

### Technical details:

* Ghost Version: 3.0.0 (upgraded from 3.0.0)
* Node Version: 10.16.3
* Browser/OS: Ubuntu
* Database: SQLite

Thank you!

**Comment by danymill** [comment]
Same issue with the same versions except for OS: MacOS 10.15 Catalina. I couldn't rollback, so I had to install clear copy 3.0.0 and import content from backup.

**Comment by gargol** [comment]
The issue here is with hitting SQLite's internal [SQLITE_LIMIT_VARIABLE_NUMBER](https://sqlite.org/limits.html#max_variable_number) limit when updating with large amount of posts having `metadata` fields set. This limit is set to 999 by default but [can differ](http://sqlite.1065341.n5.nabble.com/SQLITE-MAX-VARIABLE-NUMBER-td43457.html) depending on the distro. 

Think a possible solution would be rewriting the [05-populate-posts-meta-table.js](https://github.com/TryGhost/Ghost/blob/3.0.0/core/server/data/migrations/versions/3.0/05-populate-posts-meta-table.js#L33-L45) migration to use iterative method and update posts in small batches so the most standard limit of 999 params is never hit :thinking: 

Related issue: https://github.com/TryGhost/Ghost/issues/5810
