### ISSUE TITLE
🍎 Mac issue with 🇫🇷 French Keyboard (Dead Keys)

### ISSUE THREAD

**Issue by ScreamZ** [TryGhost/Ghost#11316]
Hello,

I'm having a Medium blog but also a French mirror using Ghost for publishing.

I noticed that ghost and Medium share similar editor and it's experiencing the same issues in terms of French keyboard.

As I described here : https://github.com/TryGhost/Ghost/issues/11112#issue-493494067 I first though it was about Firefox but in fact the issue is about something called [DeadKeys](https://en.wikipedia.org/wiki/Dead_key).

One article I found here describe the issue and using the given tips I was able to eradicate the issue on my Macbook.

https://www.foobarflies.io/backticks-on-the-mac-keyboard/

## What can we do to face this ?

I don't know the name of the editor and not even if it's open-sourced but could we track this issue to avoid strange behavior causing content annihilation like I shown above. Especially for people that are not aware of such problem and not able to easily change their keyboard configuration.

Thanks,
Regards,

Andréas

**Comment by gargol** [comment]
Hey @ScreamZ :wave: This is an interesting issue you are having and I think would be very useful to any Ghost-editor users that come across a similar situation. The editor is relying heavily upon [mobiledoc kit](https://github.com/bustle/mobiledoc-kit) by [Bustle](https://github.com/bustle) I'd suggest opening an issue there if you are able to drill down to the root cause. Don't think that the issue itself belongs to the Ghost main repository :smiley: If there is a confirmed bug in mobile-kit please feel free to reopen this issue and link to a bugfix so we could path Ghost properly. Thanks!
