### ISSUE TITLE
Figcaptions should not be included in the description/excerpt

### ISSUE THREAD

**Issue by thanosisalive** [TryGhost/Ghost#11532]
### Issue Summary

Figcaptions are mainly used to describe the contents of a figure and should not appear in descriptions (og, twitter, etc) and excerpts. It also looks ugly, because figcaptions often do not contain period and space at the end (`Something something. Figcaption textSomething something.`).

### To Reproduce

1. Create a post that starts without or with a little text and add some card (e.g. image card).
2. Check description and excerpt.

**Comment by kevinansfield** [comment]
The automatically generated excerpt that is used as a fallback when no custom excerpt or specific twitter/facebook description is provided is a very basic and generic html->text transformation. If it's not to your liking (because you've used an image or some other html at the top of your post) then you can enter your own text using the custom excerpt field, meta data description field, or even override specifically for twitter/facebook.
