### ISSUE TITLE
@site.secondary_navigation url field is empty

### ISSUE THREAD

**Issue by dhstack** [TryGhost/Ghost#11540]
### Issue Summary

Trying to loop through secondary navigation, but the url value is not populating. "Label" works as expected.

### To Reproduce

1. Add this code anywhere:

```
{{#foreach @site.secondary_navigation}}
    <a href="{{url absolute="true"}}">{{label}}</a>
{{/foreach}}
```

I expected the url to be output, but instead it seems that the slug for the url is empty. Only the root domain is put into the link.

### Technical details:

* Ghost Version: 3.x
* Node Version: Ghost Pro
* Browser/OS: Chrome/Windows x64
* Database: Ghost Pro

**Comment by gr36** [comment]
also experiencing this using:

```
{{#foreach @site.secondary_navigation}}
		<a href="{{slug}}" target="_blank">{{label}}</a> 
{{/foreach}}
```

**Comment by bernwaldl** [comment]
As far as I can tell this also applies to `@site.navigation`. Furthermore the `slug` value is also not set. It seems to be that those values are only populated in the _navigation.hbs_ template. Whether that is intentional or unintentional, that I don't know.
Anyways, I could also use this functionality - more specifically the population of the slug value - for my use case.

**Comment by kevinansfield** [comment]
1. [`{{url}}` helper only works inside the post scope](https://ghost.org/docs/api/v3/handlebars-themes/helpers/url/)
2. `@site.secondary_navigation` is raw data (as per `@site.navigation`) and can not be looped over in that way, you need to use the `{{navigation}}` helper which is template-driven using the `partials/navigation.hbs` template. Docs are here https://ghost.org/docs/api/v3/handlebars-themes/helpers/navigation/
