### ISSUE TITLE
Can't delete custom integration

### ISSUE THREAD

**Issue by antisoma** [TryGhost/Ghost#11563]
### Issue Summary

It is not possible to delete a custom integration from domain.com/ghost/#/settings/integrations by pressing the "Delete Integration" button in the "Are you sure?" modal.

Issue exists in local Windows install and on Ubuntu VPS.

### To Reproduce

1. Create a custom integration
2. Attempt to delete it with the UI

When you click on the "Delete integration" button it returns an error in Chrome/Firefox console, with error:
TypeError: e is null ghost.min-551e76deb94daf78f212a108b1f6becf.js:458:52

### Technical details:

* Ghost Version: 3.4.0
* Node Version: v12.14.1 and v10.18.1
* Browser/OS: Chrome, Firefox - Windows 10
* Database: SQLite3

**Comment by gargol** [comment]
The issue was happening on Ghost 3.4.0 only. It has been fixed in master with this change last week - https://github.com/TryGhost/Ghost-Admin/commit/855757ffe594263edc10a2725dd84321e2eb0609#diff-5d2c7241ea91e46fa48d1362bd4b2ebcL30). Fix should be released with the next version. Thanks for the report @antisoma

**Comment by gr36** [comment]
Any idea on time scale for this, at the moment I am unable to create a custom integration as it simply duplicates the one I am unable to delete

**Comment by gargol** [comment]
Hi @gr36! The fix went out with yesterday's release - https://github.com/TryGhost/Ghost/releases/tag/3.5.0
