### ISSUE TITLE
[Post Meta Split] API v2 & v3 errors when filtering across post meta table.

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11572]
See https://demo.ghost.io/ghost/api/v3/content/posts/?filter=meta_description%3A-null&key=22444f78447824223cefc48062

VS https://demo.ghost.io/ghost/api/v3/content/posts/?filter=slug%3A-null&key=22444f78447824223cefc48062

The query works for all fields which are not part of the new join table. Looks like some configuration for NQL was likely overlooked as part of the work to split the post table.

### Technical details:

* Ghost Version: 3.4
* Database: MySQL

**Comment by naz** [comment]
As suspected the main reason for the query failure is lack of defined [relation and possibly expansions](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/filter.js#L5-L56) from `posts` to `posts_meta` table in NQL. To be able to define these we'd first [have to support 1:1](https://github.com/NexesJS/mongo-knex/blob/8bf33496dea5f306ab3535fcce0f4d9830d44a16/test/integration/relations.test.js#L937) relations in Mongo-Knex and later examine how expansions would function to be able to expand field filters living in `posts_meta` table.

I've done a little spike in Ghost when looking into the issue [here](https://github.com/naz/Ghost/commit/472c97091ccadc2c8acf60476c84656c8f274678). It could be useful for a new test confirming a bug and see where things would have to go into when mongo-knex adds needed feature. 

Don't have a concrete estimation on how long the change would take but this is what I think needs to be budgeted for:
1. Design and add something a-la "oneToOne" relation support to Mongo-Knex to be able to expand existing [manyToMany](https://github.com/NexesJS/mongo-knex/blob/8bf33496dea5f306ab3535fcce0f4d9830d44a16/lib/convertor.js#L217) query builder.
2. Investigate how the fields from `posts_meta` table should be "expanded" and if there's a better way to define where to look for them instead of adding a separate configuration for each field like [here](https://github.com/naz/Ghost/commit/472c97091ccadc2c8acf60476c84656c8f274678#diff-f359249f88688ade047760ef9bca4f6bR64-R69).
3. Implement above in core :) 

@ErisDS to give better estimation on the above would need maybe half a day appetite to play with mongo-knex and figure out the deets.

**Comment by naz** [comment]
To move on needs appetite to reconfirm mongo-knex is 100% correct path to go and if so specify what exactly an how it would need to change. Guesstimating .5 day.

**Comment by naz** [comment]
Similarly to [ordering bug](https://github.com/TryGhost/Ghost/issues/11729#issuecomment-693028421) solution short term will expand existing configs and NQL to support `posts_meta` relations. Long term plan, same as in referenced comment. 

Timeboxing 1 day of work to see what kind of work might be involved on NQL level to implement short term fix.

**Comment by naz** [comment]
@matthanley after tinkering a bit in mongo-knex have a better estimation for what needs to be done:
1. [1:1 relation](https://github.com/NexesJS/mongo-knex/issues/35) implementation - **~2 days**
2. Implement a mechanism to add "expansions" generically from the model layer - something that might work would be similar to `orderAttributes` introduced when solving [ordering by relations problem](https://github.com/TryGhost/Ghost/pull/12226/commits/d62fb496ad553c73cfd3622828d923ada1f36d26#diff-f8d02ad12b13d44b912bbf46cf7193b6R177-R180) - **.5-1 days**
3. Check if there are any collisions with ordering and other relations - **few hours**, would write some regression tests

To reiterate, these all would be "short term" fixes and something that manages this case of 1:1 relation would need to come from Bookshelf or plugin abstraction. 

Let me know if you have any questions around this plan!

**Comment by matthanley** [comment]
Sounds like a good plan - are there any other 1:1 relationships in the codebase that would benefit from this also?

**Comment by naz** [comment]
No other relation, I don't think. At the moment the only other 1:1 relation in models is `posts` <-> `emails`. Don't know of any usecases where we'd need to filter/order or eager load data. Might be something we could use if any other tables "run out of space", but nothing I could think of from the back of my head straight away.

**Comment by naz** [comment]
The approach I've implemented in mongo-knex failed after I tried integrating it into Ghost itself... due to `join` statements not being picked up by knex when used in filter subqueries :tired_face: Will probably have to do "where in ()" approach that is used in many:many filtering (which has limitations on SQLite) or will try to find a way to hook eager loading of the relation pre-filtering (similar to ordering). Will continue on this issue on Monday

**Comment by naz** [comment]
Have finished implementation of this relation in mongo-knex - https://github.com/NexesJS/mongo-knex/pull/36. Next would be merging the PR and integrating new version within Ghost. Guesstimating 1 day of work.

**Comment by naz** [comment]
After the merger of https://github.com/TryGhost/Ghost/pull/12307, the bug is fixed. Next step here would be figuring out 1:1 relationship preloading on (most likely) bookshelf layer. Maybe worth creating a new issue with 1:1 support as this bug is fixed and relationship support would be covering more areas than just filtering (other [post_meta split issues](https://github.com/TryGhost/Ghost/issues?q=is%3Aissue+is%3Aopen+%5Bpost+meta+split%5D+)) // cc @matthanley
