### ISSUE TITLE
Setting 'permalinks' has no effect

### ISSUE THREAD

**Issue by joallard** [TryGhost/Ghost#11588]
### Issue Summary
Setting 'permalinks' has no effect

### To Reproduce

Given one recently published post with slug `foo`,

1. Issue ``update settings set value = '/:year/:slug/' where `key` = 'permalinks';`` in MySQL
2. Visit `/`

Actual: Post is shown at path `/foo`
Expected: Post is shown at path `/2020/foo`

### Technical details:

* Ghost Version: 3.5.0
* Node Version: ^12.10.0
* Browser/OS: All
* Database: MySQL

**Comment by gargol** [comment]
Hi @joallard, modifying database directly in not encouraged as the application won't be able to pick up the change and you risk ending up in an unknown state. Please use our forum to clarify what problem you were trying to solve and I'm sure the community will be happy to help out :wink:

**Comment by joallard** [comment]
Seemed to me like this was a bug, but okay. Thing is with the forum, that it pretty much feels like talking into the void. After all, I'm just trying to solve problems here.

**Comment by joallard** [comment]
Besides, saying this STR here is the intended behavior and not a bug is kind of a bold statement. Why wouldn't the internals matter? 

"Don't you dare hack things, mortal!"

**Comment by gargol** [comment]
> "Don't you dare hack things, mortal!"

I'm was not implying this. And I don't appreciate such attitude.

The application state is dependent on all the changes being done on the application layer not on the DB layer. To take effect in the URL service, the application should know there has been a change in state. If you do that strictly in the DB without the app restart the change won't take effect.  

Sidenote, the most appropriate way to customize your URLs within ghost is to utilize [dynamic routing](https://ghost.org/docs/api/v3/handlebars-themes/routing/) the use of `permalink` comming from the DB has been discouraged and removed since https://github.com/TryGhost/Ghost/commit/8bb7088ba026efd4a1c9cf7d6f1a5e9b4fa82575. :v:

**Comment by JohnONolan** [comment]
@joallard This isn't a support desk, and nobody owes you anything. 

https://ghost.org/faq/open-source-etiquette/
