### ISSUE TITLE
[Post Meta Split] Ordering by meta_title is not possible

### ISSUE THREAD

**Issue by vikaspotluri123** [TryGhost/Ghost#11729]
### Issue Summary

It's not possible to make an API request (internally or externally) that sorts by `meta_title`. Moreover, sorting by a related table (e.g. `posts_meta`) is allowed, but the request fails. I think this is a regression from 2.x, after the post metadata got split out into a new table.

### Technical details:

* Ghost Version: 3.13.1
* Forum Ref: https://forum.ghost.org/t/order-by-meta-title-doesnt-seem-to-work/13349
* Possible related issue:

The model base parseOrderOptions pulls in a list of permitted attributes from the child modal, including allowed relations. This allows you to set the order to one of those relations, which kind-of breaks the API request. For example, ordering by [authors asc](https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&order=authors%20asc) will give you a 400, but [title asc](https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&order=title%20asc) works perfectly fine, and [potato asc](https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&order=potato%20asc) succeeds because you can’t sort by potatoes, and therefore the order is ignored.

**Comment by gargol** [comment]
Might be related to this issue - https://github.com/TryGhost/Ghost/issues/11572, should be checked when investigated deeper.

**Comment by naz** [comment]
After deeper digging into the issue, confirming that problem is how we create the order query [here](https://github.com/TryGhost/Ghost/blob/23bf432514c67ac7714cb51846f4ffc8353afd41/core/server/models/base/index.js#L1150-L1185) and the way Post model's [permittedAttributes](https://github.com/TryGhost/Ghost/blob/8f660c32598f560027b3958e78f7b01223b482f0/core/server/models/post.js#L76-L84) function returns only `posts` table specific fields ignoring `posts_meta` fields. 

A closest candidate to explore a solution is tinkering bookshelf-relations plugin, which should be able to abstract the table split in a way that `permittedAttributes` gives back correct fields from `posts_meta` .

**Comment by naz** [comment]
This issue needs appetite do dig into possible solution through bookshelf-relations. Guesstimating 1 day.

**Comment by naz** [comment]
Note, while loading up on the context have observed another place which will need an update when the ordering is implemented - [pagination plugin](https://github.com/TryGhost/Ghost/blob/902b55f3385e249c7014f6088ee73bf24a674861/core/server/models/plugins/pagination.js#L180-L187). Specifically, `options.order` should most likely come with resolved `tableName` because pagination plugin should not know about relations and not do the `tableName + '.' + property` concatenation.

**Comment by naz** [comment]
#### Braindump after playing extensively with ordering

There are 2 separate problems that this issue raises:
1. Main one - cannot order `post` resource by a legitimate field, which comes from a 1:1 relation (`posts`:`posts_meta` tables).
2. Ordering behaves inconsistently for fields that are not meant to be ordered by: ignores unknown properties and returns `400` when trying to order by property like `authors`, which comes from a relation name. In case of any field that can't be ordered by, it should consistently ignore that field (throwing a validation error would break API compatibility, so this is a no-go)

The key to both problems is how [parseOrderOption](https://github.com/TryGhost/Ghost/blob/7309cc1ddbdad05520f3d5917ca53d895bdfd682/core/server/models/base/index.js#L1168) function relies on [permittedAttributes](https://github.com/TryGhost/Ghost/blob/8f660c32598f560027b3958e78f7b01223b482f0/core/server/models/post.js#L76-L84) to calculate all the fields that could be ordered upon.

### (pt.1) Ordering by fields which come from 1:1 relation
The missing piece here is a mechanism in model layer which would recognize a 1:1 relation and extract "orderable" fields out of related table. Additionally, the fields  would have to come in a format that includes related table name so that pagination plugin could [correctly form](https://github.com/TryGhost/Ghost/blob/902b55f3385e249c7014f6088ee73bf24a674861/core/server/models/plugins/pagination.js#L180-L187) the query, e.g: `['posts_meta.meta_title ASC']` instead of `['meta_title ASC']`.

The solution I'm thinking of here is adding a `orderAttributes` method which would be used instead of `permittedAttributes` in  `parseOrderOption`. `orderAttributes` would have the same values as `permittedAttributes` for tables with no additional relations logic, and would have special overrides on each model with "expanded" field names coming from related table.

To make above solution more maintainable would need to create a declarative way of describing which fields from related model the `orderAttributes` could be taken from. One of the possible directions to explore is expanding `hasOne` relation in bookshelf-relations - plan to timebox this direction to half a day tomorrow (cc @matthanley).

### (pt. 2) Treating all non-orderable fields the same
The solution here somewhat relates to the solution from pt. 1. When parsing order options the function should not rely on `permittedAttributes` because those are not the same fields that could be "ordered" upon. Adding a `orderAttributes` method to the base model would possibly solve the problem.

**Comment by naz** [comment]
#### Thoughts on holistically solving posts<>posts_meta ordering/filtering/change detection problems

I've dug through [bookshelf-relations](https://github.com/TryGhost/bookshelf-relations) aiming to figure out an abstraction which would allow solving current ordering, [related filtering](https://github.com/TryGhost/Ghost/issues/11572), and [change-detection](https://github.com/TryGhost/Ghost/issues/12016)(1) [problems](https://github.com/TryGhost/Ghost/issues/12046)(2). I have not found a way that would solve all of them in a holistic way. 

These are 3 distinct areas that have some or no relation to `bookshelf-relations`:
 - **Ordering** - has to do with `findPage` method from [pagination plugin](https://github.com/TryGhost/Ghost/blob/91bca9f109361e80991ce1cef2c910dcd069cf0d/core/server/models/plugins/pagination.js#L180) and depends on buggy/outdated handling in [parseOrderOption](https://github.com/TryGhost/Ghost/blob/7309cc1ddbdad05520f3d5917ca53d895bdfd682/core/server/models/base/index.js#L1168) function. Nothing to do with bookshelf-relations because the ordering fields should be calculated independently IMO not just for `Post` model but all other models that have relations.
- **Filtering** - problems here stem from lack of explicit NQL configuration for `posts_meta` table in combination with mapping posts_meta filter fields to correct ones (using `posts_meta.` prefix). This kind of mapping should be done in serialization layer same way other field mappings are done there. 
- **Change detection** - to fix this problem on a deeper level ([the fix that was done](https://github.com/TryGhost/Ghost/commit/a75e1e27db356267ef5574c3026b9a719961f421) through override to `wasChanged()` was a "patch") we could look into fixing [bookshelf-relations](https://github.com/TryGhost/bookshelf-relations/blob/760ad0dc502a7207542299e0328452a5a3a67935/lib/relations.js#L367-L375) change tracking. This might come through some special parameter passed with `hasOne` relation that posts_meta is declared with or invent a whole new relation for this specific situation. New relation could also help with elimination of [patchwork](https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L345-L355) that has to be done in Post model. This needs to be researched.

Additional note, `bookshelf-relations` inherently deals with create/update/delete operations only and doesn't have anything to do with **read operations** that are needed in case of **ordering** and **filtering**.

#### Conclusion with regards to current issue
 
Two problems that were described [in the comment above](https://github.com/TryGhost/Ghost/issues/11729#issuecomment-685740836) should be solved outside of `bookshelf-relations`. This proposed solution:
> adding a orderAttributes method which would be used instead of permittedAttributes in parseOrderOption. orderAttributes would have the same values as permittedAttributes for tables with no additional relations logic, and would have special overrides on each model with "expanded" field names coming from related table.

seems like the most viable solution for now and would solve both problems.

@matthanley would love to know if you have any feedback on this? I estimate implementing the proposed solution would take about a day.

**Comment by matthanley** [comment]
> adding a orderAttributes method which would be used instead of permittedAttributes in parseOrderOption. orderAttributes would have the same values as permittedAttributes for tables with no additional relations logic, and would have special overrides on each model with "expanded" field names coming from related table

@naz this looks like a reasonable approach to me 👍

**Comment by naz** [comment]
After implementing the ordering idea I had in mind, got faced with a Bookshelf limitation I completely forgot existed. Have my experimentation available on this spike branch - https://github.com/TryGhost/Ghost/compare/master...naz:ordering-for-posts-meta-fields. 

To sum up the problem. In pagination plugin, when [self.fetchAll](https://github.com/TryGhost/Ghost/blob/91bca9f109361e80991ce1cef2c910dcd069cf0d/core/server/models/plugins/pagination.js#L202) is done it doesn't have post_meta table loaded into the query and it fails with "no such column" error (when trying to order by `posts_meta`.`meta_title` for example). The problem of not having loaded relations when fetching records in Bookshelf is summed up with references here - https://github.com/bookshelf/bookshelf/issues/1707#issuecomment-351026830. 

There are two possible ways to get around this problem which I've been thinking of:
1. Extend pagination with detection of relations and build in a join to related table when the [ordering query is built](https://github.com/TryGhost/Ghost/blob/91bca9f109361e80991ce1cef2c910dcd069cf0d/core/server/models/plugins/pagination.js#L185). We extend the query in similar way in [filtering plugin](https://github.com/TryGhost/Ghost/blob/4ac88dc/core/server/models/plugins/filter.js) through NQL (it [adds joins](https://github.com/NexesJS/mongo-knex/blob/8bf33496dea5f306ab3535fcce0f4d9830d44a16/lib/convertor.js#L195) and filters records at the same stage). The downside for this method, is _possibly_ keeping yet another configuration that might be similar to [one in filter](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/filter.js#L5-L56). This _could_ end up hard to maintain longterm.
2. Explore fixing/extending Bookshelf itself and load up relations like `posts_meta` into the queryBuilder automatically. This potentially, would be a more maintainable approach. The downside is, I have no clue how hard this would be to achieve, would need to dive into bookshelf codebase to understand more. The problem seems to have been around in Bookshelf [since 2014](https://github.com/bookshelf/bookshelf/issues/202).

@matthanley the point Hannah made earlier about approaching the problem through bookshelf-relations is now clearer to me. Probably the limitation I've rediscovered was the reason. This issue could become a scope creep, so I think approaching it by timeboxing and researching possible directions would be best approach forward. I'm thinking of timeboxing first approach above to half a day and see what comes out and then if we really end up with need for configs would research the second approach. Let me know what you think or have any questions about the issue itself!

**Comment by naz** [comment]
#### Summary of the discussion around future plan for this issue

Short term plan (to be done now) would be implementing a solution which expands query builder object inside of pagination (or ordering) plugin based on additional configurations similar to ones done with NQL/filtering. 

Long term, aiming to develop a maintainable solution which is not based on configuration but rather on special relation type coming from Bookshelf or some other fix which might also address https://github.com/bookshelf/bookshelf/issues/202. Will timebox 1 day for research to figure out right questions and _maybe_ possible solutions. A solution that is in mind right now is expansion of  `hasOne` relation with an "alwaysFetched" parameter - this _might_ be done through a plugin or from within bookshelf itself (needs digging around).

**Comment by naz** [comment]
> 1. Extend pagination with detection of relations and build in a join to related table when the ordering query is built. We extend the query in similar way in filtering plugin through NQL (it adds joins and filters records at the same stage). The downside for this method, is possibly keeping yet another configuration that might be similar to one in filter. This could end up hard to maintain longterm.

This solution has landed in master through https://github.com/TryGhost/Ghost/pull/12226. 

Next up will be pushing pt. 2 and figuring out more generic way to handle relation inclusion in query builder object through Bookshelf/special plugin. This should help solve filtering/ordering and attribute change tracking all together.
