### ISSUE TITLE
Confusing permissions behaviour when logged in as low-privilege user

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#11758]
When you're logged in as E.g. an author, the admin panel isn't good at telling you why you can't edit a post. I've found two specific cases - the /edit URL and search, but I think they are both very similar.

### To Reproduce

Case 1: search 

1. In admin search for a post you can't edit
2. See the post listed in the results
3. Click on the post
4. You are taken to the posts list with no explanation

Case 2: /edit

1. In the frontend, find that post you're trying to edit
2. Add `/edit` to the end of the URL
3. Watch the post screen load for a while
4. You are taken to the posts list with no explanation

In both cases, there should be IMO a banner error saying you don't have permission.

In the case of search, we probably shouldn't be showing post the user can't edit at all?

### Technical details:

* Ghost Version: latest

**Comment by akshitproothi** [comment]
I'm a first time contributor and would like to work on this. How do i get started?

**Comment by ErisDS** [comment]
We have a [contributing guide](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md) as per most repositories. We don’t have anyone to coach you through issues, so you may want to start with an issue marked [help wanted](https://github.com/TryGhost/Ghost/labels/help%20wanted) as these are the ones we think are suitable for contributors.

**Comment by akshitproothi** [comment]
Good to know @ErisDS thanks, I’ll find one of those.

**Comment by naz** [comment]
@peterzimon would need a copy advice and an opinion on:
> In the case of search, we probably shouldn't be showing post the user can't edit at all?

### Banner/copy part of the solution
For reference, currently displayed **error** notification coming from server error data if the author user tries to edit not their own post (disabled redirect in code):
```
Permission error, cannot edit post. You do not have permission to edit posts.
```

At the moment when the post/page is loaded we have both user and post information and the redirect is done on the frontend side. This means we can construct and display any error using this information (there's no server involved). I'm thinking of something like this displayed as **warning** notification:
```
Permission error, cannot edit selected post "{post title here}". Only authors or administrator users can edit this post.
```
Would look like:
![Screenshot from 2020-09-21 16-11-22](https://user-images.githubusercontent.com/675397/93732382-256b4d00-fc25-11ea-8d9b-c5697c341986.png)

This message would make sense to display in both situations described in the issue. 

### Not showing posts to users that can't edit
This approach makes sense to me,  will check how easy it is to filter these records on the client. @peterzimon would be good to know if you have different opinion.

**Comment by naz** [comment]
@peterzimon to expand on the showing only editable information in search results. Similarly to showing posts that don't belong  to current author (and cause redirect), search results show "tags", "pages" and "users" to user logged in as "author", which it probably should not be showing?

**Comment by naz** [comment]
Another possible bug that have discovered while investigating these issues is that author user can't create "page" resources. This is not documented anywhere and needs more investigation.

**Comment by naz** [comment]
@matthanley not sure how to proceed with this bug. The linked issue TryGhost/Team#391 is a holistic solution improving workflow for **contributors**. This issue is somewhat related, but could be partially solved through copy updates and smarter filtering of shown search results for **all low-privilege users** (contributors and authors). 

My thinking is following. _Ideally_ we'd make an audit of behavior in Ghost-Admin for "authors" users as well and solve each inconsistency separately (like the contributor's workflow issue). If there's not much appetite for holistic approach like that, we could solve inconsistencies that have been discussed in this issue separately from contributor's improvements. 

Let me know what are you thoughts.

**Comment by naz** [comment]
@matthanley ping to check above message ;)

**Comment by matthanley** [comment]
> If there's not much appetite for holistic approach like that, we could solve inconsistencies that have been discussed in this issue separately from contributor's improvements.

@naz what would be your proposal for a small iterative improvement on what we currently have for this?

**Comment by naz** [comment]
@matthanley would break the permissions and Admin UI mismatches into following stages.

**Small change** that can be done immediately: implement the solutions that have been initially proposed in the issue description:
1. Display a banner in Admin UI with a warning notification [proposed above](https://github.com/TryGhost/Ghost/issues/11758#issuecomment-695892890) when permission redirect happens. Blocked by review of [proposed above copy](https://github.com/TryGhost/Ghost/issues/11758#issuecomment-695892890).
2. Filter out search results for authors/contributors to only show the content they can edit. Blocked by [confirmation on the improved search](https://github.com/TryGhost/Ghost/issues/11758#issuecomment-696035749) behavior.

Note, the linked [team issue](https://github.com/TryGhost/Team/issues/391) that improves usability for posts list view for contributors does not address the issues raised here! It's only related because it touches same topic - "mismatch of what we show in the UI and what logged in user can actually do"

**Bigger follow up change** would be auditing how search (for posts, pages, tags, users) and  post/page list views behave for all lower privilege user roles. An example of such inconsistencies is [described here](https://github.com/TryGhost/Ghost/issues/11758#issuecomment-696035749) and [here](https://github.com/TryGhost/Ghost/issues/11758#issuecomment-696443934), which was found during research for current issue. Note, this audit might be related and should account for the problem&solution proposed in [posts list view improvements for contributors](https://github.com/TryGhost/Team/issues/391).

**Comment by matthanley** [comment]
This is now resolved with the introduction of new designs for authors and contributors.
