### ISSUE TITLE
Unsecured image selected for bookmark card

### ISSUE THREAD

**Issue by benaltair** [TryGhost/Ghost#11870]
## Issue Summary

When embedding a certain link in the editor, creating a bookmark card, the image selected was an HTTP link instead of an HTTPS link. If you try to access the HTTP link, it redirects you to an HTTPS version, so I have no idea why Ghost would choose the non-secure option.

![image](https://user-images.githubusercontent.com/17771229/83344841-0127e100-a2c1-11ea-9320-71b31346f814.png)

The issue is that it pulls in mixed content, flagging the site as not secure in most browsers. 

![image](https://user-images.githubusercontent.com/17771229/83344842-0edd6680-a2c1-11ea-9afb-2a5dd831e3bd.png)

### To Reproduce

1. In the editor, add a link to https://liamdousti.com/
2. Go to the published page to see the card on the site
3. Check the image src link, looking for HTTP

Example is here: https://amberimageworks.org/culture/coffea/

It should pull an HTTPS source if possible, to avoid this sort of thing.

### Technical details:

* Ghost Version: 3.17.1
* Node Version: -
* Browser/OS: Chrome/Windows 10 (latest)
* Database: mysql

**Comment by ErisDS** [comment]
Hi @benaltair, 

The site you're having a problem with has a mixed content issue.

https://liamdousti.com/ only loads over https (http redirects) and yet in the metadata you can clearly see some of the linked resources from squarespace start with `http://` causing this problem, and some are correct with  `https://` or `//`.

![image](https://user-images.githubusercontent.com/101513/83866348-9a228600-a71f-11ea-9db0-07e7d1f04db4.png)

Trying to load those `http:` images even redirects to https for me 🤷‍♀️ 

Using the metadata provided by a site isn't Ghost "selecting" the wrong image. This looks to me like a bug in squarespace / the site in question. 

You could report this to the site owner, or maybe file a feature request in [Metascraper](https://github.com/microlinkhq/metascraper), (which is the tool used to pull the meta data from the page) asking them to follow redirects from http -> https and return the final URL, but that would add overhead that wouldn't be necessary at all if the site wasn't outputting the wrong urls for metadata.

**Comment by XapaJIaMnu** [comment]
I had the same issue recently: https://forum.ghost.org/t/resolved-ghost-blog-can-not-have-https-links-to-my-own-website/14828
The problem was that the ghost config had was not set to the https version of the website:
Do this
```
ghost config set url https://liamdousti.com/
```

**Comment by ErisDS** [comment]
@XapaJIaMnu That is not the same problem - you're referring to having https misconfigured on your Ghost site. This issue refers to a misconfiguration on a 3rd party site, and the expectation that Ghost's meta scraping feature could handle it.

**Comment by willkramer** [comment]
This issue is marked as being a Squarespace bug and unfortunately we can't fix or control what Squarespace does so I have a suggestion for a workaround.

When I look at the problematic post in the posts table in the MySQL database, I see that it the post html was inserted with the img src being "http://static1.squarespace.com/static/..."

I modified the html column for that post so the img src was "//static1.squarespace.com/static/..." and it fixed the security warning.

Would a possible solution be to search post content for any "http://" references in src tags and replace it with protocol relative URLs before inserting into the database?

---
_Side note:_ I already have a local fix on my own server up and running based on the way I'm deploying my Ghost site so I'm not impacted by this issue anymore. I'm curious if other people are impacted by this and if it warrants investing the time for a workaround fix.
