### ISSUE TITLE
The width (w) descriptor in the srcset attribute not always match the images real width

### ISSUE THREAD

**Issue by astab** [TryGhost/Ghost#11913]
There is an issue with the `srcset` attribute in an image card.

`srcset` provides images of the following widths: 600px, 1000px, 1600px, 2400px. No matter what size image the user uploads, all four sources are provided in the `srcset`, even if the image is smaller.

Say, the user uploads an 800px width image. The actual width of the first image in the `srcset` list is 600px and the width descriptor is 600w. But for the remaining three images the width descriptors are 1000w, 1600w and 2400w respectively, while the actual image size is 800px. When the width descriptor doesn't match the real width, you can get unexpected behavior.

I set up a quick demo with the Casper theme. If you resize the viewport, you can see that at some points the image of 800px width doesn't fill the post content of 700px width:

https://blogbox.justgoodthemes.site/testing-images/

I could enforce the image width in CSS (width: 100%) but it will stretch the image potentially making it larger than its actual dimensions.

### Technical details:

* Ghost Version: 3.19.2

**Comment by kevinansfield** [comment]
@astab `srcset` does not describe with width of images, it provides device-width breakpoint hints to the browser so it can select a src that is most appropriate for the device, resulting in bandwidth optimisations for mobile devices. Ghost will never resize images to be larger than you upload, so your post is demonstrating the expected behaviour.

> When the width descriptor doesn't match the real width, you can get unexpected behavior.

Could you detail the unexpected behaviour please?

**Comment by kevinansfield** [comment]
> srcset does not describe with width of images, it provides device-width breakpoint hints to the browser so it can select a src that is most appropriate for the device

This was an incorrect interpretation of the spec. A fix has been pushed so that `srcset` does not include any `w` values that equate to images that will not match the specified size.

Content that has problems with incorrect `srcset` values will need to be edited and re-saved after upgrading to the next Ghost version (to be released shortly)
