### ISSUE TITLE
Image component not generating "size" images but forcing them in HTML

### ISSUE THREAD

**Issue by SixBytesUnder** [TryGhost/Ghost#11944]
### Issue Summary

After updating Ghost from v3.19.2 to v3.20.3 all new images I upload using Image component render HTML with sizes, but no size images are being generated on the server.

### To Reproduce

1. Create new post.
2. Chose Markdown component
3. Add image with `![alt text](/content/images/2020/06/107_0724.JPG)`
4. Observe below, correct HTML on preview:
```html
<img src="/content/images/2020/06/107_0724.JPG" alt="">
```
5. Go back to post editing, chose Image component.
6. Upload image file.
7. Image is correctly displayed while in editor.
8. Observe below, incorrect HTML on preview:
```html
    <figure class="kg-card kg-image-card kg-card-hascaption">
      <img src="/content/images/2020/06/107_0724.JPG" class="kg-image" alt=""
       srcset="/content/images/size/w600/2020/06/107_0724.JPG 600w, /content/images/size/w800/2020/06/107_0724.JPG 800w">
      <figcaption>my caption</figcaption>
    </figure>
```

Where did the `/content/images/size/` come from? I have no folder like this on my server.

Old posts with Image component generate the following HTML:
```html
    <figure class="kg-card kg-image-card kg-card-hascaption">
      <img src="/content/images/2020/06/107_0724.JPG" class="kg-image" alt="">
      <figcaption>my caption</figcaption>
    </figure>
```
which is what I'd expect. As soon as I edit an existing post and save it, the images break with the `srcset` bit added and no actual sized images generated.

### Technical details:

* Ghost version: 3.20.3
* Ghost-CLI version: 1.14.1
* Node Version: v12.18.1
* Browser/OS: CentOS 7
* Database: mysql  Ver 15.1 Distrib 10.4.13-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by kevinansfield** [comment]
@SixBytesUnder the issue with `srcset` and `sizes` being output when the underlying installation does not support image resizing will be fixed in the next release of Ghost. After upgrading you'll need to re-render any posts that have broken images by changing something in the post content and saving.

> Where did the /content/images/size/ come from? I have no folder like this on my server.

Ghost generates resized images automatically the first time they are requested via the `/content/images/size/*` URLs. If it's not doing that then your install likely has file permission problems or the optional `sharp` binary (image processing library) was not able to be installed. If you want to fix your installation so that image resizing is available please ask on [our forum](https://forum.ghost.org) 🙂
