### ISSUE TITLE
Cannot search filtered list of members

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#11956]
When you filter the list of members and try to filter the list further using the searchfield the screen hangs up and shows the spinner infinitely.

### To reproduce:

1. Click on Members in the sidebar
2. Filter the list using any of the filter dropdowns in the top bar
3. Enter a search term

**Result:** a spinner is shown infinitely
**Expected behavior:** the list should be filtered by both the dropdown filters and the searchterm

**Comment by daniellockyer** [comment]
Fixed in https://github.com/TryGhost/Ghost/commit/f65c425786044d9ffdd5aaf835f6b84a6894f329 but missed this issue before pushing.

Sentry started flagging up a 500 error coming from the DB reporting an `Error: ER_NON_UNIQ_ERROR: Column 'name' in where clause is ambiguous` issue. The SQL and stack trace given made it pretty easy to narrow it down to the search functionality on the Members page.

https://github.com/TryGhost/Ghost/commit/f4d9a41d3bddb184b8d666c00c792e680564ee43 added a join onto `members_stripe_customers` to be able to filter by `paid`, but the `members_stripe_customers` also has `name`/`email` columns, leading to the ambiguity. The fix selects the `members` table to lookup from.
