### ISSUE TITLE
Headless: twitter:image won't be shown by Twitter cards due to robots.txt when Ghost site is set to private

### ISSUE THREAD

**Issue by tobimori** [TryGhost/Ghost#11989]
As per official documentation, a Ghost site should be set to private when running headless.
As per official headless starters, images will still be stored on the CMS site, but can't be accessed by Twitter because they respect the robots.txt which disallows all bots for all folders.
![example](https://user-images.githubusercontent.com/29142128/86277645-5a907200-bbd7-11ea-82d4-2398e30e7a83.png)

An fix would be to allow bots to access /content/images, e.g. by using a custom theme, which then redirects when a user stumbles upon the page. ([headless-placeholder](https://github.com/ShortTechDE/headless-placeholder))

Issue may be related to https://github.com/styxlab/gatsby-theme-try-ghost/issues/144

**Comment by tobimori** [comment]
Still a thing.

**Comment by jcomo** [comment]
A (not ideal, but good enough) potential workaround for those who stumble across this in the meantime:

You can create a mount path like `/ghost-proxy/` on _your_ server, where everything proxies to your ghost blog. Then, any crawlers will use the robots.txt from your domain instead of ghost.io

For example, if your ghost blog is at my-blog.ghost.io and your site is my-site.com, when you are generating the html for your pages, within the `twitter:image` (and other meta tags), you can do a string replace on the values to go from `https://my-blog.ghost.io/` to `https://my-site.com/ghost-proxy/`

As a bonus, here's a simple nginx config that pass anything to `/ghost-proxy` through to your ghost site.

```
  location /ghost-proxy {
    proxy_pass https://my-blog.ghost.io/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host my-blog.ghost.io;
    proxy_ssl_name my-blog.ghost.io;
  }
```

This still keeps your ghost blog site private, but the content (which is still public) can be freely accessed by crawlers.

Now, all that being said... this should definitely be re-opened for a solution. For what it's worth, I don't think that it should be solved with uploading a custom robots.txt -- it should just work out of the box.
