### ISSUE TITLE
No access to posts when members function is disabled

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11990]
### Issue Summary

No access to posts when members function is disabled.

### To Reproduce

1. Disable members function.
2. Go to the post.
3. If theme has support for members (Lyra, Pico, etc), you'll see CTA.
### Technical details:

* Ghost Version: 3.22.1
* Node Version: 12.18.1
* Browser/OS: All / macOS 10.15.5
* Database: sqlite3

**Comment by dsecareanu** [comment]
Can confirm this issue.

**Comment by gplone** [comment]
+1 Confirm for this issue.

**Comment by ErisDS** [comment]
Lyra and Pico are both explicitly designed to be used with the members feature.

We've changed some logic for members such that the `access` property, which is part of the members feature, is no longer exposed when members is not enabled, but when members is enabled it's now fully exposed via the API rather than only inside the `{{#post}}{{/post}}` block.

This is technically the correct behaviour 🙂 

The issue is that not exposing the property is the same as it being false, and so any theme that has `{{#if access}}` but doesn't have members enabled will return false.

I'm not convinced that changing this back is something we want to do at this point. Members is a beta feature and is therefore subject to change.

Lyra without members is literally the same as Casper.
Pico is meant for paid memberships.

I'm really not sure why these would be in use without members enabled 🤔

**Comment by fueko** [comment]
Hey @ErisDS, Lyra and Pico are just an example. 

> I'm really not sure why these would be in use without members enabled 

All themes on the marketplace will now be considered "broken". Because they are based on `{{#if access}}`.

> The issue is that not exposing the property is the same as it being false, and so any theme that has `{{#if access}}` but doesn't have members enabled will return false.

Will this logic be the correct solution?
```
{{#if @labs.members}}
{{#if access}}
{{content}}
{{else}}
CTA
{{/if}}
{{else}}
{{content}}
{{/if}}
```

**Comment by ErisDS** [comment]
Yes, adding a `{{#if @labs.members}}{{/if}}` guard around any members-specific code is the best way to ensure your theme won't do unexpected things when members is not enabled.

We will discuss adding the access property to the API permanently.

**Comment by fueko** [comment]
Thank you for confirmation, I'm starting to update themes :)

**Comment by dsecareanu** [comment]
> I'm really not sure why these would be in use without members enabled 🤔

There's a lot of membership enabled themes out there that people use for the visuals of the theme not necessarily for the membership feature (which can be toggled on/off)... and those themes are broken now (even though membership is disabled).

**Comment by ErisDS** [comment]
We have discussed this and decided to permanently add the access property to the v3 API, with a default of true. This will fix the existing broken themes. 

Note: it would be prudent for developers building themes that are intended to work with or without members enabled to double-check that all members-specific behaviour is gated with `{{if @labs.members}}{{/if}}` else things like this could happen again in future!

Members is still a beta feature and is subject to breaking changes. Therefore, relying on any helper or attribute that isn't documented in the theme docs is likely to cause pain in future: https://ghost.org/docs/api/v3/handlebars-themes/context/
