### ISSUE TITLE
Ghost 3.22.1 translation not working

### ISSUE THREAD

**Issue by jvin042** [TryGhost/Ghost#12003]
Since the update from version 3.22.1 of ghost the language translation no longer works and the english language is by default, I have this behavior on 7 clients website. I have downgrades on version 3.22 which does not have the problem. 
The name of the lang is well selected on the ghost interface.

### Technical details:

* Ghost Version: 3.22.1
* Node Version: Ghost Docker Image
* Browser/OS: Chrome
* Database: Sqlite

**Comment by ErisDS** [comment]
Adding reproduction case, which is missing from this bug report:

1. `ghost install v3.21.0 --local` (install version prior to settings changes)
2. Setup site, install WorldCasper2, set locale to e.g. fr
3. View the frontend of your site, text e.g. reading time will be "1 MIN DE LECTURE"
4. Run `ghost update`
5. Refresh frontend, translation strings are missing e.g. reading time will be "1 MINUTE READ"

The fix is to run `ghost restart`. 

@jvin042 there are no changes between 3.22.0 and 3.22.1 that could have caused this, downgraded just worked because an additional restart was triggered.

**Comment by jvin042** [comment]
A restart soluced a problem thanks.
