### ISSUE TITLE
Stripe plan validation errors during import

### ISSUE THREAD

**Issue by matthanley** [TryGhost/Ghost#12049]
### Issue Summary

Originally reported via [forum post](https://forum.ghost.org/t/import-failed-plans-cannot-have-an-amount-less-than-1/15867).

#11765 resulted in additional validation for Stripe plan amounts (via #11976) that prevents importing backups/exports from previous versions where plans were zero-valued.

### To Reproduce

1. Install Ghost 3.21.1
1. Update to Ghost 3.25.0
1. Export data
1. Attempt to import data

### Technical details:

* Ghost Version: 3.25.0

The fix for this issue should also include suitable test coverage to both confirm the issue and validate the fix. We may need to be more relaxed with validations during import, considering the related validation improvements in #12001

**Comment by naz** [comment]
@matthanley I've tried going through the reproduction steps and exported data from 3.21.1 it successfully passed through import on 3.25. Not even sure how the user could've gotter the error, because we explicitly skip import of [members_subscription_settings](https://github.com/TryGhost/Ghost/blob/37d577fa90c4dcb86d82180a581501cfba9abee4/core/server/data/importer/importers/data/settings.js#L121) :thinking:

**Comment by matthanley** [comment]
@naz I've updated the repro steps - it needs an upgrade since migrations are the only way to get the db in the state where `stripe_plans` exists as a key with the plan prices as 0 (the default is now non-zero and we have validation to enforce it).

This is a result of [this comment](https://github.com/TryGhost/Ghost/issues/11765#issuecomment-653427809):
> We have not removed existing 0 amount plans

**Comment by urlicht** [comment]
Is there any quick workaround by modifying the json file? Trying to setup again with a backup, but I got surprised by this error.
