### ISSUE TITLE
Subscribing with existing email in members list gives false positive on form submission

### ISSUE THREAD

**Issue by SamHellawell** [TryGhost/Ghost#12092]
### Issue Summary

This issue occurs in all browsers/environments. When subscribing to the blog with an existing email in the members list, the subscribe form and send magic link route tells the user that the email will be sent. The response from the `api/send-magic-link` route is also `Created.`.

### To Reproduce

1. Subscribe successfully to a ghost blog with your email
2. Try to subscribe again with the same email
3. Instead of informing the user it exists, or was an error, it says success and tells the user to check their emails
4. Email never comes as member already exists

### Technical details:

* Ghost Version: Latest
* Node Version: Any
* Browser/OS: Any
* Database: Any

**Comment by imox2** [comment]
@SamHellawell 

Not able to reproduce. Although the response from the api/send-magic-link route is 201 Created for existing and non existing member and frontend shows the same message.

**To Reproduce**
1. When I Try to subscribe again with the same email, I get a login magic link ✅ 
2. Try to subscribe again with the same email ✅ 
3. Instead of informing the user it exists, or was an error, it says success and tells the user to check their emails ✅ 
4. Email never comes as member already exists ❌    _I get an email with signin link_

![Screenshot 2020-09-05 at 1 21 01 AM](https://user-images.githubusercontent.com/6959913/92280135-6588bb00-ef16-11ea-834b-b43568f7ef36.png)
