### ISSUE TITLE
Admin UI Help Text not reflecting the routes defined in custom routes.yaml

### ISSUE THREAD

**Issue by shankscoder** [TryGhost/Ghost#12090]
The help text urls shown in the admin UI don't seem to use the current settings in the routes.yaml (if customized), but stick with defaults at time of installation.

This seems like a bug to me.

I've customized my routes.yaml as follows
```
routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /clips/:
    permalink: /clips/{slug}/
    template: index
    filter: primary_tag:clips
  /:
    permalink: /note/{slug}/
    template: index
    filter: primary_tag:-clips

taxonomies:
  tag: /topic/{slug}/
  author: /author/{slug}/
```

So, it turns out that the routes.yaml is work, as these pages are resolving to the correct paths:

- Tag Example: https://vetti.in/topic/clips/
- Post Example: https://vetti.in/clips/seneca-1/

The problem is that in the admin editor, these changes aren't reflected in the helptext, as shown here:

### Post Editor Settings
![Screenshot 2020-07-30 at 1 26 18 AM](https://user-images.githubusercontent.com/1317569/88847119-3474e680-d204-11ea-9386-98c56610338e.jpg)

### Tag Editor Settings
![Screenshot 2020-07-30 at 1 26 00 AM](https://user-images.githubusercontent.com/1317569/88847056-1e672600-d204-11ea-99f0-518d8f814c9b.jpg)
)

Note that both the help texts reflect the default settings, and not what's actually defined in the routes.yaml.

It took me a bit of time to realize that the changes were working on the front-end, but the backend isn't reflecting the changed urls.

IMO, the links should align with what's defined in the routes.yaml as then it allows staff to better visualize the url paths involved.

Might help to avoid confusion.

### Technical details:

* Self-hosted Setup
* Ghost Version: 3.25.0
* Database: SQLite

**Comment by ErisDS** [comment]
This is, for the time being, a wont-fix. 

Dynamic routing is a frontend feature and adding tight coupling to display these URLs in the admin panel is undesirable at the moment.

**Comment by brunogeronimo** [comment]
Hello @ErisDS,
Would it be possible to reconsider it?

Right now, I'm considering the option to migrate my blog to Ghost, and I am having a problem with shared URLs.

After changing the routes settings and setting up collections properly, I was able to almost mimic that structure, with a small issue.

Currently, I have two posts on my blog:
* `https://bruno.ge/trezor/`: The original version of it
* `https://bruno.ge/en/trezor`: The english version of the post above.

Unfortunately, Ghost does not allow me to keep that structure, since Ghost handles both URLs as if they were the same, and it doesn't allow me to keep that URL structure, forcing me to change one of them. The editor suggests me to use `trezor-2` for the second URL for example.

Is there a workaround for this use-case?

**Comment by brunogeronimo** [comment]
Hello @ErisDS,
Maybe I wasn't clear on the explanation. Sorry for that.

I currently have this URL problem when moving to Ghost **due to** not having a coupling between `routes.yaml` and the admin panel.

If the route defined on the custom `routes.yaml` was considered as part of the slug, I would not have this issue when moving my content to GhostCMS since one slug would be `/trezor` and the other one `/en/trezor`, and therefore allowing me to keep the same structure I currently have.

**Comment by ErisDS** [comment]
Hey @brunogeronimo I understand what you're saying, but again - your problem is not the same as this issue and is also nothing to do with your `routes.yaml`.

This issue is reporting that the help text under the "Slug" field in the post settings menu is not correct. The help text shows the expected URL based on the given slug, but doesn't take `routes.yaml` into account - so it can be wrong.

The problem you're reporting is that it's not possible to have the same slug for two posts - you want the slug for both to be `treznor` and the URLs to be `/treznor/` and `/en/treznor/`. Slug uniqueness is currently enforced at the DB level and relied on in several places in the codebase, so it's not a trivial thing to change. Definitely on our radar though.
