### ISSUE TITLE
Sending an email to paid members doesn't display a count

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#12112]
## Problem

When sending an post via email, if you go to send an email for a post with the "public" or "members only" access level set

Ghost tells you: will be published and sent to: 12 members

![image](https://user-images.githubusercontent.com/101513/89645737-56303680-d8b2-11ea-855b-2e0cf86331b8.png)

However, if you send an email with the access level set to “paid members only”

It tells you: will be published and sent to "all paid members"

![image](https://user-images.githubusercontent.com/101513/89645809-8677d500-d8b2-11ea-9ea2-d52a21847ef2.png)

However, seeing the number is critical information to make a decision on whether to send.

## Solution

We should always show the full number please!

**Comment by kevinansfield** [comment]
This is in master.

@ErisDS @matthanley I think there may potentially be some overlap with https://github.com/TryGhost/Ghost/issues/12031 if those stats are fetched via the API. Currently users with the Editor role to not see any member count in the email confirmation modal because they do not have permission to list members (we use the pagination data to get counts) but if they have permission to fetch stats we can use that endpoint instead.
