### ISSUE TITLE
Wrong mail sender when updating "Email addresses"

### ISSUE THREAD

**Issue by trongcauhcmus** [TryGhost/Ghost#12248]
### Issue Summary

Can not load config ```mail.from``` in config.json

### To Reproduce
I try to connect mailgun with ghost
when i use function update Support email address
the confirmation mail send to recipient with wrong title, although i have defined in config. It use the domain of recipient instead of taking config domain.

After debuging i found the bug at line 23 in file GhostMailer.js:  
```const address = requestedFromAddress || configAddress;```

i update this line:  
```const address = configAddress || requestedFromAddress;```
it worked

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 
Ghost-CLI version: 1.14.1
Ghost version: 3.35.0 (at ~/Documents/ghost)

* Node Version:
v10.15.3

* Browser/OS:
Firefox on Fedora

* Database:

**Comment by matthanley** [comment]
The behaviour described is the expected behaviour - when validating support email addresses we send from the same domain in order to detect DMARC policies etc that would block Ghost sending from that domain.

**Comment by samiy803** [comment]
This should not expected behaviour. The address listed in the config should be prioritized since the user is clearly trying to send from that specific address.

**Comment by octavian-one** [comment]
#15989 #12802 Related issues.
@samiy803 @matthanley

**Comment by QuentinN42** [comment]
@matthanley can you link me the documentation about that, can't find it.

Is there an override to force email being sent from mail.com when my blog is in blog.com ?

**Comment by shirish87** [comment]
@matthanley if that's the expected behaviour, then please note that in the latest version 5.49.1, the "Help! I'm not receiving emails" dialog box displays this "generated" email address to offer helpful tips:

Get in touch for help
If you've completed all these checks and you're still not receiving emails, you can reach out to get support by contacting `noreply@blog.domain.tld`

![screenshot_2023-05-27-22-31-09](https://github.com/TryGhost/Ghost/assets/304687/dd454045-9196-452c-986e-0821b7ad8917)
