### ISSUE TITLE
Incorrect theme is loaded for i18n locales when activating

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12271]
### Issue Summary

Ghost appears to load locales from the old theme folder when activating a new theme.

### To Reproduce

1. Set up a clean 3.35.5 site
1. Change the site locale to `it` (Italian) from Settings
1. Upload a theme with a `locales/it.json` file
1. Activate that theme
1. See that the translations are not working by checking the site

I've only briefly debugged, but `activeTheme` (below) is referring to the old theme name, which causes it to look up the wrong path and falls back to the `en.json` text. Possibly the i18n is being re-inited before settings cache has been updated or something (?)

https://github.com/TryGhost/Ghost/blob/d81b9c93b24d8218464925f335c956db05d0f267/core/frontend/services/themes/i18n.js#L23

I've reproduced this in 3.10.0 so it's not a new bug. Workaround is to restart Ghost which will cause it to load the correct locales.

### Technical details:

* Ghost Version: 3.35.5
* Node Version: 12.18.0
* Browser/OS: Firefox/Linux
* Database: SQLite

**Comment by naz** [comment]
The issue here spurs out of settings cache being updated after the even triggering i18n service to reload. Specifically this line: https://github.com/TryGhost/Ghost/blob/d81b9c93b24d8218464925f335c956db05d0f267/core/server/api/canary/themes.js#L40
sets a correct value to `active_theme`, but the event: https://github.com/TryGhost/Ghost/blob/d81b9c93b24d8218464925f335c956db05d0f267/core/frontend/services/themes/activate.js#L19
that triggers `init` method in ThemeI18n, is coming before settings cache has a chance to be corrected.

I think the best approach here would be to reduce dependency on `settingsCache` in `i18n` service and rely on the information coming with the event itself - would need to add current theme name when emitting `services.themes.activated` event. Possibly we could go even further and rely on `ActiveTheme` service instead of `settingsCache` to load up theme's name. The reason for this is that architecturally we are aiming to have as little dependencies on "server" services inside of "frontend".
