### ISSUE TITLE
Placing internal tag as first parameter in filter query causes a parsing error

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#12299]
### Issue Summary

When using internal tag as first parameter in `?filter` it causes a `400` "Error parsing filter" error.

### To Reproduce

1. Visit: https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&include=tags&filter=tag:-getting-started&tag=hash-internal and see filter working properly
2. Visit https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&include=tags&filter=tag=hash-internal&tag:-getting-started and notice the 400 error.

Filter order should not matter and should not be causing parsing errors. When looking into the issue would be worth checking if we should allow to filter by internal tags through Content API at all.

### Technical details:

* Ghost Version: 3.36.0
* Node Version: v112.18
* Browser/OS: FF latest
* Database: MySQL

**Comment by sainthkh** [comment]
I researched on this issue. And I found that there are some errors in the provided URL.

## Why Bad Request Happened

When a filter or filters are passed to the server by URL, it generates an NQL expression. With a single filter like `?filter=tag:-getting-started`, it is `(tag:-getting-started)+type:post`. `+type:post` is added here:

https://github.com/TryGhost/Ghost/blob/2600a20f5458684b52badd81453901c218cb5dcd/core/server/api/canary/utils/serializers/input/posts.js#L89-L95

When we replace `:` with `=` like `?filter=tag=-getting-started`, server fails parsing and returns 400 because `tag=-getting-started` didn't follow the NQL syntax. 

This is why the second URL failed. 


## Several Ways to Add Multiple Filters

When adding 2+ filters, there are several ways:

1\. Use filter multiple times: `?filter=tag:-getting-started&filter=tag:hash-internal`. One downside of this method is that we can only use `or` operator between filters. 
2\. Use `,` or `%2B`: `?filter=tag:-getting-started,tag:hash-internal` `?filter=tag:-getting-started%2Btag:hash-internal`
=>  `%2B` here is the encoded version of `+`. We cannot use `+` directly because it is replaced with a single space(` `) by Express. 
=> `,` is `or` and `%2B` is `and`

Now we can find an error in the first URL which is working. But it only applies the first tag filter and ignores the `hash-internal` filter. Express thinks `tag=hash-internal` as a new query argument with the name, `tag`, and the value, `hash-internal`, not a part of a multi-part filter. 

But there was no difference between the results because there is no post with `#internal` tag in `demo.ghost.io`. 


## The Working URLs.

The links below work:

* https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&include=tags&filter=tag:hash-internal,tag:-getting-started
* https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&include=tags&filter=tag:hash-internal%2Btag:-getting-started
* https://demo.ghost.io/ghost/api/v3/content/posts/?key=22444f78447824223cefc48062&include=tags&filter=tag:hash-internal&filter=tag:-getting-started


## Personal Opinion about Ignoring the Internal Tags in Contents API

I like the idea. But we need to loop through the list of tags to check if each of them is visible. We can't know before measuring it, but it can slow down the related API endpoints.

**Comment by ErisDS** [comment]
Closing this now as it seems the issue was malformed NQL strings and a lack of url encoding (filter params need `encodeURIComponent()` calling on them.

Note: if you use our [Content API Client](https://ghost.org/docs/content-api/javascript/) it handles all this for you.
