### ISSUE TITLE
Portal is not disabled when disabling the Button. 

### ISSUE THREAD

**Issue by rickdonato** [TryGhost/Ghost#12392]
### Issue Summary

This issue is based on the portal feature. My site already had membership enabled and the required profile pages etc.
With the portal feature enabled, even though I have removed the button via the portal setting, when users edit their payment details, and return to the site, the modal still appears. It would be great to be able to complete disable this feature via the admin portal. From what I can see this would just involve excluding the js file from being added to the DOM..

### To Reproduce

Install ghost with portal enabled. Disable the portal button, and enable membership. Then perform user member updates as user, via the member links (stripe) etc but not via the portal.

### Technical details:

* Ghost Version: 3.38.1
* Node Version: TBC
* Browser/OS: Chrome Windows 10
* Database: MySQL

**Comment by rishabhgrg** [comment]
Hey @rickdonato , thanks for raising. I looked into this and the earlier Portal script definitely had this issue where it showed the modal even if user edited their payment details via non-portal source. The latest version of Portal has fixed this and will only show modal if the billing change is done via Portal directly, otherwise not. You should be able to try it out without any changes on your end as we always load the latest version of script.

Excluding the portal js file in DOM is not a good solution because the file not only handles the modal but also any member interaction directly on theme as well so without the script none of the member actions will work

**Comment by rickdonato** [comment]
Thanks can you confirm what version fixes this.

**Comment by rishabhgrg** [comment]
@rickdonato The fix is live in Portal v0.13.1
