### ISSUE TITLE
[Portal] Portal script is not loaded on 404 pages

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12413]
### Context

Portal is currently injected in any Ghost theme via `ghost_head` helper which adds the latest script [here](https://github.com/TryGhost/Ghost/blob/master/core/frontend/helpers/ghost_head.js#L44-L48) in the header. Since `ghost_header` is used in `default.hbs` in most themes, this allows Portal script to be loaded and present on all theme pages and access Portal features like data attributes and links.

### Problem

The Portal script is not injected via `ghost_header` on error pages in theme, as a result any Portal links or data attributes used on the page doesn't work which is not ideal. This is mostly due to the missing context which `ghost_header` needs to inject most of metadata on the page, but needs more investigation.

The goal is to ideally have Portal script injected on error pages, and also making sure it doesn't cause any other unwanted side effects due to missing context.

**Comment by ErisDS** [comment]
I think this issue is mixing up error pages and 404 pages?

404 pages, e.g. in Casper, do call `{{ghost_head}}` and it will work. Some themes may not implement this though.
Error pages cannot call `{{ghost_head}}`, even if they use it, it will return empty if the status code is 500 or higher. This is because an internal server error happens, so we stop execution and just render the error. If we don't do this we get ugly "there was an error in the error template" errors as the code in ghost head invariably hits the same error.

**Comment by ErisDS** [comment]
I've looked into this today as part of another bug. It's because the portal scripts are being injected inside the `if (context)` block in ghost head.

Is there a reason they are being injected [here](https://github.com/TryGhost/Ghost/blob/main/core/frontend/helpers/ghost_head.js#L171-L173), instead of in the pre-existing [dont-do-this-for-amp block](https://github.com/TryGhost/Ghost/blob/main/core/frontend/helpers/ghost_head.js#L196-L208)?

@allouis can you confirm there is no specific reason for the original positioning https://github.com/TryGhost/Ghost/commit/8689493cf5ebd9e57dcb70e80756adb899ca7455?

**Comment by allouis** [comment]
Looks like a mistake to me! 

I do remember (incorrectly) including it for amp pages locally, and then fixing that - I'd wager a guess as that was where it was when it wasn't checking for AMP, and then I added the condition, rather than moving it!
