### ISSUE TITLE
TypeScript suggestion

### ISSUE THREAD

**Issue by ollydixon** [TryGhost/Ghost#12779]
I'm not sure where to put this; the feature request forum won't let me log in/register.

Have you guys considered rewriting the project into TypeScript?

It would be nice if we know what sort of data we're dealing with models, params and much more; otherwise, the project is very difficult to refactor and customize; breaking lots of stuff or changing a lot of unit tests, very boring way to work.

**Comment by KiraLT** [comment]
Typescript would be nice to have, but it would be an enormous refactoring. Well, it is possible to have mixed TS and JS files and refactor one file at a time. In any case, it depends a lot on Ghost core developers & contributors - how familiar they are with typescript. Because it's not a good idea to refactor everything to unfamiliar technology. 

I have [TryGhost/Portal](https://github.com/TryGhost/Portal) fork because I needed a lot to changes (multiple plans, passwords, etc...). The codebase is very messy and repetitive (don't get me wrong, it's not bad), so I rewrote the whole package to TS which let me customize it very quickly.

By the way, **feature requests and suggestions should go to [Ghost forum](https://forum.ghost.org/c/ideas/5)!* *

**Comment by ollydixon** [comment]
@KiraLT yeah I found that too; it's very hard to deal wtih; TypeScript would have made it much easier.
