### ISSUE TITLE
disable members sign-up and sign-in

### ISSUE THREAD

**Issue by y0y0z** [TryGhost/Ghost#12778]
i am using ghost 4.0.1 and would like to disable [members sign-up and sign-in](https://ghost.org/help/members-introduction/).

is there any option to do it or is it a missing feature?

**Comment by tmlmt** [comment]
Indeed, it sounds like Ghost has turned into a exclusively membership-based platform, even if you're (like me) just a dude wanting to post some stuff open to everyone. "Turn your audience into a business" says Ghost's homepage. Also, the little overlay saying "Publish with Ghost" when you want to sign up, is also a sign that development is made in order to boost Ghost as a business. 

Only way you can "deactivate" seems to be by modifying the theme and hiding the sign-up/sign-in stuff. The [removal of {{ @labs.members }} from theme properties](https://ghost.org/docs/themes/helpers/labs/) doesn't even allow theme creators to leave the option. I wish this could be simplified for opensource self-hosting users :)

**Comment by stukev** [comment]
Big +1 for me. A simple toggle in the settings would be appreciated.

**Comment by Erwyn** [comment]
+1 as well

**Comment by stukev** [comment]
Adding to @Erwyn's answer, this will hide the floating "subscribe" button:
```css
<style>
#ghost-portal-root {
  display: none;
}
</style>
```

**Comment by Erwyn** [comment]
nice catch. My theme might not be perfectly up to date so I don't have it
(yet). Thanks.

**Comment by srijan** [comment]
There's an "idea" in their forum which can be voted on/discussed: https://forum.ghost.org/t/remove-member-support-in-ghost-4/20800

**Comment by ErisDS** [comment]
There is currently no way to disable members as it is a core part of the product offering. We don't track feature or support requests here on the GitHub repo.

You are more than welcome to discuss this further on the forum (link above).

We ask that you take the time to read the issue template and not ignore it. Raising issues in spite of the guidelines means our team loses time to triaging issues instead of working on fixes and features.

**Comment by shafy** [comment]
I know this issue is closed, but you can easily turn off the Portal button in the settings.

**Comment by mdeneen** [comment]
I think that this issue needs to be reopened.  Without being able to disable this you are leaving users open to generating massive amounts of spam.  The spammer could not control the content of the message, but they could definitely get a person in trouble with their hosting provider or cause chaos within mailgun.

Given a large list of email addresses you could send them all messages through ghost using curl -- even if the host's theme was not using the member features.  You can't control the content of the message, but you can definitely send it.

To test this, I sent myself an email through a personal website which did not expose member functionality, @ErisDS.  Currently, if a user has their MTA or mailgun configured, they are open to sending as many emails as a malicious person would want to send.

**Comment by 1ndev-ui** [comment]
<style>
  .gh-head a, .header-cta {
	display: none;
  }
</style>

**Comment by 1ndev-ui** [comment]
`
<style>
  .gh-head a, .header-cta {
	display: none;
  }
</style>
`

**Comment by 1ndev-ui** [comment]
`<style>
  .gh-head a, .header-cta {
	display: none;
  }
</style>`

**Comment by 1ndev-ui** [comment]
```
<style>
  .gh-head a, .header-cta {
	display: none;
  }
</style>
```

**Comment by 1ndev-ui** [comment]
<style>
/* Removes Footer CTA Section */
.footer-cta, .site-footer-nav a {
    display: none;
}
</style>

**Comment by 1ndev-ui** [comment]
add this to your footer to remove the sign up option
```
<style>
/* Removes Footer CTA Section */
.footer-cta, .site-footer-nav a {
    display: none;
}
</style>
```
