### ISSUE TITLE
Dark Mode - Code Injection - JavaScript unreadable

### ISSUE THREAD

**Issue by petemahon** [TryGhost/Ghost#12774]
### Issue Summary

In the Ghost/Settings/Code Injection screen, dark mode makes JavaScript extremely hard to read. Functions are displayed in black on a dark background

### To Reproduce
Put any JavaScript into the box and switch on Dark Mode:

```
<script>
$('a').each(function() {
   var a = new RegExp('/' + window.location.host + '/');
   if(!a.test(this.href)) {
       $(this).click(function(event) {
           event.preventDefault();
           event.stopPropagation();
           window.open(this.href, '_blank');
       });
   }
});
</script>
```

The syntax highlighting should display functions (and all other syntax types) in a readable colour when dark mode is switched on.

### Technical details:

* Ghost Version: 4.0.1
* Node Version: 14.16.0
* Browser/OS: Version 89.0.4389.82 (Official Build) (64-bit) / Linux mint 19.3 Cinnamon
* Database: MySQL

**Comment by stromfeldt** [comment]
Not just JavaScript but also some CSS portions, which has to do with the CodeMirror theme?
<img width="327" alt="Screen Shot 2021-03-17 at 2 54 42 pm" src="https://user-images.githubusercontent.com/27488257/111429285-e7229680-874c-11eb-870d-11cb9ae4afb7.png">

I highlighted the text so that one can see what was "hidden".
<img width="327" alt="Screen Shot 2021-03-17 at 2 55 04 pm" src="https://user-images.githubusercontent.com/27488257/111429481-281aab00-874d-11eb-9481-11feab414a30.png">

Also:
<img width="368" alt="Screen Shot 2021-03-17 at 6 20 59 pm" src="https://user-images.githubusercontent.com/27488257/111429835-a2e3c600-874d-11eb-8620-ff83aa57ed38.png">

versus
<img width="368" alt="Screen Shot 2021-03-17 at 6 21 16 pm" src="https://user-images.githubusercontent.com/27488257/111429871-af681e80-874d-11eb-9741-4854c40b02c6.png">

**Comment by matthanley** [comment]
Closing in favour of #12831
