### ISSUE TITLE
Inline Code Wrapping Using Backticks Stopped Working in 4.0

### ISSUE THREAD

**Issue by ngreve** [TryGhost/Ghost#12789]
### Issue Summary

Automatic inline code using the `` ` `` character to wrap a word does not work anymore in 4.0, but worked in 3.4x.x.
I am a german keyboard layout.

### To Reproduce

You have to options to produce a backtick on this keyboard layout: 

1. Hold `shift` and press the `` ` `` key twice. This actually never worked to trigger inline code wrapping.
2. Hold `shift` press the `` ` `` key once and release `shift`. Finish by pressing `space` once. **This method worked in 3.4x.x but stopped working now.**

Oddly enough, formatting a code block with three `` ` `` using the second method, still works. 

### Technical details:

* Ghost Version:  4.1.0
* Node Version: v14.16.0
* Browser: Firefox Developer Edition 87.0b9 / Chromium 89.0.4389.90
* OS: Arch Linux

**Comment by ErisDS** [comment]
I am not able to reproduce what you are saying.

What works for me in both 3.x and 4.x (with a German input keyboard) is:

- Hold shift and press the ` key  
- Type your text
- Hold shift and press the ` key  
- Hit space to trigger the conversion

This is slightly different to the UK keyboard where hitting the ` key the second time triggers the conversion, I expect this is because of the need for the shift key. I don't think it's heinous but PRs are welcome if you want to unify the behaviour.

Neither pressing the ` key twice on the uk keyboard, nor pressing shift ` twice + space  on the german keyboard works. There has to be some input between them.

I understand people do this to try to copy and paste afterwards,  but the implementation as it stands is designed for as-you-type conversion. So this is all working as expected.

**Comment by ngreve** [comment]
If I follow your instructions I end up with input like ``àpple` ``. Notice the grave accent above the first letter. See screen recording:

https://user-images.githubusercontent.com/18660100/111908778-d75fc680-8a5a-11eb-912f-3a5f5340480a.mp4
