### ISSUE TITLE
Password Protected is looping

### ISSUE THREAD

**Issue by thethev** [TryGhost/Ghost#12785]
### Issue Summary

I just setup a Ghost bloogin site. I want to restrict access with a password (Settings > general > advanced settings > Make this site private).

### To Reproduce

1. Activate the "Make this site private" and setup a easy password (like beyibo170)
2. Save
3. Try to connect with the password. Nothing work, the connection page remains.

### Technical details:

* Ghost Version: 4.0.1
* Ghost-CLI Version: 1.16.2
* Node Version:v14.16.0
* Browser/OS: Microsoft Windows 10 Famille, v10.0.19042
* Database: sqlite3

**Comment by vikaspotluri123** [comment]
@thethev is your site served over http by any chance? I'm able to reproduce this using a local installation of ghost.

**Technical Details:**

The Set-Cookie header is ignored by Chrome because of the SameSite attribute. Message:

> This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None".

Related Header:
```
Set-Cookie: ghost-private=removedForBrevity; path=/; expires=Sun, 18 Apr 2021 11:20:43 GMT; samesite=none; httponly

**Comment by rudxde** [comment]
For me, the issue was that i had configured `url` and `urlSSL` but used a nginx reverse proxy. In the line `https://github.com/TryGhost/Ghost/blob/62ee693310af076cefbb2e8c87cb6d5f8e42ebdd/core/server/services/auth/session/express-session.js#L27` only the `url` is checked if the site is https, therefore i put the https address in the `url` and removed the `urlSSL`. Afterwards i had the TOO_MANY_REDIRECTS problem as described in this issue (https://github.com/TryGhost/Ghost/issues/11578#issue-561978162). After solving this it worked
