### ISSUE TITLE
Seeing HTTP 401 on an XHR request while not using Portal (the portal JavaScript is still being included)

### ISSUE THREAD

**Issue by valeriansaliou** [TryGhost/Ghost#12793]
### Issue Summary

Since upgrading to Ghost v4 on a self-hosted instance, a JavaScript related to Portal is being loaded (included in `{{ghost_head}}` by Ghost itself), while Portal is not used and disabled (ie. not configured).

This JavaScript is loaded from `https://unpkg.com/@tryghost/portal@~1.0.0/umd/portal.min.js`, which is not needed in this case, and attempts to perform an XHR to `/blog/members/api/member/` that returns HTTP 401 (`Cookie ghost-members-ssr not found`).

I've investigated, and found out that the Portal JS is unconditionally included in `ghost_head`. It should only be included if Portal is in use (and as well, allow to use a self-hosted JavaScript if possible, for OSS installs).

Note that Google generates SEO warnings due to the XHR request reporting as 401, which is how I found out about this newly included script.

Code references:

- JS code generator: https://github.com/TryGhost/Ghost/blob/main/core/frontend/helpers/ghost_head.js#L39
- JS code include: https://github.com/TryGhost/Ghost/blob/main/core/frontend/helpers/ghost_head.js#L181
- JS resource URL: https://github.com/TryGhost/Ghost/blob/main/core/shared/config/defaults.json#L123

Indirectly related: #12778

### To Reproduce

1. Disable Portal on a theme with `{{ghost_head}}` support
2. Inspect the blog pages, which will contain `<script defer src="https://unpkg.com/@tryghost/portal@~1.0.0/umd/portal.min.js" data-ghost="https://crisp.chat/blog/"></script>` (which we do not want here)

**I would expect the Portal script not being included in the case Portal is not configured.**

### Technical details:

* Ghost Version: `v4.1.0`
* Node Version: `v10.21.0`
* Browser/OS: (does not apply)
* Database: (does not apply)

**Comment by khassel** [comment]
meanwhile you can patch the mentioned `default.json` setting the `url` key in [line 124](https://github.com/TryGhost/Ghost/blob/eb5f7a8e2d489a24f663991af15d84f54d803bad/core/shared/config/defaults.json#L124) to an empty string (or an empty script).

This downgrades the error to a warning.

**Comment by ErisDS** [comment]
The portal script is required, whether or not you are using the portal UI as it also handles other JavaScript hooks in the theme.  Ghost doesn't know if your theme is or isn't using those hooks so the script is always required. Therefore this is expected behaviour, not a bug.

**Comment by valeriansaliou** [comment]
I see, thanks for the reply. Then I guess it'd be good that the `/blog/members/api/member/` HTTP route called return a 2xx status code even if not configured, as it's seemingly ringing alerts on Google's SEO tools, and other tools.

Which I think is a non-issue report you'll receive on a recurring basis from Ghost or Ghost Pro users.

**Comment by ErisDS** [comment]
We are looking at ways to mitigate the 401, but it's a slightly different issue :)

**Comment by ThomasArdal** [comment]
@ErisDS I feel the need to get out some frustrations here that I hope in return will help you when developing new features going forward. Introducing Membership is a great addition to the product but not something that we as a company are planning to use. My guess is that most companies won't since they earn their revenue elsewhere and the blog is there to support their business only and not be responsible for revenue. That's why I believe that from one major to another introducing a new large (almost 500 kb!) script is a bad practice. As described here the script is used for other features than just Membership which requires a lot of testing on our part to figure out if it can be removed or not (or replaced with an empty script to avoid Ghost generating invalid HTML). Also, the script is injected directly into the `head` section of the markup. We have built a custom theme and reference all JavaScripts just before the end `body` tag. As already suggested by other users, having a script this large and then in the head, completely destroys the Lighthouse score.

I hope that you can use the feedback here. Introducing stuff like this will definitely make me think twice about upgrading to a new major next time. If introducing new features like this, at least let us opt-in or out from them by separating core stuff from the feature stuff and only include the feature-specific code if enabled through the settings.
