### ISSUE TITLE
Signup Modal still accessible after hiding portal button using Ghost Admin

### ISSUE THREAD

**Issue by CraigLu** [TryGhost/Ghost#12927]
### Issue Summary

Sign in/sign up modal still accessible even if portal button is hidden. If the URL ends in `#/portal` the sign up/sign in modal will popup.

Although unlikely for someone to "discover" this URL, this seems like an oversight that `#/portal` will always lead to the modal showing up if I do not plan to have any membership at the moment (I'm hiding the portal button for a reason). Even something like `#/portal/adwadawdawdawd` will pop the modal.

### To Reproduce

1. Hide portal overlay: Settings -> Portal -> Show Portal button = off
2. append `#/portal` to end of live site URL
3. Sign up/sign in modal appears

### Technical details:

* Ghost Version: 4.3.3 (live ghost subdomain)
* Environment production
* Database mysql
* Mail SMTP
* Browser/OS: Google Chrome Version 89.0.4389.128 on macOS Big Sur Version 11.1

**Comment by ErisDS** [comment]
Hi there! This is expected behaviour. Disabling the portal button is only intended to disable the button.

If you want to disable members you need to go to settings > access and choose nobody.

 If you ever need a hand configuring your **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly 🙂
