### ISSUE TITLE
Uploading an empty redirects.yaml causes `Cannot read property '302' of undefined`

### ISSUE THREAD

**Issue by xsdg** [TryGhost/Ghost#12945]
Ghost should either reject an empty (0 bytes long) YAML file as containing zero redirects, or it should throw an exception advising that an empty file is not accepted.  My preference would be the former, since an empty YAML file appears to be technically valid according to random Googling.

That said, fundamentally, this code should be checking for whether those properties exist before accessing them for iteration:
https://github.com/TryGhost/Ghost/blob/273e22032761d39aef10e0b9a90584f31b0271c9/core/frontend/services/redirects/settings.js#L77

**Comment by xsdg** [comment]
A slightly different manifestation of this bug:
If the uploaded file contains exactly the contents `---`, then this also blows up in the expected way, but this time with the slightly different error, `Cannot read property '302' of null`

Presumably, any valid YAML file that happens to not contain the keys `301` and `302` would cause this to fail.

In particular, I notice that the tests only validate a single sample file, which happens to have both keys defined, so it would not trigger this bug:
https://github.com/TryGhost/Ghost/blob/7528ec8c3b44226896dff1edb7cd03dfd77c4e0d/test/regression/api/canary/admin/redirects_spec.js#L257

**Comment by ErisDS** [comment]
Hi @xsdg,

yaml support is quite a recent contribution to Ghost. I agree it seems the error handling could be improved. If that’s something you’re interested in working on let us know! 

Otherwise as mentioned already, if you need support getting your redirects setup on Ghost(Pro), please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly 🙂

**Comment by hey24sheep** [comment]
This issue isn't stale as there is an updated PR referecning it.
