### ISSUE TITLE
Members still have access when their status is UNPAID

### ISSUE THREAD

**Issue by xoxoxo** [TryGhost/Ghost#12956]
### Issue Summary 

Members that paid previously and now are set to unpaid seems to get access to paid content.

Seems like **@member.paid** status is paid regardless if user is paid or unpaid same with **{{content}}** helper. Only works fine if user canceled subscription.

### Technical details:

* Ghost Version: 4.4
* Node Version: 12
* Browser/OS: All
* Database: mysql

**Comment by ErisDS** [comment]
Hi @xoxoxo, apologies for the delay in response here.

This is expected, intentional behaviour. There are many use cases where accounts can be deliberately set to unpaid, where the expectation is that the member still has access. 

The only status in which members do not have access is `canceled`.

However, this information was missing from our documentation, which has now been updated. See https://ghost.org/docs/themes/members/#the-member-object and https://ghost.org/docs/themes/members/#subscription-attributes.

Importantly: 

> `@member.paid` returns `true` for members with active subscriptions in states “active”, “trialing”, “unpaid” and “past_due”. To revoke access for members with failing payments, update your Stripe settings to automatically cancel subscriptions after all payment attempts have failed.
