### ISSUE TITLE
Powered-By badge in Signup portal breaks design

### ISSUE THREAD

**Issue by lfuelling** [TryGhost/Ghost#12988]
**This is not a feature request**

### Issue Summary

As I've already described in #12960 (which a bot closed because of a wrong label), the Powered-By Badge in the subscription portal (actually the whole portal but the badge is the most annoying) is breaking my design.

I'm sorry that I've formulated it like I wanted to request a feature. The fact is: This is breaking my design, so **it's a bug**.

### To Reproduce

1. Open any Ghost Blog (preferably with a custom theme so it stings more)
2. Click the subscription button
3. The badge is at the lower left corner

A workaround I've considered is overwriting the CSS in my theme but that is not possible since the portal is implemented using iframes which can't be styled by the CSS in the parent page.

Since I don't want to sign up into yet another forum I can't *request* a specific way on how to handle that (although I have a few ideas), I just want my blog to look good.

### Technical details:

See the original ticket.

**Comment by ErisDS** [comment]
Hi @lfuelling, your issue was closed because I deliberately marked it as a feature request. Asking for a way to disable something that is currently purposefully always enabled is a feature request. As clearly stated in several places, we don't track feature requests here in GitHub. Whether you choose to engage with us about features on the forum is of course your choice, the same as it's our choice what issues we do and don't keep open on our repositories.

Portal is an optional UI. *You don't have to use it*. If you want to build your own custom signup UI in your theme, you absolutely can, here are the docs: https://ghost.org/docs/themes/members/#signup-forms.
