### ISSUE TITLE
Unable to unsubscribe from newsletter

### ISSUE THREAD

**Issue by nehalist** [TryGhost/Ghost#12996]
Toggling the newsletter results in

```
Uncaught TypeError: Cannot read property 'context' of undefined
    at portal.min.js:3
    at onToggle (portal.min.js:3)
    at onClick (portal.min.js:3)
    at Object.l (portal.min.js:3)
    at d (portal.min.js:3)
    at portal.min.js:3
    at b (portal.min.js:3)
    at an (portal.min.js:3)
    at tn (portal.min.js:3)
    at on (portal.min.js:3)
```

Reproduceable on https://demo.ghost.io/#/portal/account

Since the Portal has no issue tracker for whatever reason there's one additional thing I'd like to point out: please do NOT load the latest version of the portal script automatically. This is highly insecure and can cause serious damage for obvious reasons.

**Comment by rishabhgrg** [comment]
Thanks for the issue and PR @nehalist . By default, a released Ghost version only loads the latest patch on tagged minor version for Portal script specified in [config](https://github.com/TryGhost/Ghost/blob/main/core/shared/config/defaults.json#L123-L126). This is the expected behaviour for now as it allows us to patch any critical bug in Portal not related to Ghost changes directly.

**Comment by ErisDS** [comment]
Portal doesn't have it's own issue tracker, but it does have a security policy: https://github.com/TryGhost/Portal/security/policy

If you think you've found a vulnerability please follow the policy and disclose responsibly.
