### ISSUE TITLE
Redirects import doesn't allow .yml files

### ISSUE THREAD

**Issue by johlym** [TryGhost/Ghost#13099]
### Issue Summary

Ghost 4.x supports uploading YAML instead of JSON for a list of redirects. Under 4.8.3, at least, the UI explicitly requires that the YAML file have the `.yaml` extension, disregarding that while `.yml` is not the _official_ file extension, it is commonly accepted in the industry and widely used. JSON is not subject to this level of ambiguity (there are no `.jsn` files, for example).

### To Reproduce

1. Have an installation of Ghost 4.x, ideally 4.8.3 to reproduce this exactly.
2. Create a `redirects.yml` file based on the prescribed documentation
3. Attempt to upload, receive an error.
4. Rename to `redirects.yml`, see upload acceptance.

The Admin controller `settings/labs.js` [here](https://github.com/TryGhost/Admin/blob/main/app/controllers/settings/labs.js#L29) only defines `.yaml`.

See ambiguity cited [here](https://dev.to/derek/so-is-it-yaml-or-yml-lh2), [here](https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml), and h[here](https://www.reddit.com/r/ansible/comments/cnsspu/yml_vs_yaml_file_extention/)

### Technical details:

* Ghost Version: 4.8.3
* Node Version: 14.17.1
* Browser/OS: macOS 11.4; Safari 14.1.1
* Database: MySQL 8

**Comment by ErisDS** [comment]
I recognise there is ambiguity in the community, however `.yaml` is the official and therefore correct extension for a YAML file. Our lack of support for `.yml` is also true with the routes files, and is very intentional.

Adding support for both increases code complexity & creates additional questions and potential overhead e.g. if you upload a `redirects.yml` file, should the downloader maintain your extension or are we ok to write the file as .yaml so we don't have to go searching for different extensions - or do we now have to implement a lookup system to find the right file... and then what do we do if there are both?

I do realise it can trip up some people who are used to `.yml` files and mean they have to rename a file, but in this case, I don't think solving that is worth the cost in code and maintenance.

Alside: I'd love to see the technical world standardise on the correct extension - maybe you could go open this issue on all the projects that incorrectly use `.yml` 😬
