### ISSUE TITLE
Unable to import Members - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vicky002** [TryGhost/Ghost#13216]
### Issue Summary

I have Ghost Self-hosted. 

When I try to import my subscribers from Substack, it shows this error as shown in the image. 

I tried searching everywhere but no solution. I also tried to manually create the `Members` folder on the server but still no luck. 
![CleanShot 2021-08-07 at 20 42 50@2x](https://user-images.githubusercontent.com/5517129/128604907-9d7cab8d-0d6b-4cbb-a858-7fec4b6d9b88.png)

A summary of the issue and the browser/OS environment in which it occurs.

### To Reproduce

Go to your Self-hosted Ghost blog

1. Create a CSV file containing a few emails
2. Try to import that CSV file 

### Technical details:

* Version 4.7.0
* Environment production
* Database sqlite3
* Mail SMTP
* Server: Azure App Service

**Comment by ErisDS** [comment]
This is a bug with windows paths. Ghost is primarily written for & tested on unix/linux/mac based environments but we're happy to accept PRs fixing this.

**Comment by tawandamoyo** [comment]
Hi, I'd like to try my hand on this but not sure where to start. Also would I need to be on a Windows machine?

**Comment by chakrabortysayantan699** [comment]
Hi @ErisDS  ,  I'd like  to give a try to resolve this issue ,I am a beginner please guide me where to start  and I am using windows

**Comment by ZaidYounan** [comment]
Hi, I think I'm onto a solution but not exactly sure how to implement it within your code. The top comment on this stackoverflow thread does a good job of describing it.

```https://stackoverflow.com/questions/25090101/is-there-a-difference-between-and-paths```

It seems like there is a disconnect between the path being supplied, and how the path seperator is being interpreted. I can think of a few possible solutions to try because the node path module (which you've already imported) provides some methods to get around this, like this one.

```https://nodejs.org/docs/latest/api/path.html#path_path_tonamespacedpath_path```

Which would return the file path with the appropriate path prefix (i assume this would be "C:\\") ONLY for windows machines, and for other systems it would simply not modify the file path. But I'm new and I'm currently unfamiliar with node.js, so haven't yet figured out how to implement that to test it.

**Comment by deepto98** [comment]
@ErisDS If this issue is still open, can I pick it up?

**Comment by danimajo** [comment]
See https://github.com/TryGhost/Members/pull/355
