### ISSUE TITLE
macOS Non-Latin IME input issue

### ISSUE THREAD

**Issue by lifehome** [TryGhost/Ghost#13325]
### Issue Summary
When you tries to input non-latin glyphs(e.g., Chinese characters) into the editor, either plain text or with addon like Markdown block or HTML block, it always breaks.

Not only cannot type properly, but typing with IME also breaks the entire blog post...  
It is very frustrating to "undo" and "redo" all the typings and things...

### Security concerns
I am aware that Ghost probably using mobiledoc for a while? I am not yet having the time to trace down the rabbit hole, but I do see there are CVE for that specific library, and I am really concerned if I should continue the use of Ghost...?

### To Reproduce
1. Create a new post
2. Start typing some non-latin characters

### Screencast
https://user-images.githubusercontent.com/1886237/133989711-0fdc2be7-f593-44ee-8ba0-7ce00ab80335.mp4

### Technical details:
* Ghost Version: `4.14.0`
  - Docker tag: ghost:alpine(`ghost@sha256:7f22aaffb1e46803280101e22f54c19d958405d25faf0bc0035ef63ce08b21f7`)
* Node Version: `14.17.6`
* Browser/OS:
  - Client side: macOS 11.6 on Firefox 92.0
  - Server side: Arch Linux on Linux kernel 5.13.13
* Database: Probably SQLite...?

### Possible related issue (and probably not getting fixed on the root cause?)
- codemirror/CodeMirror#4096
- #12820
- #12268
- #11460
- #9801
- #9289
- #9012
- #8319

**Comment by mkyos** [comment]
The problem of typing CJK texts with initials seems to have been solved in the current version. Do you mean such an issue?

**Comment by ErisDS** [comment]
Hi there 👋 

I suspect this is an upstream issue in [mobiledoc-kit](https://github.com/bustle/mobiledoc-kit). So that we can be sure would you be able to test out the same key strokes in the mobiledoc kit demo here:

https://bustle.github.io/mobiledoc-kit/demo/ 

Please let us know if you can see the same issue when typing there or not.

Also, in terms of us being able to reproduce the issue, it would be very handy if you could provide the exact reproduction steps, including exactly which keys are being pressed and their order, plus which main keyboard language you are using.

If you're able to, screencasts with the keyboard viewer present on mac, or that otherwise show the exact keys pressed would be very helpful.
