### ISSUE TITLE
Typing Japanese characters at the end/beginning of a link text duplicates input

### ISSUE THREAD

**Issue by sidemt** [TryGhost/Ghost#13740]
### Issue Summary

When you type at the end or beginning of a link text with Japanese IME it does not work properly.
It may happen with other non-Latin languages too such as Chinese or Korean.

### Steps to Reproduce

1. Create a new post
2. Type some text and convert it into a link
3. Place the cursor at the end of the link text
4. Turn on Japanese IME and start typing Japanese
   Example: Type "nihonngo" on your keyboard to input Japanese Hiragana characters "にほんご", and then convert it into Kanji characters "日本語" by hitting the space bar. Confirm the conversion with the enter key.

**Actual behavior:**
The input characters get duplicated every time you type. And they delete the link text.
![ghost_editor_japanese2](https://user-images.githubusercontent.com/25644062/141615527-26c4db0b-faf7-4d1b-8e06-bb99faeb2e0e.gif)

If you placed the cursor at the beginning of the link text in Step 3, then only the first letter you type is duplicated.
![ghost_editor_japanese4](https://user-images.githubusercontent.com/25644062/141615589-5d43182c-2126-4306-bcc2-d84050519300.gif)

**Expected behavior:**
The Japanese text should be displayed correctly.

If it worked correctly, the input behavior should look like this even if it was next to a link text.
![ghost_editor_japanese3](https://user-images.githubusercontent.com/25644062/141615538-dfda370d-d0c4-4208-8003-3fc80574283f.gif)

### Ghost Version

4.22.1

### Node.js Version

14.18.1

### How did you install Ghost?

Ubuntu 18.04.6 LTS (WSL)

### Database type

MySQL 5.7

### Browser & OS version

Chrome 95.0.4638.69 (Official Build)(64 bit)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by baptiste00001** [comment]
Did a bit of digging and I see that when the cursor is placed at the end of a link, every key input creates a new text node instead of grouping the text as one unique text node.
The result is that each character is taken separately and "い" "n"　is input instead of "に"
(you can reproduce it by opening the developer tools in Brave or Chrome)

I noticed that there is no such problem in the wordpress editor.
I checked and noticed that in wordpress when the focus is on a link text, the editor automatically adds a Zero Width No-Break Space at the end of the text. (Hex Code: &#xfeff; Decimal Code: &#65279;)
That character is removed once the focus is lost.
Not sure if this is what helps but it might me worth investigate.

Also, the wordpress editor uses tinymce as their javascript library.
Maybe there is something in that library that takes care of Japanese input.

**Comment by baptiste00001** [comment]
OK
Forget about the Zero Width No-Break Space.
I think that this actually unrelated to the problem.

What would be an easy fix though would be to change the behavior such that when inputing text at the end of a link text it adds text inside the `<a></a>` tags instead of outside, so that no new text node is created.

so for example a text like this 
<a>some text</a> 
would become
<a>some textに</a>
instead of
<a>some text</a>いn

This is after all the better behavior in my opinion but it would change some habits.

**Comment by baptiste00001** [comment]
Here is some code found in core/client/lib/koenig-editor/addon/components/koenig-basic-html-textarea.js 

```
// if the cursor is at the end of one of our "special" markups that can only be
// toggled via markdown expansions then we want to ensure that the markup is
// removed from the edit state so that you can type without being stuck with
// the special formatting
function toggleSpecialFormatEditState(editor) {
    let {head, isCollapsed} = editor.range;
    if (isCollapsed) {
        Object.keys(SPECIAL_MARKUPS).forEach((tagName) => {
            tagName = tagName.toLowerCase();
            if (head.marker && head.marker.hasMarkup(tagName) && editor._editState.activeMarkups.findBy('tagName', tagNa
me)) {
                let nextMarker = head.markerIn(1);
                if (!nextMarker || !nextMarker.hasMarkup(tagName)) {
                    // there is a bug somehwhere that means after pasting
                    // content the _editState can end up with multiple
                    // instances of the markup so we need to toggle all of them
                    editor._editState.activeMarkups.filterBy('tagName', tagName).forEach((markup) => {
                        editor._editState.toggleMarkupState(markup);
                    });
                }
            }
        });
    }
}
```

Looks like this could be the place to check.

**Comment by baptiste00001** [comment]
The problem seems to be that in some areas (bullet lists, link text) the HTML in the editor is refreshed for every key input.

Therefore languages that require several consecutive key inputs to write one character are broken (Japanese, French accents, German special characters,...)

This issue is actually related to those two other issues concerning dead keys: #13058 and #11316

I don't see any simple fix except stopping refreshing the HTML for every key input.
Would be nice to get the opinion of some members of the core team.

**Comment by ErisDS** [comment]
Hi there 👋 

I suspect this is an upstream issue in [mobiledoc-kit](https://github.com/bustle/mobiledoc-kit). So that we can be sure would you be able to test out the same key strokes in the mobiledoc kit demo here:

https://bustle.github.io/mobiledoc-kit/demo/ 

Please let us know if you can see the same issue when typing there or not.

Also, in terms of us being able to reproduce the issue, it would be very handy if you could provide the exact reproduction steps, including exactly which keys are being pressed and their order, plus which main keyboard language you are using.

If you're able to, screencasts with the keyboard viewer present on mac, or that otherwise show the exact keys pressed would be very helpful.

**Comment by baptiste00001** [comment]
Hello,

I can confirm that in the mobiledoc kit demo, Japanese words are duplicated.

Unfortunately, the issue has already been reported since 2019 on their github, including in [this thread ](https://github.com/bustle/mobiledoc-kit/pull/661), but was never fixed.

Concerning the keys pressed to reproduce the problem, I see the behavior in the mobiledoc kit demo and in Ghost editor to be a little bit different.

First add Japanese keyboard in the mac system preferences

**Typing 日本語 ("nihonngo" then enter) in the mobiledoc kit demo, word is duplicated**

https://user-images.githubusercontent.com/54464650/143533961-ea0eca13-84c9-48e1-8269-f955475aa7cf.mov

**Typing 日本語 ("nihonngo" then enter) in the Ghost editor it works fine**

https://user-images.githubusercontent.com/54464650/143534048-ada1654b-9a8b-4d25-bb1a-5143f2bf9dc2.mov

**However typing 日本語 ("nihonngo" then enter) in the Ghost editor at the end of a link it becomes broken**

https://user-images.githubusercontent.com/54464650/143534151-41dfd1ca-1da0-47eb-99c5-e1acd187af4f.mov

**If there is a space after the link it works fine again**

https://user-images.githubusercontent.com/54464650/143534298-734202da-4ed2-4015-9199-1ab0bb214c67.mov

Again, maybe not of the highest priority, but a bit of an annoyance for East Asian writers.

**Comment by ErisDS** [comment]
Ok great, thanks for providing this information. It seems to me that there may be a Ghost-specific bug around links. 

A PR fixing this would be greatly appreciated by those using IME.
