### ISSUE TITLE
Magic links creates member even if subscription access is set to “Only people I invite”

### ISSUE THREAD

**Issue by sunknudsen** [TryGhost/Ghost#14019]
### Issue Summary

Clicking magic link creates member even if member has been deleted and subscription access is set to “Only people I invite”.

As a result, banned member (for example) can recreate him/herself within a 24-hour window.

### Steps to Reproduce

1. Set subscription access to “Only people I invite” on `/ghost/#/settings/members`
2. Create new member on `/ghost/#/members`
3. Log in as new member on `/`
4. Click magic link in email
4. Delete member on `/ghost/#/members/…`
5. Click same magic link in email

Member is logged in and is no longer deleted.

### Ghost Version

4.32.2

### Node.js Version

14.18.2

### How did you install Ghost?

Using Ghost CLI on macOS Big Sur

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by matthanley** [comment]
Hey @sunknudsen 👋🏼

Signup links are currently implemented as signed URLs so that Ghost doesn't store any member information (such as email address) until they've explicitly opted-in from the email. As Ghost doesn't store any state related to the signup, it means we're unable to revoke the signup URL, and once a member has been deleted we have no record of that member ever existing so they're able to sign up again.

This is expected behaviour at the moment, and is not a bug. Adding the ability to ban specific members from signing up would be a feature request that belongs on the [forum](https://forum.ghost.org/c/ideas/5).
