### ISSUE TITLE
AMP YouTube video looks too small 

### ISSUE THREAD

**Issue by rubalv96** [TryGhost/Ghost#14020]
### Issue Summary

When you insert a YouTube video into a post and view it with AMP the video looks very small. The <amp-youtube> element that Ghost generates contains fixed width and height sizes.
There is no solution to view those YouTube videos with a proper size in the AMP version.

![image](https://user-images.githubusercontent.com/36295331/150339812-3697bfb6-e909-4910-ad0e-7a7ce3cad4c3.png)

### Steps to Reproduce

1. Insert a YouTube video in a post.
2. View this post in the AMP version
3. You will see that the inserted video is displayed at a very small size.

### Ghost Version

4.3.3

### Node.js Version

v14.17.1

### How did you install Ghost?

Ubuntu 18.04.5 LTS

### Database type

SQLite3

### Browser & OS version

Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Thanks for the bug report. We'd love a Pr to fix this :)

**Comment by denik1981** [comment]
Seems the problem is that Amp is trying to parse an already defined iframe with fixed set widths and heights. And to be non-obtrusive I believe it is extracting those and using them as their own attributes giving the wrong expected behavior of having a tiny video. 

The width and height are already present from the model and I don't think they are necessary because in non-amp pages there is a process which is sanitizing videos giving them a responsive behavior (check jquery.fitvids.js).

With my lack of knowledge about what ghost does, I cannot say very much, but I suspect the place on where to check for a fix is within the Koening editor which is IMHO rendering the HTML iframes that we are seeing in the persistent model. Check for _popupateIframe function and see if it is possible to remove the width and height attributes from there.

**Comment by sahyrlelyaams** [comment]
Wanted to try my hand at fixing this...
Any pointers on how to view the post in AMP?

**Comment by matthanley** [comment]
@sahyrlelyaams you can add `/amp` to the end of the URL for a published post to view the AMP rendered version.
