### ISSUE TITLE
Static Asset Management

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#1405]
It's time to upgrade Ghost's static asset system to something a little more heavy duty, so that we can handle more use cases, and also add proper cache control headers as discussed at length in issue #932 (closed in favour of this issue).

We need to be able to serve static assets for 
- Ghost admin
- themes 
- apps
- images

This should entirely replace or wrap our current usage of connect static.

We still need to be able to hot-swap themes.

This needs to be abstracted so that it uses local file storage by default, but so that we can provide a way for apps to override this. They may wish to use a CDN, or store files elsewhere.

Static assets need to be versioned so that the cache can be invalidated. This should be done using a hash of the file which is appended to the filename, something like (ghost.js -> ghost.aba23928.js)

We'll need a helper for outputting script and style tags for managed assets both in themes, and in the Ghost admin, something like:

* `{{asset "css/screen.css"}}` for themes, and if you're on Ghost it will look like 
* `{{asset "css/screen.css" ghost="true"}}` (or it could be {{asset "css/screen.css" "ghost"}})

It would be nice if this looked for a specific (assets/css, assets/js) structure by default, encouraging theme developers to structure their theme in a consistent way, but could be overridden.

**Comment by ErisDS** [comment]
Closing this. At some point we'll probably want to add a much more extensive asset pipeline to Ghost, but what we have pretty much works for now. When it's time to add something better, we'll get it spec'd out in more detail.

**Comment by smasher164** [comment]
I'm having trouble with browser caching of my assets. Because browsers don't cache files with a query string `?v=`, I think a possible fix would be to rev the file names differently. Instead of `mylogo.gif?v=1.2`, we should use `mylogo.1.2.gif`. This provides both the advantage of cache busting, as well as proxy caching of assets.

Looking through the helpers/ directory, `Ghost/core/server/helpers/utils.js` seems to be inserting the query string `<%= source %>?v=<%= version %>`. However, I'm not sure how to change it because `<%= source %>` contains the file extension.

**Comment by ErisDS** [comment]
> Because browsers don't cache files with a query string

To the best of my knowledge, all modern browsers do cache files with a query string. Some network-level caches do not. Modifying the filename instead of adding a query string is a non-trivial change that would require a significant reworking of file lookup.

**Comment by vvo** [comment]
:100: to what @ErisDS, browser do cache query strings. Still, not using query string is safer when behing proxies/CDNs etc.
