### ISSUE TITLE
Cannot format text to "heading two"  

### ISSUE THREAD

**Issue by ochronus** [TryGhost/Ghost#14146]
### Issue Summary

When I select some text and try to convert it to "heading two" using the popup controls, nothing happens. I tried 3 different browser engines.
Worked perfectly before the latest update.

Uploading 20220214_201657.mp4…

.

### Steps to Reproduce

1. Select text in the post editor
2. Press "heading two" in the popup
3. Nothing happens

### Ghost Version

4.36.0

### Node.js Version

v16.14.0

### How did you install Ghost?

Using the official guide on an Ubuntu VPS

### Database type

MySQL 8

### Browser & OS version

Mac OS X 12.2.1 ; Brave 1.35.101 ; Safari 15.3 ; Firefox 98.0b4

### Relevant log / error output

```shell
No console errors
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Kerumen** [comment]
This was fixed in https://github.com/TryGhost/Admin/commit/9c9b55c7274734bc40dc7b32059a59aaee028d85 but it looks like the release that was supposed to include this was created empty.
See the diff between the `v4.36.0` and `v4.36.1` here: https://github.com/TryGhost/Admin/compare/v4.36.0...v4.36.1

@kevinansfield Do you think you can resolve this? Thanks!

**Comment by kevinansfield** [comment]
4.36.1 was a patch release for a specific issue. The fix for this issue will be included in the next full Ghost release that's currently scheduled for tomorrow.

**Comment by ochronus** [comment]
Thank you for the quick turnaround and for keeping us updated 🙏
