### ISSUE TITLE
Hot-reload of themes

### ISSUE THREAD

**Issue by KenanSulayman** [TryGhost/Ghost#1433]
Ghost should hot-reload themes to eliminate the necessity of restarting it in order to see a new theme. I am not aware of the technical restraints of the templating engine used, so I won't PR on this. Comments on hot-reloading?

**Comment by sirlancelot** [comment]
Would it be possible to just read the themes when the settings page is loaded?

**Comment by ErisDS** [comment]
@sirlancelot not currently, we'd need an API endpoint to do this and that has a bunch of other prerequisites including permissions, file storage abstraction etc. Improving theme management in Ghost is something we're working towards though.

**Comment by vdemedes** [comment]
At the moment, I see 3 solutions:

1. Use [chokidar](https://npmjs.org/package/chokidar) to watch `content/themes/active_theme` folder to change (as suggested by @szelpe). Chokidar is proven to be reliable and easy on system resources. Whenever a change occurs in an active theme directory (not just in `content/themes`), Ghost reloads and recompiles template files.
2. Use cache for theme files with expiration time, so when items expire, theme is reloaded.
3. After request to blog finished, trigger a theme check (`fs.stat` to see if anything was changed). Of course, this check should not run after each request, but with some debouncing (once in 10 minutes, for example). We could also come up with some other strategy, on when to run a theme check.

For the best user experience, option 1 is the best. 

Must also be mentioned, that for either of possible options, we need to implement a way to reload theme files on-demand (involves resetting express view cache).

**Comment by ambrosechua** [comment]
A public API endpoint to reload the current theme would be useful. Is it on the roadmap?

**Comment by kevinansfield** [comment]
No public API endpoint. There is already a private API endpoint for uploading a theme which does go through all of the necessary cache invalidation etc (and is being refactored heavily in the current alpha) so that's usable if you are running in production.

When developing a theme it's suggested to run ghost locally in development mode where changes to theme files are picked up automatically.

**Comment by ErisDS** [comment]
This issue is ancient, officially the oldest issue on our repository. 

In Ghost 1.0, we've overhauled how themes behave. We now have the theme uploader. In addition we have `ghost install local` and a section in the docs, which explains an easy way to setup reloads for theme development here: https://docs.ghost.org/v1.0.0/docs/install-local#section-developing-themes.

Given the way Ghost themes work, even with the refactoring, I don't think it's worth the additional complexity and overhead to get hot reloading working. The best we were ever going to get was a reload button. 

I'm going to close this issue, and hope that the tools we now have are sufficient. 

I'd be super interested in any contributions that make it easy for local installs to also have livereload or other useful tools, but I think most people add build pipelines etc to their themes directly.
