### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by anaclumos** [TryGhost/Ghost#14450]
### Issue Summary

Ghost 4.42 on Ubuntu 20.04 LTS has a memory leak.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/31657298/162530153-72b8b44a-c54c-4187-a359-204fc2093f17.png">

### Steps to Reproduce

Just run the Ghost for a couple of days, and the ram usage will choke the server.

### Ghost Version

4.42

### Node.js Version

v16.14.0

### How did you install Ghost?

Digital Ocean One-Click Droplet

### Database type

MySQL 8

### Browser & OS version

Ubuntu 20.04 (Backend)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @anaclumos 👋🏻 Would you be able to provide more info on your server setup? How much RAM does your system have? If you have `htop` installed, can you post a screenshot of the output so we can see the RAM breakdown across processes 🙂 

I spun up a $5 DigitalOcean 1-click instance running Ubuntu 20.04, Node v16.14.0, MySQL 8 and Ghost 4.44.0 about 10 days ago and I'm not seeing any similar issues.

**Comment by anaclumos** [comment]
Unfortunately, I cannot provide info since I have destroyed the droplet and now use a 2GB droplet. Ghost uses ~1.2 GB of memory, which is more than I expected, but it is running stable. However, based on the reactions, it seems like other people are also experiencing the issue; I will keep the issue open so that anyone else who experiences the issue can contribute.

**Comment by ErisDS** [comment]
Thanks for coming back with some more info. The amount of memory that Ghost uses will be dependent on the number of posts, images and other resources that the site is handling, as there is a lot of in-memory caching.

As well as the droplet we fired up to test this, we obviously run a lot of other instances of Ghost and have no signs of a leak at present, meaning if there is one it must be obscure or very specific to a certain setup.

I'm going to close this for now as there's nothing further we can do at present, but if anyone else is experiencing this and can provide us with a reproduction case we can of course reopen it.

**Comment by emadotjar** [comment]
@ErisDS I have the same problem using a Basic $6/mo droplet.
I'm adding some info to help you solve this issue, please, let me know if you need more investigation from my side.

Droplet
**CPU Type**: Shared CPU
**vCPU**: 1 vCPU
**Memory**: 1GB
**SSD**: 25GB
**Transfer**: 1TB

Ghost
**Ghost-CLI version**: 1.19.3
**Ghost version**: 5.2.3

As you can see attached to this message, a memory spike created a couple of outages and the droplet had to be restarted in order to restore the service.
<img width="973" alt="Screenshot 2022-07-13 at 10 41 18" src="https://user-images.githubusercontent.com/93657879/178705512-88af42f0-de75-4620-993d-14719b29415c.png">

@daniellockyer I even attached a screenshot of the output of `htop` as you previously asked.
<img width="1434" alt="Screenshot 2022-07-13 at 11 51 21" src="https://user-images.githubusercontent.com/93657879/178705614-be19fc61-37d8-4db8-8cd0-4ea86634368c.png">
