### ISSUE TITLE
Impersonation tokens do signup action if no account is found

### ISSUE THREAD

**Issue by Johnnyyyy1234** [TryGhost/Ghost#14508]
### Issue Summary

When a user is deleted it is expected that all tokens associated with that account are revoked. This is currently not the case.

Creating a token before deleting a user creates the account again when pasted into the browser.

### Steps to Reproduce

1. Create an access token for an account.
2. Delete that account.
3. Paste that token into your browser.
4. User is created again.

The user should NOT be created again and all tokens should be revoked when a user is deleted.

### Ghost Version

4.44.0

### Node.js Version

16.14.2

### How did you install Ghost?

OS - Debian 11 with MariaDB 10.5.15

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there @guidefox. Ghost's magic links are based on JWTs, the tokens aren't stored and there's not really a concept of revocation here. What's happening is that the magic link has a fall back behaviour of creating a new account if no matching account is found.

I realise that's a little jarring, but it's a brand new account that is created, not an old one being restored.

I think it would make sense to pin the impersonation links to only be allowed to do signin, rather than falling back to signup, to make this a little less weird.

**Comment by guidefox** [comment]
Ah, that makes more sense. I think that the current behavior can be improved because it is a little bit jarring right now.

Perhaps a dedicated button for having impersonation tokens re-create the account instead of doing it automatically would be a better solution.

And maybe make the tokens one use only? or at least provide the option to have it expire after one use.

**Comment by ErisDS** [comment]
This has cropped up in other forms recently, and is something we want to prioritise fixing.
