### ISSUE TITLE
Multiple accounts for members

### ISSUE THREAD

**Issue by benjaminrancourt** [TryGhost/Ghost#14840]
### Issue Summary

When the user use the same email address to login but with different case sensitivity, multiple accounts are created.

![image](https://user-images.githubusercontent.com/7907713/168697466-95f95d96-8508-4883-96c9-1abe70ce5c69.png)

### Steps to Reproduce

1. Sign in using your email (`Name@Google.com`)
2. Click on the sign up link you received
3. Logout
4. Sign in using your email (`name@google.com`)
5. Click on the sign up link you received
6. Check your members in Ghost admin and you should see multiple accounts for the same email address

### Ghost Version

4.47.1

### Node.js Version

v14.19.1

### How did you install Ghost?

Docker

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey there @benjaminrancourt, this is due to sqlite3 not doing case sensitive unique constraints by default, and knex not handling the difference. It is therefore only an issue in development as we don't recommend running SQLite3 in production.

If anyone is really keen to get this fixed, it would be great to see knex get more love for things like this, so that operations like creating unique constraints are consistent across databases.
