### ISSUE TITLE
Editor On Mobile (Android) is unusable

### ISSUE THREAD

**Issue by hndrk-themer** [TryGhost/Ghost#14968]
### Issue Summary

I can't really use the Ghost Editor on my phone. It's limited like here [#14948](https://github.com/TryGhost/Ghost/issues/14948), but it also acts weird dependent on the Browser I'm using.

### Steps to Reproduce

Fennec Browser: (Firefox Mobile)
1. Open a new Post on your Phone.
2. Type # to create a new headline. 
3. Type Headline

= Weird text gets multiplied everywhere. Even if i want to delete the text its gettig more multiplied lol.

![IMG_20220605_155847](https://user-images.githubusercontent.com/84930289/172054476-a346ae3b-9258-4d64-8176-1220c4ca52b4.jpg)

Bromite Browser: (Chromium)
1. Open a new Post
2. Type # to create a new headline

= the # is popping up AFTER the text curser and even if you point it behind the # no headline can get created with Bromite

![IMG_20220605_155400](https://user-images.githubusercontent.com/84930289/172054057-8087661a-2b56-4d23-89f3-f977f33fcbf3.jpg)

### Ghost Version

Docker:latest

### Node.js Version

18/16 (Docker)

### How did you install Ghost?

Docker, Debian 11.

### Database type

SQLite3

### Browser & OS version

Fennec, Firefox, Bromite, Chome, One Plus Nord, Lineage19.1 (Android 12.1)

### Only Workaround

Go to Desktop View - add a markdown Field - inside markdown the text/keyboard seems to work fine.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by hndrk-themer** [comment]
its not so weird on different mobile browsers, it seems like the editor is also incompatible with mobile keyboards.

For example hitting the Enter Key on GBoard leads to just close the Keyboard, but not a new paragraph. The AOSP-Keyboard can create a new paragraph with the enter key, but when hitting the "back" key to remove a text the keyboard is closing.

**Comment by BirbEXE** [comment]
there were so many bugs with the mobile editor that I couldn't include them in my issue (#14948)
the mobile experience needs a LOT of refining
honestly though, text editing on browsers is so hard to get right I think that a mobile app for ghost might be an overall better option

**Comment by ErisDS** [comment]
> honestly though, text editing on browsers is so hard to get right I think that a mobile app for ghost might be an overall better option

For this reason, Ghost is not developed with mobile editing in mind - it does work fairly well on iOS devices, but that's almost by accident. There are no touch events in the editor for example. 

There are also upstream issues with mobile editing that we'd need resolved, before the mobile editing experience could reach the desktop experience, for example [this one](https://github.com/bustle/mobiledoc-kit/issues/589).

We love mobiledoc, and are keen to see more people get involved and help to resolve these issues.

The bug raised by @BirbEXE was fixed in a PR by another member of the community @pelmers. The fix has been merged today, and will be in the next release. We've gotten a bit behind with merging PRs but are trying to catch up as fast as we can.

If anyone is interested in contributing to the mobile experience on Android and wants to chat more generally about the bigger picture problems and approach to solving them etc, we do have a contributor section on the [forum](https://forum.ghost.org/c/contributing/27).
