### ISSUE TITLE
Broken npm dependency

### ISSUE THREAD

**Issue by paulcarroty** [TryGhost/Ghost#15171]
### Issue Summary

`tryghost-adapter-manager` is broken.

```
$ npm i ghost@5.7.1
...
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /tmp/gh/node_modules/ghost/components/tryghost-adapter-manager-0.0.0.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/gh/node_modules/ghost/components/tryghost-adapter-manager-0.0.0.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Working fine with ghost 5.4.

### Steps to Reproduce

^

### Ghost Version

5.7.0, 5.7.1, 5.6

### Node.js Version

16.16

### How did you install Ghost?

^

### Database type

SQLite3

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey @paulcarroty - installing Ghost as a package in this way is not a supported method. Please use Ghost-CLI to install it 🙂

**Comment by markhillard** [comment]
@paulcarroty, I ran into the same issue when upgrading my fork of https://github.com/cobyism/ghost-on-heroku. My automatic deploys to heroku were working fine up until some version after 5.4.1. Then when running `npm update` locally I started getting a ton of "tarball corrupted" errors and the upgrade would bomb out. Same errors showed up on my next heroku build when viewing the build console there.

I know how to use the Ghost CLI locally, but I'm not sure how to integrate it with my repo so that Ghost CLI runs on heroku so it can install/update all the dependencies properly.

**Comment by markhillard** [comment]
@paulcarroty yeah my repo doesn't work right now. I have been testing some things out in heroku but no luck yet. I'll report back if I make any progress.

**Comment by paulcarroty** [comment]
@markhillard [figured it out](https://github.com/nixsanctuary/heroku-buildpack), happy blogging.

**Comment by markhillard** [comment]
@paulcarroty, nice work! I also tried running `ghost install` on the "heroku-postbuild" step in package.json, but it kept telling me that I couldn't install ghost because the directory wasn't empty. I didn't know about those additional flags after the command. Thanks very much for getting back to me.

**Comment by paulcarroty** [comment]
@markhillard Yeah, a bit dirty 'cause the node_modules merge, but my patient was out when Heroku pruned all `postinstall` changes there. Heroku free plans will be closed soon together with motivation to improve anything. Have fun!

**Comment by HelmmDev** [comment]
@paulcarroty @markhillard is there still a live repo that works for ghost to heroku? Looks like you guys figured it out ~2 years ago, but the link is dead. I'm trying (in vain) to get 5.90.0 onto heroku - need help!

**Comment by paulcarroty** [comment]
I don't think the repo is still available after Heroku free tier elimination. AFAIR the idea is very simple: move all packages from monorepo to `node_modules` and  set  `NPM_CONFIG_PRODUCTION=false` or `YARN_PRODUCTION=false`.

**Comment by markhillard** [comment]
@HelmmDev, I switched everything to [Render](https://render.com/) when Heroku removed the free tier. Here is a fork of the ghost-on-render public template they offer: https://github.com/markhillard/ghost-on-render.

Not sure if you're able to switch providers altogether, but it might be worth a shot.
