### ISSUE TITLE
Canonical URL don't save in description of tag.

### ISSUE THREAD

**Issue by uPagge** [TryGhost/Ghost#15225]
### Issue Summary

When filling in the Canonical URL field in the tag description and then saving it, it is not saved. If you log out and log in, this field will be empty. Sometimes it is saved, but if you fill in the Canonical URL in another tag, then it will disappear in the previous one

### Steps to Reproduce

When filling in the Canonical URL field in the tag description and then saving it, it is not saved. If you log out and log in, this field will be empty. Sometimes it is saved, but if you fill in the Canonical URL in another tag, then it will disappear in the previous one

### Ghost Version

5.8.3

### Node.js Version

docker

### How did you install Ghost?

docker

### Database type

MySQL 8

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hey @uPagge, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by kevinansfield** [comment]
I believe was fixed in https://github.com/TryGhost/Ghost/commit/08b099e5274c3471724375924067381029b62220 that was included in  5.14.0.

Looking at the previous ["scratch tag" properties](https://github.com/TryGhost/Ghost/commit/08b099e5274c3471724375924067381029b62220#diff-4e94d60c9b1367944a5edc8dfe09fe358a24c3c7b655a3d0768dadd174ff9066L11) we were using, the `canonicalUrl` field was missing which meant it would appear updated in the UI but not be saved. The tag form has been simplified to get rid of the scratch value concept so we shouldn't hit that problem again in the future.

**Comment by ErisDS** [comment]
Confirmed
