### ISSUE TITLE
Regression: Redirect to signin/re-authenticate modal not shown when logged out

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15291]
We've had a regression with how unauthenticated requests are handled by Admin. Unauthenticated requests could occur if you've logged out in another tab and didn't realise you'd gone back to editing on a tab that looked like it was still logged in.

## Steps to reproduce 

1. Open Ghost admin and ensure you're logged in in two different tabs
2. In tab 1, open the editor
3. In tab 2, logout
4. In tab 1, attempt to save

## Previous behaviour
- whilst editing - show a re-authentication modal to allow quick sign-in and save
- whilst performing any other action - redirect to signin screen

## Current behaviour:
- all actions - show a slightly cryptic alert message `Authorization failed Unable to determine the authenticated user or integration. Check that cookies are being passed through if using session authentication.`

This is likely happening because we've moved from a `401` to a `403`. The cookie is being sent so the request is not "Unauthenticated" but it no longer matches a valid session so its "Unauthorized".

Admin isn't currently set up to recognise a 403 and trigger the auto-logout/re-authenticate behaviour. There are potential edge cases if we treat 403 and 401 the same when it's a genuine "not permitted" error but Admin shouldn't be making any such requests unless your role is changed by another user whilst you're using it.

Note: There is a skipped test for the re-authentication modal here: https://github.com/TryGhost/Ghost/blob/0695f74a653bff85d5a08ee7f97fc9a4a8ddbe63/ghost/admin/tests/acceptance/authentication-test.js#L97 which may have contributed to this regression slipping in. Ideally we'd get this test running again as well to prevent this regressing in future.

### Ghost Version
5.10

**Comment by h2akim** [comment]
Hi @ErisDS 

It seems that re-authentication modal is shown correctly - when attempting to save & auto save.
The alert message is shown when the user dismisses/close the modal without authenticating.

![Screenshot 2022-09-07 at 8 08 21 AM](https://user-images.githubusercontent.com/514048/188761860-2c132f8c-f87b-4dac-b606-183d68477063.png)

But, when user already dismiss the re-authenticate modal for the first time (either not re-login / already login on another tab), the re-authenticate modal would not show again. Is this an intended behaviour?

Some other related issue is, when user re-authenticate in tab 2 after first re-authenticate modal is dismissed on tab 1. Clicking back on `< Posts` is redirected to sign-in page instead of Post page.

https://user-images.githubusercontent.com/514048/188763552-42ac8cd3-eda2-4571-a17c-141a1698b399.mov

**Comment by ErisDS** [comment]
> It seems that re-authentication modal is shown correctly - when attempting to save & auto save.

Oh odd, I can't reproduce it now either!

> But, when user already dismiss the re-authenticate modal for the first time (either not re-login / already login on another tab), the re-authenticate modal would not show again. Is this an intended behaviour?

I think not 🤔 

> Some other related issue is, when user re-authenticate in tab 2 after first re-authenticate modal is dismissed on tab 1. Clicking back on < Posts is redirected to sign-in page instead of Post page.

Hmm that sounds like it needs fixing 😬 care to take a stab at it?

**Comment by h2akim** [comment]
Sure, will take a look at this bug.
