### ISSUE TITLE
Markdown blocks are all separated, breaking footnotes

### ISSUE THREAD

**Issue by Joshuatanderson** [TryGhost/Ghost#15299]
### Issue Summary

The documentation says that footnotes are possible, and can be achieved with some simple markdown.

This is not really the case.

Footnotes only work within a single block.

However, the natural use case for a footnote is to cite throughout the page, and to have all citations at the bottom.

This does not work.

### Steps to Reproduce

1. Create 2 MD blocks.

**The first block:**
[^1] First footnote in page

**The second block:**
[^2] Second footnote in page

[^1]: First footnote, explained
[^2]: Second footnote, explained

**Expected Behavior**
For the document to render a first footnote, and a second footnote, like the github engine, or any standard MD engine.

This behavior is implied here. https://ghost.org/changelog/markdown/#markdown-footnotes

**Actual Behavior**
The Ghost editor treats the two MD blocks as separate. 
This makes footnotes effectively useless, unless a page is written in nothing but a single MD block.

### Ghost Version

5.0 (should be current)

### Node.js Version

Unknown. Deployed on ghost.io

### How did you install Ghost?

Ghost.io

### Database type

Other

### Relevant log / error output

```shell
N/A
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
Hi @Joshuatanderson, thanks for this detailed report.

The behaviour you describe is a known and expected limitation of the current Ghost editor. In order to use footnotes in the way you want, you would need to use a single markdown block for your post.

The reason for this lies within limitations of the underlying [mobiledoc format](https://github.com/bustle/mobiledoc-kit/blob/master/MOBILEDOC.md) on which the editor is built. In order to support footnotes in the wysiwyg editor or across mobiledoc cards it would require an update to the mobiledoc spec to support something like annotations, before we'd be able to build out an implementation in our editor.

The other choice would be to completely rebuild the editor using a different technology.

As I'm sure you can imagine, neither of those paths is a trivial amount of work to undertake.  

At present, the limitations within the current editor aren't considered a priority that would warrant investing the effort that'd be required to overcome them, but this is a balance that we keep a very close eye on and it could change at any time.

This of course doesn't preclude other people from working issues upstream & unlocking the possibility for footnotes. 

For now, I'm going to close this as an expected limitation in Ghost.
