### ISSUE TITLE
Unsaved changes modal not shown in member newsletter subscriptions

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15507]
### Issue Summary

When leaving the member details screen, the unsaved changes confirmation modal is not shown when there are unsaved changes to newsletter subscriptions.

### Steps to Reproduce

1. Set up some newsletters
2. Open the details screen for a member
3. Toggle on/off a newsletter subscription
4. Navigate away from the member details screen
5. No unsaved changes modal is shown

### Ghost Version

5.16

### Node.js Version

16

### How did you install Ghost?

ghost install

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by SerpentBytes** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by ErisDS** [comment]
@shivamchourasia4 we only assign issues to https://github.com/TryGhost/Ghost/issues/15503. There is no open PR for this issue so it's free to work on.

**Comment by hey24sheep** [comment]
I just tested it, Isn't it correct though? The form might be touched but the state didn't change. Meaning, if the newsletter toggle was 'on' before and it was toggled to 'off' then 'on' again. It should not show the "unsaved" modal because the changes never happend, the form is back to default. User doesn't need to save something which already is same in the database.

The same thing happens, if you type something in notes and just undo it. It will not show "unsaved" modal.

**Comment by ErisDS** [comment]
You are correct that if the state doesn't change, then the modal shouldn't appear. But this bug is very specific:

> When leaving the member details screen, the unsaved changes confirmation modal is not shown **when there are unsaved changes to newsletter subscriptions**.

The modal is not appearing when there _are_ unsaved changes.

**Comment by jasham** [comment]
So I have created one post.

![image](https://user-images.githubusercontent.com/23471755/193718811-bc31010b-0f3b-41fb-80d6-b3a39aa0667a.png)

Now going to the existing member page.

![image](https://user-images.githubusercontent.com/23471755/193718904-b8910c3f-e302-442d-915b-348bbe035cb6.png)

Opened existing member detail

![image](https://user-images.githubusercontent.com/23471755/193718976-6f5e6501-85a2-460e-b38d-7cc4165dee6a.png)

no changes are done only toggle on/off is done and then navigated to the next screen. Are we expecting to show the popup to save the details at this point ?? Is this the scenario ??

**Comment by h2akim** [comment]
Hey, some heads up for those who want to work on this issue.

This issue also affects `Labels` changes - when added new delete labels.

Both labels and newsletter changes should expect the page to show below popup when trying to navigate to other page `WITHOUT` saving

![Screenshot 2022-10-04 at 11 18 18 AM](https://user-images.githubusercontent.com/514048/193727084-7f2d96ac-3f48-45bf-973e-3d6bda23389a.png)

Changes by means are that the initial state is different from the current state. (initial: ON, current: OFF)

It could be due to `isDirtyAttributes` not set to `true` when change is done to relationship (hasMany) - in this case, label and newsletter.

**Comment by kevinansfield** [comment]
> It could be due to isDirtyAttributes not set to true when change is done to relationship (hasMany) - in this case, label and newsletter.

Correct. Changes to relationships are not currently tracked by Ember Data's built-in dirty property tracking.

In this case we'd need to manually track that newsletters/labels have been changed and use that alongside `hasDirtyAttributes` for showing the unsaved changes modal.
