### ISSUE TITLE
Comments section does not support RTL languages (Arabic, Hebrew, ..)

### ISSUE THREAD

**Issue by alfarhan** [TryGhost/Ghost#15752]
### Issue Summary

In case the Publication Language setting is ar language, it should align text to be rtl (from right to left). I can help in translating the labels.

### Steps to Reproduce

Make Publication Language "ar" like on my website alfarhan.ws. 
The comment section on post pages will ignore this setting.

### Ghost Version

latest

### Node.js Version

latest

### How did you install Ghost?

self hosting

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**First image (current view) which is wrong** 

![1](https://user-images.githubusercontent.com/2324349/199565363-858db44f-5186-4b18-bbfe-34426b0e7de3.png)

**Second image (i used browser inspector to make the comment section RTL)**

![2](https://user-images.githubusercontent.com/2324349/199565538-dadaa565-5c8a-41a5-8438-e1e1c046e56e.png)

**Comment by ErisDS** [comment]
Hey there, thank you so much for the bug report.

That does sound like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by alfarhan** [comment]
Thanks @ErisDS 
I uploaded 2 screenshots above to view the current and how it should look.

**Comment by akash19coder** [comment]
@ErisDS I would like to give this issue a try 😀 .

**Comment by alfarhan** [comment]
> @ErisDS 

Any hope? highly appreciate your support

**Comment by ErisDS** [comment]
A PR for this issue would be very welcome.

**Comment by deounix** [comment]
@ErisDS

The main languages that uses RTL scripts:

1. Arabic (ISO 639-1 Code >> ar)
2. Aramaic (ISO 639-1 Code >> ????)
3. Azeri (ISO 639-1 Code >> az)
4. Dhivehi/Maldivian
5. Hebrew
6. Kurdish (Sorani)
7. Persian/Farsi
8. Urdu

And some of them doesn't have an ISO 639-1 Code for example: (Aramaic) so we can't count on **Publication Language** to decide whether this langauge should be displayed from right to left or left to right.

I think the best way to do it is to add a new option in the admin panel (settings/general) under **Publication Language**

`Site Direction`: which is basically a dropdown with two options `(LTR - RTL)`.

Site Direction should be applied to the admin panel also because doing it only on (user side or comments section) make no sense.

Please let me know if you're ok with what I mention because I would like to help with this issue.

**Comment by a0m0rajab** [comment]
@alfarhan I think this could be solved from the CSS file in the theme folder, would not this solve the issue?

If a pull request should be made for this, It would be at the https://github.com/TryGhost/comments-ui repository, we can get the idea from @deounix and create a list for RTL languages to check it at the repository. Instead of complicating the UI for non RTL users as what mentioned in this comment: https://github.com/TryGhost/Casper/pull/306#issuecomment-479492611

@ErisDS is there a way to pass the language as parameter to the comments-ui?

**Comment by alfarhan** [comment]
> @alfarhan I think this could be solved from the CSS file in the theme folder, would not this solve the issue?
> 
> If a pull request should be made for this, It would be at the https://github.com/TryGhost/comments-ui repository, we can get the idea from @deounix and create a list for RTL languages to check it at the repository. Instead of complicating the UI for non RTL users as what mentioned in this comment: [TryGhost/Casper#306 (comment)](https://github.com/TryGhost/Casper/pull/306#issuecomment-479492611)
> 
> @ErisDS is there a way to pass the language as parameter to the comments-ui?

The theme css does not cover this. Adding codes to the header will it make an impact since the whole comment area design is in iframe.

**Comment by farhan787** [comment]
@alfarhan I checked your Arabic website and you're right if we set direction to `rtl` in HTML headers then other HTML components like NavBar, etc are also reversed, we'd need to make changes in the CSS for RTL languages.

**Comment by a0m0rajab** [comment]
@farhan787 sounds great! Could you figure out how to pass the localeCodes to the comments-ui? I got stuck at that point.

**Comment by farhan787** [comment]
@a0m0rajab the comments data comes in the `script[data-ghost-comments]` component, see [this](https://github.com/TryGhost/comments-ui/blob/6de9cc06d9cbb77392f631de9fce63951a6c4524/src/index.js#L28). 

I got a bit occupied in some personal things, I was fixing the CSS styles for Right to Left direction, if you'd the CSS sorted then you can follow below steps to test your changes,

You can hardcode the data for testing purpose with your local dev setup, like this, before [this line of code](https://github.com/TryGhost/comments-ui/blob/6de9cc06d9cbb77392f631de9fce63951a6c4524/src/index.js#L38)

```js
dataset = {
        ghostComments: 'http://127.0.0.1:2368/',
        api: 'http://127.0.0.1:2368/ghost/api/content/',
        admin: 'http://127.0.0.1:2368/ghost/',
        key: '533a0e67d59dac0119f600d0ce',
        styles: 'http://127.0.0.1:5369/public/main.css',
        title: 'null',
        count: 'true',
        postId: '63a6163af8fbe027fdba0133',
        sentryDsn: '',
        colorScheme: 'auto',
        avatarSaturation: '60',
        accentColor: '#FF1A75',
        appVersion: '0.12',
        commentsEnabled: 'all',
        publication: 'The Daily Awesome',
        isRtlLang: true
    };
```

After this, in your ghost repo, add this comments key in the package.json file to point to the local comments-ui server. 
```json
"comments": {
        "url": "http://127.0.0.1:5369/comments"
    }
```

The CSS changes would also reflect in the ghost server's UI.
