### ISSUE TITLE
Database migration error going from 5.24.2 to 5.25.0

### ISSUE THREAD

**Issue by sanjay** [TryGhost/Ghost#15930]
### Issue Summary

Upgrade had to be rolled back because of a database migration error.

### Steps to Reproduce

ghost update

### Ghost Version

5.24.2 -> 5.25.0

### Node.js Version

14.20.1

### How did you install Ghost?

Digital Ocean droplet

### Database type

MySQL 8

### Relevant log / error output

```shell
✖ Restarting Ghost
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: alter table `suppressions` add constraint `suppressions_email_id_foreign` foreign key (`email_id`) references `emails` (`id`) - Referencing column 'email_id' and referenced column 'id' in foreign key constraint 'suppressions_email_id_foreign' are incompatible.
Help: Error occurred while executing the following migration: 2022-11-24-10-36-add-suppressions-table.js
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by sanjay** [comment]
Not sure what to do here and how to get this upgrade to work.  Is there something I should do to my database manually to get it in the right situation for this migration?

**Comment by bird-in-hat** [comment]
Solved: https://github.com/TryGhost/Ghost/issues/15743

**Comment by ErisDS** [comment]
This sounds like an issue with collation in the database. See:
https://ghost.org/docs/faq/troubleshooting-mysql-database/#error-er_cant_create_table-with-_foreign-key-constraint-is-incorrectly-formed_
https://ghost.org/docs/faq/supported-databases/#how-to-update-mysql-5-to-mysql-8

Root cause may be https://github.com/TryGhost/Ghost-CLI/issues/1718
