### ISSUE TITLE
Autocorrect, autopunctuation, and autocapitalization not working on iOS Safari

### ISSUE THREAD

**Issue by josephdpurcell** [TryGhost/Ghost#16049]
### Issue Summary

The features of autocorrect, autopunctuation, and autocapitalization are not working on iOS.

I took a video recording of the behavior.

<details>
<summary>View recording</summary>

https://user-images.githubusercontent.com/778111/209568830-c15144b7-37f7-4e80-a817-9827038df5de.MOV

</details>

### Steps to Reproduce

1. Install Ghost
2. Login as an admin
3. Create a post
4. In the post body notice the first character is capitalized, but no other characters get capitalized
5. Notice that entering two spaces does not result in a period followed by a space
6. Notice that misspelled words do not result in a prompt for the correct spelling

### Ghost Version

5.26.2

### Node.js Version

16.19.0

### How did you install Ghost?

Docker on Linux

### Database type

SQLite3

### Browser & OS version

iOS 15

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by josephdpurcell** [comment]
I see https://github.com/TryGhost/Ghost/issues/13097#issuecomment-869559495 which suggests the mobile experience has not been a priority for Ghost.

The Markdown editor on Directus also does not support these features: https://github.com/directus/directus/issues/16690.

Tangential for some context, I am on a journey to find a "good" mobile experience authoring content which I suggest should include support for these features. Ideally, I would also like to write it using Markdown. I have notes here: https://github.com/directus/directus/discussions/16762, which includes a link to a spreadsheet where I am evaluating various editors and CMS's. My experience is showing me that authoring Markdown on a mobile device has very limited support, aside from things like GitHub and StackOverflow.

**Comment by ErisDS** [comment]
These are all upstream issues with mobiledoc's handling of keyboard input: https://github.com/bustle/mobiledoc-kit

You're welcome to raise the issues there and work on fixing them. As you've called out yourself, only the biggest orgs manage to implement great markdown editing experiences in mobile browsers - because it's very hard. To achieve the same experience as desktop it takes either extensive implementation work or a native app.

These things are not currently something we have enough demand for to prioritise, but that may change in future.

Upstream fixes are always welcomed though 🙂

**Comment by josephdpurcell** [comment]
Thank you for the clarification! I incorrectly thought Ghost used markdown-it for the editor.

I created a ticket on Mobiledoc https://github.com/bustle/mobiledoc-kit/issues/786.
