### ISSUE TITLE
Unclear how to use Search in headless mode

### ISSUE THREAD

**Issue by NathanC** [TryGhost/Ghost#16198]
### Issue Summary

Just set up Ghost and search is working well in the managed mode, but the content API documentation doesn't seem to reference searching—I'm integrating this with my React site and want to provide a search feature. An [old issue](https://github.com/TryGhost/Ghost/issues/5321) about search was closed as complete (and all the other references to search I can find are marked as closed/done) but I can't find out how to access it, what's the standard way to use search for a headless usage of Ghost?

Thanks for the help, and for offering this open source!

### Steps to Reproduce

Search for info on how to use search headless

### Ghost Version

5.32.0

### Node.js Version

16.19.0

### How did you install Ghost?

Ubuntu 22.04, docker compose

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by NathanC** [comment]
The documentation doesn't mention this, at least that I can find. Documentation can be buggy; I searched for a while outside of it too, found various discussions and issues that all seemed closed/resolved. There are two old issues that mention it, both are closed, and one is locked.

I'll ask in the forum, but @ErisDS it really would be nice if the docs were clear on this. If the feature isn't supported and there's not parity here, that's fine, but it'd be good to know when evaluating this for headless use.

**Comment by markstos** [comment]
If you have less than about 10,000 posts, you could have a template that writes out the titles you want to search during build time. The search engine is then just essentially searching and filtering through that data structure of titles and possibly posts.

You could also use the Content API to grab all the titles and cache for a period on the client and again, the search function could essentially become a client-side filtering function.

I just tested keeping the Developer Tools open while using the on-site search and... it makes no network requests. That suggests, the post titles are already there on the client side, so Ghost itself appears to be working like that-- filtering through content that's already on the client. 

The beauty of this design is that's a perfect match for a "headless" blog, because no API calls back to the Ghost server are actually needed. It could be used even on a statically hosted blog.

Even if search can be implemented using the existing Content API, I agree it could helpful to provide some guidance there, since people might be looking for a "Search API".
