### ISSUE TITLE
i18n Milestone 3: Wrap all public-facing strings

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#16628]
_This issue is part of our community i18n project. The full project is documented [on the Ghost forum](https://forum.ghost.org/t/hacktoberfest-project-i18n-for-portal-member-emails-comments-ui-sodosearch/33062)._

---

✨ We have now started shipping our [i18n beta](https://forum.ghost.org/t/help-translate-ghost-beta/37461) in Ghost, and we're merging community pull requests to [add & update languages](https://github.com/TryGhost/Ghost/tree/main/ghost/i18n/locales).

However, not all public-facing strings in Portal and our member emails are currently interpolated for translations. In order to have a full set of translations, we need to ensure all strings are wrapped with the `t(..)` helper.

#### Setting up

1. Clone the Ghost repository and [set up your local environment for development](https://ghost.org/docs/install/source/)
2. Run `yarn dev --portal` to get things running at http://localhost:2368/
3. Toggle `Enable Portal translations (beta)` from http://localhost:2368/ghost/#/settings/labs
4. (optional) Change the Publication Language to make it easier to find uninterpolated strings: http://localhost:2368/ghost/#/settings/general 

#### Wrapping strings

Once you've found a public-facing string from code review or by using Portal/Ghost signup emails, you can easily wrap it so it will be picked up for translation.

1. Add `t('..')` around the string
  a. You may need to import the `t` function from the AppContext in Portal 	
2. Run `yarn translate` within `ghost/i18n` to ensure the locale JSON files include the new strings

You can see plenty of examples of how this is currently done using this search query: https://github.com/search?q=repo%3ATryGhost%2FGhost+path%3Aghost%2Fportal+%7Bt%28%27&type=code

Please take extra care to ensure you pass any variables into the `t` function, and make sure HTML escaping does not cause problems with the output.

#### Contributing

Commit the changes and submit a PR for us to review and merge 🙂 

Be sure to read the contributing guide and reference this issue on the 3rd line of the commit: https://github.com/TryGhost/Ghost/blob/main/.github/CONTRIBUTING.md

---

Thank you to all contributors on the i18n beta so far 🙏🏻 

If you speak a language that is not included in our current set of supported languages, please consider [submitting it](https://forum.ghost.org/t/help-translate-ghost-beta/37461) 🌐

**Comment by eugene0928** [comment]
new language is added

**Comment by sam-lord** [comment]
Hard case here:

https://github.com/TryGhost/Ghost/blob/fca78b2bae67a9386c95feb56e4576b6e1df2512/ghost/portal/src/components/pages/AccountHomePage/components/EmailPreferencesAction.js#L20

Since we've got the <span> which is used to remove a word on mobile for a shorter string.

We could do something like:

```
<span>
    <Interpolate
        syntax={SYNTAX_I18NEXT}
        string={t('You\'re <span>currently</span> not receiving emails')}
        mapping={{
            span: <span className="gh-mobile-shortener" />
        }}
    />
</span>
```

This keeps all the words in the translation string, but adds a span with no context - which would make it hard for the translator to know whether to keep that in the translated string, since they can't see what it's used for.

**Comment by sam-lord** [comment]
One more hard one: https://github.com/TryGhost/Ghost/blob/9cc202aae388e57dfcb2fc718117614112cc3e46/ghost/portal/src/components/Notification.js#LL48C33-L48C33

These notifications include a break-line, presumably because the site title might be long. Since the site title might go somewhere else in the sentence it doesn't seem right to just translate the first part, unless we added a colon to demonstrate that the site title will follow the string.

**Comment by daniellockyer** [comment]
^^ This was inadvertantly closed by the PR but we're basically done here anyway 🙂

**Comment by daordonez11** [comment]
Hey @daniellockyer quick question could you apply the `t(..)` helper on email services? Today I found that [email template paywall](https://github.com/TryGhost/Ghost/blob/main/ghost/email-service/lib/email-templates/partials/paywall.hbs) does not support translations and it is a public-facing string. Is there a way to include translation into this component? I can help with solving that issue. I'm currently trying to work with Ghost(Pro) to build a Spanish newsletter.
