### ISSUE TITLE
Inconsistent markdown (beta editor)

### ISSUE THREAD

**Issue by illiteratewriter** [TryGhost/Ghost#17454]
### Issue Summary

When writing in markdown, the change appears in the editor, but when you publish it or look at the preview that change might not be what you expect, but it shows the markdown text.

https://github.com/TryGhost/Ghost/assets/5787110/f5bad6e9-3777-481a-9f16-1d1ba2725d4c

In this video, you can see I've bolded some content inside the markdown and it shows bold in the editor, but it is not getting applied on the preview.

### Steps to Reproduce

1. Create some text 
2. make it bold by adding ** in front and back of a word
3. editor shows text bolded correctly but the website shows it as not bold

### Ghost Version

5.55.0

### Node.js Version

18.12.1

### How did you install Ghost?

Ubuntu

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by RohitLakh** [comment]
For anyone picking up this issue, the issue is with how the data is stored rather than how it's rendered. 

https://github.com/TryGhost/Ghost/assets/34619861/a16ce192-1ea9-47b1-a1ba-6006dbead0e1

If the user saves the post without pressing enter or clicking elsewhere the lexical editor keeps the whole node as one but when moved to a new line there are 2 nodes, one with the format as 1 (bold) and the other 0.

**Comment by harshul786** [comment]
Can I contribute to this issue? if still active.
