### ISSUE TITLE
Ghost v5.56.0 has some routing issues with @siteurl helper

### ISSUE THREAD

**Issue by sergiospagnuolo** [TryGhost/Ghost#17528]
### Issue Summary

Ghost v5.56.0 has some routing issues with @siteurl helper. All my internal links are breaking and I get the following error:

![Captura de Tela 2023-07-28 às 13 29 39](https://github.com/TryGhost/Ghost/assets/13594270/71611978-6d48-4431-9bd4-bbe1178e0fa6)

### Steps to Reproduce

1. update to v5.56.0
2. use the @siteurl helper
3. a warning appears in the content manager

### Ghost Version

v5.56.0

### Node.js Version

v16.14.2

### How did you install Ghost?

CLI

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by betschki** [comment]
Same goes for the @page helper:
<img width="543" alt="CleanShot 2023-07-28 at 20 26 41@2x" src="https://github.com/TryGhost/Ghost/assets/25703384/1adaec52-1481-43cd-ae96-c7930a9ea6bd">

This is from a blank and fresh install using `ghost install --local` – the error therefore comes from the current Casper theme.

**Comment by cathysarisky** [comment]
The second error seems to be a real issue with 5.56.  (That's a brand new helper that's apparently not getting recognized.)

But your first error is a typo - the correct expression is {{@site.url}} - note the dot.  If this isn't one of the included Ghost themes, you'd want to report the problem to the theme creator, not here. :)

**Comment by ErisDS** [comment]
Hey @sergiospagnuolo, what @cathysarisky has said is correct - this is not a bug in Ghost but rather a bug in your theme. There isn't and has never been a `{{@siteurl}}` helper, it should be `{{@site.url}}`. 

Because it doesn't exist it won't do anything, that behaviour hasn't changed. What has changed is we have wired up a missing check that looks for these issues and reports on them.

@betschki the issue you've run into is different-but-related and reported here: https://github.com/TryGhost/Ghost/issues/17529

**Comment by sergiospagnuolo** [comment]
Tks for the answers. Funny that `siteurl` has always worked for me, it is working now as we speak. It just stopped working on the new version. But I will make the changes and then update the version.
