### ISSUE TITLE
Split headers break mobile usability (according to Google crawler)

### ISSUE THREAD

**Issue by cathysarisky** [TryGhost/Ghost#17810]
### Issue Summary

The new split layout header cards work great on actual phones, but cause Google to report (in Google Search Console) that the page is not mobile responsive because it is too wide.  The problem originates in this CSS:

```
.kg-layout-split .kg-header-card-text {
    padding: 12vmax 4vmax;
}
```

And in the 'quirky' behavior of the Google mobile crawler, which rather than scrolling, just sets the page height as tall as it needs to be.  So if you have a fairly long page (5000px), that causes the horizontal padding to be 100px on each side.  Which causes the page to be wider than the viewport (but only for the Google mobile crawler, because there are no phones that tall).  Which causes Google to report that it won't serve the fancy new landing page as a search result for mobile phone searches.  Argh!

### Steps to Reproduce

See above.
Occurs in unmodified Casper, and Ruby, and probably all themes, because it's coming from the cards css, not the theme css.

### Ghost Version

5.59

### Node.js Version

not relevant, happens on my 16.x and Ghost Pro

### How did you install Ghost?

Both self host in VPS and on Ghost Pro.

### Database type

MySQL 8

### Browser & OS version

Google crawler problem.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment]
Hey there, thank you so much for the detailed bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by iprasandeep** [comment]
Hi  @daniellockyer , @cathysarisky 
 
The issue with Google reporting that the page is not mobile responsive due to excessive width can be resolved by modifying the CSS  - 

```
.kg-layout-split .kg-header-card-text {
    padding: 12vmax 4vmax;
    max-width: 100%; 
    box-sizing: border-box;
}
```


max-width: 100%; -  This addition ensures that the header cards won't extend beyond the width of the viewport, addressing the issue where Google reports excessive width.

box-sizing: border-box; - This property ensures that padding is included within the defined width of the element, preventing padding from adding to the overall width.

Please let me know if could I fix this issue. I need guidance to set up Ghost locally on my machine.

**Comment by cathysarisky** [comment]
Hey @iprasandeep , I believe this issue (which was bigger than just that one spot I saw it in) has been addressed recently in this commit:
https://github.com/TryGhost/Ghost/commit/c759f419a1868676b8e57fcffc36b4d1cb3b8732

If you need help settings up Ghost locally, please post over on forum.ghost.org.
