### ISSUE TITLE
Unable to Customize Hierarchical URL Structure for Pages via Routing

### ISSUE THREAD

**Issue by newlyhorizons** [TryGhost/Ghost#17941]
### Issue Summary

I have encountered an issue with the hierarchical URL structure for pages in Ghost CMS, specifically related to dynamic routing configuration. Currently, it seems impossible to customize the URL structure for pages, which is causing inconvenience for our website management and content organization. Below are the details of the issue and a possible solution:

1. Problem Description:
Under dynamic routing configuration, it is not possible to customize the URL structure for pages. This limitation affects our ability to organize and manage content efficiently. Pages are more suitable for our needs in certain cases, but the inability to customize their URL structure is a roadblock.

2. Current Behavior:
The current behavior of Ghost CMS restricts the customization of hierarchical URL structures for pages. This limitation forces us to use posts for content organization, even though pages would be more appropriate in some situations.

3. Expected Behavior:
We expect to be able to customize the hierarchical URL structure for pages, similar to how it can be done for posts using {slug}. This change would greatly improve our content management and organization capabilities.

Proposed Solution:

1. Problem Resolution:
We propose allowing dynamic rendering of pages' URLs using the routing configuration, similar to the way it is done for posts by {slug}. This should be a relatively small change in the system and would provide flexibility in organizing content.

2. Standardize Hierarchical URL Structure:
Alternatively, an option to standardize the hierarchical URL structure or directory-based structure by rendering files from the self-hosted Ghost directory could be considered. This would align with the basic expectations of any Content Management System (CMS).

3. Benefits:
Implementing this change would benefit all Ghost CMS users by eliminating the need for workaround solutions and custom code to achieve the desired URL structure. It would enhance the usability of pages for content creators and businesses and reduce unnecessary complexity. Moreover, it must be fundamentally usable feature.

We kindly request that the Ghost CMS development team consider implementing this enhancement in a future update. It would greatly improve the experience for all users and eliminate the need for patchwork solutions.

Thank you for your attention to this issue, and we look forward to a positive resolution since it will help us a lot of creators and business by this small change.

### Steps to Reproduce

Write the routing.yaml code for pages just the same as for the posts. The filters and other controllers won't work dynamically as expected. Only when manually a path is defined along the data source in the routing.yaml file then only it is possible to route but still it doesn't works dynamically.

Reference: 
https://forum.ghost.org/t/create-hierarchical-url-structure-dynamic-routing-for-pages/38596

https://forum.ghost.org/t/seeking-advice-best-practices-for-yaml-implementing-brand-and-category-tagging-content-organization-and-latest-posts-on-my-website/38584/

### Ghost Version

5.61.0

### Node.js Version

18.16.0

### How did you install Ghost?

GCP & Ubuntu

### Database type

MySQL 8

### Code of Conduct

- [x] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
The 5.61.0 release has been deprecated due to a broken admin area build. Downgrade to 5.60.0 or wait for 5.61.1

**Comment by rarelyrandom** [comment]
Hello! I don't really how and what this platform works like but soon as I came across this page while checking in Google to solve the exact same issue yet I had to create this GitHub account only for this sake. Please understand the need of this it is a very simple change people like me are looking for me. It is really appreciated if you could respect my time and efforts also as a ghost user. I saw that this case has been closed but please reopen and fix it. I am badly desperate for this since the missing of this feature has become a great blocker to our whole project and requires unrequired works to make the desired changes.
Please do understand it is simply not we are asking for some optional feature it is like a basic thing which you will find on GitHub hosting and other CMS too yet how come Ghost can't have it!??
Even if this is not in roadmap then adding it won't be any damage rather it will reduce extra dependency and extra manual code modification.
Just one change, don't we have the rights to even request for a feature to be brought which is literally a basic necessity. In fact, I saw that bot comment of mentioning to put this in forum but let me say that it never gets picked up among those useless and      unrequired fancy things.

I just wanted this feature from ages but not a single time any proper response was there from your team. They would just say some random solutions that never worked and always tried to escape with the epic dialogue of not being in roadmap.

At least this one little time if you could take this request up respecting my efforts to type this and time we spent with the teams to modify unrequired codes, I would be really grateful if you could add this to your sidemap not even the roadmap.
