### ISSUE TITLE
Comments not displayed correctly in 5.60

### ISSUE THREAD

**Issue by rusty1281** [TryGhost/Ghost#17942]
### Issue Summary

After updating to the new 5.60 Docker image, the comment section works but it is not displayed correctly.

<img width="686" alt="Screenshot 2023-09-03 at 10 17 31" src="https://github.com/TryGhost/Ghost/assets/5110408/a1718380-c406-4360-8c8f-2929c7a793a3">

This happens with the custom (Casper) theme as well as the official 5.7 one.

Using the docker 5.59.4 image (on multiple sites) the display is still correct. Also, restoring this affected instance to the 5.59.4 docker image, the comment section is displayed correctly:

<img width="518" alt="Screenshot 2023-09-03 at 10 56 21" src="https://github.com/TryGhost/Ghost/assets/5110408/c7cfe712-014c-46ef-8e6c-d5725c3c8fd5">

### Steps to Reproduce

Updating to Docker image version 5.60 (currently on hub.docker.com), results in the comment section not being displayed correctly. Using a custom, or up-to-date theme, results with the same issue.

On 5.59.4 (same host different docker container instance) the comments are working fine:

<img width="622" alt="Screenshot 2023-09-03 at 10 26 29" src="https://github.com/TryGhost/Ghost/assets/5110408/15875566-32e1-432c-b891-2122eea1e9a4">

### Ghost Version

5.60

### Node.js Version

16.20.2

### How did you install Ghost?

Docker running on Synology NAS host

### Database type

MySQL 8

### Browser & OS version

Safari (macOS 13.4) and Firefox on the same system. Also Safari on the latest iOS OS

### Relevant log / error output

Noticed "Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy." error in the browser console. This is also reporting on the working setup with 5.59.4, but as said, the comment section is showing. Also, the Casper 5.7 loaded theme still lists this error when accessing the 5.60 instance.

On top of this, there is also "Failed to load resource: the server responded with a status of 404 (Not Found)" pointing to the `/content/files/comments-ui.min.js.map` file. This file does exist on both the "non-working" and "working" setup and it is listed inside the location. Accessing it via the URL in both cases results in a 404 error, so not sure if this is relevant to this particular case.

_No response_

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Because this happens with the official Casper theme, I agree it sounds like a bug and the log output you provided seems to point to the cause.

Seeing a 404 returned for a `.map` file is normal, as these are options file used for debugging that help mape line numbers in compiled JavaScript to the line numbers in source TypeScript.

**Comment by rusty1281** [comment]
> 

Tnx for the reply. the 5.61 version atm is still not available as a Docker image so not sure if this was already fixed in that version or not, but I guess we will have to wait and see.

**Comment by markstos** [comment]
It's not mentioned as a bug fix in the Changelog so I would expect it's not fixed. 

https://github.com/TryGhost/Ghost/releases/tag/v5.61.0

**Comment by SimonBackx** [comment]
Hey @rusty1281 ! Thank you for taking your time to report this issue. There were some changes since Ghost v5.60, mainly that this version includes a new version of the comments app (v0.13). What changed in this version is that we no longer load the CSS for the comments via a separate file, but we add it inline. It sounds like the CSP headers (or manually added meta tags in your html file) of your server don't allow inline CSS. You will need to update your server configuration to allow this by updating your `Content-Security-Policy` header. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

What I don't entirely understand is how Portal is working for your site, since we use the same technique for Portal and Portal also requires inline styles.

**Comment by markstos** [comment]
v5.61.1 has been released if you want to try that (The release is out, I have not checked if the Docker build is ready yet).

**Comment by rusty1281** [comment]
> v5.61.1 has been released if you want to try that (The release is out, I have not checked if the Docker build is ready yet).

That is the plan, but no image is ready atm with that version

**Comment by SimonBackx** [comment]
> Are we talking about something deployed as part of this image/contianer or my reverse proxy? I have 6 other ghost instances all on the same version (not on 5.60 due to this) all running under the same reverse proxy.
I'm talking about the reverse proxy, or other software that can affect the HTTP headers in your setup outside of Ghost. Do you mind sharing a link to your site (doesn't matter if it is on the older version), and maybe some information about your reverse proxy setup (a configuration file could be helpful)?

Updating to v5.61.1 won't solve the issue I'm afraid. So I would skip that for now.

**Comment by rusty1281** [comment]
> > Are we talking about something deployed as part of this image/contianer or my reverse proxy? I have 6 other ghost instances all on the same version (not on 5.60 due to this) all running under the same reverse proxy.
> 
> I'm talking about the reverse proxy, or other software that can affect the HTTP headers in your setup outside of Ghost. Do you mind sharing a link to your site (doesn't matter if it is on the older version), and maybe some information about your reverse proxy setup (a configuration file could be helpful)?
> 
> Updating to v5.61.1 won't solve the issue I'm afraid. So I would skip that for now.

Sure. 

The current 5.94.4 version of the site (production) is this: https://www.blackvoid.club. This is also the version that my test deployed site is currently running. I can upgrade it to 5.60 so you can have them side by side?

**Comment by SimonBackx** [comment]
Hey @rusty1281 ! Thanks for sharing that. I've looked at your site and see that the `comments-ui.min.js` file is loaded from `https://www.blackvoid.club/content/files/comments-ui.min.js` which is not the default config. If you update Ghost, you also need to make sure this file is updated and serves the latest version of comments-ui for the corresponding Ghost version. If you serve an older comments App for the latest Ghost version, it won't work together and the styles won't load because we no longer pass the CSS file location to the app (because it was removed). As a result, older versions of the comments app won't be able to load any CSS. 

You can find the default latest version in `ghost/core/core/shared/config/defaults.json` in the Ghost repository. Which is `https://cdn.jsdelivr.net/ghost/comments-ui@~{version}/umd/comments-ui.min.js`where `{version}` is replaced by `0.13` for Ghost v5.60 

Updating your setup so that it always uses the latest version should fix your issue 😊

**Comment by rusty1281** [comment]
@SimonBackx thank you for your feedback! This was completely on my end and my mistake. I completely ignored the fact about that file that I have implemented it manually because I wanted quotes to be customized and better presented (visually). 

After one hour of searching the code I finally recalled that I have used a custom docker-compose variables (comments__styles) to load that file. 

After removing it, it all works as expected. 

Thank you again and sorry for wasting everyone’s time. 

Kind regards!
