### ISSUE TITLE
Mobile Web Editor Functionality Issues in Ghost: Delays, Cursor Errors, and Text Duplication

### ISSUE THREAD

**Issue by Emporea** [TryGhost/Ghost#18190]
### Issue Summary

The web editor functionality in Ghost is experiencing severe performance issues when used on mobile devices. Writing on mobile is delayed, and several erratic behaviors are observed, including flickering when marking text, the cursor switching randomly, duplication of text across lines, and unexpected letter placements in front of the cursor.

### Steps to Reproduce

1.     Access the Ghost web editor using a mobile device.
2.     Attempt to create or edit content.
3.     Experience delays while typing, flickering when selecting text, and erratic cursor behavior.
4.     Note instances where text is duplicated across lines or letters appear in unexpected places.

### Ghost Version

5.63

### Node.js Version

18.17.1

### How did you install Ghost?

npm install ghost-cli -g

### Database type

Other

### Browser & OS version

Firefox, Android, Ubuntu

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment]
Please upgrade Ghost to 5.63.0 or newer, try to the new beta editor and see if the issue please persists for you.

If so, please report your specific Android version. You also mentioned "Ubuntu" as your OS version. Are you testing this on the mobile version of Ubuntu?

You mentioned Firefox as well, please try another Android browser such as Chrome to see if the issue is browser specific.

And if you have this problem over a high-latency connection like a cellular connection, try it from the same mobile device on wifi and see if the situation improves.

In any case, the future of Ghost is with the new beta editor, so the most important thing is to upgrade Ghost and test with that.

**Comment by markstos** [comment]
> Since the new editor is labled as "beta" i assumed its less stable than the legacy editor. Just by definition.

That's true, but it's also where current development is happening,, while current editor may eventually be retired. If it works with the new editor but not the old editor, the "fix" may be to wait until the new editor is stable.

**Comment by daniellockyer** [comment]
We've found that a lot of these issues have gone away with the new editor (that is in beta status). This was actually one of the reasons we developed a new editor.

I'd suggest trying the new editor out and seeing if the same issues crop up 🙂
