### ISSUE TITLE
Checkmarks next to tiers benefits that have been filled in have incorrect background colour in dark mode

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#18872]
### Issue Summary

As the title says, checkmarks next to tiers benefits that have been filled in have incorrect background colour in dark mode.

**EDIT:** This was with the free tier, I don't know whether or not this also occurs with paid tiers.

![Xnapper-2023-11-06-16 50 50](https://github.com/TryGhost/Ghost/assets/27488257/3f2135c9-0b96-4d63-940b-8915ba31e525)

### Steps to Reproduce

1. Navigate to Tiers while in dark mode
2. Add a benefit
3. See that the background of the checkmark to the filled-in-benefit has the incorrect background colour

### Ghost Version

5.71.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Akhi88S** [comment]
yes @stromfeldt, background color as showing in following capture is causing the issue here.
<img width="1349" alt="Screenshot 2023-11-11 at 4 59 03 PM" src="https://github.com/TryGhost/Ghost/assets/39363939/a665f800-e27d-4b59-9562-6ef2c570f2b4">

Hey @daniellockyer  @peterzimon, can you please assign the issue to me.

**Comment by dvdwinden** [comment]
Hi @stromfeldt, 

Thank you for reporting this issue — it should now be fixed.
