### ISSUE TITLE
Emoji picker of callout cards has a light background in dark mode

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#19038]
### Issue Summary

As the title says, the emoji picker of callout cards has a light background in dark mode.

![Xnapper-2023-11-17-16 10 28](https://github.com/TryGhost/Ghost/assets/27488257/6e7372ea-6fee-4184-a66b-490ea32111c0)

### Steps to Reproduce

1. Create a callout card in dark mode
2. Select the emoji picker
3. See that the emoji picker has a light background

### Ghost Version

5.73.2+moya

### Node.js Version

Yes

### How did you install Ghost?

Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Firefox 119, macOS 13.6

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Abhishek7Tech** [comment]
Hello @stromfeldt I would like to contribute and fix this issue.

**Comment by subratdev18** [comment]
@markstos can i work on this issue?

**Comment by suprabhat15** [comment]
hey @markstos I am interested to work on this issue.

**Comment by markstos** [comment]
@Abhishek7Tech @suprabhat15 Normally you don't have to wait for permission to contribute to open source. Just code a patch and submit a PR if you are interested.

Even if someone replies and says "OK, go work on it", there's not a guarantee your PR will be accepted anyway, perhaps for quality or style reasons.

If you want to want to let other people you are working on a PR so they don't duplicate effort, you can leave a note like "I'm starting on a PR for this now". 

And if you two of you want to contribute competing PRs, you can do that. The one that's contributed first or if some higher quality is likely the one to be merged. 

If the only reason you would be creating the PR is because you are interested in having it merged, and not because you would actually use it yourself, I suppose that's that's a reason to find out if there's interest first.

But this issue seems like it's a clearly a bug that the project would definitely want fixed.

**Comment by asenseofpradhyu** [comment]
Hello @stromfeldt 

The fix for this issue has been implemented in the [Koenig](https://github.com/TryGhost/Koenig) repository. Once the changes are merged, the dark mode will work in the emoji picker.

You can track the progress of the pull request https://github.com/TryGhost/Koenig/pull/1085
