### ISSUE TITLE
[Casper Theme v5.7.0] Code block not displayed properly

### ISSUE THREAD

**Issue by aarnoud** [TryGhost/Ghost#19410]
### Issue Summary

As you can see on this [page](https://shadow-codex.com/install-shadow-client-rpi5/) or here as an image the code blocks (bash language) are not wrapping properly as on the admin, post edit page.

**Safari :**
<img width="830" alt="Casper Safari" src="https://github.com/TryGhost/Ghost/assets/3198544/121f50e6-8f02-4596-9132-4001e3f7ed24">

**Ghost Admin :**
<img width="836" alt="Ghost Admin" src="https://github.com/TryGhost/Ghost/assets/3198544/b3181b06-7abb-4fd4-b89b-c67bc2070e28">

Also on the UI/UX standpoint in the post edit page, the type of code (bash/vim/....) makes it hard to read bellow.

### Steps to Reproduce

1. Make a long code block with text
2. Check from website it's not wrapping using Casper v5.7.0 theme and "bash" language

### Ghost Version

Ghost-CLI version: 1.25.3 / Ghost version: 5.75.2

### Node.js Version

18.17.1

### How did you install Ghost?

Debian Bookworm / 

### Database type

Other

### Browser & OS version

Safari 17.1.2 & Chrome 120.0.6099.129 / MacOS 12.7.1 (intel)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by DanielOX** [comment]
@aarnoud please referer to the following screenshot. it is shwoing proper wrapped version under 
**Add uinput support and reboot** title.  I am using **Firefox 121.0.** 
<img width="1525" alt="Screenshot 2023-12-31 at 7 26 58 PM" src="https://github.com/TryGhost/Ghost/assets/33195456/a1e9d859-2b5b-4b3c-95c6-91834d4d9764">

**Comment by aarnoud** [comment]
@DanielOX I was more expecting something like this :
<img width="1745" alt="wrap" src="https://github.com/TryGhost/Ghost/assets/3198544/24cff128-4b5b-4dab-9cdc-b85b1ae43ad3">

**Comment by minimaluminium** [comment]
It's a common practice to show the `<pre>` tag content as it is instead of wrapping it automatically. It was intentional to add horizontal scrolling to the tag. You can either format the code in the editor or use the code injection method as you've already done above.

Some references:

**DigitalOcean:**
![CleanShot 2024-01-24 at 12 18 32](https://github.com/TryGhost/Ghost/assets/1418797/1eb9df9e-acdc-492a-a83e-107328a586da)

**NextJS:**
![CleanShot 2024-01-24 at 12 19 50](https://github.com/TryGhost/Ghost/assets/1418797/994bc599-4b93-4373-b974-b3d016149a69)

**Netlify:**
![CleanShot 2024-01-24 at 12 20 30](https://github.com/TryGhost/Ghost/assets/1418797/0cfd9607-41d1-40fe-81ea-31e7b4e6f4d6)
