### ISSUE TITLE
Generate and store coverage reports from Travis

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#2029]
Similar to / after #1063 

Update our tests on travis to also generate the coverage report, and then ~~store the .html file somewhere on GitHub~~ send the results to CodeClimate.

- ~~We should at some point create a GitHub repo especially for storing data/images/etc from the tests~~
- ~~.html files could be stored in gh-pages or in the wiki, or just as files in a folder on the repo, with a date stamp so we can see which is the latest.~~

None of that is necessary, we have a CodeClimate account, and can use that to collect and display coverage data in a nice format.

**Comment by hoxoa** [comment]
Can take a look at this

**Comment by hoxoa** [comment]
Sorry for taking longer.
@ErisDS can you please go to [Code Climate](https://codeclimate.com/github/TryGhost/Ghost) and click on the button `Set Up Test Coverage` on the right side (you need to be loged in). Then search for the token, something like `CODECLIMATE_REPO_TOKEN=token`. After that go to [Travis](https://travis-ci.org/TryGhost/Ghost/) and to `Settings --> Environment Variables --> Add new variable` and paste the token. `name` is `CODECLIMATE_REPO_TOKEN` and `token` is the token you copied ;) `Display value` stays on default (off). 

One question, there are a few ways on running the coverage task. 
* put the coverage task at the end from `grunt validate` so travis runs it.
* in the `package.json` make a new script `coverage` witch runs `grunt coverage` and is executed from an `after_script` in travis.yml
* or don't modifiy the grunt task or package.json and put it in the `travis.yml` file in an `after_script:` so travis runs it after the script (test aka grunt validate --verbose).

So which of the three ways shoud I take? I personally prefer the last, because you don't have to change the grunt task or the package.json and travis will run it, not that it's a thing, but the data-sending-to-code-climate-task will be in an after_script, so I'd simply had to at three lines in the `travis.yml`.

**Comment by ErisDS** [comment]
Hey @hoxoa apologies for taking so long to get around to doing this. I think you're correct on preferring the last option. We don't really want coverage running for every build, so doing it at the end makes most sense I think?

**Comment by hoxoa** [comment]
@ErisDS thanks for the setup.
My english skills aren't the best, so maybe I wrote something misleadingly. I meant with the last option, we don't have to modify any files except the `travis.yml`. The coverage task will still be run on every build and on all of the 9 jobs. 
But I will try to get the number down, so that the task will only be run by as little as possible and at the best only at one job. 
Another option would be to run the coverage task only when the build passed, so is green on travis.

**Comment by ErisDS** [comment]
Our tests take a pretty long time to run as it is, so I'm keen to find a way to only run coverage at the end, so I think doing it with `after_success` is the right option?

**Comment by hoxoa** [comment]
Ok, will put it in the `after_success` and try if I can get it to run only on one job. 
Will make a PR soon and then we can see how it works.

**Comment by halfdan** [comment]
For reference: https://github.com/travis-ci/travis-ci/issues/929 and a workaround for that issue at https://github.com/dmakhno/travis_after_all

**Comment by ErisDS** [comment]
I was watching this as it built - it looked like it sort of worked (the first build stayed until the final one passed), but the coverage didn't get sent to codeclimate. I've made sure the correct token is in Travis and restarted the build.

I'm thinking have the first build hang around might not be a good idea. We only have 8 concurrent jobs, and 9 builds meaning that if a few PRs get updated and one or two builds fail (which is a regular occurrence because our builds are frequently flakey) we'd run out of jobs. 

Instead of using test_all, we could simply only run coverage on the first build? E.g. check if `$DB` is 'sqlite' and `$TRAVIS_NODE_VERSION` is 0.10 - and only in that case do the coverage?

**Comment by hoxoa** [comment]
@ErisDS me too :D the token is ok, the coverage wasn't generated (the grunt coverage task wasn't started) and therefore the file was not found and couldn't be send to Code Climate. I think I fixed this, so this time it should work.

Yep this is right, per se this is a good way, but when something hang, or the other 8 builds need time, the first job waits very long.

This was exactly my first idea, check for db and version and then only run when it passed. The only thing this way is, when a new node version is out e.g. 0.13 and you remove the old 0.10, you have to update this check, otherwise it won't work, but this isn't that complicated. Maybe just put a comment in the `travis.yml` and everything is fine.

Another idea I had was to check for the env vars (DB=sqlite3 NODE_ENV=testing) and then only build when it passed, this way we don't have to check the node version, but it then is build three times and not one. (But when iojs and nodejs are merged together I think you only check against two versions ;) but still more then one). 

One thing I will also check if I can get it implemented (should work) is to check if the build is a PR or not. My thought was to only generate and send coverage when the build is `!=PR`, so it will only run when a finished PR is merged in master. Then it is fewer then to check every PR and it should be enough to have it regularly updated.

**Comment by hoxoa** [comment]
Ok, this time everything is green and coverage was generated, but couldn't be send. Just checked why and found the mistake.

See [this](https://travis-ci.org/TryGhost/Ghost/jobs/68636072) build and [this](https://travis-ci.org/TryGhost/Ghost/jobs/68531094). The first is a PR, the second a merge. See line 95 on the second the `env var` is set. On the PR only the one from the `travis.yml` but not the profile one.
So when we want the coverage task only be run from merge everything is fine, but if we also want it from pr, I/we need to put it in the file.  

When you check my PR you can see at the end, that the job was waiting `889.77 seconds` so `14.8295 minutes` on the other jobs to finish witch is very long.

The whole coverage generating and sending takes only `21.04 seconds` so even if we run this 3 times it is only `1 minute`.  Because of this I would they we shouldn't use the `wait-for-all-thing`.

**Comment by ErisDS** [comment]
I think it would be best to run it just the once, on a single version, without the wait-for-all thing ( and preferably the first build, but changing the build order would also be ok) and I agree that running it only on merges rather than PRs would be preferable.
