### ISSUE TITLE
Got "Request not understood error" after clicking the "go to analytics" button

### ISSUE THREAD

**Issue by tigerzioo** [TryGhost/Ghost#20773]
### Issue Summary

In the ghost admin, when click "go to analytics" of a post, It shows "Request not understood error".

### Steps to Reproduce

Go to ghost admin
Click "Posts"
Click "go to analytics" button of any posts
![analytics](https://github.com/user-attachments/assets/61469f52-c754-48be-8c32-b01d12af9381)
Got this error
![400](https://github.com/user-attachments/assets/9e651da5-04f9-496c-8af1-252dd8f7805b)

### Ghost Version

5.89.1

### Node.js Version

not sure

### How did you install Ghost?

debian docker

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by 9larsons** [comment]
Hi @tigerzioo, could you please confirm what db you are using? The last time someone brought this up, they were using MariaDB which has been unsupported for a while now.

**Comment by tigerzioo** [comment]
Yes, I am using MariaDB. Thank you for letting me know. Actually MariaDB works pretty good on Ghost. This is the only place I see the error. Unfortunately I can only use MariaDB on this server for now. I will still use Ghost though there is one issue. I really like Ghost. Thank you all for making this good blog platform.

**Comment by 9larsons** [comment]
Got it, glad to hear you're enjoying it! I'm not aware of any other limitations at this time.

**Comment by skyblaster** [comment]
I'm seeing this issue and also using MariaDB (11.5.2) with Ghost 5.94 thru 5.103.

When I click https://example.com/ghost/#/posts/analytics/674a5ec52c30890001333135/

I can see the URL it's trying to access is: https://example.com/ghost/api/admin/posts/674a5ec52c30890001333135/?formats=mobiledoc%2Clexical&include=tags%2Cauthors%2Cauthors.roles%2Cemail%2Ctiers%2Cnewsletter%2Ccount.conversions%2Ccount.clicks%2Csentiment%2Ccount.positive_feedback%2Ccount.negative_feedback

This results in the following:
`{"errors":[{"message":"Request not understood error, cannot read post.","context":"Could not understand request.","type":"BadRequestError","details":null,"property":null,"help":null,"code":"ER_BAD_FIELD_ERROR","id":"d7c4e670-b209-11ef-944a-f52ba402cf28","ghostErrorCode":null}]}`

If I remove `%2Ccount.conversions` then I get a proper response:
https://example.com/ghost/api/admin/posts/674a5ec52c30890001333135/?formats=mobiledoc%2Clexical&include=tags%2Cauthors%2Cauthors.roles%2Cemail%2Ctiers%2Cnewsletter%2Ccount.clicks%2Csentiment%2Ccount.positive_feedback%2Ccount.negative_feedback

Is this a common result of using MariaDB, or could it be due to a lack of a "count.conversions" field?

Thanks!
