### ISSUE TITLE
excerpt outputs unwanted contents

### ISSUE THREAD

**Issue by steinwaywhw** [TryGhost/Ghost#3846]
## Description

When I have a short post with some `<script>` tag in it, those scripts are rendered as plain text on the index page by `{{excerpt}}`.
## Live Demo

http://www.steinwaywu.com/
Please look at the blog post "One-liner to Find Out Available Ports in /etc/services" where I included some javascript `$(".readme").parent().parent().remove()` to delete the "readme" file from an embedded gist.
## Environment

I'm running on Ghost Pro, with a custom theme based on Casper 1.0. The customization only involves adding few more javascript library.
## Suggestion

Probably should add some pre-processing to filter out unwanted stuff, e.g. scripts, mathjax equations.

**Comment by ErisDS** [comment]
This will be fixed by the changes outlined in #5060

**Comment by preslavrachev** [comment]
I am experiencing the same issue with version 0.6.4. I have manually added a custom script to embed GfyCat videos at the top of one of my posts. As a result, the excerpt of that post on the index page shows the entire content of the script (see the attached image). This is definitely not a desired behavior, since I am sure that Google will index it that way, and it also makes absolutely no sense to an incoming visitor.

![screenshot](https://cloud.githubusercontent.com/assets/86060/9540341/04a4f768-4d5e-11e5-9606-1db57e82dbe9.png)

**Comment by ErisDS** [comment]
You can work around this by placing the scripts at the bottom of the post instead of the top.

**Comment by ErisDS** [comment]
Closing this issue in favour of the new custom excerpt #8793. We can revisit improving the automatic excerpt some other time if there is more demand for it.
