### ISSUE TITLE
[Discussion] Make Ghost's Markdown parser adhere to CommonMark

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#3959]
We know that markdown is ambiguous. Let's unambiguate it as per ~~http://standardmarkdown.com/~~ http://commonmark.org and implement the syntax in our markdown parser.

Ref: http://blog.codinghorror.com/standard-flavored-markdown/

**Comment by beobast** [comment]
I would suggest [Remarkable](https://github.com/jonschlinkert/remarkable) as a javascript implementation of [CommonMark](http://commonmark.org/). I personally use it for my projects : it's easy to extend.

- Supports the CommonMark spec + syntax extensions + sugar (URL autolinking, typographer).
- Configurable syntax! You can add new rules and even replace existing ones.
- High speed!
- Community plugins on npm.

**Comment by novaugust** [comment]
Right now, commonmark isn't useable for us as its specs lead to something nasty for live-rendering of the markdown. Hannah originally wrote up a great issue about it with them, but when they changed the name they nuked all their old issues.  
The problem is that astericks around words are interpreted differently depending on if there is a space or not, causing distracting flashing text if you're editing within an already created punctuation group (something that's fairly common, I'd say)

![commonmark](https://cloud.githubusercontent.com/assets/1207005/6900819/0ed46b18-d6be-11e4-9a8d-211936578604.gif)

I'm going to close this issue against that for now; perhaps one day we'll change our live-rendering, or commonmark will reconsider their spec in light of this live-rendering usability issue.

**Comment by joeldrapper** [comment]
@novaugust couldn't you run a simple filter on the markdown content that removes trailing spaces, before parsing it with CommonMark? You'd have all the benefits of complience (or near complience) with a proper Markdown spec and you'd solve this usability issue for the live preview.

I'm no regular expression expert but this is the idea...

![meow](https://cloud.githubusercontent.com/assets/246692/9332259/b1695a7a-45bb-11e5-804a-424a11a26e32.gif)
