### ISSUE TITLE
Themes: {{excerpt/content round=“up”}}

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4017]
There have been a number of discussions around improving the excerpt functionality. Many people prefer to use the `content` helper rather than the `excerpt` helper and have more HTML. There is also a lot of dislike for the `words` and `characters` options because they cut off words and sentences in the middle.

To resolve this, let's add a new `round` parameter to the `excerpt` and `content` helpers which moves the cut off point to the end of the nearest sentence, the option should accept "up" or "down" to determine which way to round.

The difficulty here will be with picking what counts as the end of a sentence. I think a full stop or double newline make sense?

For the content tag, there is already a concept of 'sentence terminating tags' in the downsize library but I don't think it takes full stops and newlines into account at present.

**Comment by brokenalarms** [comment]
The discussion of how best to round, whether to strip html or not etc in some way misses the point, as it seems to not consider the control of where an excerpt begins. This is what brought me to this thread after making my first post - if the first line of my post is a sub-heading, then it appears as plain text and therefore out of context. I want to limit my excerpt to the first paragraph following that heading.

The problem is also outlined here in the same way (wishing to exclude a leading blockquote): 
https://ghost.org/forum/using-ghost/17745-exclude-content-for-excerpt/
...and partially addressed (through a hack) here:
https://ghost.org/forum/using-ghost/15991-customize-post-preview/.

In both situations, the desired behaviour is to specify both start and end points for an excerpt via tags in the HTML. This obviates the need for ghost controlled rounding up/down by paragraph at all...

I apologise if this is being considered, but all the discussion around this keeps leading to this thread which seems to not address the problem :)

**Comment by isaaki** [comment]
I agree with @brokenalarms. It seems that there should be a dead simple yet flexible approach to giving users full control of their excerpts (on a post-by-post basis). While rounding up or down is helpful, it seems far from solving the real problem: users not being in full control of their excerpts.

Some type of wrapper block seems ideal, which could start and stop at any point in the post. It'd be extra-sweet if this could optionally be removed from the body of the post itself, enabling "excerpt-only excerpts." 

Just my 2 cents :)

**Comment by codeaid** [comment]
I totally agree with Isaac - in my view specifying the lenght of excerpts doesn't solve the problem. There must be a way of specifically setting the start and end of one.

I'm sure I'm not the only one, but on my blog my excerpts can range from a couple sentences to a whole paragraph with (programming) code examples.

My suggestion would be the same as @breakingco's - to introduce new markdown/html element(s) that would allow defining the start and end of an excerpt. Start could be optional and if only the end tag is present then assume that start is the start of the article itself.

That would be far more flexible than just saying I want the first 30 words because that rule won't be valid for other posts.

**Comment by arianf** [comment]
What about incorporating a `<!--more-->` tag, to ease the transition from WP to Ghost, like in this pull request #4973

**Comment by ErisDS** [comment]
As I explained in the [PR for this issue](https://github.com/TryGhost/Ghost/pull/4421#issuecomment-64831068) after further thought this really didn't feel like the right approach. Determining the 'end of a sentence' is incredibly difficult to do in a reliable way, and so the PR drifted towards paragraph rounding, which then lands us in a weird half-way house.

Therefore it seems far more sane to add paragraph-level truncation to the existing word and character-level truncation. As well as adding back in some formatting, as outlined in the new excerpt improvements issue #5060.
