### ISSUE TITLE
Refactor Middleware + Express Apps

### ISSUE THREAD

**Issue by halfdan** [TryGhost/Ghost#4172]
This is a follow up to #1961 and #4069.

The Ghost middlewares are currently a complete mess. We have two apps (blog and admin) and some middlewares for each in `middleware/index.js` and others in `middleware/middleware.js`. Some of the middlewares are shared between both apps, others really only make sense on one. The separation of blog and admin into their own express apps was a good start to get things cleaned up. 

As part of this issue the following tasks should be considered:

- [x] Find a new home for each middleware
- [ ] Refactor /ghost/api into its own express app
- [ ] Clean up the set up process of Ghost (how the express app gets initialised)
- [x] Improve test coverage for middleware

I'll be working on all of these.

**Comment by ErisDS** [comment]
I'm interested to hear if this went any further? There've been a lot of different attempts and angles on solving the middleware, and ghost-as-middleware problems, and I've spent significant time myself recently trying to figure out what steps to take to try to improve the core of Ghost core to make everything a bit nicer and specifically - more testable.

Going to cc @gleneivey, @JoshWillik, @hswolff and @jaswilli here - all people who have dived into the murky depths and tried to make Ghost better.

A couple of issues worth referencing as well:

* Good old #827 - we'd love to make Ghost usable as express middleware
* This issue - finishing up the partial refactor of the different express apps inside of Ghost
* The unloved #2182 - optimising Ghost boot (and potentially lazy-loading modules when they are needed rather than intialising everything at the beginning)
* And just for fun mentioning the idea that we'd like more dynamic routing: #4519 - so that routes like /author/ or /tag/ can be customised (and translated).

This is a massive bundle of stuff that I'd like to fix. At the heart of it all, we need to make the internal Ghost modules behave more like modules, and reduce the amount of glue we need to hold everything together. I've been thinking about how to unpick it into stages and I think, wait, know that task is way beyond one person. It would be great to work together to figure out how to rejig the Ghost internals into something simpler.

**Comment by robconery** [comment]
I made some good progress, but came up against everything you just wrote, which put me exactly where I was a year ago: there needs to be a decent cleanup done here. And I have some ideas.

I wrote a bit reply here which I just deleted as I don't want to overwhelm :) but basically: yes. I walked right into a wall and couldn't go further without pulling up weeds and moving *everything* around which I know you don't want. `/core` needs to be gutted - it's put together in a very "script-y" way which means that modules are being treated as includes and everything is bound together.

Moving forward... I think a freeze should go in and a month taken to clean things up. Some ideas I had are:

 - Move modules to a `/lib` directory to keep with Node standards. Move isolated bits (authentication, caching, middleware stuff) into their own repos and reference them in package.json using a Github URL
 - Use an app.js file in the root to do what it's supposed to do: create the express app and configure it by calling into various Ghost modules
 - Simplify `/admin` by sticking the views in the views directory. There's no need to be tricky here, just pop it in there and let it go. No need for a second app either (the problem you encountered RE views missing was actually rather silly and easily fixed by passing an absolute reference to the admin view, not switching the views directory on the fly).

I'll stop here, I *sincerely* do not want to rehash our conversation from a year ago :). I'm happy to help as needed but for this to work we need to freeze things and restructure - and I'm all yours if you choose to.

**Comment by JoshWillik** [comment]
## Comments on #827 

I haven't been closely following the state of the ghost core for a little while, but I'm surprised #827 is still open.
Between the midddleware PR #3849 and the HTTPS bugfix from PR #4435, Ghost has been working as (mounted)middleware on [my site](https://www.joshwillik.com/blog) without issue for quite some time now. Both PRs still pass tests.

This is obviously going to be biased, but I've always felt that my approach to Ghost-as-middleware was the cleanest proposed solution. The **whole** implementation is [26 lines of code](https://github.com/JoshWillik/Ghost/blob/middleware/core/middleware.js). 

The only other real solution I've seen -- #4101 -- separates the boot process into totally different paths: ghost-standalone and ghost-as-middleware. I think this introduces unnecessary code complexity; there is more code surface area and the two paths functionally achieve the same result.

*Sidenote: #4101 bundles a lot of good changes, like being able to pass a config object directly instead of a config file path. I think a lot of the work going into that PR is fantastic. I just don't think it's the right way to go for ghost-as-middleware.*

I don't really have any thoughts on the second two, other than they're both great ideas.
Unfortunately I don't have the time to tackle either right now (unless you're looking for a new employee ;P)

Just my 2 cents.
*If I misunderstood the issue's purpose, my apologies, feel free to delete this comment.*

**Comment by robconery** [comment]
Also - I forgot to add this - the entire `api` module is a disaster. It's a data access interface as well as an HTTP endpoint - really hard to test (as I'm sure you've found out) and makes things difficult to use.

**Comment by robconery** [comment]
@ErisDS I have an idea: what would be the best way to "arm-wave" a structure that might make sense that we could steer towards? In other words - a dart-board/target where we could look at files and functional bits and then split out exact tasks?

I think, for instance, that a great first step would be to identify the isolated bits that go into Ghost (off the top of my head): authentication, authorization (role-based stuff), CMS workflow, an HTTP API, a data-access surface, mutable config, the Ember app, caching, update-checker, etc.

Once these are laid out, the next step is moving them to their own modules with their own tests, Gruntfile, package.json, etc.

Once that's complete, then we mesh them all together into Ghost 0.7 :).

I'm happy to take a stab at this along with you and whomever - let's just decide what venue/format. Google docs maybe? I'm open to anything.

**Comment by ErisDS** [comment]
@robconery This is a tongue-in-cheek woaaah! Slow down there! (although the last comment you just wrote whilst I was writing this is waaaay more along the lines of what I'm thinking).

I'm starting this conversation so we can gather together concrete ideas on how to move forward **because** the task is big and scary for someone on their own. I strongly believe if we collaborate as a group of smart people, we can come up with a game plan, and a set of steps to get us there. No need for a big freeze or scary rewrite.

@hswolff did some excellent work last year to start moving the ship in the right direction. I think if there's a group of us all working on a plan we'll get there much less painfully.

All that said, let me comment on a couple of things:

@JoshWillik (and @gleneivey) The reason #827 is still open is because there are competing ideas, and it's very difficult to assess which direction is the right one. As you say - there are great ideas in both PRs, but there's also my underlying niggling feeling that the reason it's been so hard to get a sensible solution is due to underlying problems (that are what this discussion is intended to get to the bottom of).

@robconery modules being in the same repo or a different repo is a religious debate and not one we need to have to solve the problem at hand. I think the focus should be on refactoring the code so that each isolated piece acts as a module and is fully testable in its own right. A discussion/decision on whether or not it makes sense to move them out can and should be deferred until we have the luxury of being able to do it ;)

I think it would be a good first step to collect some examples of well-structured projects that we can borrow from?

**Comment by robconery** [comment]
@ErisDS Yep, understood. The one bit of clarification however is that breaking modules into their own repos is something you might want to consider sooner, and it's less of a religious decision as it is a long-term one. For instance - I keep bringing up Authentication. If that doesn't change much, then push it out. If you can tweak it "out of band" and improve it on its own - it is a fine choice to move to it's own repo. Grunt did just this with its internals (the CLI vs. the runtime).

I do agree, though: first thing is to sketch it out :).

For well-structured stuff, anything in https://github.com/tj is worth looking over. Also, since I brought up Grunt - look how they've scaled their stuff by breaking it out! https://github.com/gruntjs

**Comment by JoshWillik** [comment]
+1 for [TJ](https://github.com/tj), the man is a wizard.

**Comment by robconery** [comment]
@JoshWillik Totally agree. I have quite a number of friends who have a "Shakespeare Conspiracy" going with the guys - they're convinced he doesn't really exist and, instead, that he represents the work of 5 or 6 others. In fact I had one friend go into his Git repo and analyze commits and times as well as location - pretty funny.

**Comment by JoshWillik** [comment]
@robconery I'm half inclined to believe the theory. It helps me cope with my personal productivity being less than 5% of his. :stuck_out_tongue_winking_eye:

**Comment by ErisDS** [comment]
I think I could have phrased my question a little better - I was thinking more along the lines of looking for specific examples of patterns inside of projects that we could use to nurture the Ghost internals a little. For example, during the boot process we do a lot of require('thing') and then thing.init() calls (this is what #2182 is sort of about).

Perhaps a good example to start on, would be the mailer - surely we can refactor it so it lazy-loads when we need to send mail, rather than initialising it on boot. 

It's small and serves a single purpose, so perhaps we can throw together some examples of an ideal structure for it, and use it as a template?

**Comment by hswolff** [comment]
re: splitting out modules into their own repo...at this point in time it's not necessary imo. I'd be more in favor of following what React has done and allow for usage of sub-modules within Ghost the way you can with React. [For an example look how this Three.js + React project uses modules within React.](https://github.com/Izzimach/react-three/blob/master/src/ReactTHREE.js#L24-33)

This would allow us to get our footing towards isolating individual functionality and still allow it to be exposed such that it could be used by 3rd-party libraries.

IMO the first tangible step towards making Ghost more modular is by shifting all the modules within Ghost to be run on demand, not upon being required and included in another file. I did some work on this, I'm not sure where it was left off however.

But what you said @robconery about Ghost being very "script-ey" is very true, and I think just moving away from that as strongly as possible will be a good first step.

Also I do think we need some idea of one top-level coordinator for a Ghost application instance. That being the thing that coordinates all the modules so that together it equates to a running Ghost application.

**Comment by hswolff** [comment]
Another thought would be to shift the code structure towards isolated modules, [similar to what Ember does](https://github.com/emberjs/ember.js/tree/master/packages).  This is where the `src` and the `tests` exist alongside each other and are treated as if they existed in isolation.

The Ghost app itself would be another module that just consumed the other ones.

**Comment by robconery** [comment]
@ErisDS One pattern than I've seen a number of times (which I can't remember where) is that your app emits events at various points during startup. You then initialize the bank of modules that you'll need, passing in the app to each (in a constructor or factory, whatever). The module then simply wires up what it needs to do when the app emits certain events.

The hard part here is knowing when these events are finished and when the app can start. Usually it's OK to have these things fire up asyncronously - in other words *is it really necessary to wire up the mail engine and then move on?* - probably not. So, you do the necessaries: load up the middleware, fire up the DB and then start the app.

This has the major benefit of allowing extensibility in the future with modules you add in.

**Comment by robconery** [comment]
@ErisDS So my answer above is basically "Yes" - with EventEmitter it's quite easy and extensible to wire things, but sometimes not completely obvious. Here's an example in pseudo-code:

```javascript
var app = express();
app.emit("instantiated");
//we need some data
var DB = require("./lib/db");
//instance the db and
//connect it
app.db = DB.connect(app, connectionString);
```

The only thing we'll probably need right away is to know the DB is connected and we can have the DB module tell us that's the case:

```javascript
var DB = function(){
  var db = {};
  db.connect = function(app, connectionString){
    //psuedo connection code
    client.connect(connectionString, function(err,dbInstance)){
      app.db = dbInstance;
      app.emit("db-connected");
    };
  }
  return db;
}

module.exports = DB;
```

in our app.js bootstrapper we can listen for this event:

```javascript
app.on("db-connected", function(){
  //we have a db instance on app, so let's do whatever else we need!
  app.mailer = require("./lib/mailer").load(app);
  app.auth = require("./lib/authentication).load(app);
});
```

In this case we have an open DB connection so we're good to go. The only thing I can think of that might need to be done that takes a while is the update check - but that can be handled using sockets and it really doesn't need to go off during startup. 

But, for the sake of argument you could...

```javascript
app.on("update-checked", function(updateReady){
  //http.createServer(app).listen...
});
```

**Comment by ErisDS** [comment]
This is definitely not done yet!
