### ISSUE TITLE
Authorize screen

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#4178]
This belongs to the OAuth Epic: #4004 - please read this for the big picture of what this issue is for :)

---

To allow a registered client to authenticate a user it is necessary to implement a special login page.

URL:
`/ghost/authorize`

Flow:
- Client redirects the user to `/ghost/authorize`
- Information about the application is displayed (including client permissions)
- User inserts username and password and confirms
- Ghost redirects back to the client application

This issue will need some design guidance from @JohnONolan :).

Examples from other services can be found on the `hello.js` website by klicking on the third party service icons (http://adodson.com/hello.js/#hellojs).

I'm uncertain how this could fit into our Ember admin? Any opinions from our ember savvy ppl are very appreciated.

**Comment by JohnONolan** [comment]
Initial flow concept:

## [Connect to Ghost]

Once someone hits "Connect to Ghost" button on a 3rd party service, the following page loads from Ghost.org. This is designed for ease of use for 3rd party developers so they only have to implement a single button rather than an additional form to determine what URL to make their API request to.

The only function of this form is to redirect the request to the appropriate place.

![image](https://cloud.githubusercontent.com/assets/120485/7018587/157e0b0c-dd0f-11e4-97c9-650fe3f16f07.png)

## Authenticate app (signed in)

If you're already signed in to your Ghost blog then you see the following screen

![image](https://cloud.githubusercontent.com/assets/120485/7018597/3cf37cbc-dd0f-11e4-87df-fe952237a198.png)

## Authenticate app (signed out)

If you're not signed in, or you click on the "Not you?" link in the previous ^ design - you see a login form. If you fill out this form and press "allow" - everything is done in the background. No extra clicks or screens.

Also note with this screen we're accessing a blog with no @blog.logo so we're displaying @blog.title instead

![image](https://cloud.githubusercontent.com/assets/120485/7018615/76371114-dd0f-11e4-94ad-065278ebf787.png)

## Notes

Icons are inconsistent because they represent a new set which we'll be using soon. In the mean time the equivalents of these icons in the existing set can be used.

Sketch3 file: http://cl.ly/aZOu

**Comment by sebgie** [comment]
@JohnONolan any thoughts on displaying 'client permissions'?

![twitter___authorize_an_application](https://cloud.githubusercontent.com/assets/539213/7018847/d86363ac-dd09-11e4-9257-f0d0de586ca5.png)

**Comment by JohnONolan** [comment]
I looked at many (many many) flows:

![image](https://cloud.githubusercontent.com/assets/120485/7018876/7b009ad2-dd12-11e4-84e6-f46342f67ada.png)

Permissions I think is an enhancement not necessary for first iteration - and we should see how demand pans out. Even some of the biggest apps keep it very simple:

![image](https://cloud.githubusercontent.com/assets/120485/7018902/bf49083c-dd12-11e4-9396-3ef9332d7da4.png)

**Comment by sebgie** [comment]
Adding permissions later makes sense, just wanted to clarify that it wasn't lost :+1:.

**Comment by ErisDS** [comment]
I'm closing all OAuth and most API issues temporarily with the `later` label. 

RE: OAuth, for the next 2-3 months we'll be implementing an official Ghost OAuth login system, providing global access to all Ghost blogs with a single login. We'll be opening issues around this system soon, and I don't want to cause confusion with OAuth for the API.

JSON API Overhaul & OAuth access are currently scheduled next on the [roadmap](https://trello.com/b/EceUgtCL/ghost-roadmap)

**Comment by ErisDS** [comment]
Reopening this issue as the design reference for OAuth screens

**Comment by ErisDS** [comment]
Closing with `later` label until we prioritise this again.
