### ISSUE TITLE
Encode helper is broken in many fabulous ways

### ISSUE THREAD

**Issue by haydenbleasel** [TryGhost/Ghost#4362]
Hey,

Just working on [an issue](https://github.com/haydenbleasel/ghost-themes/issues/13) for one of my themes where I can't use the `{{encode}}` helper on the homepage. Basically I've made the sharing links (Twitter, Facebook, etc - similar to the one in Casper) a partial so it can be included on any page, but `{{encode title}}` or `{{encode meta_title}}` both return `%5Bobject%20Object%5D` on the homepage. Looked through the Ghost docs and there wasn't any sign of a post-template only restriction so I'm opening it up as a bug here.

**Comment by kirrg001** [comment]
@evexoio 

> This still exists, I've tried to reproduce it with the Casper theme:

Yeah, the issue is still open and unresolved.

> is it still really a bug we should fix, or are we ok with it this way?

From

> This is half a known bug, half a documentation issue, and half a misunderstanding about how helpers work. 

Possible solutions were explained with lot's of details in this [comment](https://github.com/TryGhost/Ghost/issues/4362#issuecomment-61071420). This issue needs more research and a final decision. It has currently a low priority for the Ghost team.

**Comment by ErisDS** [comment]
Closing as stale: I think we can fairly say this hasn't been annoying enough to warrant a fix.
