### ISSUE TITLE
Don't output meta tags with blank content

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4424]
If a user doesn't enter anything for their post's meta description, the meta description tag is still output but with an empty content, like: `<meta name="description" content="">`

If the content is empty, the tag should never be output in the first place.

Ref [this comment](https://github.com/TryGhost/Ghost/issues/4413#issuecomment-62363069)

**Comment by Kikobeats** [comment]
hey guys, some problem here.

I understand that the first purpose for `meta_description` is use it in combination with html `meta` tag, but basically if you don't set the `{{meta_description}}` of your post, is in blank (in the post preview you have a preview using the first paraph but actually the variable is empty!)

so, IMHO, basically the right way should be, if the variable is empty, get the html content of the first paraph like the preview.

Use `{{excerpt}}` instead of `{{meta_description}}` when is blank doesn't fix the problem because is not possible to access in the context.

**Comment by JohnONolan** [comment]
So: outputting an empty meta description is definitely completely wrong. We shouldn't be doing that. However: outputting any random content as a custom meta description is actually worse for SEO, not better. If you *don't* enter a meta description, Google will choose the most relevant content to the search term on the page to display as the meta description - which is far better. More info: http://moz.com/learn/seo/meta-description

One option is what @javorszky said:

```
{{#if meta_description}}
    <meta name="description" content="{{meta_description}}" />
{{/if}}
```

however I'm intrigued by @joeldrapper's suggestion. He's actually right, I can't think of a compelling reason why meta description needs to be in the theme rather than in `{{ghost_head}}` - though the same could potentially be argued for `<title>`

Other than: It's slightly un-obvious so maybe theme authors would end up duplicating it cause they don't understand why it's not there? Not sure.

**Comment by joeldrapper** [comment]
@JohnONolan If an app or setting could optionally append `- {{@blog.title}}` (as is the custom of most websites) to the end of the title tag, it probably should be in `{{ghost_head}}` too.

I don't think theme authors would duplicate the tags if it was made very clear in the theme documentation what was included in `ghost_head` but it would effect current themes.

**Comment by ErisDS** [comment]
This wormed it's way into my brain again recently.

> however I'm intrigued by @joeldrapper's suggestion. He's actually right, I can't think of a compelling reason why meta description needs to be in the theme rather than in `{{ghost_head}}` - though the same could potentially be argued for `<title>`

We could certainly output both the title and description in the `{{ghost_head}}` helper. There are a few small downsides:

- current themes would end up with duplication, which is possibly undesirable?
- we'd need to consider customisation options (should it be opt-outable?)
- if we do this, why do we have a meta_title and meta_description helper anyways?

None of these are particularly terrible, they just make things a tad more complicated than they would otherwise be, so I thought up some other options:

I'm not a fan of the idea of modifying the `{{#if}}` helper and so far we've kept to this, opting to build our own rather than overriding the defaults.  So instead, I've got 2 possible helper changes that could solve the problem:

## 1. Use the `{{#has}}` helper... it would require an update, but one that would be useful in other situations. 

Either (ugly - not a fan)
```
{{#has meta_description="true"}}
    <meta name="description" content="{{meta_description}}" />
{{/has}}
```

Or (swap `any` for an attribute name of your choice, could be `property` or `attribute` or `value` or even `notEmpty`)

```
{{#has any="meta_description"}}
    <meta name="description" content="{{meta_description}}" />
{{/has}}
```

The nice thing about this idea is that there plenty of other use-cases for checking if a particular piece of data is available. 

```
{{#has any="tags, feature"}}
 ... this post has either got at least one tag, or it is featured
{{/has}}
```

With this change, you would wrap the meta tags in Casper and other themes would soon follow suit.

## 2. Change the `{{meta_description}}` helper

We could change the meta helpers to have an optional property (again the name is not important just trying to get across a concept):

`{{meta_description html="true"}}` 

This tells the helper to output the full HTML, and the logic for outputting the full HTML would be to only output the description if it was present. We could add the same property to meta_title, although it is less relevant.

Again this change would allow us to make a useful update to casper and let everyone else follow suit without causing any issues.

My favourite is adding some sort of property detection to the `{{#has}}` helper, as that makes sense in multiple use cases, but I'm not opposed to any of the other solutions. Getting to a clear decision would be good as most of these are quite easy to implement.

**Comment by JohnONolan** [comment]
I'm very in favour of moving the whole thing into ghost_head.

The helpers are still relevant - Theme authors may want to output meta content in other places - but I guess that could be a data helper instead of a custom one or whatever

**Comment by damianmuti** [comment]
Was this feature added? I'm trying to find a way to print a page's meta_description if it is present in the page settings.
