### ISSUE TITLE
New Navigation Helper

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4541]
This is part of the Navigation epic: #4535

--- 

![image](https://cloud.githubusercontent.com/assets/120485/5228785/917b5448-7717-11e4-9b1d-1e24a48e5729.png)

Once we've got data stored in the database for navigation items (see #4539), we need to add a new `{{navigation}}`. 

For the content in the above screenshot this helper would output, exactly:

```HTML
<ul class="nav">
    <li class="nav-home"><a href="http://my-ghost-blog.com">Home</a></li>
    <li class="nav-about"><a href="http://my-ghost-blog.com/about">About</a></li>
    <li class="nav-news"><a href="http://my-ghost-blog.com/tag/news">News</a></li>
</ul>
```

### Current State

If the current request URL matches the URL in a nav item then nav output adds "current" class, like

```HTML
<li class="nav-home nav-current"><a href="http://my-ghost-blog.com">Home</a></li>
```

This means that inside the helper, we need to loop through the items from the database, and check if any of them match the current request URL. If it does, we should add a new `current` property to that item in the list, and pass this to the template.

### Handlebars Template

This should work like the `{{pagination}}` helper, so the format can be overridden with a `navigation.hbs` partial. The default to override being something like:

```HANDLEBARS
<ul class="nav">
    {{#foreach nav}}
    <li class="nav-{{label}} {{#if current}}nav-current{{/if}}"><a href="{{url}}">{{label}}</a></li>
    {{/foreach}}
</ul>
```

### Filter

The navigation helper should pass the data through a filter after it has been processed for the current state, and before it gets passed to the template.

**Comment by nsfmc** [comment]
hi, i've done a brief amount of work on this and think i might be able to have a working version of this helper in the next few days. i have a few questions to ask that i'l ask in irc via irc, but i think i have a good grasp on how to implement this. Writing some helper spec tests right now and will aim to have a branch commit to reference for feedback in the next day or so.

**Comment by nsfmc** [comment]
@ErisDS a few small questions, the template above suggests
```handlebars
    <li class="nav-{{label}} {{#if current}}nav-current{{/if}}"><a href="{{url}}">{{label}}</a></li>
```

but it seems like the class the li's class should probably be `nav-{{labelSlug}}` where `labelSlug ~= generateSlug(label)`

since the class *probably* doesn't need the same uniqueness guarantees as post slugs do (since it's prefixed by `nav-`, would it be fine to implement a simple slugify() for labelSlug which looks like `label.toLowerCase().replace(/[^\w ]+/g,'').replace(/ +/g,'-')`? This seems like a fast enough transform that i'm guessing it's fine to leave as a computed property in the {{navigation}} helper and not worth storing in when creating the navigationItems in the first place.

my other question: is something like `{{current}}` implemented right now in some other part of the codebase? it feels like something that might be problematic to reimplement.

**Comment by nsfmc** [comment]
any comments and feedback on the [above commit](https://github.com/nsfmc/Ghost/commit/c75072d09c59c6e3d6ae9f7e02be98789f795566) welcome

**Comment by jaswilli** [comment]
It sounds reasonable to me to convert invalid characters into dashes and use that as the CSS class name.

As far as `{{current}}` goes, you should have access to a `relativeUrl` property in the helper so that you can match the navigation item's `url` property against it.

**Comment by nsfmc** [comment]
great, thanks for the feedback @jaswilli . this [line here](https://github.com/nsfmc/Ghost/commit/c75072d09c59c6e3d6ae9f7e02be98789f795566#diff-3cba55965ffe9b33b5d88a441bfc8a31R31) has the relevant slugify. I'll start work on implementing `{{current}}` tonight, the `relativeUrl` hint is super useful.

The next thing i was wondering is where you think an appropriate place to add in the navigation data. it seems like `frontend.js` is where things like tags and pagination get dropped in, not totally sure what the best way is to query for the NavigationItems here (or if i should call back to an api method to do that query...) 

i'll get the other things working and ping as those get finished though. Thanks again for the feedback.

**Comment by nsfmc** [comment]
hi, i have a quick question about where i should add the navigation items to the context of the page (in `frontend.js`). I tried it two different ways and they're both kinda messy, so i'd appreciate any feedback you have:

the first is by adding a parallel `api.settings.read('navigation')` in `getPostPage()` This then would propagate the navigation items similar to pagination via the options parameter that gets passed through to `api.posts.browse` and from there, it would then be re-extracted into the context object in `formatPageResponse()` similar to the way pagination is.

the second is by calling `api.settings.read('navigation')` from within `formatPageResponse()` and then having that return a promise. This would require changing all its callers to execute the template rendering in a `.then()` and would require altering the method to accept parameters to merge immediately.

Although the first approach feels a bit gross to me since it's a bit tangly, but it also feels less weighty than changing the semantics of the `formatPageResponse` method. I'm trying the first one and commit it and welcome any feedback on it.

**Comment by jaswilli** [comment]
Hi @nsfmc,

It sounds like you're generally on the right track.  I wouldn't add something into `getPostPage()`, for example, that does something unrelated.  I'd look into adding another function to get the navigation setting and then refactor the controller methods as necessary.

**Comment by nsfmc** [comment]
hi @jaswilli , with those last two commits, it looks like the work for the helper is done. I'll leave integrating `{{navigation}}` in casper to whoever heads that up. Let me know if you want me to make any changes or have any feedback for how this might be improved.

thanks for your help with this! hacking on ghost has been a treat.
