### ISSUE TITLE
Allow users to credit Cover Photos they use to the original author

### ISSUE THREAD

**Issue by behrangsa** [TryGhost/Ghost#4569]
Hi,

For cover photos, I usually find CC licensed photos on Flickr and then add them to my posts.

It would be nice if I could add a line of text or caption to the cover photo images and credit the original author or add some ad-hoc text:

![Cover Photo](https://cloud.githubusercontent.com/assets/18451/5273472/dd15e7f2-7adb-11e4-807d-84e6d68d61e4.png)

Thanks.

**Comment by ErisDS** [comment]
Hi @behrangsa, since you wrote this we created a [wishlist](http://ideas.ghost.org/) so that we could do a better job of collecting suggestions like these. GitHub is a pretty poor tool for collecting feature requests as there's not really a good way to get proper validation of your ideas. 

I recommend raising this on the [wishlist](http://ideas.ghost.org), so that we can get a better idea of how important this is to our users and prioritise creating a solution accordingly.
