### ISSUE TITLE
Tag names - unique constraint.

### ISSUE THREAD

**Issue by jaswilli** [TryGhost/Ghost#4687]
Is there a reason why the `tags.name` column doesn't have a unique constraint?  I searched through the issues and didn't really see any direct discussion, despite there being some previous issues on attempts to prevent duplicates.

I think historically the tag input widget has attempted to enforce uniqueness of tag names but now with the addition of the tag management page, tags can be created/edited to have duplicate names.  Unfortunately there are areas of the code that assume a tag name is unique--the tag suggestion list in the editor, as well as the `updateTags` method in the post model class, for example.  If you create two tags with the same name things start behaving badly.

I can't really think of a use case for two tags to have the same name?  It seems to me that we ought to add a unique constraint to `tags.name` in addition to trying to prevent this in the various tag UIs.

**Comment by ErisDS** [comment]
Be good to get this change made, thinking about it the reason why the unique constraint is not there, is because post.title and user.name doesn't have it, so it was just an oversight that tag.name should have it.

The main issue we're going to have with adding the constraint now, is that the code doesn't prevent duplicates, so there may be duplicates in the database already. I'm not sure how we can fix that so that the constraint can be added :anguished: 

Adding an `order` integer to `posts_tags` would also be good as we could start to work towards outputting tags in the order they were added to the post, and allowing that to be re-organised.

**Comment by nerdonaleash** [comment]
Although some time has passed since this was discussed I'd like to reopen it, because in my imho it is an unnecessary constrain to theme and app developers.
To be honest - I'd like to ask the question the other way around: which reason is there to make the tag names unique? 

- imho for the uniqueness of tags the url assigned to the tag should be enough to identify the tag
- as soon as hirachical tags arise it(uniqueness of names) will constrain us from using tags with the same names but different semantic meanings and urls in differentt sub trees/paths of the hirachy, because they have to be unique.
- They're unnecessary extra db constraints

As an example: I am currently trying to abuse tags for navigation in a multilingual ghost...where it is nothing but unusual for the tags  to have the same names (in both languages).
To decide which tag in which language to choose in the editor I've added a "language-hash-tag" to the tag (for example "Java & More #de") and removed it in the UI using a custom helper.

I would rather propose an optional or wildcard field (free to use for whatever) to tags. This would enable theme and app developers to do more with tags and the upcoming tag hirachies than the usual blog offers atm.
Like for example implement and offer more complex and/or specialiced tag based navigations implemented using ghost and it's api only. 
Also multilingual blogs with the same tag names in n (being the language count)-hirachies would enable ghost to offer sth no other lightweight blogging plattform can offer - being honestly multilingual.

I am aware of the fact that the editior's multiselect textfield's autocomplete would have to be refactored to also show the url or the tag's optional field to securely decide which tag to use.

**Comment by ErisDS** [comment]
Been digging through really old issues...

I think all the really bad UI issues with this are gone now that the tag input component has been rebuilt. 

Now that we have a concept of visibility, I can start to see more cases where we might not want to enforce unique tags. 

This hasn't really come up as causing issues, so I think we can safely close this for now and revisit it if we decide to change to logic around tag names.
