### ISSUE TITLE
Bug: Footnote Markdown Syntax Inside Code Ticks Showing HTML

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#4700]
### Issue Summary

When trying to put the [^n] inside of the code ``, it shows the full html instead of the markdown syntax

![screen shot 2014-12-21 at 10 28 01 pm](https://cloud.githubusercontent.com/assets/4715098/5521845/d624d938-8960-11e4-85ee-de82ec45fd74.png)

### Steps to Reproduce

1. Open a post
2. Type in the following: [^1] with a ` on either side
3. You will see the full html instead of the markdown you have typed

### Technical details:

* Ghost Version: 0.5.7
* Client OS: Ubuntu 12.04
* Server OS: Ubuntu 12.04
* Browser: Chrome
* Database: SQLite
* DigitalOcean

**Comment by ErisDS** [comment]
The problem here is that the footnotes code only extracts `pre` blocks before doing it's thing. 

See [ghostfootnotes.js#L81](https://github.com/TryGhost/Ghost/blob/master/core/shared/lib/showdown/extensions/ghostfootnotes.js#L81)

Other extensions like highlights extract both `code` and `pre` blocks: 

- [ghosthighlight.js#L25](https://github.com/TryGhost/Ghost/blob/master/core/shared/lib/showdown/extensions/ghosthighlight.js#L25)
- [ghostgfm.js#L47](https://github.com/TryGhost/Ghost/blob/master/core/shared/lib/showdown/extensions/ghostgfm.js#L47)

Fixing this issue requires adding the code block extraction and replacement to footnotes and adding tests to check that it's working the way we expect now.
