### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by pensierinmusica** [TryGhost/Ghost#4734]
Hi,

It'd be awesome to have the possibility to add image captions whenever needed. If I'm not mistaken, it shouldn't be too hard to implement this feature either.

I've seen someone has come up with [this solution](https://ghost.org/forum/using-ghost/2797-image-captions/).

Would you like me to look into possible alternatives for a moment, and come up with a proposal or pull request?

Cheers!

**Comment by lemur3** [comment]
I'm not sure how ghost converts its markdown, but in my use of Jekyll which uses kramdown, I've been able to add 'captions' to images by putting an extra bit of css and using the 'inline attribute' feature...

http://kramdown.gettalong.org/syntax.html#inline-attribute-lists

so an image that i want a caption on looks something like this:

![Cool Image of a Ghost](/location/of/ghost/image.jpg)
*Check it out a caption about a ghost!*{: .midcaption}

which refers to some simple CSS (which may not be the most beautiful)

.midcaption {
    width:100%;
    display:block;
    font-size: $base-font-size * 0.90;
    font-family: $italic-serif-font;
}

perhaps some of that functionality can be pulled in

**Comment by pensierinmusica** [comment]
Thanks @joeldrapper for detailed answer, and @lemur3 for the suggestions  :)

**Comment by ErisDS** [comment]
Hi @pensierinmusica, as other people have commented, this is possible by using HTML in the editor, and adding captions to markdown isn't really a trivial thing to do.

Nonetheless, since you wrote this we created a [wishlist](http://ideas.ghost.org/) so that we could do a better job of collecting suggestions like these. GitHub is a pretty poor tool for collecting feature requests as there's not really a good way to get proper validation of your ideas. 

I recommend raising this on the [wishlist](http://ideas.ghost.org), so that we can get a better idea of how important this is to our users and prioritise creating a solution accordingly.

**Comment by pensierinmusica** [comment]
Thanks, done!
