### ISSUE TITLE
Informing users when the autosave goes wrong

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4761]
This is effectively the follow on from #4543. We've now got autosave working much more reliably, and more importantly if things go wrong it will recover.

Further still, in 0.5.7 we got better session handling on the editor, such that if you get logged out (which is a common problem which interferes with autosave) you get the option to log in again via a modal on the editor, meaning less chance for losses.

However, there's still no warning to the user if autosave isn't working for some reason. A couple of different options were proposed in #4543 and #4558, which centered around the idea that a warning should be displayed if we get more than X failures in a row.

To take directly from @jaswilli's [comment on #4543](https://github.com/TryGhost/Ghost/issues/4543#issuecomment-65112840)

> Instead of a flag indicating that an error has been shown, we could have a counter that gets incremented when auto-save is invoked and is set back to zero after a successful save. That way we could do something like:

```
if ((this.get('saveAttempts') % 5 === 0) && options.silent) {
  // show an error after 5 missed auto-saves
}
```

The main problem with these ideas is that we don't really know what's going on, so it's probably worth thinking about introducing better logging of events in Ghost, and using Ghost(Pro) to build a picture of what's needed. Still I wanted to record this before closing #4543 as something we probably need to do.

**Comment by felixrieseberg** [comment]
Using Facebook, Gmail and various other services, I got used to simple "offline" hints. [Offline](https://github.com/hubspot/offline) is one of the solutions that I like a lot - in principle, not saying that we should use the library). In particular, I like the idea of catching a failed AJAX call and retrying it when connection has been reestablished.  Basically, I think that a good solution would work with all of Ember data's ajax requests, not just the post autosave.

An error message on failed autosave with regards to save not working might be useful too, but since we can't give useful fixing information for the save issue anyway, we might as well go and report troubles for all AJAX troubles we might run into.

**Comment by ErisDS** [comment]
This hasn't really turned out to be a problem, so closing until we see it causing trouble for users.
