### ISSUE TITLE
Versioning while mulitple people edit simultaneously

### ISSUE THREAD

**Issue by benheb** [TryGhost/Ghost#4769]
I've looked through the road map to try and find something on this, but not seeing it. I'm wondering if there are any plans to improve simultaneous editing in Ghost. We have a blog setup with 6 users, but any time more than one are in a post, each save overwrites the other's work. It would be great (knowing getting to the point of Google docs is a huge undertaking) to at least know when someone else is viewing the draft, and or if they have made changes. Are there plans for something here that I'm just not seeing? 

Thanks!

**Comment by novaugust** [comment]
Yep, it's in the road map, just under "revisions" rather than "versions" :) https://trello.com/c/1wAHv8jZ/34-post-revisions
Took me a bit to find it myself, but I knew it was in there somewhere, heh
I'm going to close the issue, but feel free to keep commenting and I can reopen if there's any need =)
Cheers

**Comment by benheb** [comment]
@novaugust awesome! I see it went from backlog to next then back to backlog, is it in the pipeline for soonish? Or down the road aways...

**Comment by novaugust** [comment]
@benheb Anything in the backlog is pretty much undateable, or "down the road aways" as you say ;)  There's quite a bit ahead of it in "Next", and I think that there's a few other pieces in the backlog that are likely to get moved up before revisions do, though that's completely me speculating
