### ISSUE TITLE
Gravatar profile image breaks when Gravatar image rating is greater than "G"

### ISSUE THREAD

**Issue by Trendy** [TryGhost/Ghost#4770]
I recently changed my Gravatar to a picture of me holding a beer, and rated it as "PG". After doing so, my profile picture in my Ghost blog began to appear as a broken image. 

![screen shot 2015-01-07 at 11 07 22 pm](https://cloud.githubusercontent.com/assets/3655670/5657748/fd824c40-96c1-11e4-9e94-f18b4d24400a.png)

**Issue**
If a user is using their Gravatar for a profile image and they switch the image to one with a rating greater than "G", their profile image in Ghost will now be a broken image.

**Steps to reproduce**
* Create a new user account using an email address that has a Gravatar associated with it (rating of "G")
* Visit http://www.gravatar.com and change your Gravatar rating to "PG"
* Visit your Ghost blog and look anywhere the profile picture should appear (login as the user, etc)

**Separate note**
If you attempt to create a user account and your Gravatar is already rated above "G", no profile picture is set (because the current implementation returns a 404 for anything above "G").

**Suggestions on a fix?**
I've found where the issue occurs, but need some guidance as to how to proceed with a fix.

I could make a simple change to increase the acceptable rating for Gravatars (to which level would be up for discussion), or just fix the broken images when a user happens to switch to a Gravatar that is not rated "G".

**Comment by ErisDS** [comment]
Hi @Trendy thanks for the incredibly detailed report! This issue is a work of art :+1: 

Firstly, I think that Ghost showing a broken image is a bug that ought to be fixed - I am sure there are other reasons why we might get into this state other than the rating (internet problems, gravatar service problems etc) but whilst we have a pretty straightforward reproduction case, it would be great to fix it so that it always falls back to the default if at all possible.

Secondly, I don't think Ghost needs to have any opinion what-so-ever on someone's profile picture. Therefore I think we can also increase the acceptable rating so that it doesn't matter what rating the picture is. If you do signup not realising Ghost will pull your gravatar and want to remove it, that's easy to do.

**Comment by Trendy** [comment]
@ErisDS Haha, thanks, I like to file good bug reports when I come across something!

I'll tackle this in two parts. Tonight I can get all ratings of Gravatar's working/committed and then I'll investigate a way to fallback to the default when a 404 error occurs.

**Comment by jaswilli** [comment]
Hi @Trendy,

The way I understand it, dealing with the broken/404 image result is really easy to handle.  There's a `d` (for default) query parameter that takes a few options.  Right now we have it set to return `404` if the Gravatar isn't available.  If it's set to `mm` it will return the "silhouette" image--that's probably what we should be going with.

http://en.gravatar.com/site/implement/images/

**Comment by Trendy** [comment]
@jaswilli I had the same thought earlier today, actually. 

If no one else is opposed, I believe that would be the easiest solution.

**Comment by jaswilli** [comment]
Probably still want to do the initial check with `d=404` so that we can only save the Gravatar URL as the user's image if they actually have one, but if they do, I'd say swap out `404` for `mm` at that point.
