### ISSUE TITLE
Bug of migrate data from mysql to sqlLite3:

### ISSUE THREAD

**Issue by xiaoyuzhzh** [TryGhost/Ghost#4776]
### Issue Summary
when I migrated my blog data from mysql to sqlLite3,I got a error:
    'cannot read uuid of undefined!!!'

### Steps to Reproduce

First I export my data from BAE.
Then I start up my local blog try to import it.
Two blog project is not the same version.
My orepation is in the picture ghost_import.gif.

### Technical details

* Ghost Version which the data is exported from: 0.5.5
     and the version of the local one is:0.5.7
* Client OS: windows 7
* Server OS: windows 7
* Node Version: 0.10.33
* Browser: 360
* Database:from mysql ,want to migrate to sqlLite3.

![ghost_import](https://cloud.githubusercontent.com/assets/7897498/5675075/f966d3bc-97f0-11e4-8adc-c9ee706f99bd.gif)

**Comment by xiaoyuzhzh** [comment]
Do I need to post my data?

**Comment by ErisDS** [comment]
I think this is far more likely to be an issue of going from 0.5.5 to 0.5.7 than being anything to do with the difference in database. We changed some logic in how UUIDs are handled.

It would be great to find and fix what is happening. @xiaoyuzhzh it is likely that somewhere in your JSON export file there is an item which doesn't have all the right data. If you open the file and have a quick read of it, looking for anything with lots of blank items, you might find the culprit. Otherwise sharing the export file via a gist would be very helpful.

Short term, if you find the offending piece of data it should be easy to manually fix it so that the import works.

**Comment by felixrieseberg** [comment]
I remember working on the importer and already fixing a bunch of issues around missing/changing uuids - I'd be happy to take a look. 

@xiaoyuzhzh, I'd love to see the export file. We could probably fix this issue in the importer very easily once we know who the troublemaker without an uuid is ;)

**Comment by xiaoyuzhzh** [comment]
Sorry for answer so late.How can I send my export file to you.Would you mind give me your Email.@felixrieseberg
And I will try to use ghost witch version is 0.5.7 to connect mysql directly ,will that work?
For now ,I have not success yet.Something wrong with my bae.

**Comment by felixrieseberg** [comment]
@xiaoyuzhzh: My email is felix.rieseberg@microsoft.com.

**Comment by ErisDS** [comment]
Did anything ever come of this?

**Comment by xiaoyuzhzh** [comment]
@ErisDS can't figure that out.

**Comment by xiaoyuzhzh** [comment]
I was just found that the data exported from version of 0.5.5 is the wrong data. Even the same version project can not import the date.But I still don't know what's wrong with the data.

**Comment by cobbspur** [comment]
Hey there @xiaoyuzhzh would you mind sending me the file (if you can send it to david at ghost.org)
and I can start to take a further look into this for you :)

**Comment by ErisDS** [comment]
Going to close this as we don't have access to the data to find out what's wrong :( If anyone has an example JSON that breaks in this way please let us know and we'll investigate further.
