### ISSUE TITLE
Generated post URL from title should replace @ with dash

### ISSUE THREAD

**Issue by mwbrooks** [TryGhost/Ghost#4782]
Post URLs are generated from the post title, which is awesome!

Special characters in post URLs such as `.` are replaced with a dash. This is also nice because the period often separates words and the dash keeps the URL readable.

__Problem:__

I've noticed that the `@` is removed instead of replaced with a dash. If this was intentional, then you can go ahead and close this issue:)

However, for myself, this often results in URLs that jumble words. For example:

-  `phonegap-cli@4.1.2` --> `/phonegap-cli4-1-2`
- `PhoneGap Meetup@Vancouver` --> `/phonegap-meetupvancouver`

It would be nice to replace the `@` with a `-` so the URLs are generated as:

-  `phonegap-cli@4.1.2` --> `/phonegap-cli-4-1-2`
- `PhoneGap Meetup@Vancouver` --> `/phonegap-meetup-vancouver`

Cheers,
Michael

**Comment by ErisDS** [comment]
Hi @mwbrooks thanks for this. It seems like a sensible change to make (thanks for the detailed examples). I assume @claydiffrient is also voting in favour. If there are no objects I'm all for merging the PR.

**Comment by jaswilli** [comment]
I think it's worth taking a look and making a decision about any other reserved characters that would be better converted to `-` instead of removed.

**Comment by claydiffrient** [comment]
I agree that taking a look at other potential replacements would be a good idea.

**Comment by ErisDS** [comment]
@claydiffrient it would also be fabulous to add some test coverage to capture these changes.

The characters are: 
- punctuation: `'`, `"`  `:`  `,` `;` `?` and `!` `'`, `"`
- and-like things: `&` `+` and `|`
- at `@`
- slashes: `/` and `\`
- brackets `[` `]` `(` `)` `<` and `>`
- other symbols `$` `£` `#` `%`  `*`  `=`  `^`  and `~`  

The issue is, as I see it, where symbols are used to separate words without spaces. Usually, there would be spaces as well as the symbol, and the spaces would end up being collapsed down into a single dash. 

So the question becomes what symbols, like the `@` sign, are likely to be used without spaces as word separators, as opposed to being used as prefixes and suffixes that don't require the concept of a space.

I think the answer to this is anything and-like for sure and probably a lot of the punctuation (colons and commas).

However, from another perspective, we do already collapse down multiple dashes, so if there is more than one dash that's ok. The main thing that I don't think we do currently, is trim away a leading or trailing dash.

If we de-duplicate and trim away leading/trailing dashes, then we can probably replace most characters with a dash, rather than removing it and the question becomes which characters can't we do that for - to which the answer is  'any character which could appear in the middle of a word' - i.e basically just `'`

Or did I just massively over-simplify this?

Tests and real-world use cases would be helpful I think :)

**Comment by claydiffrient** [comment]
@ErisDS I'll give this another shot.  I think you've done a good job at outlining what needs to happen.  I'll take another look at the code and modify the replacements.  I'll make sure to add tests to cover it as well.  I mostly jumped into this looking for a way to volunteer some time for a project and saw this issue thinking I could help out with it.  So, as far as real world cases I'm not sure about.  It'd be great for @mwbrooks  to weigh in a bit more with more potential real world cases.

**Comment by claydiffrient** [comment]
@ErisDS I just pushed a commit up to #4783 that adds specs based on our discussion here.  I'll plan on getting them passing tomorrow or the next day.  I just wanted to make sure I had decent coverage in place for what we were wanting to accomplish.  Let me know if you see anything wrong with them and I'll adjust as needed.

**Comment by mwbrooks** [comment]
> The issue is, as I see it, where symbols are used to separate words without spaces. Usually, there would be spaces as well as the symbol, and the spaces would end up being collapsed down into a single dash.
>
> So the question becomes what symbols, like the @ sign, are likely to be used without spaces as word separators, as opposed to being used as prefixes and suffixes that don't require the concept of a space.
> ...
> If we de-duplicate and trim away leading/trailing dashes, then we can probably replace most characters with a dash, rather than removing it and the question becomes which characters can't we do that for - to which the answer is 'any character which could appear in the middle of a word' - i.e basically just '

This is a fantastic summary @ErisDS! Thanks.

@claydiffrient My real-world cases are quite limited to the following:
- phonegap-cli@4.1.2 `/phonegap-cli-4-1-2/`
- PhoneGap Vancouver Meetup @ 7:30pm `/phonegap-vancouver-meetup-7-30pm/`

This boils down to `- @ . :` as the special characters that I use. The `:` could become a `-` or simply removed. However, I prefer @ErisDS's simple and predictable approach over building special characters for certain characters because you can't satisfy everyone :)

@claydiffrient While I'm unfamiliar with the Ghost code-base, commit f354a1b looks clean, well written, and complete to @ErisDS's outline. Nice work!
