### ISSUE TITLE
In sitemap-posts.xml should posts that are features have a higher priority?

### ISSUE THREAD

**Issue by nodesocket** [TryGhost/Ghost#4792]
In `sitemap-posts.xml` should posts that are checked as **featured** have a higher priority than the rest of the posts? Currently it looks like all posts are `80%`, perhaps featured posts should be `90%`?

**Comment by jgable** [comment]
It's like I could [read your mind](https://github.com/TryGhost/Ghost/blob/master/core/server/data/sitemap/post-generator.js#L40).

:balloon:

**Comment by ErisDS** [comment]
I'm trying to determine if this is a correct usage of the [priority field](http://www.sitemaps.org/protocol.html#prioritydef)? 

The priority field is always relative to the site itself, rather than to any other site. So, if featured content is given a higher priority, then search engines consider those posts to be more important (in terms of search engine display) than other posts. I'm also not sure what the common use of featuring is - whether it's permanent (and therefore more relevant to search engines) or temporary. 

Personally, I think it is correct that if I mark a post as featured, then I would also like search engines to display this post over an non-featured one. I have also found reference to other people using featured posts and priority in this way: http://www.growingwiththeweb.com/2014/05/xml-sitemaps-in-jekyll.html

The question of whether this is a permanent increase in priority, and if that's how sitemaps work is also quite interesting, because if the priorities are able to fluctuate then perhaps the most recent post should also be given higher priority? 

I'm just thinking out loud, interested in what other people think as well.

**Comment by halfdan** [comment]
> Please note that the priority you assign to a page is not likely to influence the position of your URLs in a search engine's result pages. 

That sentence (from http://www.sitemaps.org/protocol.html) and several other sources on the web indicate that the priority is used only as an indicator on how important you deem the page to be.

> Search engines may use this information when selecting between URLs on the same site, so you can use this tag to increase the likelihood that your most important pages are present in a search index.

Given that, I agree with @ErisDS that featured posts should get a higher priority than unfeatured posts.

However, giving a more recent post a higher priority is unnecessary I believe, as search engines seem to prefer newer content over older already. The priority indicates a relative importance of a single page compared to the rest of pages and a more recent post isn't necesarily more important than one that was written two years ago.

**Comment by ErisDS** [comment]
Just to quickly summarise my thoughts on this:

The sitemap priority info will only ever (potentially) impact on which pages from a site appear in the search engine result for that site. Although a featured post is intended to be temporary, it still makes sense to offer up a slightly higher priority via the sitemap as a way for the search engines to factor in that this post is considered more important than others by the author. 

Presumably, the search engine will then use this information in conjunction with other details such as the freshness of the content and its own data (clicks?) to determine which links to display.
