### ISSUE TITLE
Spellchecker is not working

### ISSUE THREAD

**Issue by lepinay** [TryGhost/Ghost#4802]
The spellchecker is not working when I edit a blog post (tested in firefox and chrome).

I'd expect some red squiggly line showing up here:

![region](https://cloud.githubusercontent.com/assets/2689930/5740272/1985d156-9c02-11e4-80a7-9c3421c55df0.png)

**Comment by halfdan** [comment]
Hello @lepinay and welcome to Ghost!

Spellcheck is currently not possible due to the use of CodeMirror as editor. There is an ongoing effort however to move off of CodeMirror and enable spellcheck (https://trello.com/c/UWWRTdrF/30-spellcheck). If all goes well the next release may ship with browser supported spellcheck: https://github.com/TryGhost/Ghost/issues/4368.

**Comment by ErisDS** [comment]
Closing as a duplicate
