### ISSUE TITLE
[Feature] Support for Post Series

### ISSUE THREAD

**Issue by esatterwhite** [TryGhost/Ghost#4818]
I would like to be able to publish a series and link individual post as parts in to a series. For example,  may start a series Called Fuzzy Kittens, and once a month add a new part to the series that features a new fuzzy kitten.

Users would be able to see other parts in the same series and quickly navigate to other parts. 

It should also allow a series to be featured, rather than individual posts.

While this is technically possible with carefully named tags and titles,that makes management difficult and makes for a bad end user experience as they are left to trudge through older posts to find additional parts the series.

**Comment by corani** [comment]
+1

**Comment by ErisDS** [comment]
Hey @esatterwhite, since you wrote this feature request we created a [wishlist](http://ideas.ghost.org/forums/285309-wishlist) so that we could do a better job of collecting ideas like this and understanding what our users really find important. The wishlist is a much better way to gather support and validation for an idea, as it reaches far more of our community than issues on GitHub do. I really recommend re-raising this there :+1:

**Comment by esatterwhite** [comment]
[Done](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7323605-support-for-post-series)
