### ISSUE TITLE
IE9 login screen blank page, JavaScript error: replaceState

### ISSUE THREAD

**Issue by RicSwirrl** [TryGhost/Ghost#4836]
Trying to log in to the admin interface in IE9 (/ghost) gives a blank screen. 

There's an error in the JavaScript console:

SCRIPT438: Object doesn't support property or method 'replaceState' 
vendor.min.js?v=8fb2accd1a, line 9 character 12869

I'm guessing this is because IE9 doesn't support replaceState. Is IE9 support for ghost admin intended?

**Comment by RicSwirrl** [comment]
Which JavaScript dependency requires this? Ember(?) Any pointers for a workaround?

**Comment by ErisDS** [comment]
Hi @RicSwirrl, As far as I know it isn't required directly by Ember, but is required because Ghost uses Ember's [history API feature](http://emberjs.com/guides/routing/specifying-the-location-api/) to have urls rather than hashes in the admin panel. Ghost is not expected to support IE9, I'm afraid I don't think this can be worked around and I'd wager that even if it could, you'd likely face much bigger problems once this one was solved.

**Comment by RicSwirrl** [comment]
Hi @ErisDS Thanks for the reply! I'm a happy Ghost user, :) but I'm sad about the IE9 thing. I'd love to recommend Ghost to a client, but this might be a sticking point for them. :-|

**Comment by ErisDS** [comment]
To me, trying to run Ghost in IE9 is a little bit like trying to play a Blu-ray in a standard DVD player - if you want to use the latest & greatest in tech, you have to invest a little in the gadgetry to get it to work :)

Of course, with the web there is usually a way to build fallbacks, but those are costly to implement and mean that some users get a reduced experience. If the demand was high, it might be worth it, but currently the demand is just not there.

**Comment by JohnONolan** [comment]
Not even Google (Market cap: $345,000,000,000) has supported IE9 for over a year. http://googlesystem.blogspot.com/2013/11/google-drops-support-for-ie9.html

There's no way we're going to.

**Comment by nickfoerster** [comment]
I know this topic is old (found it through Google looking for a workaround). I am forced to use IE9 at my office due to it being government. I like to write during breaks/lunch and would like to access the Ghost admin panel. Would it be better just to use something like MarkdownPad and publish the posts later or should we expect something soon?

**Comment by letsjustfixit** [comment]
@nickfoerster as john explained above Ghost wont wupport IE9 anymore (as it is outdated).
The best i can recommend you is to use portable firefox :) if that is a possibility.
