### ISSUE TITLE
Errors in `startup-check.js` should exit non-zero (currently 0)

### ISSUE THREAD

**Issue by chilts** [TryGhost/Ghost#4849]
When something goes badly wrong on startup, such as dependencies not being there, we should complain loudly (which we do) but we should also exit with non-zero so that whatever started Ghost knows that there was a problem.

This applies to all of `packages()`, `contentPath()` and `sqlite()` in this file: https://github.com/TryGhost/Ghost/blob/master/core/server/utils/startup-check.js

I'm happy to submit a PR if this sounds ok?

**Comment by jaswilli** [comment]
Hi @chilts,

The reason those checks use `process.exit(0)` is to avoid the generation of long, confusing error output and stack traces from things like npm.

Because `startup-check` is checking for a class of error/misconfiguration that is likely to be encountered only by way of a mistake in setting up the environment by users who may not be very experienced, it's really helpful to not have to wade through a hundred lines of "stuff" to try and figure out what went wrong.

If you have an example of a real-world situation where Ghost exiting with a status of `0` is problematic we can discuss it and see if we can come up with a solution, but absent that I'd prefer to be pragmatic and make this class of error as easy as possible for our users to troubleshoot.

**Comment by chilts** [comment]
That sounds like a reasonable solution (to the excess of noise from npm).
