### ISSUE TITLE
Bug: Meta description doesn't work inside of `{{#foreach posts}}`

### ISSUE THREAD

**Issue by msiemens** [TryGhost/Ghost#4850]
### Issue Summary

Right now `{{meta_description}}` returns an empty string when used inside of `{{#foreach posts}}`. On the other hand doing `{{log meta_description}}` prints the correct string to the console.

### Steps to Reproduce

This happens wherever there's a `{{#foreach posts}}`. For simplicity's sake, here are steps to reproduce this with the default theme (Casper):

1. Replace `{{excerpt ...}}` with `{{meta_description}}` in `partials/loop.hbs`
2. Visit a page with a post list (for example the frontpage) and notice the empty text instead of the post description.

I think I got a patch ready but first wanted to ask whether that's intentional or a actually bug.

### Technical details

* Ghost Version: 0.5.8

**Comment by novaugust** [comment]
Sounds like a bug to me. Thanks for the great report :) Feel free to throw the PR up!

**Comment by msiemens** [comment]
Thanks :) The PR is #4851

**Comment by ErisDS** [comment]
This bug is also true for `meta_title`.

I think both the `meta_title` and `meta_description` helpers need a little love, and I think they need to be rewritten to depend on the current context, rather than the value of relativeUrl, so that they are more robust.

The [is helper](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/is.js#L11) shows the proper way to get hold of the current context, and the [documentation for the is helper](http://themes.ghost.org/v0.5.10/docs/is#contexts) shows what the various contexts are. 

I think the rules for what the `meta_title` and `meta_description` should be ought to be the same, with the exception of the addition to fix this issue, which is that if `this.meta_[description/title]` is set (i.e. the helper is being called inside of an object which has the property), then that should be returned instead. This should probably be the first rule in each case.
