### ISSUE TITLE
NoPermissionError in app development

### ISSUE THREAD

**Issue by erguotou520** [TryGhost/Ghost#4896]
I know that app is still in developing, but I am really puzzled at how to development an GHOST app.

1.I have read this WIKI [App Ideas Permissions](https://github.com/TryGhost/Ghost/wiki/App-Ideas-Permissions) , it just describe some suggestion, but should I do all of those in my development?

2.Following the WIKI [Apps Getting Started for Ghost Devs](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs),  I get start with developing my own app which can reset GHOST's cover to other pictures. Here is the core code.
```javascript
_app.api.settings.edit({settings: [{key: 'cover', value: pic}]}, {context: {internal: true}});
```
I debuged my app, and I found that no datas was wrote into the `apps` database, so my app throws a "NoPermissionError". How can I fix it?
![no_app](https://cloud.githubusercontent.com/assets/7945757/6077339/f75bb094-ae28-11e4-9ad3-2659361d906f.png)

**Comment by ErisDS** [comment]
Hi @erguotou520, as you have identified, Ghost apps are still a work in progress. There's not much you can do with them at the moment, and I understand it's frustrating but beyond the docs apps are very much a 'figure it out if you can' kind of thing right now. You can always swing by the IRC channel and see if you can find someone to walk through what you have and haven't done, but otherwise we don't really  expect any of this to properly work just yet.
