### ISSUE TITLE
[0.5.8] "(Server was not available)" dialog after any operation with database, 301 on /ghost/api/v0.1/...

### ISSUE THREAD

**Issue by 07Gond** [TryGhost/Ghost#4947]
**With DOMAIN -> http://silvianunezdelarco.com/**

When execute for example, "Save" in Settings:

- *In Forever Logs:*
181.64.253.198 - - [24/Feb/2015:23:41:33 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"
181.64.253.198 - - [24/Feb/2015:23:41:34 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"
181.64.253.198 - - [24/Feb/2015:23:41:34 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"
181.64.253.198 - - [24/Feb/2015:23:41:35 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"
181.64.253.198 - - [24/Feb/2015:23:41:35 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"
181.64.253.198 - - [24/Feb/2015:23:41:35 +0000] "GET /501.shtml HTTP/1.1" 301 - "http://silvianunezdelarco.com/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"

- *In Chrome Console:*
Remote Address:107.6.148.2:80
Request URL:http://silvianunezdelarco.com/ghost/api/v0.1/settings/
Request Method:PUT
Status Code:301 Moved Permanently

**BUT with IP:PORT for the same web**

When execute "Save" in Settings :

- *In Forever logs:*
181.64.253.198 - - [24/Feb/2015:23:43:42 +0000] "PUT /ghost/api/v0.1/settings/ HTTP/1.1" 200 - "http://107.6.148.2:8888/ghost/settings/general/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2314.0 Safari/537.36"

- *In Chrome console:*
Remote Address:107.6.148.2:8888
Request URL:http://107.6.148.2:8888/ghost/api/v0.1/settings/
Request Method:PUT
Status Code:200 OK

**Comment by ErisDS** [comment]
Hi @07Gond, I'm sorry to hear you're having trouble with Ghost.

I don't fully understand what it is you're reporting here - it looks like you have some sort of configuration issue with your domain? In the logs the 301 lists `GET /501.shtml` - which is not something from Ghost. Installation, configuration and other support questions are better suited to our [forum](https://ghost.org/forum), rather than GitHub which is for bugs.

If I'm wrong and you have found a bug, we have a handy bug report template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) that may help you to find the right information to include to help us understand the issue.
