### ISSUE TITLE
Tags on static pages

### ISSUE THREAD

**Issue by vmatekole** [TryGhost/Ghost#4953]
{{has}} assert fails on a known tag for a static page. It appears that tags are not available on static pages on 0.5.8v.

**Comment by halfdan** [comment]
Hi @vmatekole 
Can you please give details on how to reproduce the issue you are describing?

**Comment by vmatekole** [comment]
{{#has tag="about"}} class="about" {{/has}} on a static page that has a tag "about" results in false assert.  When {{tags}} are output no tags are rendered.

**Comment by halfdan** [comment]
This seems to work properly for me. Can you make sure that you are in the correct template file? (`page.hbs` if present)

**Comment by vmatekole** [comment]
I forgot to add this is a custom page page-about.hbs.

**Comment by vmatekole** [comment]
@halfdan  did you manage to reproduce?

**Comment by ErisDS** [comment]
Hi @vmatekole, sorry to hear you're having trouble with your theme.

This issue is not a reproducible bug in Ghost.

I suspect that this is an issue with how you've implemented your custom page template. My guess would be that you are using the `{{#has}}` and `{{tags}}` helper outside of the post scope.

The [handlebars](http://themes.ghost.org/docs/handlebars) and [post](http://themes.ghost.org/docs/post) helper sections of the documentation should help to explain what I mean.

If you have any further questions about how themes work, our friendly [forum](https://ghost.org/forum/themes/) community will be able to help.

**Comment by vmatekole** [comment]
Confirmed. Thanks for getting back!
