### ISSUE TITLE
After 5.9 master merge my 5.8 npm start log

### ISSUE THREAD

**Issue by qLb** [TryGhost/Ghost#4992]
I installed 5.8, worked perfectly, i tried to install clean 5.9 after stable merge

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ghost@0.5.8
6 info start ghost@0.5.8
7 verbose unsafe-perm in lifecycle true
8 info ghost@0.5.8 Failed to exec start script
9 error ghost@0.5.8 start: `node index`
9 error Exit status 255
10 error Failed at the ghost@0.5.8 start script.
10 error This is most likely a problem with the ghost package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node index
10 error You can get their info via:
10 error     npm owner ls ghost
10 error There is likely additional logging output above.
11 error System Linux 3.18.6-1-ARCH
12 error command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
13 error cwd /home/qlb/code/kamienica.pub
14 error node -v v0.10.33
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```

**Comment by ErisDS** [comment]
Hi @qLB, sorry to hear you're having troubles.

As far as I can see from the logs, you're still trying to start Ghost 0.5.8 so it doesn't look like you've pulled 0.5.9 correctly via whatever means you used. The stable branch should be working fine.

As this is an environment/install issue, rather than a bug in the software, I recommend posting on our [forum](https://ghost.org/forum/installation/new/) - the new topic page on the installation forum provides lots of hints at what sort of information to include so that the community can help you debug your problem.

**Comment by qLb** [comment]
I'm still investigating, somehow the grunt process is not shutting down
properly after ctrl+x out of it and the above error illustrates the log for
ip:port conflict.

**Comment by halfdan** [comment]
CTRL+X does not exit the process - it moves it in the background. What you want is CTRL+C

**Comment by qLb** [comment]
<= noob... :P thanks
