### ISSUE TITLE
[Feature] Custom navigation - additional field

### ISSUE THREAD

**Issue by juliancwirko** [TryGhost/Ghost#4997]
Hi, I wonder if we can have one more field (type String) in the settings/navigation fields so we should be able to add some custom data for example for FontAwesome icons like:

```
{{#foreach navigation}}
    <a href="{{url}}"><i class="fa fa-fw {{customdata}}"></i><span>{{label}}</span></a>
{{/foreach}}
```
or
```
{{#foreach navigation}}
    <a href="{{url}}"><span class="{{#has customdata='featured'}}label label-success{{/has}}">{{label}}</span></a>
{{/foreach}}
```

I know that I can use ````slug```` and prepare my own css styles for icons but this is just an example. I bet that it could be helpful. Isn't it?

Or maybe it should be possible as a Ghost plugin extension?
I think that for themes devs it could be helpful.

**Comment by ErisDS** [comment]
Hi @juliancwirko, thanks for taking the time to write this up.

I think that this doesn't really suit Ghost core because it only really makes sense to theme developers, rather than users. If the navigation UI had a 'custom data'  or even a 'class name' field, a lot of people would be very confused by that. It also would only ever work in the case that the theme made proper use of the extra field, and in the case that it was a generic 'custom data' field, it could do different things depending on the theme - all very confusing. 

I understand the problem though, and that having icons for menus is quite common. Perhaps the problem can be solved in a different way using the code injection tools? Alternatively, if the real underling problem is just needing to be able to set custom classnames, perhaps we could create a way to do that without adding an extra field.

However, I think the use case for this is super small at the moment, which makes it hard to justify spending any time on outside of making apps possible so that this could be done as an extension. The best way to find that out for sure though, is to add it to our brand new [wishlist](http://ideas.ghost.org) to see if it gets support. If it does then we can happily revisit this.

**Comment by juliancwirko** [comment]
Hi, it all makes sense, thanks :)
