### ISSUE TITLE
Getting 403 error on deleting a blog post.

### ISSUE THREAD

**Issue by kushdilip** [TryGhost/Ghost#5003]
I am running latest 0.5.9 version of ghost on digitalocean in a subdirectory, so the url is like mywebsite.com/blog.  Everything is working fine except deleting a blog post.

deleting gives me below error
`Your post could not be deleted. Please try again.`

In chrome console, I am getting 403 http error
`DELETE http://www.MYWEBSITE.com/blog/ghost/api/v0.1/posts/1/ 403 (Access Denied) vendor-dev.js?v=dde9f7fb8d:9761`

I also tried previous tagged versions and stable branch as well.

**Comment by ErisDS** [comment]
Hi @kushdilip - did you manage to get this resolved? At an initial guess, it sounds like you might have been logged out of your session whilst in the admin panel and that logging in again would resolve it.

Other than this it could be that Ghost didn't install properly, that you had a different session issue or issue with a particular role, or that your site is somehow misconfigured. 

It's really hard to track down an issue like this without very detailed information and this isn't reproducible as reported - I'm able to delete blog posts on a blog running under a subdirectory without an issue. Therefore this seems like it's probably environmental and blog specific, rather than a bug in Ghost. The [forum](https://ghost.org/forum) and IRC are more suited to getting support for this sort of thing than GitHub.

If this does turn out to be a reproducible issue, we have a handy template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports) that should help you provide more detailed info so that we can reproduce and fix the bug.

**Comment by kushdilip** [comment]
@ErisDS This issue is still not resolved for me. No, I'm not getting logged out of session. I tried different approaches like multiple manual installs, moving from sub directory to root level domain. At last I destroyed the digital ocean droplet and now running the DO's one click ghost install version. And guess what, the exact same issue exists. May be something to do with my Nginx configs, but I didn't touch in case of one click install. Really not able to figure out what's happening.

**Comment by ErisDS** [comment]
Hey @kushdilip really sorry to hear you're still having problems. I recommend posting the full details of all the steps you've taken in the [installation forum](https://ghost.org/forum/installation/) - when you click the [post a new topic](https://ghost.org/forum/installation/new/) button it shows you a list of useful things to include, and I recommend listing all the things you changed from the standard DO install which lead to the problem.
