### ISSUE TITLE
Add multiple title images per post 

### ISSUE THREAD

**Issue by hatched** [TryGhost/Ghost#5005]
Certain designs call for having multiple style or multiple dimension title images per post depending on the form factor(mobile, desktop, etc) or location(hero, featured, etc) the post is being displayed. It would be nice if this functionality could be added along side some generated or defined naming scheme so that a template could determine what image to show when.

It would be impossible to try and define all of the possible placements and size requirements head of time as these are highly theme dependant. So I propose that the edit post pane allows the user to upload any number of images and then allow the user to tag those images with a user defined tag which the image handlebars helper could use to show the appropriate image. 

Using the tag method will also work with multiple sizes generated via the yet-to-be-implemented image resizer mentioned in #4453. The `{{image}}` helper already has the convention for passing additional information into the helper so it would look something like `{{image tag="featured"}}` or `{{image tag="100x240"}}`

**Comment by novaugust** [comment]
Hey @hatched, thanks for taking the time to write up the feature request.

I can't speak for the Ghost team, but for me personally, this seems to fail one key requirement to [making it into Ghost Core](https://github.com/TryGhost/Ghost/wiki/What-makes-it-into-Ghost-core%3F): "Would it likely be useful to the majority of our user base."

To me, this feature adds some complicated UX that most users won't even want to deal with. I definitely see the use case you're talking about, but that sounds more like an advanced usage that would be powered by a third-party app built to meet that need.

**Comment by hatched** [comment]
Thanks for the reply @novaugust. I wouldn't be opposed to this functionality being added via an extension of sorts but this feature may be a short step depending on how they plan to implement the multiple image size functionality mentioned in #4453. 

If the example that they have `{{image size="small"}}` is to be used then it's not much of step to change *size* to *tag* (or the like) for broader functionality.

**Comment by ErisDS** [comment]
Hi @hatched, let me reiterate @novaugust's thanks for dropping by and taking the time to write this.

We had a realisation recently that GitHub (and our forum and trello boards) are all pretty rubbish for collecting feature requests. Either there's no way to add one (trello) or there's not really a good way to get proper validation of your ideas (here on GitHub or the forum) because you're talking to just a small section of the community & there's no way to vote. 

We wanted to do a better job of capturing ideas and understanding which ones were important to our users, so we setup a new [wishlist](http://ideas.ghost.org/forums/285309-wishlist) and added a link in the [Ghost admin UI](http://blog.ghost.org/wishlist/).

I think this is exactly the sort of idea that belongs there, so I encourage you to raise it there so we can see how big of a splash it makes and prioritise it accordingly. I'm going to close this issue here as it's not something we're actively working on, and if/when we do start we'll raise a set of spec issues.
