### ISSUE TITLE
Bug: Creating a code block after a list, no matter how many blank lines I type, it always show two blank lines.

### ISSUE THREAD

**Issue by xsxsxszs** [TryGhost/Ghost#5012]
![image](https://cloud.githubusercontent.com/assets/5842525/6554861/ef36309e-c69a-11e4-863b-690728cae214.png)

**Comment by ErisDS** [comment]
Hi @xsxsxszs, welcome to Ghost's GitHub.

Your issue doesn't state what you expect the behaviour to be in this case? For future reference we have a bug report template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports) that shows the information that is useful to include when raising a bug.

The behaviour displayed in your screenshot is common to showdown, the original Markdown.pl library, and many others - as shown by [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+This+is+a+list%0A%0A++++++++Line+1%0A%0A++++++++Line+2%0A%0A%0A%0A%0A%0A++++++++Line+3%0A).

There are various other interpretations by other libraries, but I don't think that this interpretation is necessarily wrong? Going to close this for now as it's not something we control (it's part of showdown), but if someone has information that can show one of the other interpretations as being more correct or more useful, then we can look at revisiting or trying to get it fixed in showdown.
