### ISSUE TITLE
The single backslash \ in icons font content turn into double backslash \\ after sass complile

### ISSUE THREAD

**Issue by lf2941270** [TryGhost/Ghost#5020]
![image](https://cloud.githubusercontent.com/assets/5663474/6569975/0f752b9c-c72e-11e4-8a81-1996ec46f43c.png)
I face this problem in my Win7 64bit system, ruby version is 2.2.1, sass version is 3.4.13
This problem can be fixed by edit this file /Ghost/core/client/assets/sass/modules/icons.scss, and i have create a pull request of that.

**Comment by lf2941270** [comment]
Sorry, I've made a mistake.

**Comment by ErisDS** [comment]
Hey @lf2941270, sorry I meant to comment and let you know I wasn't able to reproduce this. 

Ghost doesn't depend on the ruby/sass on your machine, it uses node-sass but I'd be interested to know what the issue was / what the solution was - then anyone else who has the same problem can find the answer :)

**Comment by lf2941270** [comment]
I don't know how, the repository I cloned 3 days ago  was out of date, the version of my repository  was 0.4.x, and the version of TryGhost/Ghost was 0.5.x. At that time, I didn't notice this. When I updated my repository , the problem in this issue has gone away.
