### ISSUE TITLE
Change to unpublished post title doesn't update post url

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost#5062]
When I change the title of an unpublished post, the post URL doesn't update. I understand that if a post has already been published, changing the URL might not be desired, but prior to publication I'm often making dramatic changes to the post title, which I'd like reflected in the URL. What makes this more pressing is that the post URL isn't displayed on the same screen, so it's very easy to miss.

**Comment by nuclearpengy** [comment]
I can identify with this. Currently I have the strangest slugs but I'm in the habit of checking now. We'd need an elegant way to achieve this.

We could probably trigger with auto-save or with manual save.

We'd need to consider the various things to check:
* did the user edit the post title
* did the user manually override the slug in the past - it might be irritating if you've already got a slug sorted out but you make a refinement to the post title and your slug gets changed.
* we'd need to check if post is published or not

It might however be best to submit this on the ideas site: http://ideas.ghost.org/forums/285309-wishlist

**Comment by dbalders** [comment]
I can definitely see how this feature would make that easier, as it is something I have thought about before, but I personally think that it should not be changed. My reason is that it could be a problem is if someone writes a title, saves a draft, checks the slug, likes it, and then decides to make one quick title change before publish, now what they checked is no longer valid. I think it is a lot easier to update the slug when I make an update to the title if I want the url to change, then be constantly checking it to make sure its correct, or didn't change so I don't publish an article with a bad url.

Url's are very important to many people, and I think beyond just creating one when the post is initially saved, Ghost shouldn't be touching that based on what it thinks the user wants.

**Comment by jonblack** [comment]
@dbalders 
You could do what @nuclearpengy suggested and check whether the user has already changed the slug. If they have, leave it alone.

**Comment by novaugust** [comment]
Checking if the user has changed the slug is nontrivial. We'd need to make another column to keep track of something like that, and I don't really see something like that happening. So it'll come down to a design decision from the people up top.
The reason I don't see this happening is because we have no way of knowing if the user has changed the slug. If someone set the title, then customized the slug, then changed the title again, they probably don't want the slug to change.

I'm going to close this for now; please feel free to create a feature request at our [user wishlist](http://ideas.ghost.org/forums/285309-wishlist) though; if we see this start to get traction we'll definitely revisit it! Thanks for taking the time to raise the issue, @jonblack

**Comment by jonblack** [comment]
@novaugust 
By another column I assume you mean in a database. Is that really needed? When the slug is generated, it's done so in a predicable manner (a post title will always produce the same slug), so if it doesn't match what's expected, the user has changed it. There are probably edge cases I'm not thinking of, but I thought it useful to add this comment in case someone comes looking.

**Comment by JohnONolan** [comment]
fwiw I agree with this issue and @jonblack's reasoning above sounds pretty sane to me. This problem is really an unintended consequence of introducing auto-save - I've bumped into it several times.

**Comment by nuclearpengy** [comment]
Not that this is how we should do it, but the workflow works pretty well, I'd reckon this would be regarded as a pretty standard 'core' feature.

![screen shot 2015-03-24 at 13 20 53](https://cloud.githubusercontent.com/assets/1669838/6800635/f1a6c188-d228-11e4-9eb8-bc6f3d6ec07c.png)

click edit

![screen shot 2015-03-24 at 13 21 02](https://cloud.githubusercontent.com/assets/1669838/6800642/fa6b05d6-d228-11e4-906a-2bd23e93f91c.png)

I have no idea what's technically happening behind the scenes, but it works pretty well.

```</chirping from the sidelines>```

**Comment by ErisDS** [comment]
Whilst not strictly a bug, because we built it this way on purpose, this behaviour does need changing now that we have autosave.

I think it should be possible to keep track of whether the current slug is generated from the current title, and then on a title change, if the slug is generated update it. If it is a custom slug, leave it alone. Definitely quite fiddly though, and we need to ensure we don't auto-update the slug after the post is published.

**Comment by dgonzalez** [comment]
Why don't we add another status... let me explain (although I am not sure of the full post lifecycle):
- **Draft:** the post is a draft, never been published.
- **Published:** the post is now public.
- **Unpublished:** the post has been pulled back from published into draft again.

This will enable us for having better traceability in the future (as the user will be able to quickly track the posts that the public has already viewed).

Then the solution to this "bug" (I think it is a feature change) will be as trivial as change the slug when the post is on the "Draft" status and don't change it (just do it manually) when the post is in any other status.

**Comment by ErisDS** [comment]
There's no need to add an extra status to determine if a posts has been published and then unpublished, as the post will have a status of draft but have a published_at date set, although that will change in future. 

However I think the word 'unpublished' is confusing in the original issue title/description, as it's actually (as I understand it) referring to any draft post, regardless of whether it has or hasn't been published.

**Comment by jonblack** [comment]
@ErisDS your assumption is correct, I was indeed referring to a draft post

**Comment by ErisDS** [comment]
I am of the opinion that a database field is overkill here. Whilst it's true that the only way to know 100% if the field has been edited by the user is to track edits and then set a boolean, even then it's still impossible for us to detect user intention:

E.g in the case that the user edits the field, but the result is no change, is the intention that they meant to not edit the field, or that they meant for the field to stay as it is regardless of future changes to the title?

By treating the slug as a sort of hashed form of the title, we can verify if any changes have been made to the slug. So when there is a change to the title we know both what the title was, and what it is now. Using what the title was we can verify that the slug is a valid slugified version of the old title. If that's true and the post is a draft the slug is safe to update, otherwise don't update the slug.

This should result in a significant improvement to the behaviour of the slug without having to introduce the complexities of storing a flag.

**Comment by dgonzalez** [comment]
Very elegant solution. I'll work on it today and I'll update the PR.

**Comment by dgonzalez** [comment]
The only problem I can see with it is when the user has published the post, for some reason, goes back to draft and then the title is changed. When the post is published again the slug will be from the new title but the user might expect to have the old slug as it was published before. Are we ok with this behaviour?

**Comment by jonblack** [comment]
I think the comment above by @ErisDS answers your question:

>If that's true and the post is a draft the slug is safe to update, otherwise don't update the slug.

**Comment by dgonzalez** [comment]
Slug is not updating when the post is draft anymore... is this a desired effect or is it another bug?

e.g. Create a new draft, save it, edit the title, save it and the slug didn't change.

**Comment by ErisDS** [comment]
@dgonzalez I'm a bit confused by your comment - what you're describing is the exact bug that is raised here?
