### ISSUE TITLE
Sign download files (Ghost ZIP archives)

### ISSUE THREAD

**Issue by crepererum** [TryGhost/Ghost#5074]
## Abstract
Currently ghost download archives (mostly http://ghost.org/zip/ghost-latest.zip) are not digitally signed by anyone. The download server supports TLS (that's not mentioned in the docs btw), but the server can get compromised. This might not even be the administrators fault because of unknown bugs in the used software and zero day exploits. The implication of an infected ZIP file is that **all ghost installations worldwide** that update to the affected release would be compromised as well. As this effects the server side and the client side code, this would have dramatic consequences. I doubt that users check the sources for backdoors when downloading the software because the size and complexity of the code base (that holds for every not-tiny project) renders the attempt unpractical. Because this attack scenario is so effective, it is nearly 100% sure that this will happen someday.

## Solution
I propose to sign all ghost ZIP files using PGP (or [GnuPG](https://www.gnupg.org/) nowadays) and a state of the art key (e.g. RSA 2048 or 4096). The key should be private and only be used by one team member (e.g. @ErisDS). To increase security, the public part of the key should be verified using platforms like [keybase.io](https://keybase.io/). The possibility of checking the integrity of the ZIP file should be mentioned in the docs.

## Affected issues
 - #5071 (see comment about the content field and security implications)

**Comment by ErisDS** [comment]
Hi @crepererum, thanks for taking the time to write this up.

I understand the desire to be able to verify the authenticity of the zip file, however, I think the number of people that would make use of this would be incredibly minimal. I think this kind of verification in needs to be done without user involvement, or not at all. Therefore it doesn't really make sense for us to do anything like this until we have an automated update process in place. 

In the shorter term, there are other ways to achieve the same effect. You can use the [npm module for Ghost](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module) instead of the zip file, as npm has checksumming built in, or you could create a script to fetch the zip from both [Ghost.org](http://ghost.org/downloads) and [GitHub](https://developer.github.com/v3/repos/releases/#get-the-latest-release) and compare the two to check they are identical.
