### ISSUE TITLE
Partial/summary RSS feed with images support

### ISSUE THREAD

**Issue by HLFH** [TryGhost/Ghost#5079]
Hi,

We need partial RSS/summary feed with images support. 

In WordPress, in Settings > Reading, we could configure the RSS feed of our blog as:
-a full RSS feed
-a partial/summary RSS feed
![Partial RSS feed](http://pix.toile-libre.org/upload/original/1427548195.png)

Furthermore, with the [RSS Image Feed plugin](https://wordpress.org/plugins/rss-image-feed/), we have images support for the summary RSS feed.

In fact, there are two issues with full RSS feeds and MailChimp:
-automated RSS-driven campaigns with full RSS don't drive traffic and contribution to our blog
-RSS-driven campaigns with full RSS - or partial RSS without images - are awful.

Ghost core should support partial RSS feeds with images. 

Thanks in advance,
HLFH

**Comment by ErisDS** [comment]
Hey there @HLHF, which version of Ghost are you running? Ghost's RSS feed has output images since 0.5.9. 

As for making RSS more configurable such as creating summary feeds, these kinds of options will be available in the future with apps. If you would like to request a feature for core you can do so through our new [wishlist](http://ideas.ghost.org), where our users are able to vote on the features they want most.
