### ISSUE TITLE
Ghost as NPM Module, Route doesn't work

### ISSUE THREAD

**Issue by nodeGarden** [TryGhost/Ghost#5081]
Do we have to make any considerations for routes in the Parent App when loading as a subdirectory?
I followed the steps at: https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module#mount-ghost-on-a-subdirectory

**app.js:**
```javascript
var app = require("./server.js").init(util, _debug);  // Returns  { app: express() ... }

var ghost = require('ghost'),
    parentApp = app.app;

ghost().then(function (ghostServer) {
    parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);
    ghostServer.start(parentApp);

});
```

**config.js:**
```javascript
config = {
	
	paths : {
		subdir : path.join(__dirname, "/blog/")
	},
...
}
```

**in my ```routes.js``` file (sub-loaded inside ```server.js```):**
```javascript
	app.get("*", function(req, res, next) {
		// Handle all urls
	});

// now commented out because it didn't work:
/*
	app.get('/blog/*', function(req,res) {
		console.log(ghostServer());
		//ghostServer.start(parentApp);
		//ghostServer.rootApp();
	});
*/
```

Is there a reference I could pass to my ```/blog/``` route that will enable this? The app itself works when I hit port 2368, but not the blog. If I take out my ```routes.js``` include, then Ghost works, but not the app.

**Comment by CWSpear** [comment]
You want Ghost to "always be running." Basically, by setting it up to run via express, you can think it of creating a "fallback," and so if it doesn't match another route, then it will fallback to Ghost:

```js
var express = require('express');
var ghost = require('ghost');

var parentApp = express();

parentApp.get('/test', function (req, res) {
  res.send('Test Page');
});

ghost().then(function (ghostServer) {
    parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);
    ghostServer.start(parentApp);
});
```

Going to `/test` will display "Test Page," and going to any other URL will show your Ghost blog.

**Note** that I don't run my npm-installed Ghost in a subdir, and in my testing just now, no matter what I did, `ghostServer.config.paths.subdir` was always `''` in `0.5.10`. This may be a bug. But if I replace `ghostServer.config.paths.subdir` with `/blog/`, then I see the blog at `/blog/*`, and error at `/` (since I don't have an `express` route registered there) and "Test Page" at `/test`.

I believe this is what you're going for?

**Comment by nodeGarden** [comment]
Thanks CWSpear. I could replicate what you did once I strip out my own 404 handler route. But I'm looking to do the opposite, everything EXCEPT /blog/ being handled by parent app.

I went the Nginx proxy route instead, and works great: https://www.allaboutghost.com/how-to-install-ghost-in-a-subdirectory/  .  This might be a better route if I want to have multiple instances of the servers for each app (parent / ghost) independently. 

... will let one of the admins close this thread if they decide to not support the reverse model.

**Comment by CWSpear** [comment]
I did find that to get `ghostServer.config.paths.subdir` to be nonempty, you have to actually set your url in `config.js`, i.e. `url: 'http://example.com/blog/'` and then the `subdir` will be **/blog/**.

Anyway, if you do that, then *that* appears to do what you want. Anything that doesn't with **/blog/** routes was giving me route not found errors from my express app and not from Ghost. I'm not at my computer to test this, but I assume you could then set up a 404 handler on the `parentApp` and get what I know believe you are going for.

Or setting up a 2nd proxy works, too. My thought is it is easier to set up a single app to manage, but this is just my personal blog and not a large app, so ease of maintainability weighs a little more than power/flexibility.

**Comment by ErisDS** [comment]
> I'm looking to do the opposite, everything EXCEPT /blog/ being handled by parent app.

I'm pretty sure this is what you end up with if with the code @CWSpear suggested. Effectively Ghost can be mounted at a route within another application, so that it only handles that route. Ghost does not (yet) suit being used as middleware - you'll find [issues](https://github.com/TryGhost/Ghost/issues/827) & related PRs open about this, but it shouldn't prevent you doing what you need to do.
