### ISSUE TITLE
Scrolling preview pane doesn't scroll markdown pane

### ISSUE THREAD

**Issue by Atlantic777** [TryGhost/Ghost#5102]
When I scroll the markdown pane, right (preview) pane syncs with it and scrolls to the right position. When I scroll that preview pane, it doesn't scroll markdown pane.

I am not sure if this is unimplemented feature or a bug, but I would like to see such behaviour in Ghost's editor. :)

  |  |
-----------------|--------------
Version:         |       0.5.10
Environment: | production
Database:      | sqlite3
Mail:              | Native

**Comment by ErisDS** [comment]
Hi @Atlantic777, and welcome :)

This behaviour is entirely intentional and I'm afraid not something that should be changed. Ghost's scroll syncing isn't very smart (it's based on percentages) and sometimes gets out of sync. 

Therefore, if both panes caused the other to scroll as you are suggesting, then it would become very, very common to get into a state where you can't see what you're typing and the preview of it at the same time. It would be an incredibly frustrating user experience. 

Therefore, deliberately, only the left pane triggers the syncing, and the right pane is free to be scrolled by the user without affecting the left pane.
