### ISSUE TITLE
Post Archive

### ISSUE THREAD

**Issue by edwardessing** [TryGhost/Ghost#5134]
Howdy, I'm really enjoying the ghost platform. However there is a major feature that I feel is absent: a post archive. This archive would utilise the 'date published' of a post. As a result you would easily be able to filter down posts to a particular year, month etc. (from my experience, the majority of blogging platforms will simply conjoin the month and the year for filtering i.e. July 2015, August 2015)...

Here are some examples of post-date archives / filtering:
- http://www.parkandcube.com/site-archives/
- http://shinebythree.com/archive/2015/

p.s. for what it's worth, it would be awesome if you could make an archive page that uses it's own, stylised (more thumbnail-y I imagine) post 'loop'.

Thanks again!

**Comment by ErisDS** [comment]
Hi there @edwardessing. In my opinion, specifically date-based archives are quite an old fashioned blog concept, and more importantly something that is too wide in scope to be built as a specific feature in Ghost core. There's just too many possibilities in terms of how you categorise or filter the posts, what URLs to use, etc. I don't think there's one obvious and clear way to do it that would [serve 90% of people's](https://github.com/TryGhost/Ghost/wiki/What-makes-it-into-Ghost-core%3F) needs.

Instead we're working on flexible tools to allow you to extend your blog in different ways like [channels](https://github.com/TryGhost/Ghost/issues/5091) and the [get helper](https://github.com/TryGhost/Ghost/issues/4439). These tools are intended to give the widest set of possibilities and make them super easy to work with, so that you can completely customise the way your blog's content is displayed.

Nonetheless, I may be wrong, but unfortunately GitHub is not a good place to get feedback and traction for an idea. Recently we launched a new [wishlist](http://ideas.ghost.org/) for feature requests. This wishlist is accessible from inside your Ghost admin panel and reaches a much wider audience, so why not add your suggestion there?

**Comment by edwardessing** [comment]
Hmmm I'm quite surprised that you would think date-based filtering is old-fashioned – I'm currently migrating a client from Blogger over to Ghost and she's indicated that it is a blogging standard in her circles (fashion blogging [which, incidentally is a massive portion of web blogging imo] ) . Anyway the channels sounds interesting, and thank you for the reply!
