### ISSUE TITLE
Upgrade from 0.5.10 to 0.6.0 failed.

### ISSUE THREAD

**Issue by Ter0** [TryGhost/Ghost#5137]
Manual upgrade on a Linux box (Ubuntu 14.04) failed with the error:
```
ERROR: Extension 'undefined' could not be loaded.  It was either not found or is not a valid extension. 
```
Followed the upgrade steps as per usual, deleting `core/` and unzipping new release. Also attempted to delete `node_modules` and re ran `npm install --production` but got the same error. A fresh install of 0.6.0 worked fine on the same box. Downgrading to 0.5.10 worked fine.

**Comment by cwonrails** [comment]
Exact same issue here except on DigitalOcean one-click-install. All past updates have worked. Spun up a new 0.5.10 one-click install droplet and updated, still failed, so not an nginx/config.js issue.

**Comment by hkalant** [comment]
Same here. Upgrade to 0.6.0 on DigitalOcean gives a 502 error.

**Comment by THPubs** [comment]
Same here! Tried on the local machine.

**Comment by ErisDS** [comment]
The error `ERROR: Extension 'undefined' could not be loaded.` means the wrong version of the showdown module is installed.

I believe this is due to a double-edged problem:
1) The `npm-shrinkwrap.json` file has gone missing from the release & is not in the zip
2) The update instructions haven't been updated to mention replacing the `npm-shrinkwrap.json` file

Please delete this file, and then rerun `npm install --production`. Everything should be OK after this.

**Comment by THPubs** [comment]
@ErisDS Thanks it worked!

**Comment by ErisDS** [comment]
The release zips on Ghost.org and GitHub have now been updated to include the missing `npm-shrinkwrap.json` file.

You can simply remove the file from your upgraded install, redownload the release zip, or grab the missing file from [here](https://gist.github.com/ErisDS/1246a55da11a9d2dc1f0).

The normal upgrade procedure is to replace`npm-shrinkwrap.json` along with `index.js`, `package.json` and the `/core` folder from 0.6.0 onwards.

**Comment by hkalant** [comment]
Alright. Everything is back to normal now. Thanks @ErisDS. Great work on supporting Ghost users.

**Comment by cwonrails** [comment]
What @hkalant said :) 

:+1: @ErisDS

**Comment by ErisDS** [comment]
I think it's safe to close this now :)
