### ISSUE TITLE
Using "Tab" keyboard button in Editor just navigates thru webpage objects. Can't intent.

### ISSUE THREAD

**Issue by ttnny** [TryGhost/Ghost#5139]
When working within the Editor, I couldn't get the "Tab" keyboard to intent. Hitting "Tab" is just navigating thru objects of the webpage.

Notes:
- Upgraded successfully to v0.6.0.
- Chrome version 41.0.2272.118 m (64-bit) (the same before upgrade).
- No adjustments to OS settings.

**Comment by ErisDS** [comment]
Hi @ttnny this was an intentional change made in 0.6.0. Having the editor steal tabs is pretty bad for accessibility and is non standard behaviour as tab & shift-tab are supposed to navigate forward and backward through the page. 

At the moment, we intend to keep it this way. If there is high demand, we could add a `ctrl/cmd + {}` shortcut for indent / unindent. If that's something you'd like to see, why not vote for it on the [wishlist](http://ideas.ghost.org/forums/285309-wishlist/suggestions/7564533-ctrl-cmd-shortcut-for-indent-unindent) ?
