### ISSUE TITLE
Bug: {{author}} & {{tags}} not showing up when using {{#prev_post}} or {{#next_post}} 

### ISSUE THREAD

**Issue by ireade** [TryGhost/Ghost#5150]
### Issue Summary

In my post.hbs, I wrote - 
    
    {{#prev_post}}
    <h2>{{title}}</h2>
    <h3>Posted on {{date format="D MMMM YYYY"}} by {{author}}</h3>
    {{excerpt words="80"}}
    {{/prev_post}}

Everything but the {{author}} was outputted.

### Technical details

* Ghost Version: master - latest commit:  9ea2f5535e456a13d41f4aec06445317fdef1f31

**Comment by ErisDS** [comment]
Hi @ireade thanks for the bug report. Good find, I'll betcha `{{tags}}` won't work either :disappointed: 

This is because when we fetch the next / prev post over the API, we do so with:

`/api/posts/:id?include=prev` or `/api/posts/:id?include=next`

Following this convention, if we want to include tags and authors in the response we'd need to tell the API to do that, something like:

`/api/posts/:id?include=prev,prev.tags,prev.author` or `/api/posts/:id?include=next,next.tags,next.author`

However, the API doesn't support this yet and I'm wondering if we ought to actually restructure this to be:

`/api/posts/:id/prev?include=tags,author` or `/api/posts/:id/next?include=tags,author` so that it's neater.
