### ISSUE TITLE
Cannot install from stable branch (0.6.2)

### ISSUE THREAD

**Issue by StevenLangbroek** [TryGhost/Ghost#5190]
I'm trying to run ghost from `stable` branch (0.6.2), but when I run `grunt init`, I get errors in the `shell:ember:dev` task:

```
Running "shell:ember:dev" (shell) task
Future versions of Ember CLI will not support v0.10.21. Please update to Node 0.12 or io.js.
version: 0.2.2

A new version of ember-cli is available (0.2.3). To install it, type ember update.
BuildingBuilding.Building..Building...Building
Error: EMFILE, open '/Applications/MAMP/rf-blog-stable/core/client/tmp/tree_merger-tmp_dest_dir-EIEztQLG.tmp/ghost/validators/tag-settings.js'
Warning: Command failed: 
Error: EMFILE, open '/Applications/MAMP/rf-blog-stable/core/client/tmp/tree_merger-tmp_dest_dir-EIEztQLG.tmp/ghost/validators/tag-settings.js'
 Use --force to continue.

Aborted due to warnings.
```

I found an earlier issue with regards to setting ulimit, but even setting it to 16384 (well above recommendation) didn't help. Any thoughts as to what's going on here?

**Comment by novaugust** [comment]
Hey @StevenLangbroek, Problems like this are more suited for either our [public slack's#help](https://ghost.org/slack/) channel or help [forums](https://ghost.org/forum/installation/) - we try to keep github limited in scope to just bugs and implementation details.
That said: depending on the method you used to change your ulimit, the change may not be active 'til your next session. Use `ulimit -n` to see what your session's running at. `EMFILE` is the unix error for maximum number of open file descriptors being hit, and is definitely fixed by setting your ulimit higher.
