### ISSUE TITLE
Footnotes from different posts have same ids

### ISSUE THREAD

**Issue by iacchus** [TryGhost/Ghost#5269]
Hello, using Ghost version 0.6.2

If I have two posts using footnotes on the home page for example,  their IDs are always the same, ie., both first footnotes ([^1]: ) of each post will have id #fn:1

So when I click ¹ of the second post on the page it will open the anchor of the first post's footnote and not it's own.

**Comment by letsjustfixit** [comment]
well footnotes work that way in most engines ive seen: they shouldnt appear on the homepage/index as in most cases there is only a short summary of some kind is on the homepage -> nor the footer nor the footnotes are supposed to be visible there..
what do you think the proper solution would be?

**Comment by kassius** [comment]
Maybe prefixing it with post uri or any unique post id like #fn-post-uri:1

**Comment by ryrych** [comment]
Can't confirm it. All footnotes are replaced with empty strings in the index page.

https://github.com/tryghost/ghost/blob/39dfb2c09a95f04a01300b4216cf2798b160ee2f/core/server/data/meta/excerpt.js#L6-L10

### Technical details:

* Ghost Version: master (latest commit: 39dfb2c09a95f04a01300b4216cf2798b160ee2f)
* Node Version: 0.10.40
* Browser: Chrome 48.0.2564.116 (64-bit) on Mac OS X 10.11.3
* Database: SQLite

**Comment by dbalders** [comment]
To accomplish putting a post id into the field, i believe we would have to pass the post ID into the ghost showdown fork (erisds/showdown) where it is re-formatting the text. Is this something we want to move forward with?

**Comment by halfdan** [comment]
@dbalders The post ID isn't necessarily guaranteed to exist at all times (e.g. when creating a new post before the first save)

**Comment by ErisDS** [comment]
This is only an issue, I believe, if you output full content on the list page instead of the excerpt. Therefore I think it's more a manifestation of users not being happy with the excerpt helper.

It's incredibly difficult to fix, and in my opinion too much of an edgecase to be worth the effort, especially given the changes coming in the new editor.

If anyone has a smart idea for a fix, I'm happy for a PR. Otherwise closing this as a won't fix.
