### ISSUE TITLE
support new versions of iojs

### ISSUE THREAD

**Issue by edsadr** [TryGhost/Ghost#5271]
iojs support was added for 1.2, would be nice to support newer versions

**Comment by ErisDS** [comment]
Just to reiterate what I said on slack for clarity: I feel that this is largely a waste of time. io.js is now going to be merging back into node, so our focus should be on being ready for any advancements that come when that happens but otherwise not keeping up with each individual version of io.js.

The major problem being that each of our dependencies has to have support for any io.js version, including complex dependencies like sqlite3 and node-sass. We have to be able to run a build as well as run the code on that version in order to declare the version 'supported'. Not only that but none of the npm infrastructure has been (or now will be I imagine) updated to support io.js - so our engines flag in package.json is a hack that will cause issues if io.js version numbers reach early node version numbers.

In order to update our supported io.js version, we need to know that both the development + production builds work, as well as the test suite. It is also necessary to verify that all of our dependencies will support io.js without issues. This isn't a quick or easy task to do regularly & it's also pretty tough to merge, because without re-doing all of those checks how do we verify that it's OK?

if io.js was continuing separately, we'd have to put in place a plan for officially keeping up-to-date or decide to drop support, but with the news that the merger is coming, I'd far rather we keep our ear to the ground with regard to the merger, and ensure we are aware of any potential problems there so that we can be ready when it is done.

Of course if you want to spend your time on this then you can, and we'll do our best to find a way to get a PR verified. I'm just not keen on spending a bunch of time on supporting something that isn't going to be around much longer when there are so many other things to do :wink:

**Comment by edsadr** [comment]
I see your point ... but yeah kind of want to use some of my time doing this... at the end is about updating dependencies... and dependencies should be updated from my point of view, to make it work with the current version of iojs wasn't that hard.. just 1 dependency needed to update, sending a PR now

**Comment by k-j-kleist** [comment]
@ErisDS: +1
