### ISSUE TITLE
admin page breaks when blog name includes braces 

### ISSUE THREAD

**Issue by ferrao** [TryGhost/Ghost#5294]
If i setup my blog name to include braces, like say {ferrao} , it shows up nicely, but the admin page is not accessible anymore.

**Comment by ErisDS** [comment]
To clarify this issue:

It only happens if the `{` is the first character, and the error in the console appear as:

![](http://puu.sh/hUB7r.png)

The minimum case is having the blog title set to exactly `{`, in which case the error message changes to:

![](http://puu.sh/hUBgk.png)

The issue doesn't occur at all if there are any characters before the `{`

**Comment by ferrao** [comment]
I can confirm that inserting a blank space as the first character is a good workaround for this.

**Comment by ErisDS** [comment]
Heh I know what's causing this - it's my dirrrrty hack here: https://github.com/TryGhost/Ghost/blob/master/core/client/app/utils/config-parser.js#L14
