### ISSUE TITLE
Unable to insert pictures into posts

### ISSUE THREAD

**Issue by vegasbrianc** [TryGhost/Ghost#5300]
After upgrading to 0.6.3 I'm unable to insert pictures into posts. When I add a picture to the post the picture actually gets uploaded to the server but I see the cat gif shaking it's head back and forth  but the picture never appears. When I hover over the gif it displays the error "No File Chosen"

If I link directly to the picture which was uploaded this works fine.

No errors are in the log files that I can find.

**Comment by ErisDS** [comment]
Hi there @vegasbrianc. This sounds a lot to me like a broken upgrade in which case repeating the process again carefully following the steps should help.

I'm going to close this as it seems like an environment problem, rather than an issue with the software (it's not reproducible). If you need more help, please visit the #help channel on [slack](https://ghost.org/slack).

If you think I'm wrong and this is a bug, please update the issue to include more details as explained in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) and we'll reopen it right away.
