### ISSUE TITLE
[Zelda] Password Strength Component

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5309]
This is required as part of the User Onboarding epic: #5315 

----

As part of the new fangled wonder that is Zelda, we're updating the create account and setup screens to be much more user-friendly.

One addition that would be awesome for both screens, is to include a (good) password strength indicator. That means something that calculates entropy rather than checking to see if you included a number and some punctuation or some other not-actually-secure rules.

![](http://puu.sh/hWMwV.png)

The design for the metre is already in master, merged in with Zelda (shown above). It lives to the right of the password input and has 5 little grey dots that are meant to light up green as your password strength improves. i.e. the password should be evaluated as you type.

[zxcvbn](https://github.com/dropbox/zxcvbn) seems like a great entropy calculator and has an API that will work for this case, however I'm not sure if it's a good candidate due to the odd way it is expected to be used. Happy to see a different lib used, but it must use entropy and not character-based rules.

The intention for this component is to display feedback to the user about whether their password is truly a good password or not, but the information will not be used as validation, so that users are not actually prevented from signing up if they have a 'bad' password.

The result of this issue is expected to be a new password field component which displays the indicator, and calculates & displays strength as you type. Please write ember unit tests for the component. Wiring it up into the right places would be nice too :)

**Comment by acburdine** [comment]
@ErisDS I did some digging and came up with a couple of other options other than zxcvbn. There's [this](http://rumkin.com/tools/password/passchk.php) entropy calculator, although I couldn't find a Github link for it. However, someone re-wrote it to run faster and that's on Github [here](https://github.com/sc0ttyd/passchk_fast).

Personally I would choose zxcvbn, as it's integrated into Dropbox's registration form; however, I do see what you mean with how it's used in an odd way. I do think it would work in this case, but it also adds ~700kb to the library, as opposed to the other one which is less than 100.

I'll do some comparison testing between zxcvbn library and the other one on Github, comparing the accuracy of the entropy/speed/ease of implementation.

**Comment by ErisDS** [comment]
@acburdine this sounds great!

**Comment by acburdine** [comment]
@ErisDS After doing some comparison testing, I believe zxcvbn is the better choice for a couple of reasons. The primary reason is that it is used in production at Dropbox, making it decently tested as to it's efficacy. Another reason is that it contains a list of a bunch of commonly used passwords (which is the reason it's ~700kb), and uses that list to improve its entropy check. Lastly, it contains an api for determining a score from 0-4, which lends itself very well to the password security meter.

That being said, the other library is much smaller in size, but it doesn't check for commonly used words that have been changed slightly [description](http://xkcd.com/936/). Also, the way it adds functions to the namespace doesn't quite work correctly, so if it is chosen, it will potentially take some forking/rewriting in order to make it work correctly.

I have started working on a component (almost finished) using zxcvbn. Because they are somewhat similar in usage, switching from one library to the other is very simple (if I can reconfigure the passchk_fast library). I should have a PR submitted in an hour or so.

**Comment by ErisDS** [comment]
In order to reduce the need to add ~700kb to the size of the package just for this feature, I have been wondering if we could add some code, or publish a bower package which just links to the main library [on a cdn](http://cdnjs.com/libraries/zxcvbn)? That's how zxcvbn intend it to be used. 

I think it should be possible to make the password indicator only appear if the library is loaded, meaning that you get a normal input if you're not connected to the internet, and get the advanced behaviour only if it's available?

**Comment by jaswilli** [comment]
I think this fails the 90% test.  As a normal user I have no pressing need for a sophisticated password complexity calculator, and certainly not at the expense of a 700KB download. I can see the value for someone running a hosting service but aside from that it's usefulness is pretty marginal.

Also, going the CDN route would trigger `PRIVACY.md` and it would need to be able to be turned off.

**Comment by ErisDS** [comment]
After hunting around for a smaller library that does a proper entropy test rather than a check for certain characters & length and failing, I think we need to pull this from core. 

Instead, it should be done as an app. We're not really anywhere near to being able to do that *just* yet, so I'm going to label this issue with `apps` and close it for the time being. I'll reopen it / respec it when it's doable.

**Comment by acburdine** [comment]
@ErisDS with TryGhost/Ghost-Admin#99 lazy-loading of scripts is possible. Would this be something that could be done with that?
