### ISSUE TITLE
Stop auto-focus when editing post

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5383]
When you write a new post, the post-title field is auto-focused so you can start writing right away. This is good.

When you edit a post, the the post-content field is auto-focused, and the textarea scrolls to the very bottom to place the cursor at the end. This is not desirable.

I believe the correct behaviour is not to auto-focus any field when editing an existing post.

**Comment by ErisDS** [comment]
I'm reopening this, because fixing it has created another issue - or rather, there was a reason for this behaviour and without it we need to implement a different workaround for the underlying problem. 

The issue is when transitioning from a 'new' post to saving a post and therefore being in 'edit' mode. The transition causes a reload of the template, and loses the active focus. This transition currently happens when you focus out of the title field. 

The manifestation of the problem can be seen when you finish typing a title and either use the tab key or mouse to enter into the editor, it gains focus, the transition happens, and the focus is lost - i.e. to reproduce what I'm describing:

1. Start a new post
2. Type your title
3. Hit 'tab' or click in the editor window.
4. You'll see your cursor in the editor window briefly, and then it will disappear completely.

This creates a jarring user experience and is very definitely not the right thing to do.

To resolve this, it was assumed that when you focus out of the title field, the next thing you want focused is the editor, therefore after the edit route loaded we were auto-focusing the editor window.

This transition is one of the trickiest things we have in our ember code - we've never quite managed to get it sorted out so that it works perfectly, there's always been a caveat.

The ideal solution here would be to find a different way to handle the change from a new post, to a saved post. I'm not sure what options Ember gives us, but we really can't be the only people running into this!

As a fall back, I think it would be possible to only auto-focus the editor if the edit screen has loaded as the result of a transition from new? Or to find and store the active focus, pass it to the new route, and recreate it?
