### ISSUE TITLE
Move post tags input into PSM

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5385]
Tags input got nuked in #5384 - this needs to be moved into the post settings menu (under publish date). This should be mostly moving ember things around, with some minor CSS edits to make it look right in the new location.

**Comment by acburdine** [comment]
Could this potentially go with #3800, or should they be two separate things?

**Comment by ErisDS** [comment]
There is an issue for doing this (with much discussion) here: https://github.com/TryGhost/Ghost/issues/3800. Might be an idea to move that issue into zelda instead of this one?

It does involve rebuilding the component, but we need to do that anyway because if we move the component into the PSM I think we should change the way it is saved so that we can (hopefully) resolve #4999.

**Comment by ErisDS** [comment]
I've moved #3800 into Zelda in favour of this.
