### ISSUE TITLE
Require-Tree: refactor or replace with dependency or both? 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5492]
In `core/server/` there's a file called `require-tree.js` which will load a directory of directories or files and also has some code for parsing a package.json file.

It's used mainly for loading `content/themes` and `content/apps`, figuring out what's in there and whether it's valid (hence the lumping together of package.json stuff). It's a bit of a mishmash of directory-reading code & validation / messaging. 

It's also (kinda weirdly) used to load all the model files in `core/server/models/index.js`.

Essentially, it seems to me to be a bit of an iceberg - it points at a whole bunch of stuff that could be refactored & cleaned up. Every time I look at it I end up on an Alice-in-Wonderland style tour of bits of our codebase that need cleaning up - but it's very, very difficult to break down into small well-spec'd issues.

Perhaps we should replace some of the directory-reading bits with dependencies, and put custom tools in `core/server/utils`, or perhaps we should look more carefully at how to group together code that deals with themes and apps.  I'm sure there are modules out there for reading directories, and I've seen one for validating package.json files. 

If we do need our own tools they should probably be in `core/server/utils` and be unit tested.

I'm sure there are small bits that can be teased easily out, so I thought I'd leave this issue here as a route in to finding things to improve and an issue to tag against in PRs.

**Comment by halfdan** [comment]
Looked at `package-json-validator`, a package that powers package-json-validator.com - it would be easy to replace our validations with that package. Sadly the latest version on npm has a bug where it requires the author field to be present (PR is already merged). 

Otherwise, usage of  `readDir` and `readAll` is scattered throughout the code base. Definitely opening portals to Narnia when trying to refactor that stuff. We already depend on `glob`, so we could use that to traverse directories. 

The problem with both those functions is that they do more than their name makes clear.

**Comment by ErisDS** [comment]
> The problem with both those functions is that they do more than their name makes clear.

Perhaps that's the first thing to solve? Cleaning up the code so that isolated functions do what they say they do?

**Comment by halfdan** [comment]
@ErisDS On that. Preparing a PR.

**Comment by halfdan** [comment]
Result of today: https://github.com/TryGhost/Ghost/compare/master...halfdan:feature/refactor-require-tree - cleaning up/opening PR tomorrow.
