### ISSUE TITLE
grunt init task fails if cwd has spaces in it 

### ISSUE THREAD

**Issue by kerrmarin** [TryGhost/Ghost#5495]
Hi there,

I was following the installation instructions in the readme when this happened:

```
ghost|stable ⇒ grunt init
Running "shell:ember:init" (shell) task
Warning: spawn ENOENT Use --force to continue.

Aborted due to warnings.
```

Looking at the `--verbose` output:
```
ghost|stable ⇒ grunt --verbose init
[omitted output]
Running "shell:ember:init" (shell) task
Verifying property shell.ember exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, execOptions={"cwd":"/Users/kerrmarinmiller/Desktop/Work/Web\\ projects/04_KerrMarin/ghost/core/client","stdout":false} 
Command: echo Installing client dependencies... && npm install
chdir(): No such file or directory
Warning: spawn ENOENT Use --force to continue.

Aborted due to warnings.
```

If I change my path to: `/Users/kerrmarinmiller/Desktop/Work/Web/04_KerrMarin/ghost/core/client` (note the lack of whitespace in the path now) it works fine.

I'm running node v0.12.5
I'm on a mac

**Comment by ErisDS** [comment]
I've verified this issue on mac. I believe that ember-cli is escaping the path as well as our Gruntfile.js, resulting in the double escaping, although I wasn't able to find out for sure.

I've tested this fix on mac: https://github.com/ErisDS/Ghost/commit/a97d073f8bd7b65fe57bdb3b5a47060b46f66ca1

Can someone (maybe @cobbspur) verify whether the problem also occurs on Windows? Is it also fixed by this change? 

Providing it's ok on Win as well I'll open a PR with the fix.

**Comment by cobbspur** [comment]
Hey @ErisDS I could not replicate the issue on windows

**Comment by cobbspur** [comment]
Tested this a little further. 

The issue can be replicated on Windows for a fresh install. 

The fix works on windows as well as mac. :+1:

**Comment by kerrmarin** [comment]
:+1: great stuff
