### ISSUE TITLE
Grunt dev doesn't watch for server-side changes

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5502]
Even though according to the config [it did not](https://github.com/TryGhost/Ghost/commit/40f59e2e4bf9516906e7dfde04100d6bacfbb862), I'm 100% certain that the watch task used to reload after changes to the server-side code, as well as client side.

When working on things like helpers & the API it is handy to have the watch task reload as well. 

If it is possible without making the watch task crash due to too many files, it would be nice to add the server-side files back to being watched.

**Comment by lukaszklis** [comment]
I've checked it and I think that the problem is somewhere else. Whenever I ssh into vagrant's machine and start `grunt dev` from there, open a file in vim inside the vm and save it, watch is triggered properly. Whenever I'm using a text editor/IDE outside of the vm and I try to save changes, watch doesn't seem to work anymore.

I've recorded two videos illustrating the issue:
- [Using editor inside of VM](https://dl.dropboxusercontent.com/u/97752/ghost-inside%20vm.mp4) (MP4 file, ~11MB)
- [Using editor outside of VM](https://dl.dropboxusercontent.com/u/97752/ghost-outside%20vm.mp4) (MP4 file, ~4MB)

This seems more like an issue with https://github.com/TryGhost/Ghost-Vagrant, doesn't it?

**Comment by halfdan** [comment]
@ErisDS `grunt dev` does reload after [changes to the server](https://github.com/TryGhost/Ghost/blob/40f59e2e4bf9516906e7dfde04100d6bacfbb862/Gruntfile.js#L77-L83) - it doesn't perform a livereload of the browser though. Is that what you want?

**Comment by lukaszklis** [comment]
@halfdan does it trigger the reload whenever you're saving a file outside of the VM for you? For some reason on my machine it doesn't do that...

**Comment by halfdan** [comment]
@lukaszklis I think those are two seperate issues. This issue here is about changes in `core/server/` that currently don't trigger a live reload (express restarts however). The issue you're mentioning is probably an issue with NFS and Ghost-Vagrant.

**Comment by lukaszklis** [comment]
@halfdan yeah, I'll open an issue in a related project. Thanks!

**Comment by ErisDS** [comment]
I'm so confused - I was having an issue where it wasn't restarting (not live reload, just the normal express restart) when I made changes when @lukaszklis reported his issue, and so I thought there must be a bug.

However, I guess I must've had a local issue because it's all working now. Going to close this issue in favour of https://github.com/TryGhost/Ghost-Vagrant/issues/65.
