### ISSUE TITLE
image insertion is inconvenient

### ISSUE THREAD

**Issue by longcang** [TryGhost/Ghost#5513]

**Comment by ErisDS** [comment]
Hi @longcang, could you please take a few moments to read through our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md)? If you would like to file a bug, there are details there of how to do it, alternatively if you want to make a feature request, visit our [wishlist](http://ideas.ghost.org) - you might find there are suggestions there you'd like to vote on.

At the moment this issue is doesn't contain anything other than an unexplained opinion - so I can't really do anything other than close it.
