### ISSUE TITLE
Bug: Mailto links not working when using same domain

### ISSUE THREAD

**Issue by MichielDeMey** [TryGhost/Ghost#5561]
### Steps to Reproduce

1. Have a blog hosted at http://bar.io
2. Set a navigation item to mailto:foo@bar.io

This will result in a link to http://bar.io  and not one to mailto:foo@bar.io.
Works as intended when using a domain different from bar.io (e.g. foo@baz.io works)

I believe this is because the mailto link shares the same domain as the blog Ghost is hosted on.

### Technical details

* Ghost Version: stable 0.6.4 - latest commit:  202d90e0636323234cab57863f8cf9048fb4dd17
* Casper Version: 1.2.4.

**Comment by ErisDS** [comment]
Hi @MichielDeMey I'm not able to reproduce this issue on Ghost 0.6.4 with Casper (I tested it out on Ghost pro and it worked just fine), I did find a regression in master, but I'll sort that out separately. I recommend swinging by our [slack](https://ghost.org/slack) channel so that we can help you troubleshoot what's going on in your case.

**Comment by ErisDS** [comment]
Reopening as bug report updated with reproducible case :+1:
