### ISSUE TITLE
Gravatar requested on every entered character during signup

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5563]
Whilst typing an e-mail address in the setup, a request is fired to gravatar for every keypress. This isn't ideal and I imagine (not yet tested) that it may cause slow-down on mobile.

Adding a debounce here should mean that ideally we only make one request to gravatar once the user has finished typing.

http://recordit.co/VPBO27YGPF

**Comment by acburdine** [comment]
I noticed this when I was coding the profile image component, but I wasn't sure exactly what to do for debouncing. 

Another thing that could be done is to check if the email is a valid email, and only send the request if it is.

**Comment by kevinansfield** [comment]
You could debounce with something like the following:

```
imageBackground: '',

emailChanged: Ember.observer('email', function () {
    Ember.run.debounce(this, this.applyImageBackground, 500);
}),

applyImageBackground: function () {
    var email = this.get('email'),
        size = this.get('size'),
        url;
    if (email) {
        url = 'http://www.gravatar.com/avatar/' + md5(email) + '?s=' + size + '&d=blank';
        this.set('imageBackground', `background-image: url(${url})`.htmlSafe());
    }
},
```

**Comment by acburdine** [comment]
That sounds good. I'll modify my PR to do that

**Comment by jaswilli** [comment]
Seems like you'd want to defer the fetch until after focus has left the email input, especially since that's when the user input is validated.

I'd look into to not sharing a property between the email input and the profile image component.  Make the flow:  `focus-out -> validate email -> set a validEmail property on the controller which is what is being passed into `{{gh-profile-image}}`.  That way you only validate the input once, and don't have to introduce complexity and arbitrary lag in the image component.
