### ISSUE TITLE
When signing up, there is always error throws "Your password must be atleast 8 chars long"

### ISSUE THREAD

**Issue by shal1y** [TryGhost/Ghost#5572]
When a user tried to accept the invite from a Ghost blog, and when trying to get past the initial sign-up, the system will always invalidate and never validate a password. If however, reports nothing when the password is "actually" less that 8 chars. The system just sits there in that situation.

version: 0.6.4

**Comment by ErisDS** [comment]
Hi @shal1y, this is the same bug as reported here: #5564, which has a PR open to fix it.

This is a bug in master, not in Ghost 0.6.4 so it would seem you are running the master branch rather than a stable version of Ghost. I recommend switching to the `stable` branch, or using a release zip. If you need a hand doing that swing by our [slack](https://ghost.org/slack) community.

**Comment by shal1y** [comment]
Thanks Eris, I'll try the stable branch
