### ISSUE TITLE
Are users able to add tags to posts?

### ISSUE THREAD

**Issue by jyek** [TryGhost/Ghost#5582]
In version 0.6.4, are users able to add tags to posts in the editor?

<img width="1045" alt="screen shot 2015-07-18 at 9 53 45 am" src="https://cloud.githubusercontent.com/assets/3284409/8759869/f01994ac-2d32-11e5-817d-1347054f48a0.png">

**Comment by acburdine** [comment]
@jyek This doesn't look like version 0.6.4. This looks like Zelda, which is the new admin interface and isn't quite ready yet, which is why it is on the master branch of the repository. If you are using the Github repository, please use the stable branch :smile:

In the master branch, though, there isn't the ability to add tags to posts yet. There's a work-in-progress PR for it that will hopefully be finished soon.

**Comment by halfdan** [comment]
Hi @jyek,
You seem to be running master and not 0.6.4. Master is currently heavily being worked on and has many UI changes - not all of which have been implemented yet. If you have questions about Ghost, please join our [slack](https://ghost.org/slack/) community. GitHub is for tracking problems with the software itself.

**Comment by jyek** [comment]
Thanks so much guys.
