### ISSUE TITLE
Uploading a blog cover image through settings fails with misleading error messages.

### ISSUE THREAD

**Issue by alanosman** [TryGhost/Ghost#5597]
Uploading a blog cover image through settings fails with misleading error messages.

I traced it down to Ghost code, inside API/utils.js.  

Line 39 should be:       
  return options[filename] && options[filename].mimetype && options[filename].path;

it was
  return options[filename] && options[filename].type && options[filename].path;

and line 42 should be:
  var type = file.mimetype,

it was 
  var type = file.type,

In both cases, type is undefined and is leading to these conditions failing and reporting errors about permissions, when its not a permission error at all..

![image](https://cloud.githubusercontent.com/assets/2914981/8825204/46f6fc0e-304b-11e5-9e32-9f9bd2a6baa6.png)

**Comment by alanosman** [comment]
btw, I was making an assumption that type should have been mimetype.  I don't really know the code, was just trying to understand why it was failing to load.  If type was supposed to be something else then I obviously got this wrong.

**Comment by ErisDS** [comment]
Hi @alanosman can you please update your issue with your environment details? There's a handy bug reporting template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) that shows the kind of information that's useful.

**Comment by alanosman** [comment]
### Issue Summary
Uploading a blog cover image through settings fails with misleading error messages.


### Steps to Reproduce

1. Log into Ghost as admin
2. Click Settings
3. Upload blog cover
It will fail. 

This is a bug because...
I traced it down to Ghost code, inside API/utils.js.

Line 39 should be:

return options[filename] && options[filename].mimetype && options[filename].path;

it was
return options[filename] && options[filename].type && options[filename].path;

and line 42 should be:
var type = file.mimetype,

it was 
var type = file.type,

In both cases, type is undefined and is leading to these conditions failing and reporting errors about permissions, when its not a permission error at all..

### Technical details

* Ghost Version: 0.6.4 as reported by NPM 
* Client OS: Windows 7, 64 Bit (also tested on Mac OSX Yosemite)
* Server OS:  Windows 7, 64 Bit  (also tested on Mac OSX Yosemite)
* Node Version: v0.10.36
* Browser: Chrome
* Database:  Sqlite3

**Comment by ErisDS** [comment]
This issue is not reproducible on windows 7 64bit or mac OSX yosemite chrome, and I've never seen anything like it.

As far as I can tell it looks like you've got a hacked / modded version of Ghost?

Here's what it should look like if you console log the object you get when uploading an image:

```
uploadimage: { 
  type: 'image/jpeg',
  encoding: '7bit',
  name: 'myimage.jpg',
  path: '/var/folders/qm/tsdrxdyx2033l7szbx0y14_r0000gn/T/1440445285639b6ac749f38547ad84c76b299225e2769' 
}
```

And here's the code in Ghost that creates that object:

https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/ghost-busboy.js#L43

The only other thing I can think of is that you've got the wrong version of busboy, or some other missing dependency causing this to be different.

**Comment by dschwertfeger** [comment]
I ran into the same issue today.

I'm using Ghost as an npm module in an existing Express app. In my Express app I use `multer`. 

I noticed that the `file` event was never fired, so I never got into the `busboy.on('file', function onFile(fieldname, file, filename, encoding, mimetype) { … }` code path which would create the `uploadimage` object as you describe.

Mounting the `ghost` middleware before `multer` remedies this problem.

I don't have time to dig deeper into this but maybe this gives you an idea of what's happening or helps someone else who ends up here.

**Comment by ErisDS** [comment]
@dschwertfeger when you say 'the same issue' do you mean that you got an object with `mimetype` instead of `type`? If not, then the issue is not the same. 

I do not know why this issue is occurring - the OP has not updated with any more details as this doesn't make any sense given the code. 

With regards to your issue with needing to mount multer after Ghost, I imagine you'd need to be sure you mount in such a way that Ghost doesn't get that middleware, so that would make sense. Perhaps you could add this requirement to the [module documentation](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-NPM-module).

**Comment by dschwertfeger** [comment]
Exactly. I got an object with `mimetype` instead of `type` because I didn't get into the code path that rebuilds the object with the `type` attribute.

From what I remember, it looked like the `'file'` event busboy is listening for in the code that you pointed out is not fired.

>  Perhaps you could add this requirement to the module documentation.

Sure, I can do that.

**Comment by ErisDS** [comment]
@dschwertfeger right, thanks for explaining - that makes much more sense. I think it's pretty expected that mounting multiple middlewares for file uploading would cause a conflict and there's not much we could do in Ghost to prevent that. Adding some thing to the documentation to explain this is probably the best outcome?
