### ISSUE TITLE
Ember / Ember-Cli / Ember Data Updates

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5630]
This issue serves as a place to store information about the updates we need to do, what blockers there are and who is working on them.

@jaswilli said [this](https://ghost.slack.com/archives/ghost/p1436894285007354):

> I have a working ember-cli 1.13.whatever along with ember-data 1.13.5 that’s blocked on a regression in the RESTAdapter

The current upgrades in ember are not considered to have any major bug or security fixes which we need, and therefore it's recommended we hold off on upgrading until after Zelda ships.

If you have more information about what needs to be done, or are working on it, please drop a comment here :+1:

**Comment by wycats** [comment]
@ErisDS I'd definitely finish up your current work before trying to do an upgrade, but please ping us if there's anything we can do to help transition off of deprecated features.

I see you're already on 1.13.2, so it probably won't be too difficult.

**Comment by acburdine** [comment]
@ErisDS after looking through the codebase a bit, there's definitely some somewhat major changes that will have to made to the codebase. If there's no one else that wants to, I'm more than willing to tackle this after Zelda ships.

**Comment by acburdine** [comment]
Also, Ember Simple Auth is nearing 1.0 status. I've been upgrading a couple of my personal applications to use the new version, so it might be a good idea to add that to this issue

**Comment by wycats** [comment]
@acburdine I'd be interested to know what the major areas of work will need to be.

**Comment by acburdine** [comment]
I guess I overstated, mostly referring to ember-data, but the big one that I saw was the switchover to the Helper API instead of the HTMLBars.makeBoundHelper syntax. There's probably also several uses of Ember.keys floating around in the codebase.

That's for the Ember changes at least. The Ember-Data 1.13 upgrade will be somewhat major because all of the deprecated find functions have to be switched over.

**Comment by jaswilli** [comment]
@wycats There's nothing really major that needs to be done.  Our big push to Ember 1.13/2.0 was done in #5468.

As far as Ember-Data goes I have/had everything working on 1.13 as of a month or so ago but was blocked against model state transitions not working like they did in the 1.0.0-beta series (context: https://github.com/emberjs/data/issues/3524#issuecomment-120720633).

I haven't been tracking ember-data closely since then so I just need to circle back and see what the current situation is.
