### ISSUE TITLE
Pressing markdown shortcuts multiple times

### ISSUE THREAD

**Issue by nknapp** [TryGhost/Ghost#5636]
When I open the markdown editor, select a piece of text and hit Ctrl+K multiple times, the following happens

* The initial text is `the initial text`
* After hitting Ctrl+K the first time: `the ~~initial~~| text` The `|`represents the cursor
* After hitting Ctrl+K again: `the ~~initial~~~~|~~`. So far that's understandable.
* After hitting Ctrl+K again: `the ~~initial~~~~~~|~~~~`.
* After hitting Ctrl+K again: `the ~~initial~~~~~~~~|~~~~~~`.
  This is rendered as "the ~~initial~~~~~~~~~~~~~~"

I would have expected a toggling behaviour, at least when hitting the combination the third time. Pressing shortcuts should not produce broken markdown.

**Comment by ErisDS** [comment]
Hi there @nknapp & welcome,

The expected behaviour of the editor keyboard shortcuts is to insert the correct markdown symbols - they're essentially a shorthand. If you make a selection it will wrap the selection with the markdown symbols. If you have no selection, the cursor is wrapped. There is no expectation that toggling behaviour would work in the current iteration of the editor as it has no concept of state maintenance. 

Future iterations of the editor may have more underlying state handling, and therefore toggling would naturally work. If you're keen to see toggling work for keyboard shortcuts, I recommend raising it as a feature request on the [wishlist](http://ideas.ghost.org). It's not something we're looking to change in the current editor.

**Comment by nknapp** [comment]
Thanks for pointing me to the wishlist. Took me a while to take care of it, but I have now added a feature request there. By now, I have also read the contributing guidelines, which I should probably have done before raising. Nice document btw (the guidelines).
