### ISSUE TITLE
Support any image format and implement proper file type detection.

### ISSUE THREAD

**Issue by SushiDude** [TryGhost/Ghost#5664]
Upon attempting to upload a [WebP](https://developers.google.com/speed/webp/) for my blog cover image, I was presented with the following error:

>The image type you uploaded is not supported. Please use .PNG, .JPG, .GIF, .SVG.

By simply changing the file extension from .webp to .jpg it accepted the file, but served it with Content-Type:image/jpeg.

This raises two concerns:

- Ghost arbitrarily blocks many image formats. Ghost should allow any format.

- Ghost’s file type detection is primitive and can not accurately judge file types. This results in the serving of false content types.

[As of posting, support for WebP is currently at the top of the Ghost wishlist.](https://ideas.ghost.org/forums/285309-wishlist/suggestions/7191829-image-optimization)

I would recommend looking into how the program [file](https://en.wikipedia.org/wiki/File_(command)) detects file types.

**Comment by sebgie** [comment]
Hey @SushiDude and welcome to the Ghost issue tracker on GitHub!

> Ghost arbitrarily blocks many image formats. Ghost should allow any format.

It's not arbitrary, it's intentional. We try to support 80 % of the use cases which are covered with the available file formats. Feel free to open a PR for adding WebP to the list of supported files. If it is considered a valuable addition by the community the PR will be merged.

For security reasons we don't allow uploading of any file format (see: https://www.owasp.org/index.php/Unrestricted_File_Upload).

> Ghost’s file type detection is primitive and can not accurately judge file types. This results in the serving of false content types.

Correct. Therefore we ask to please upload a file with the correct format and not to rename the file extension ;-). The file detection is quite primitive because it has to work with different combinations of Node.js, operating systems and browsers. Any pointers to useful libraries (maintained, no compilation required, Windows/Linux/OSX compatible) are highly appreciated.

> As of posting, support for WebP is currently at the top of the Ghost wishlist.

Support for WebP is not the main subject of the item on the wish list. It asks for "Image Optimization" which is actively discussed in issue #4453.

**Comment by SushiDude** [comment]
@sebgie
>It's not arbitrary, it's intentional.
>For security reasons we don't allow uploading of any file format (see: https://www.owasp.org/index.php/Unrestricted_File_Upload).

This fails to make sense. What is your threat model? To prevent the owner and administrator of a blog from uploading a malicious file in order to protect the blog from himself? There are massive issues with this:
- Why would the owner of a blog want to attack himself?
- The owner already can include code in any blog post because it is Markdown which is really just HTML. The administrator could use the Code Injection feature. The person who runs the blog likely has root on the server and control over the domain.
- The file upload restriction feature can be fooled by changing the file name. I doubt you even read the OWASP link that you posted, considering how you missed the massive “Weak Protection Methods and Methods of Bypassing” section. Not to mention that SVGs, which you consider to be a safe file format, can include JavaScript and CSS.

>We try to support 80 % of the use cases which are covered with the available file formats.

You could support 100% of the use cases by removing this intentional *security* feature.

>Any pointers to useful libraries (maintained, no compilation required, Windows/Linux/OSX compatible) are highly appreciated.

While I have never used it before, [mmmagic](https://www.npmjs.com/package/mmmagic) appears to be a decent Node.js library. It is asynchronous and is just a binding to libmagic--which is the library that file uses. However, this has to be compiled.

>Any pointers to useful libraries ... no compilation required

Ghost’s dependency tree already has a massive number of compiled libraries and programs. Why does the file type detection library need to not require compilation?

**Comment by jaswilli** [comment]
Fantastic. I look forward to your PR to improve image handling.  No dependencies with native bindings, though.

> Ghost’s dependency tree already has a massive number of compiled libraries and programs.

You're going to have to back that claim up by showing your work.  Pretty sure you could run an instance of Ghost in production without any dependencies that require native bindings.

**Comment by blueForestIcarus** [comment]
As to the original point, I agree that is is unnecessary to white-list acceptable file types. If you have security concerns, you should blacklist file-types you find to be a risk, rather than restrict functionality by only allowing those which you have decided to place in the config file. 

What type of files are you concerned about?

**Comment by SushiDude** [comment]
@jaswilli
>You're going to have to back that claim up by showing your work. Pretty sure you could run an instance of Ghost in production without any dependencies that require native bindings.

Off the top of my head I can think of SQlite and Node.js which requires OpenSSL, V8, zlib, and libuv which are all massive and are written in C/C++.

>I look forward to your PR to improve image handling.

I never said that I was going to submit a pull request. I am not familiar with the Ghost code base and this seems like a fairly simple change; it would be better for one of the Ghost developers to implement.

**Comment by ErisDS** [comment]
Hi @SushiDude, 

Please submit feature requests via our [wishlist](http://ideas.ghost.org) rather than through GitHub, as that allows us to measure traction. We use this list to help determine what goes into the roadmap and how to prioritise features - you'll see image optimisation, including WebP support are top of the list right now. You can also access the wishlist any time from inside the Ghost admin: 
![](http://puu.sh/jXKwm.png).

(screenshot from Zelda)
