### ISSUE TITLE
[Bug] Tag Page allows invalid tags

### ISSUE THREAD

**Issue by halfdan** [TryGhost/Ghost#5685]
The tag page currently allows me to insert tags that are not valid in the PSM. An easy example is: `,,,` which can be added on the tag page but not in the PSM (where the comma acts as a delimiter to finalise a tag).

**Comment by kevinansfield** [comment]
Currently there is no validation (server or client-side) for tag names, although tag slugs will have invalid characters stripped.

I haven't fully checked yet but I'm guessing tags with commas must always have been an issue in the post tags input as the comma is used as an action key for the input rather than being "invalid" in the conventional sense.

This raises the question - should commas be allowed in tags anywhere? They would definitely cause issues if being typed in the PSM although if the comma isn't the first character it should be possible to select the tag from the autocomplete list.

As a follow-on, if we're guarding against commas are there any other characters that should be considered invalid for tags?

**Comment by ErisDS** [comment]
As far as I remember, the intention was to make commas invalid in tags, but nothing else. I think double quotes are possibly going to end up being problematic as well (thinking about GQL) - but the intention was to keep tag name as liberal as possible & keep all the sanitisation in the slug part.
