### ISSUE TITLE
Bug: Odd tag component behaviour when pressing Cmd/Ctrl+S 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5708]
Aside: I'm a serial cmd+s-er, I can't help myself.

If you enter some tags into the new tag component which are not yet saved in the system, and then press `cmd/ctrl+s`, the new tags disappear. They reappear on refresh.

Steps to reproduce (shown in the gif):

1. Start a new post
2. Open the PSM, and enter some tags - I entered one each of both existing and non-existing tags to demonstrate
3. Hit `cmd+s`, suddenly the brand new tag is gone. The existing one is still there though.
4. Refresh the editor, new tag comes back, both are present and correct.

![](http://puu.sh/jMFSi.gif)

**Comment by kevinansfield** [comment]
This isn't limited to `cmd/ctrl+s`, you'll see the same behaviour by clicking the 'Update' button then re-opening the PSM.

**Comment by ErisDS** [comment]
Ah yeah - seeing that too.

**Comment by kevinansfield** [comment]
I haven't tracked down the exact problem yet but I believe it's something to do with `model.tags` getting updated slightly before the `availableTags` query has updated and so the selectize addon ignores the post tags that aren't in the available tags array. This _shouldn't_ be an issue because the availableTags array should still have contain the new tag but it appears the object references for the new tags get changed during save :confused: 

Hopefully I'll be able to find a fix or workaround in the morning.
