### ISSUE TITLE
forceAdminSSL: true does not work in 0.70

### ISSUE THREAD

**Issue by tomhowson** [TryGhost/Ghost#5824]
Hi,

I have found taht forceAdminSSL: true deos not work in 0.70 of ghost. 

Thanks,

Tom.

**Comment by sebgie** [comment]
Hey @tomhowson,

I'm sorry but I can't replicate any problems with `forceAdminSSL: true`. If it doesn't work I would assume that it has something to do with your environment. We have a slack channel (ghost.org/slack) with a very helpful community for issues like that.

If it turns out to be a bug it would be very helpful if you could provide more information about your environment and what the actual/expected behaviour is.
