### ISSUE TITLE
{{navigation}} not working in partials

### ISSUE THREAD

**Issue by adammcarth** [TryGhost/Ghost#5836]
The global navigation variable isn't working in partial templates. I include `partials/menu.hbs` in my theme's `default.hbs` layout, and within that menu partial consists the code:

```html
<nav role="navigation">
  {{#foreach navigation}}
  <a class="menu_link" href="{{url}}">{{label}}</a>
  {{/foreach}}
</nav>
```

...this results in the output:

```html
<nav role="navigation">
</nav>
```

Now, if I change `menu.hbs` to use `@blog.navigation` instead, it kind of works:

```html
<nav role="navigation">
  {{#foreach @blog.navigation}}
  <a class="menu_link" href="{{url}}">{{label}}</a>
  {{/foreach}}
</nav>
```

Outputs:

```html
<nav role="navigation">
  <a href="menu_link" href="/">Page Title</a>
  ...
</nav>
```

But the issue now is that the `{{url}}` isn't working properly under this new code (all links are coming back with `/`). Is this a bug?

**Comment by gonzalobustos** [comment]
+1

I have the same problem when trying to use `@blog.navigation` in a partial: `{{url}}` and `{{slug}}` helpers are not working properly, only `{{label}}` works as expected.

**Comment by ErisDS** [comment]
Hi there @adammcarth & @gonzalobustos - I'm sorry to hear you're having trouble setting up navigation in your themes. The behaviours you're describing here are what I'd expect to happen. 

The navigation feature in Ghost makes use of a special partial called `navigation.hbs` to define the HTML for your navigation - please have a read of the documentation: http://themes.ghost.org/docs/navigation and if you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #themes channel where we're able to provide support.

**Comment by adammcarth** [comment]
@ErisDS Makes sense, but then in that case I found this a really confusing way of wording that, especially for custom theme developers: "You can override the HTML output by the navigation helper by placing a file called navigation.hbs inside of content/themes/your-theme/partials. Details of the default template are below."

Is there a distinct reason why you made `navigation` only available to the `navigation.hbs` partial?

**Comment by ErisDS** [comment]
Just to follow up here with what was explained in slack:

The `{{navigation}}` helper is all you need in order to output the navigation menu in your theme - no partial is necessary, no looping is necessary. The `{{navigation}}` helper can be used anywhere and does all the work for you.

If, for some reason, you aren't happy with the structure of the HTML being output from the `{{navigation}}`` helper and want to change it, then you can create a new partial which must be called `navigation.hbs` - this then overrides the default partial provided by Ghost [here](https://github.com/TryGhost/Ghost/tree/master/core/server/helpers/tpl).
