### ISSUE TITLE
Bug: cyrillic posts trouble after update

### ISSUE THREAD

**Issue by karonator** [TryGhost/Ghost#5856]
Hi all.
I'm from russia, and I used ghost for my personal blog about ios developement.
Ghost was installed on my own server (debian) and all was cool.

After upgrade to 0.7.0 all my posts (russian characters) were shown like questions.
I opened the database (mysql) and see all my posts in russian, so there was all good in database after update.

Then I tried to copy the text and create the new cyrillic post. I was surprised. It showned on the site good, but now there was some black magic in database (like Ð”ÐµÐ»ÐµÐ³Ð).

In config file there is charset  : 'utf8'.
If you need the access to the server, I can give it to you.

**Comment by karonator** [comment]
* Ghost Version: 0.7.0
* Client OS: Mac OS X 10.10.5
* Server OS: Debian 8.2 (Wheezy)
* Node Version: v0.10.22
* Browser: Chrome 45.0.2454.93
* Database: MySQL

**Comment by ErisDS** [comment]
@karonator Did you upgrade anything else at the same time as Ghost? E.g. Node, Debian, or MySQL?

> After upgrade to 0.7.0 all my posts (russian characters) were shown like questions.

Where did you see this? In the admin panel or the front of your blog?

> Then I tried to copy the text and create the new cyrillic post.

What happens if you create a post without copying text?

**Comment by karonator** [comment]
> Did you upgrade anything else at the same time as Ghost? E.g. Node, Debian, or MySQL?
Nope =(
> Where did you see this? In the admin panel or the pages of your blog?
In the panel and in the pages
> What happens if you create a post without copying text?
I recorded the video for you, look please: https://youtu.be/_9uh03dbiOM

**Comment by ErisDS** [comment]
Due to an incompatibility issue with the knex & MySQL dependencies that Ghost has used since creation I would expect the contents of your MySQL database would likely be double-encoded. This would make them unreadable to you, but still work when fetched and saved in Ghost because the double-encoding is handled in both directions.

In the video, I only see a problem inside the database - which is expected and is not a problem unless you are having problems reading and editing your posts. 

I have had a similar report of issues with Korean characters, which impacts Chrome, but not Safari. When I look at that blog in Chrome, I see the characters correctly. I have tried to access your blog but it appears to be offline.

What version were you on prior to upgrading?

Can you try in an incognito window in Chrome and in another browser?

Can you further clarify that you're seeing issues on the blog itself and not the database?

**Comment by ErisDS** [comment]
Another question: In Chrome, can you try going to the menu at the top and choosing View > Encoding and making sure it's set to UTF-8?

**Comment by karonator** [comment]
> What version were you on prior to upgrading?
I not remember, smth like 0.6.4 I think...

> Can you try in an incognito window in Chrome and in another browser?
Tested in icognito window and in Apple Safari - same story =(

> Can you further clarify that you're seeing issues on the blog itself and not the database?
Well, the problem is in the ghost-database magic. For example, I can't use old database (utf8 encoded) with all my old posts (((
I'm afraid that if I will use ghost now, it will save posts good but there will be wrong data in database, and in one day when you will fox thos issue,  I'll need to reencode all database...

> In Chrome, can you try going to the menu at the top and choosing View > Encoding and making sure it's set to UTF-8?
Checked, it's UTF8

Hannah, maybe the direct access to the server will help you?

**Comment by ErisDS** [comment]
@karonator - I don't think access to your server is going to help, as it is not yet clear what has happened or if there is an issue - we're talking about it in #dev in Slack if you'd like to come and help us understand fully.

**Comment by ErisDS** [comment]
After a further discussion in slack it was determined that this was due to the double encoding issue I explained above. At present it is expected that the DB is unreadable as the chars there are double-encoded. Creating & retrieving posts works as expected.

**Comment by karonator** [comment]
Thank you!
