### ISSUE TITLE
Image upload in new post does not work.

### ISSUE THREAD

**Issue by ekollof** [TryGhost/Ghost#5895]
When uploading an image to a new post, the waiting cat appears, but no image does. The image does arrive on the server. I'm running Ghost 0.7.1 on FreeBSD 10.2 with MariaDB as a backend. The browser is Chrome.

Screencast of problem in action here:

https://drive.google.com/file/d/0B5MzsgMZ9IeFaFhHNDl1NF9HVVU/view

**Comment by halfdan** [comment]
@ekollof Hi there, for support please check out our Slack community: http://ghost.org/slack. 

In your case I'm guessing that Ghost does not have write permission to the `content/images/` folder - you may want to check permissions on the folder.

**Comment by ekollof** [comment]
Permissions are fine. I can get to the images from the browser by using the full url. The image upload does not seem to insert the image path into the image tag after uploading.

**Comment by ErisDS** [comment]
Hi @ekollof, I'm sorry to hear you're having trouble. The issue you're describing is not a bug in Ghost, but is rather likely caused by some detail of your quite specialised env. If you need help debugging the issue, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!

**Comment by ErisDS** [comment]
This was due to CloudFlare's rocketloader. The troubleshooting guide has been updated accordingly: http://support.ghost.org/troubleshooting/#i-can’t-upload-images
