### ISSUE TITLE
Clear "saving failed" notifications on reauthentication

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#5903]
### Issue Summary

Leaving a tab open until your session expires will cause your next save to fail (duh!), throwing up an error message and asking you to reauthenticate. 
After having done so, the "saving failed" error messages stick around. It would sure be nice if they were cleared out after a successful login.

<img width="1476" alt="screen shot 2015-09-30 at 07 53 02" src="https://cloud.githubusercontent.com/assets/1207005/10194919/70986258-6748-11e5-802e-15147c4a999a.png">

### Steps to Reproduce

1. Open a post for editing
2. Expire your session
3. Force a save, triggering reauthentication + save error message
4. Supply your PW
5. Error messages stick around

### Technical details:

* Ghost Version: 0.7.1
* Client OS: Mac OS X 10.10.1
* Server OS: GhostPro
* Browser: Chrome 45

**Comment by kevinansfield** [comment]
@ErisDS it seems like it might be useful to have a "key" of some description for notifications/alerts so that we can have a more fine-grained method of clearing alerts as right now it's all or nothing unless we check for the message text.

For example on sign-in attempts and successful sign-in we could clear only the sign-in related alerts and not worry that we're also wiping out alerts generated by other areas of the app.

**Comment by ErisDS** [comment]
Yep, sounds good to me - this was a zelda audit item that never go it's own issue - any duplicate alerts are not supposed to stack, but rather replace the last one. I couldn't find out the right Ember Array incantation to do that :wink:
