### ISSUE TITLE
configurable template

### ISSUE THREAD

**Issue by Kikobeats** [TryGhost/Ghost#5906]
I didn't find a way to do it and I think that could be powerful for develop more complete themes.

Imagine that you have a structure of your posts in a common file called `post.hb` but, instead of stay here, you have a file called `grid.hbs`

For visualize your posts need a `post.hbs` file, so let's create one and load the template structure as: 

```hbs
{{!< grid }}
```

Now, in another part of your theme (for example, an especial page) you want to use the same structure that a common post, but you want to disable comments and hide the sidebar. Just configure the grid call as:

```hbs
{{!< grid sidebar='false' comments='false'  fullscreen='true'}}
```
of course in my grid implementation I must a block (or something) where I do something like:

```hbs
{{#if sidebar}}
  {{> sidebar}}
{{/if}}
```

so configure the call is useful to avoid duplicate files and keep all in order.

**Comment by ErisDS** [comment]
@Kikobeats This is an interesting idea :+1: 

In order to determine whether this idea has traction with other theme developers, I recommend raising it on our [wishlist](http://ideas.ghost.org) rather than here on GitHub. We use that list to prioritise work, so if it got a lot of votes we could look at reopening this issue and implementing the feature. 

Note: It would need to be implemented in [express-hbs](https://github.com/barc/express-hbs) rather than in Ghost as that's where the layout functionality comes from.

 In the meantime, you can use things like `{{#is post}}` or `{{#has tag='something'}}` to conditionally load bits of your template, but I can certainly see how this would be a useful addition.

**Comment by Kikobeats** [comment]
done! :-)
