### ISSUE TITLE
Blog cover display of setting page is too large on the IE11 Windows Phone 8.1

### ISSUE THREAD

**Issue by bohanyang** [TryGhost/Ghost#5908]

**Comment by kevinansfield** [comment]
Hi @bohanyang, can you provide a screenshot please? Also let us know your Ghost version and any other details that may be relevant. Thanks.

**Comment by ErisDS** [comment]
There is a bug report template in our [contribution guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) which shows the details we need in order to be able to follow up on and fix a bug.

There's not enough info here to really do anything, so I'm going to close the issue for now. Will reopen when details are provided.

**Comment by bohanyang** [comment]
Thanks. I've found that the issue was solved in 0.7.1.
