### ISSUE TITLE
redirect loop when password protecting blog at example.com/private/

### ISSUE THREAD

**Issue by Patagonicus** [TryGhost/Ghost#5914]
I've set up an instance of Ghost behind nginx as a reverse proxy. Ghost can be reached under `example.com/private/` (so the admin interface is at `example.com/private/ghost/`). The nginx config looks like this:

        location ~ ^/private(/.*)?$ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                proxy_pass http://127.0.0.1:2368;
        }

The correct URL (`http://example.com/private/`) is set in `config.js`.

When enabling password protection for the blog a user that is not logged in gets a redirect loop (Ghost sends a redirect to `/private/` which is what the user requested. When following the redirect Ghost sends the same redirect.). When already logged in the blog works as intended. Using a different folder such as `foo` instead of `private` does not trigger this behavior.

* Ghost Version: tested 0.7.0, 0.7.1 and master (f7015600b8bbd61d76fa324fff69fac2dd8c2452)
* Client OS: Gentoo Linux (amd64)
* Server OS: Gentoo Linux (amd64)
* Node Version: 0.12.6
* Browser: Chrome 45.0.2454.85 and wget-1.16.3-r1
* Database: SQLite

**Comment by ErisDS** [comment]
This sounds like it is probably caused by the fact that `/private/` is a special route in Ghost itself. Somewhere there is probably a check for `/private/` that isn't taking the subdirectory into account properly. A PR with a fix would be very much appreciated.

**Comment by delgermurun** [comment]
@ErisDS found bug [core/server/config/urls#50](https://github.com/TryGhost/Ghost/blob/master/core/server/config/url.js#L50).

But what is the reason behind this code? Can we delete it?

**Comment by ErisDS** [comment]
@delgermurun  The code in question is there to ensure that routes which are generated by various parts of the Ghost application don't end up with the subdirectory appended twice. I'm afraid removing it would break more use cases than it fixes. 

@Patagonicus it seems to me that using the route `/private/` with a blog which is also password protected ends up with quite an ugly URL, anyone visiting the page and needing to log in will have to visit `/private/private/`, is this something you were doing short term whilst testing?

The reason that I ask is that I think the fix is going to be less than trivial, for a very very edge usecase, when absolutely anything other than `/ghost` or `/private` would work!

**Comment by Patagonicus** [comment]
@ErisDS That domain is hosting two blogs, one public, one private (i.e. for just a small number of people), calling it `/private/` seemed to be the logical choice. I've since renamed it to `/secret/` which is working fine (except for a bug with the theme we wanted to use, but I still have to track that down as I can't reproduce it).

I think *something* should be done about this, but it doesn't necessarily have to be making the code work when the blog is hosted under `/private/`. A warning/error when trying to enable private mode if that is the case would be fine with me.
