### ISSUE TITLE
query parameters in a custom handlebars helper.

### ISSUE THREAD

**Issue by marktheis** [TryGhost/Ghost#5957]
I'm trying to make a custom handlebars helper that serves specific content based on the query parameters in the url: `ghostblog.com/page?query=something.`

```
hbs.registerHelper("custom_helper", function(option, res, req) {
    var url = res.data.root.relativeUrl;
  });
```
the relativeUrl strips it out and the query string is nowhere else in the response.

I would appreciate if there is anyone that knows how to get the query string or knows an alternative method to this.

**Comment by ErisDS** [comment]
Hi @marktheis - we have a #themes channel in our [slack](https://ghost.org/slack) community for exactly this sort of question :wink:. Ghost doesn't support registering custom helpers, so if you're hacking core to add one, then this isn't a bug or issue with the Ghost software itself.

If you're trying to change part of your template based on query parameters, then I would classify that as dynamic data rather than static. Ghost is designed to be heavily cached and anything you write in a theme template should be considered 'static'. I'd recommend using JavaScript instead in this case.

**Comment by marktheis** [comment]
Sorry. It's of course not a bug. 
I somehow skipped over your slack channel. I'll take a look over there :blush:
