### ISSUE TITLE
Express error: request entity too large

### ISSUE THREAD

**Issue by devilankur18** [TryGhost/Ghost#5998]
I created a new post with too much content, and express started throwing errors. 
```
Saving Failed!
```

I inspect in to it and its related to express data post limit. I have to change the file `core/server/middleware/index.js` to make it work
```
// Body parsing
    blogApp.use(bodyParser.json({limit: '50mb'}));
    blogApp.use(bodyParser.urlencoded({extended: true, limit: '50mb'}));

```

Is there a better way to set limit via config.js ??

**Comment by ErisDS** [comment]
Hi @devilankur18, sorry to hear you're having trouble. I've not heard of people encountering this before, except in cases where their nginx/apache configuration, browser or ISP was limiting the size of the request.

I don't think that the code you suggested is the correct solution to the problem, as the limit for bodyparser defaults to `100mb` according to their documentation: https://github.com/expressjs/body-parser#limit and therefore would already be greater than 50mb. 

I recommend updating this issue, framing it as a bug report with reproduction steps - there is a template in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs), which outlines all the information it would be useful to include. That will help us to reproduce the issue so that we can understand it.

**Comment by anonrig** [comment]
Hello @devilankur18 

@ErisDS is correct. You don't have to change your bodyparser limit.

I believe that the problem is based on `nginx` part of the server. You can increase the maximum body size from your .conf file. I suggest adding the following:

```
client_max_body_size 240M;

client_body_buffer_size 128K;
```

**Comment by reinoudk** [comment]
I was able to reproduce this running Ghost without nginx. 

### Issue Summary
Cannot create posts larger than 100kB. This is due to the default bodyParser limit of ```100kb```.

### Steps to Reproduce
1. click on New Post
2. Copy (75kB) content of https://gist.github.com/reinoudk/4c1c8e63d2970c0d2275#file-75kb-txt to content
3. click on SAVE DRAFT
4. Copy (150kB) content of https://gist.github.com/reinoudk/4c1c8e63d2970c0d2275#file-150kb-txt to content
5. click on SAVE DRAFT

### Observerd result
Step 2 successfully saves the post.

Step 5 shows an error:
```
Saving failed.
The server returned an error (Server was not available).
```

### Desired result
Step 5 should also save the draft.

### Technical details

* Ghost Version: master - latest commit:  bec5db59807adfc6cd2b0c688ea12854e3860953
* Client OS: Windows 8.1
* Server OS: Windows 8.1
* Node Version: 0.10.40
* Browser: Chrome 46.0.2490.80 m
* Database: sqlite

**Comment by devilankur18** [comment]
@ErisDS I also thought that my nginx was causing the problem, but as I started debugging,  it as not nginx. Nginx has no error logs, and the max-post size was already 100mb there. 


Here is the post which was causing the problem in creation. Everything got fixed after I have added added 2 lines of code mentioned above. 

http://blog.smugglr.co/2015/10/23/we-made-it-open-season-and-got-100s-of-agencies-as-users/


@ErisDS I think you misread the limit size, its `100kb` not `100mb` on https://github.com/expressjs/body-parser#limit

**Comment by fwb7014** [comment]
@devilankur18  You are right,it works for me.

**Comment by marcoliceti** [comment]
It would be nice to have a dedicated setting instead of having to manually change that lines.

I know 1mb is a reasonable limit for textual content, but I plan to add a few base64-encoded pictures in my posts. In such scenario, that limit could be too low.

**Comment by mazard** [comment]
Same problem here, I had to change:

./web/api/canary/content/app.js:15:    apiApp.use(bodyParser.json({limit: '200mb'}));
./web/api/canary/admin/app.js:16:    apiApp.use(bodyParser.json({limit: '200mb'}));
./web/api/canary/admin/app.js:17:    apiApp.use(bodyParser.urlencoded({extended: true, limit: '200mb'}));
