### ISSUE TITLE
Ghost CI

### ISSUE THREAD

**Issue by jgillich** [TryGhost/Ghost#6056]
A long time ago we [talked](https://github.com/TryGhost/Ghost/issues/1603) about running tests on multiple operating systems using Docker and Jenkins. Today, Travis offers support for docker natively so I though I'd give it a try.

Here are the results:
https://github.com/jgillich/Ghost-CI
https://travis-ci.org/jgillich/Ghost-CI

* Runs tests on 6 different Linux distributions
* Supports multiple versions per distribution
* Works on any CI that provides Docker API access
* Adding new distributions is a matter of minutes

The way it works is basically: Render handlebar templates to Dockerfiles, bundle them with Ghost in a tarball, then use the Docker API to build images and run them.

It was a fun little project, now the question is can you use any of this? Integrating this in the main repo wouldn't be a good idea because it takes tons of resources, not to mention that it only runs on VMs. I think this would be something to run maybe once a week and before releases.

**Comment by cwonrails** [comment]
This is really cool! Thanks for your work here :)

**Comment by jgillich** [comment]
I've [rewritten this](https://github.com/jgillich/chimera) to be a simple executable that is configured through a dotfile. @ErisDS if you are interested, let me know. If not, that's fine too. :wink:

**Comment by ErisDS** [comment]
I think this is really cool, but I'm struggling to think of how we can use it. We've been trying to optimise our builds for a while because they take too long and get in the way of development. Also worth noting, we're thinking of pushing towards having a single 'standard' install, which would likely be Ubuntu LTS, with much clearer documentation etc that centres around that one single platform. 

The idea being that of course, Ghost will work on other platforms, but that documentation, fixes or improvements focused on any other platform would be community led. Ideally, we want to get more people into our [Core Team](https://github.com/TryGhost/Ghost/wiki/Core-Team) so that this sort of thing can happen much more easily.

With regard to testing using [chimera](https://github.com/jgillich/chimera), I'm thinking it would be cool to see something like a Ghost-Nightly repo that automatically has master pushed to it each night and runs these multiple builds. Something like this could potentially be used for memory & performance testing as well - something else I'd love to see, but I just haven't had enough time to set it up.

**Comment by jgillich** [comment]
About the standard install, maybe you could do it via Docker image, [like Discourse](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md#install-discourse)? It's their default installation method, and I think it's pretty great.

Nightly builds sounds like a good idea, but I'm not sure how to do the push. Do we
* add a after_success hook that checks the date of the last commit and pushes to the repo?
* use some third-party service? (not sure if something like that exists)
* Throw a cron job on some server?
* Do something else?

**Comment by ErisDS** [comment]
> About the standard install, maybe you could do it via Docker image, like Discourse?
We've thought about that, quite a bit, and the conclusion was it isn't any more user-friendly. Docker is dev friendly, but quite confusing to a large group. It's still a possibility though.

As for how to do nightlies then either:

> use some third-party service? (not sure if something like that exists)

This.. if we can find something, maybe https://nightli.es/ ??

Otherwise

> throw a cron job on some server?

Prob this?

**Comment by jgillich** [comment]
Nightlie.es looks good. There's also [Travis Cron](http://traviscron.pythonanywhere.com/).

I've set up the [repo](https://github.com/jgillich/Ghost-Nightly) and it will let it run for a few days to make sure things are reliable before transferring it. About distros, you probably don't want any more than [these](https://github.com/jgillich/Ghost-CI/blob/master/config.js#L2), right?  :)

**Comment by jgillich** [comment]
https://travis-ci.org/jgillich/Ghost-Nightly/jobs/94897638#L6643

And my last comment said something about reliable testing. :grinning:

**Comment by ErisDS** [comment]
Closing this as it's pretty out of date now and the links are dead 😉
