### ISSUE TITLE
Look @ optimising the Ghost .zip & .js file size

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6149]
The very first release of Ghost was 1.7MB. Since then, we were slowly growing, up to 2.4MB in 0.6.4. However, the three 0.7.x releases have increased significantly faster, at 2.7, 2.7 & 3.2 MB respectively.

Almost all of this extra weight seems to be coming from vendor.js, although ghost.js is also growing.

Here's a table showing those main files and how they've changed over the last 4 versions.

| version | ghost.js | ghost.min.js | vendor.js | vendor.min.js |
| :-- | --: | --: | --: | --: |
| 0.6.4 | 951,692 | 460,776 | 3,873,560 | 1,270,938 |
| 0.7.0 | 1,064,897 | 514,160 | 4,379,867 | 1,420,503 |
| 0.7.1 | 1,156,730 | 518,014 | 4,381,850 | 1,421,394 |
| 0.7.2 | 1,418,668 | 585,806 | 6,108,228 | 1,484,640 |

I'm not sure what strategies we can use to try to minimise this, as I realise it's being bumped up by the inclusion of libraries. Some questions:
- are there libraries/addons we are using that could be swapped for something smaller?
  - swapping codemirror for prism could save us 300kb [notes](https://ghost.slack.com/archives/dev/p1440513068000038)
- are there any dev-only dependencies getting included at all?
- is there a better minification library?

**Comment by kevinansfield** [comment]
Ember 2.2 should reduce this a bit. I'm also looking to replace selectize which is a big jquery plugin with ember-power-select which is much smaller.

I'll have a review of other plugins too.

**Comment by kevinansfield** [comment]
@ErisDS which size unit are you using and which method are you using to obtain them? I've just run `grunt release` locally on master as I wanted to get a before/after with the ember 2.2 PR but I'm seeing the following in the built files (sizes in `bytes` as listed by `ls -l`):

|   ghost.js   | ghost.min.js |   vendor.js  | vendor.min.js |
| ------------:| ------------:| ------------:| -------------:|
|   1,135,877  |    587,941   |   6,120,964  |    1,485,973  |

**Comment by ErisDS** [comment]
Lol I was being a moron and using `du` to list out recursive sizes and forgot to switch to a sensible unit. Updated to use bytes from `ls`

**Comment by kevinansfield** [comment]
Hmm, the jump from Ember 1.13.x to 2.2.x didn't result in as big a drop as I was expecting:

| version   |   ghost.js   | ghost.min.js |   vendor.js  | vendor.min.js |
| --------- | ------------:| ------------:| ------------:| -------------:|
| master    |   1,135,877  |    587,941   |   6,120,964  |    1,485,973  |
| ember 2.2 |   1,159,226  |    599,591   |   5,852,743  |    1,425,220  |

**Comment by acburdine** [comment]
Just an update at the filesizes we're looking at right now (with some of the dependency updates):

| version | ghost.js | ghost.min.js | vendor.js | vendor.min.js |
|---------| -----------:|-------------:|-----------:|----------------:|
| master | 1,300,999 | 672,610 | 6,367,308 | 1,621,218 |

I suspect once jquery-ui is removed that will change somewhat, but just so we know that some of the dependencies we've added have increased the dependency size a decent amount.

**Comment by ErisDS** [comment]
Other than jQuery UI - do we know who the worst offenders are?

**Comment by acburdine** [comment]
Here's some testing I did just to check what large libraries we have.

| | ghost.js | ghost.min.js | vendor.js | vendor.min.js |
|--------|---------:|----------:|---------:|---------:|
| without jqueryui / touch-punch | same | same | 5,891,634 | 1,380,428 |
| without ember-cli-selectize | 1,300,746 | 672,466 | 6,238,796 | 1,566,488 |
| without codemirror | same | same | 5,941,902 | 1,426,439 |
| without all of them | 1,300,746 | 672,466 | 5,337,716 | 1,130,915 |

So jQuery UI is definitely the largest one. CodeMirror is second largest, and ember-cli-selectize is third. I also took a look at the image-uploading library but that one's not large.

Another interesting thing happened when I removed ember-cli-mirage -> by itself that caused over 1MB drop in the `vendor.js` filesize - down to about 5,000,000 bytes. However, `vendor.min.js` was the same size -> because ember-cli-mirage loads a lot of dependencies for testing / development purposes this makes sense.

So honestly, I believe if we focus on shrinking the ghost.min.js and vendor.min.js size as much as we can that would probably be better in the long run than trying to shrink the full size file. After all, the min is what gets used in production.

I did have a look at that editor linked in slack => just a note though it uses contenteditable and thus could be subject to weird browser behavior.

**Comment by kevinansfield** [comment]
I think with CodeMirror we could unbundle it from the core files and load it only when the Code Injection screen is viewed for the first time. I'm doing that in the CodeMirror mobiledoc card where it's working well, I can extract the relevant code for use in the Code Injection screen.

**Comment by ErisDS** [comment]
I cut a release of 0.7.9, and it clocked in like this:

| version | ghost.js | ghost.min.js | vendor.js | vendor.min.js |
|---------| -----------:|-------------:|-----------:|----------------:|
| master | 1,304,362 | 1,276,296 | 7,076,525 | 4,759,106 |

I'm looking at the minified files and they don't appear to be minified at all = there are comments and proper spacing :disappointed:

**Comment by ErisDS** [comment]
This issue is 18months old. We haven't really had complaints about the size of the download. I definitely think we should aim to keep it around 5mb unless we're adding major new features, but I don't think there is really anything we can do to majorly. Even getting rid of codemirror would only be fractional and probably not worth the effort.

The main problem is the 8MB uncompressed vendor.js file, which I'm not sure we can reduce without removing dependencies that we rely on.

Closing for now.

**Comment by kevinansfield** [comment]
Removing the development assets via #8890 results in the following sizes:

Ghost-1.2.0.zip: **2,393,446**

| ghost.js | ghost.min.js | vendor.js | vendor.min.js |
| --: | --: | --: | --: |
| 0 | 766,716 | 0 | 2,305,018 |

This is a huge reduction in overall release zip filesize. There is still quite a bit scope for reducing the Ghost-Admin asset sizes but I think we can open separate issues for that as optimisation opportunities are discovered and addressed.

**Comment by kirrg001** [comment]
Re-opening because of #8809. This PR will reduce the build, because we no longer build the development assets, but keep the functionality of running the release build in development mode.

**Comment by kirrg001** [comment]
Closed via #8809.
