### ISSUE TITLE
There is no user with that email address.

### ISSUE THREAD

**Issue by Alucardology** [TryGhost/Ghost#6176]
I logged into example.com/ghost/ and put my email address and password in, it returned me with "There is no user with that email address." 

By checking the SQLite3 database, I'm certain that the email address and password I have entered is correct, and it says the user is "active." I was logged in yesterday before I went to sleep, and I did nothing to my blog and my server before I encountered this problem this morning. Does anyone have any idea how to fix it?

---

On the login page, the browser returned "example.com/ghost/api/v0.1/authentication/token 404 Not Found."

**Comment by ErisDS** [comment]
Hi @Alucardology this really sounds like a support issue, rather than a bug in the software. My best guess would be that an app or server restart happened and switched the mode / env of your blog from production to development. If you need more help, please use the #help channel on [slack](https://ghost.org/slack).

I'll reopen this if it is found that there is a reproducible bug.
