### ISSUE TITLE
Bug:Number Listing

### ISSUE THREAD

**Issue by wakaouzool** [TryGhost/Ghost#6196]
### Issue Summary
When we implement to local site, we create a post, and the right side of page will automatically update what we type into the left side area. The number listing is synchronise when we type 1. 2. 3., and the right side area will show 1. 2. 3. , but when we changed to 1. 2. 3. or 4. 2. 5. , the right side area still show 1. 2. 3., and it doesn't change even we upload the post.
### Steps to Reproduce

1. This is the first step
We create a post or update an existing post. We type a number list, like 1. 2. 3. and the right side for preview is also showing 1. 2. 3. number listing, but we changed to 1. 2. 2., the right side still show 1. 2. 3.
This is a bug because...
it should be changed to 1. 2. 2. after we modify it.
### Technical details

* Ghost Version: master - latest commit:  INSERT COMMIT REF
* Client OS: Mac OS El Capiton, Ubuntu 14.0.4
* Server OS: Mac OS El Capiton, Ubuntu 14.0.4
* Node Version: v 0.10.40
* Browser: Chrome 47.0.2526.73 (64-bit) Firefox 42.0
* Database: None (Install Ghost include)
<img width="1680" alt="defect001" src="https://cloud.githubusercontent.com/assets/8571399/11708037/c496b176-9ebf-11e5-97eb-0887a4a1953f.png">

**Comment by ErisDS** [comment]
Hi @wakaouzool, thanks for the detailed report. This is not a bug, it is expected behaviour. 

The markdown for a numbered list (when you type 1., 2. etc) translates your list items into the HTML for an ordered list. HTML then outputs a number for each item, starting at 1 and incrementing each time. For most use cases this is not only expected but desired behaviour, as it means you don't have to worry about getting the numbers right in a long list, you can just type 1. 1. 1. if you prefer.

To write a list of numbers which are not correctly ordered, you would need to break out from markdown. You can do this in a couple of ways e.g. typing `1)` or `1-` instead of `1.`. Alternatively, if you want your numbers to beheadings typing `### 1.` will give you a level 3 heading and won't change your numbers.

I hope this helps. If you have more questions about markdown, please visit the #help channel on [slack](https://ghost.org/slack).
