### ISSUE TITLE
URL field displayed twice for image upload with fileStorage:false

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6224]
Steps to reproduce:

1. Change your `config.js` so that you have `fileStorage: false`
2. Click to edit the blog logo/cover image
3. Add and save an image if you don't already have one
4. Click to edit the image again if needed then click the delete icon
5. Click to focus the URL input
6. The URL input will be be duplicated

This only happens after deleting an existing image, there is no duplication when adding an image to a previously empty field.

![double-image-url-field](https://cloud.githubusercontent.com/assets/415/11810727/2205977a-a328-11e5-8038-6b85a1e087fb.gif)

**Comment by kevinkucharczyk** [comment]
A similar thing happens (under the same conditions, meaning `fileStorage: false`) in the post image editor:

![ghost](https://cloud.githubusercontent.com/assets/3127419/11850259/7db1b86a-a42c-11e5-932d-8a7ed48851bf.gif)

I think I have a fix ready - will open a PR soon. The problem seems to be some uploader init calls being called multiple times.
