### ISSUE TITLE
Bug: npm-shrinkwrap.json contains devDependencies 

### ISSUE THREAD

**Issue by petrosagg** [TryGhost/Ghost#6263]
### Steps to Reproduce

1. checkout the stable branch
2. run `npm install --production`

npm will ignore the `--production` flag and install the modules specified in `npm-shrinkwrap.json` which include `devDependencies`. By default `npm shrinkwrap` excludes `devDependencies`[1] unless `--dev` is set.

Since the stable branch is intended for production use these dependencies should be exluded.

[1] https://docs.npmjs.com/cli/shrinkwrap#other-notes

### Technical details

* Ghost Version: stable - latest commit:  4bcdd810beee9b8dad6e904ee39190d9a6e602b1
* Server OS: Ubuntu 14.04.3 LTS - 3.13.0-36-generic #63-Ubuntu
* Node Version: v0.10.40
* npm version: 1.4.28

**Comment by ErisDS** [comment]
Hi @petrosagg, did you try running Ghost from the stable branch?

The stable branch contains source code, which needs to be built in order to run. The dev dependencies like grunt are needed to complete those build tasks - therefore they are required and should not be excluded.

If you want a version of Ghost that comes pre-built for production and doesn't need the dev dependencies, then both the npm package and zip files are pre-built.

**Comment by petrosagg** [comment]
@ErisDS hm I see what you mean. I missed this because I was trying to re-install node_modules in a previously built folder. Thanks for the quick response
