### ISSUE TITLE
#get helper and API can't filter two-words tags

### ISSUE THREAD

**Issue by toblerone1963** [TryGhost/Ghost#6275]
Hi,

I tried to get a list of posts with a specific tag in two words using those methods:

`{{#get "posts" filter: "tag:Getting Started"}}`

and

`$.get(ghost.url.api('posts', {filter: 'tag:Getting Started}))`

Neither works.

Cheers

**Comment by kevinansfield** [comment]
Hi @toblerone1963,

When referencing tags (or other items) using the `filter` parameter you need to use the `slug` rather than the `name` as slug is the unique reference and has a format that is API and URL compatible. For example if you have not changed the "Getting Started" tag from the default dummy data then you could use `{{#get "posts" filter="tag:getting-started"}}`.

If you need more help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. You can get help & support there from the Ghost community, which we're not able to do here on the GitHub bug tracker.

**Comment by toblerone1963** [comment]
Yeah ! It's working ! Many thanks

Cosme Buxin
06 95 39 68 85

2015-12-30 16:58 GMT+01:00 Kevin Ansfield <notifications@github.com>:
