### ISSUE TITLE
buildAboutPage task fail

### ISSUE THREAD

**Issue by huguangju** [TryGhost/Ghost#6276]
Run `grunt init`, when running "buildAboutPage" task, throw a error message:  
```shell
Running "buildAboutPage" task
Fatal error: Cannot read property 'headers' of undefined
```

* Ghost Version: master (latest commit: 000d3a100f3e830e6b9dde993e23151748e15ac9)
* Client OS: Mac OS X 10.10.5
* Server OS: Mac OS X 10.10.5
* Node Version: 0.10.41
* Browser: Chrome 47.0.2526.106 (64-bit)
* Database: SQLite

**Comment by ErisDS** [comment]
Hi @huguangju is this consistently reproducible? I am unable to reproduce.

The error message means there was no response from the GitHub API, so it was probably a temporary issue or perhaps a permanent issue with your particular network. You can copy the `core/client/app/templates/-contributors.hbs` from the 0.7.4 zip file in order to bypass the issue.

Going to close this for now as a network issue, will reopen if a way to reproduce without network issues is found.
