### ISSUE TITLE
[Improve] Sitemap : differentiate update frequency for posts/pages/tags/authors

### ISSUE THREAD

**Issue by Faber73** [TryGhost/Ghost#6283]
core/server/data/xml/sitemap/base-generator.js support one frequency settings for all types. For a good optimization need to set hours for last 24h posts, daily for oldest posts, daily for tags, weekly for all another.

thank you

**Comment by ErisDS** [comment]
Hi @Faber73 can you provide some explanation of why your suggestion makes sense? What is this based on? Do you have reference material?

**Comment by Faber73** [comment]
I don't have documentation about it except many experience in journal and news website, where need to have a fast search engines index.

When you set last 24h to update hours you will have spiders that come to check update often. If you set all items weekly, you must to send your sitemap manually every time.

If you check the most wordpress sitemap plugins, you will look that they optimize the sitemap like this.


sorry for my poor english, hope you understand :-)

**Comment by ErisDS** [comment]
I do understand, however we don't generally make changes to things like this without proper research & reference material to use to base the changes upon, I'm sure there's room for improvement. If you have time to put something together, that'd be great, but otherwise I recommend putting it on the wishlist as something someone else could investigate improving.

Gonna close this for now, will reopen if someone has something concrete we can work from.

**Comment by Faber73** [comment]
Yes, I understand. But in anycase have the opportunity to change the freq for type it's a right think :-)

**Comment by Faber73** [comment]
Dirty, but better of nothing :-)

```
        var oneday = 24 * 60 * 60;
        var oneweek = 7 * 24 * 60 * 60;

        var lastdate = new Date(datum.updated_at).getTime() / 1000;
        var nowdate = Math.floor(Date.now() / 1000)
        var diffdate = nowdate - lastdate;

        if (diffdate < oneday) { CHANGE_FREQ = 'Hourly'; } else { CHANGE_FREQ = 'Daily'; }
        if (diffdate > oneweek) { CHANGE_FREQ = 'Weekly'; }

```
