### ISSUE TITLE
Blog post completely lost after editing it

### ISSUE THREAD

**Issue by guillaumew** [TryGhost/Ghost#6288]
- In a first tab create a new article.
- In a second tab view the list of articles (admin view).
- Write and publish the article on the first tab.
- Edit the article of the second tab (you don't even have to save or anything)

The whole article has been erased with no mean to restore it.

**Comment by ErisDS** [comment]
Hi @guillaumew, firstly, I realise this is a very, very frustrating issue. 

I am not sure I 100% follow the steps you're describing. If you are on the content view which shows the list of posts, and open a post, it should open with the latest content that was saved on the server. There was an old bug where this didn't happen but this was fixed several versions ago. What version of Ghost are you on?

If you have the same post open in 2 tabs, edit it and publish it in one, and then go back to the pre-published version in another tab, then yes, this issue will occur. This bug is being tracked with a fix in progress in issue #5599.

**Comment by guillaumew** [comment]
We're using Ghost v0.6.4.
I see we're not up to date. We'll update.

Thanks for your quick answer.
