### ISSUE TITLE
Allow access of private blog RSS with password

### ISSUE THREAD

**Issue by philipithomas** [TryGhost/Ghost#6306]
**Motivating Problem**: We have a private blog for our company that is password-protected. I'd like to have new posts go to our slack channel using Zapier. 

**Current behavior**: `blog.com/rss` 404s on a private blog

**Proposed behavior**: `blog.com/rss` 404s; `blog.com/rss?password=abc123` succeeds. 

There are some obvious security issues, including that the plaintext password would show up in HTTP logs, but I think that password-protected blogs are not supposed to be high-security.

**Comment by nuclearpengy** [comment]
I don't think this approach is ideal.

Consider this: Parsing a user's password into a URL will show in their history and can be subject to a whole bunch of other issues if they're on a work computer that logs browser history or on a shared computer such as an internet cafe.

I feel secure blogs should be secure, whether it's being used by a whistle blower, journalist or a family who doesn't want the photos of their children to be publicly accessible. I don't feel we should build insecurity into core.

If you would like to have RSS available on a password protected blog consider implementing it the way Ghost did when they launched their internal blog, using a VPN with basic HTTP auth.

Here's a thread about it: https://twitter.com/JohnONolan/status/558036097847271425

Also note, ideas and feature requests should be submitted on this URL: https://ideas.ghost.org/
You can also browse and vote on other ideas that may be similar to this one.

**Comment by philipithomas** [comment]
@nuclearpengy That thread is interesting, but it's not at the application layer. We're using  Ghost Pro and wish to avoid setting up a server for this

**Comment by nuclearpengy** [comment]
Ah ok. Yeah, I'm on Ghost pro too. :)

**Comment by nuclearpengy** [comment]
This issue is related: #6290

**Comment by halfdan** [comment]
More realistically, I think, Zapier should at some point in the future integrate with the Ghost API (once stable) and import from there. This way Ghost admins can authorise Zapier to read posts from the API without ever giving away the password in plain text.

> but I think that password-protected blogs are not supposed to be high-security.

I disagree here. Password protected blogs should protect the user content and not leak it so easily.

**Comment by ErisDS** [comment]
I'm totally onboard with the frustration of the underlying problem here, but not with the solution. Your problem statement is:

> We have a private blog for our company that is password-protected. I'd like to have new posts go to our slack channel.

And then your feature request is for RSS to work if you provide the password in the url.. sure it's one solution, but it's far from the best IMO! RSS isn't something that can easily be secured, HTTP basic auth has the same problems as your proposal. So let's move away from the old tech.

I'm really surprised this one hasn't got more votes: http://ideas.ghost.org/forums/285309-wishlist/suggestions/11179533-webhook-slack-notifications-on-new-posts. Would love to see Zapier & IFTTT on there too :)

Current thinking on these is that we may add one or two useful integrations to core, and split them out into apps later. So knowing which ones are what people want most would be great -> go vote :grin:
