### ISSUE TITLE
navigation's `current` property not working as expected

### ISSUE THREAD

**Issue by macool** [TryGhost/Ghost#6432]
our issue started when I realised we set the `current` state only for root (`/`) path. As in this site: http://cafrilosa.com

and I did some digging and realised the `current` property here https://github.com/TryGhost/Ghost/blob/adc8f9989378a7e9b6b7e7976707a9648a0d9815/core/server/helpers/navigation.js#L57 is not being set for paths as they differ as such: `'/page' != '/page/'`

so I submitted a PR for our own repository which sets the `current` property using a regexp rather than comparing exact strings: https://github.com/noggalito/cafrilosa/pull/42

now I realise using a regexp may not be the best solution as we may end up having unexpected behaviour as well, and would be happy to provide help to address this

**Comment by acburdine** [comment]
duplicate of #6424 I think?

**Comment by ErisDS** [comment]
@macool Can you please provide a bit more information? It's not clear whether you're talking about the bug we just fixed in 0.7.6 (https://github.com/TryGhost/Ghost/issues/6422) or a new bug.

There is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that should give you a good idea what sorts of info to include.

**Comment by macool** [comment]
@acburdine @ErisDS yeah, seems it's a duplicate from #6422. Sorry for that, I was looking for something similar but didn't see that one
