### ISSUE TITLE
nodejs LTS update to 4.3

### ISSUE THREAD

**Issue by zxcso** [TryGhost/Ghost#6473]
Now the latest nodejs LTS version is 4.3, but ghost only recognize 4.2 and will show ERROR: Unsupported version of Node when starting, though there is a way to omit the version check, but I think it's better to add support for 4.3 to prevent confusing users.

**Comment by zxcso** [comment]
2016-02-09, Version 4.3.0 'Argon' (LTS), @jasnell
Note that this release includes a non-backward compatible change to address a security issue. This change increases the version of the LTS v4.x line to v4.3.0. **There will be no further updates to v4.2.x.**

**Comment by nevi-me** [comment]
Why are we pinning Nodejs versions? I run 5.x in development, and I'm on 4.3.0 in production. Something made Ghost stop working 2 weeks ago, one of its dependencies, haven't tracked it down yet.

Now when trying to reinstall or update to 0.7.6 I get an unsupported engine problem.

**Comment by naoyak** [comment]
@nevi-me see discussion in #6477. Understandably the team didn't foresee that Node would do a version bump for the 4.x LTS line, I guess. Personally I would prefer a warning over a hard failure when running Ghost on an unsupported Node version, but certainly I see the logic from a support POV.

**Comment by nevi-me** [comment]
Thanks @naoyak but I'm still left confused. Does it mean that I can't run Ghost if I'm on 4.3?

I see @ErisDS 's argument, but from my understanding in following the LTS discussions, there were still possibilities of SEMVER-MINOR although that wasn't going to be encouraged.

I've had to turn off my Ghost blog because it's coupled with my Express app, and I'd rather have the blog down than my whole site.

As #6477 hasn't been accepted, would my only option be to fork and add support for my engine(s) as I also indicated that I use 5.x? If that approach of mine's unstable I'll maybe look for an alternative, or write the Markdown files manually as I used to do before using Ghost.

**Comment by naoyak** [comment]
I was going to fix #6477 per feedback from @ErisDS (i.e. preserve 4.2 support) but I screwed up the commit history so closed for now, hopefully submit a new PR later.

You can always set 'GHOST_NODE_VERSION_CHECK=false', which is what I do in development and on my production instance on Heroku running Node 5.

**Comment by nevi-me** [comment]
Alright, let me try that. I'll add it to my environment vars if it works well

**Comment by nevi-me** [comment]
Thanks, installed with the flag.
