### ISSUE TITLE
lodash@2.4.2 deprecated. Shows warning in installation. #6474

### ISSUE THREAD

**Issue by yash14123** [TryGhost/Ghost#6474]
Command : sudo npm install -g grunt-cli
This shows the error:  
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

package.json needs to be updated (I guess).

**Comment by ErisDS** [comment]
Ghost uses lodash v3. 

This warning (which is only a warning) comes from the `grunt` package, through their dependency on findup-sync, and their dependency. From the looks of it there's a new version of grunt coming which ought to remove the warning. 

This only happens when installing the dev dependencies to build Ghost from source.
