### ISSUE TITLE
Pagination is not working on post.hbs

### ISSUE THREAD

**Issue by nag-uf** [TryGhost/Ghost#6475]
Pagination is working on index.hbs and not working on post.hbs

**Comment by ErisDS** [comment]
This is working as expected. There is [no pagination info available on post.hbs](http://themes.ghost.org/docs/context-overview#section-context-table) because there is only one post available.

If you want to add links to next and previous posts there are [specific helpers](http://themes.ghost.org/docs/prev_next_post) for this.
