### ISSUE TITLE
Add a way to go back to the correct page of the index from a post page

### ISSUE THREAD

**Issue by dubeg** [TryGhost/Ghost#6497]
Case 1: 
  - user browses the index, goes on post X from page Y.
  - Insert link "Go Back" that links to page Y of the index.

Case 2:
  - user goes on post X from somewhere else (user typed directly in the address bar, or from an external link)
  - Either hide the link "Go Back", or insert a link to the first page of the index.

I had a couple of solutions, none looking too good.

## Solution 1: document.referrer  
Cons

- Unreliable
- Should probably not be used at all

## Solution 2: history.back()
Cons

- If the post page contains links to IDs (ex: on section titles) in the post, and the user uses them, the history gets filled with them. Therefore, when clicking on the "Go Back" link in that case, it would simply go back to the last header. That would be annoying.

## Solution 3: sessionStorage

The idea here is to store locally the page number (or simply the URL of the paginated index) as the user browses the index. When accessing the post page, a script would have access to the last page of the index that the user went on.

The sessionStorage is different for each page, so there wouldn't be issues between 2 tabs. However, there are two cases where it could be problematic:

1. When the user goes "back" using the link, the post could now be on a different page, pushed away by recently published posts.

2. The user browses the index, then browses somewhere else, then access a post page via an external source. The stored page number/URL would then probably be incorrect.

## Solution 4: using the API
I still haven't checked it, but maybe you would know if this is feasible, and I would like some thoughts on this. In the meantime, I'll be looking at it.

**Comment by ErisDS** [comment]
Hi @dubeg, 

I do not believe this is a common use case. It is normal to link to the home page [like this](https://github.com/TryGhost/Blog/blob/master/post.hbs#L16), and otherwise let users use their own 'back' button. Pagination is a changeable thing - if a new post is published whilst the post is being read, the page that the post is displayed upon could change. 

To request a feature for Ghost you can add your idea (or vote on a similar one) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)

If you want to chat about building themes, I recommend joining our [slack](https://ghost.org/slack) team, where you'll find both a #themes channel and a general #help channel.

**Comment by halfdan** [comment]
I agree with @ErisDS in that it is best to let the user use the back button of the browser. What you are trying to build is the exact behaviour provided by every browser.

**Comment by dubeg** [comment]
@halfdan I agree now. 

When I started thinking about it, I thought the Back button of browsers was inefficient. Small, in the browser head, and may contain one or many URL fragments that leads you somewhere in the same page before going back to the index. 

But I don't think now that there's a better solution.
