### ISSUE TITLE
Theme folders are public

### ISSUE THREAD

**Issue by chrisWhyTea** [TryGhost/Ghost#6516]
Uhm hi ... I just found out that the folder of the current theme is wide open for the public ... I expected that only the assets folder would be available but not the whole theme folder here the example:
`https://dev.ghost.org/index.hbs?v=2c8cb92861` and you get the index.hbs of the current theme...
of course it would make sense if ghost would use the hbs files on client side but as far as I know they get processed on the server side ... so why make them public available ?

**Comment by ErisDS** [comment]
It was done that way because 1) there are other kinds of files that you may want to serve, e.g. just a static .html file and 2) originally the assets folder wasn't really a requirement, just a suggestion which has evolved.

However, there are certain file types we don't expect to be served from a theme, including handlebars: https://github.com/TryGhost/Ghost/blob/cdc98dce150c25e863398de8279606d5be080904/core/server/middleware/static-theme.js#L8-L8

Seems like you've found a bug in the filetype detection code.

**Comment by chrisWhyTea** [comment]
well yes the md ans json filse are served as well..

**Comment by halfdan** [comment]
Working on a fix

**Comment by chrisWhyTea** [comment]
Hmmm so its pretty much blacklisting... hmmm well it looks like i found at least a workaround for putting stuff inside the folder that i don't want to have served (less files or other file types that are not listed in the blacklist array...) just adding a dot before the folder (thankfully my IDE still shows the folder ;D) at least my local setup and the dev.blog don't serve them (tried .gitignore file and the .git folder (btw. the dev.blog said "Sorry, you've been blocked") while the local installation said 404)...
