### ISSUE TITLE
0.7.4 -> 0.7.8 Cannot read property 'getDatabaseVersion' of undefined 

### ISSUE THREAD

**Issue by iBotPeaches** [TryGhost/Ghost#6554]
### Issue Summary

During an upgrade (forgot a few), so was going from `0.7.4` to `0.7.8`. I followed the source upgrade, like usual and after starting the service. I was met with this.

```
> ghost@0.7.8 start /home/connor/ghost
> node index

ERROR: Cannot read property 'getDatabaseVersion' of undefined 
 
 TypeError: Cannot read property 'getDatabaseVersion' of undefined
    at Object.init (/home/connor/ghost/core/server/data/migration/index.js:81:22)
    at /home/connor/ghost/core/server/index.js:72:27
    at tryCatcher (/home/connor/ghost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/connor/ghost/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/connor/ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/connor/ghost/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/connor/ghost/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/connor/ghost/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/connor/ghost/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17) 
```

### Steps to Reproduce

1. Have a Centos7 box using MySQL and Ghost 0.7.4
2. Attempt upgrade to 0.7.8
3. See failure.

### Technical details:

* Ghost Version: 0.7.4 (before upgrade), 0.7.8 (during failure)
* Node Version: v4.2.6
* NPM Version: 2.14.12
* Browser/OS: n/a 
* Database: MySQL (MariaDB 10.1.11)

It looks like the current DB version is `005`. My database is `004`. So I need an upgrade I think. Either way I think this commit caused it - https://github.com/TryGhost/Ghost/commit/1ad7a91f4ddbe83bb95e26a3d3bf1d980f8a4bcf

EDIT: I downgraded back to 0.7.4 and everything is working again. I'll hold off on upgrading.

**Comment by ErisDS** [comment]
> It looks like the current DB version is 005. My database is 004. So I need an upgrade I think. Either way I think this commit caused it - 1ad7a91

The current database version is still 004 - not sure where you got 005 from?

> I followed the source upgrade, like usual

I'm not sure what this means, but the error you're reporting sounds to me like an upgrade that hasn't completed properly. Either step 3 was missed, or step 4 did not copy all files correctly: http://support.ghost.org/how-to-upgrade/#3.-delete-the-old-files

Note that there is no database or fixture migrations happening between 0.7.4 and 0.7.8.  Also, L81 of `core/server/data/migration/index.js` (the line throwing the error) runs to check if it needs to do something **every single time Ghost boots**. 

Therefore, if this was a bug, rather than an upgrade issue, everyone starting Ghost in 0.7.8 would experience it. 

To verify that the folder structure is correct after an upgrade, you can run `ls core/server/data/*` and verify that the file locations [match those in GitHub](https://github.com/TryGhost/Ghost/tree/master/core/server/data)

**Comment by pokrface** [comment]
I got this exact error when upgrading from 0.74 -> 0.78, and the problem turned out to be just what @ErisDS speculated: I didn't delete the contents of `core` before copying the new core files over to the production install. After doing an `rm -rf /myghostdirectory/core/*` and then copying the 0.78 core files to a fresh empty directory, the problem behavior ceased and my blog loaded without any problems.

**Comment by ykushch** [comment]
@pokrface solution works. Had the same issue and done exactly what proposed here.

**Comment by ErisDS** [comment]
Just to clarify: if you're not deleting `core` as part of the upgrade, then you're not upgrading properly 😉 

These is the official upgrade guide: http://support.ghost.org/how-to-upgrade/

**Comment by ykushch** [comment]
@ErisDS yep, thanks for info! I've used tutorial on digital ocean for updating ghost and it didn't work :smiley:

**Comment by ErisDS** [comment]
@ykushch you should probably let them know that!

**Comment by ykushch** [comment]
There is a solution for that with updating `core` in comments section :)

**Comment by ErisDS** [comment]
@ykushch can you link me to the documentation and I will report it - a comment is not good enough IMO 😉

**Comment by ykushch** [comment]
@ErisDS Sure thing. Here it is [digital ocean ghost update](https://www.digitalocean.com/community/tutorials/how-to-configure-and-maintain-ghost-from-the-command-line).
