### ISSUE TITLE
Bug: Adding Google Custom Search for Casper theme displays input box incorrectly due to padding in css table def

### ISSUE THREAD

**Issue by packled** [TryGhost/Ghost#6559]
### Issue Summary
Bug: Adding Google Custom Search for Casper theme displays input box incorrectly due to padding in css table definition (low priority)

### Steps to Reproduce

1. Add Google Custom Search box and you will see the input field is displayed lower than it should be.

This is a bug because...
It looks wrong

### Technical details
The issue is in screen.css for the Casper theme.
table th,
table td {
    padding: 8px;
    line-height: 20px;
    text-align: left;
    vertical-align: top;
    border-top: #EFEFEF 1px solid;
}
If the "padding: 8px" is removed, it displays correctly.

My workaround was to define a static page for the Search and then put put in a "style" with padding: 0px to override. 

This works totally fine for me so this is a very low priority issue but wanted to make you aware since people may run into this very easily.

* Ghost Version: master - latest commit:  INSERT COMMIT REF - Ghost-0.7.7
* Client OS: MacOS El Capitan and Ubuntu 14
* Server OS: MacOS El Capitan and Ubuntu 14
* Node Version: v0.12.4
* Browser: All latest versions

**Comment by ErisDS** [comment]
Hi @packled, would you mind please re-raising this on the [Casper](https://github.com/TryGhost/Casper) repository? I don't think removing `padding: 8px` from all table cells would be the correct fix, but if you can figure out a way to target the Google custom search box directly I'm sure a PR would be welcome.

**Comment by karlredman** [comment]
I'm only commenting here because the issue doesn't exist on the casper tickets and because the discussion is already here: 
Hi, I just went through this for a few hours working on a fix-ish through the odin theme -derived from casper.The problem is deffinately associated with the tables. Specifically, body {line-height: 1.75em;} and table {margin: 1.75em 0;} in screen.css are being inherited by the google widget. 

My temporary fix was to comment out those lines for now until I have the time to look further. If I get the chance I'll open a ticket or submit a patch to [casper](https://github.com/TryGhost/Casper).

**Comment by jmayereup** [comment]
From within Google Site Search, I changed my search box theme to minimalist and then copied the code. It seems work fine.
