### ISSUE TITLE
Bug: Sometimes Deleted Posts Don't Get Removed from Search

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#6562]
### Issue Summary

Sometimes when you delete a post, that post doesn't get removed from the immediate search results. It seems to get removed after another page load, but if you go right back into searching, then it may still show the post there

![delete post stays in search](https://cloud.githubusercontent.com/assets/4715098/13325378/6d1d6ae8-db96-11e5-9b2b-a2923488a53c.gif)

### Steps to Reproduce

1. Search for a post and open it
2. Delete that post
3. Search for it again in the search, it will still be there

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 0.10.38
* Browser/OS: Chrome Mac
* Database: SQLite

**Comment by kevinansfield** [comment]
That is possibly expected: the search input currently has a 10 second content expiry, so if you click on the search input (which loads all of the search data) and then you delete a post and the click back in the search bar within 10 seconds you won't see refreshed results. 

It's a bit of an arbitrary time limit designed to reduce the load on the backend and your net connection as right now search is very naive and simply loads/refreshes _all_ of the data up-front. Once we have proper server-side full search capabilities then the search results will be as real-time as possible.

If however you are seeing the old post still there after some time > ~10 seconds then that definitely points to a bug.

**Comment by franciscop** [comment]
I would love to take a look at this (first time contributing to Ghost), it seems easy enough to fix and a good way to get started. Would just deleting the search cache when deleting a post be enough?

**Comment by kevinansfield** [comment]
@franciscop Thank you for the offer but it would add a fair bit of complexity to something that's due to be replaced.

The search component is isolated and holds the search cache internally, in order for anything that manipulates post/tag/user objects to invalidate the cache then the search system would need to be extracted out into a service, injected into the models, have events fired at the correct time, and so on, all to avoid a 10-second delay of possibly-not-up-to-date results.

Once server-side search is implemented the client-side cache will disappear as it will work directly with the result set returned from the server. The server would then also be responsible for invalidating it's internal search cache (if it has one) and is in a much better position to do so as it will be able to handle events from all concurrent users whereas the client will only know about changes the current user has made.

**Comment by dbalders** [comment]
The 10 seconds definitely makes sense. I thought it was just another page load that was actually making it refresh. Go ahead and close if you would like.
