### ISSUE TITLE
Bad Url in email

### ISSUE THREAD

**Issue by moafred** [TryGhost/Ghost#6598]
### Issue Summary

In email (reset password and invitation) i got "email.www.domain.com" instead of "blog.domain.com" configured in config.js

However It's seems that like the code use config.url:
https://github.com/TryGhost/Ghost/blob/411dd470022ba6541595074c7b465219b24cc25a/core/server/api/authentication.js#L169

### Steps to Reproduce

Send reset password email

### Technical details:

* Ghost Version: 0.7.8
* Node Version: v0.12.11
* Browser/OS:  Debian 8
* Database: MySQL

**Comment by ErisDS** [comment]
Hi @moafred, sorry to hear you're having trouble. This sounds like you're using a mail service which edits certain urls in the email - Mailgun can be configured to do this, I believe.

It's definitely an issue with your setup, rather than a bug in Ghost (else we'd have tonnes of people reporting this), so I'm gonna close this. If you need more help tracking down the issue, I recommend visiting the #help channel in [slack](https://ghost.org/slack).
