### ISSUE TITLE
Password change does not verify current password

### ISSUE THREAD

**Issue by namilica** [TryGhost/Ghost#6620]
### Issue Summary

Account password can be changed in the profile page without giving the current password.

### Steps to Reproduce

1. Login and go to profile page
2. Put new password without giving the current one
3. Change password

I believe it should require the previous password.

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 4.4.0
* Browser/OS: Firefox/Linux
* Database: sqlite3

**Comment by ErisDS** [comment]
Nice catch! 

Just to clarify the issue:

- When you visit your own profile page in the admin, there is an 'old password' field. If you visit someone else's page for whom you have permissions to update their profile, you won't see that field.
- If you fill out the current password & confirm password boxes, but leave the 'old password' field blank, the form incorrectly validates, submits, and works. This should fail the validation checks.

This is tricky because, being on your own profile page is the only time at which the old password is required. If you use the reset password flow, or edit someone else's password, the old password is not required.
