### ISSUE TITLE
Refactor Token tables

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost#6626]
With the upcoming db version 005 we have the opportunity to clean up access and refresh token tables.

I would like to merge access tokens and refresh tokens into one table and identify the the token type using a field that holds an id (1 = access token, 2 = refresh token). This split was token over from the OAuth examples and in hindsight makes no sense at all :-(.

As PR #6496 made clear that we need to know which refresh token issued an access token it'll also be   necessary to add an internal relationship between tokens.

Proposed token table structure:

| id | token | user_id | client_id | type | issued_by | expires |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | `<token>` | 1 | 1 | 2 |  | `<timestamp>` |
| 2 | `<token>` | 1 | 1 | 1 |  | `<timestamp>` |
| 3 | `<token>` | 1 | 1 | 1 | 2 | `<timestamp>` |

Token 1: refresh token, issued from username/password
Token 2: access token, issued from username/password
Token 3: access token, issued by token 1

**Comment by jaswilli** [comment]
I wonder if it wouldn't be simpler to leave them in separate tables and just use the standard bookshelf one-to-many pattern?

**Comment by kirrg001** [comment]
From #7432

The main reason for this issue is to connect the AT and RT.
I thought about this a little more. Let's start with a valid future case.

Example case: 
- you change your password in Ghost
- the request to change the password only transmits the access token
- so Ghost wants to delete all tokens related to this user (AT + RT)
- if we don't know the related refresh token to the access token, who changed the password, we would logout the user

**This example case is only valid for password authentication!**

For remote authentication, the password change doesn't happen in Ghost directly. It happens at `my.ghost.org`. Even if the remote authentication service would tell Ghost that the password has changed, we won't be able to detect which session need's to be deleted?Ghost knows the remote access token, but it's stored in the user table. So it's only one remote token for all sessions of a user. The current state is that Ghost doesn't know if a password change happens. As this is not implemented, we need to think about this case in the future if we add the functionality to kill sessions if a password change happens.

Anyway, I would still add the `issued_by` column, but i wouldn't add a hard relation between RT and AT table. It's just a column, which remembers the identifier of the RT.

**Comment by sebgie** [comment]
> Anyway, I would still add the issued_by column, but i wouldn't add a hard relation between RT and AT table. It's just a column, which remembers the identifier of the RT.

This issue is from a time where there was no centralized auth service. :+1:
