### ISSUE TITLE
Error 231 (invalid Node version) with Node 4.4.0 and Ghost 0.7.5

### ISSUE THREAD

**Issue by jgentes** [TryGhost/Ghost#6630]
This seems to work fine locally and on CircleCi (my test environment) but on Heroku I'm seeing this:

```
2599 error node v4.4.0
2600 error npm  v2.14.20
2601 error code ELIFECYCLE
2602 error ghost@0.7.5 preinstall: `npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`
2602 error Exit status 231
```

I've even tried `GHOST_NODE_VERSION_CHECK=false` to no avail.

I've tried building without cache (`NODE_MODULES_CACHE=false`) and still no dice.

Is there a simple way to test that startup-check.js script from the command line?

Thanks,

-James

**Comment by ErisDS** [comment]
Hi @jgentes, sorry to hear you're having trouble. 

You can execute the `startup-check.js` script from the command line using the code output in the error message: 

`npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`

Or just

`node -e "require('./core/server/utils/startup-check.js').nodeVersion()"`

However, the problem here is that you need to upgrade to the latest version of Ghost (0.7.8). As mentioned in the [release notes](https://github.com/TryGhost/Ghost/releases/tag/0.7.8) prior to 0.7.8 Ghost only supported node v4.2 as we were under the impression that the LTS would stay at that minor version & so that's what our support was tied to. We fixed this to be 4.x when 4.3 came out.

Hopefully this should get you on your way. If you need any more help, please swing by our [slack](https://ghost.org/slack) team where you'll find our community :smile:

**Comment by jgentes** [comment]
Thanks Hannah, I appreciate the quick response and all your effort to make Ghost awesome.
