### ISSUE TITLE
Refactor uploaders and replace jquery-file-upload in gh-profile-image

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6661]
Following on from #6651 we now only have one place still using the `jquery-file-upload` dependency and that's `gh-profile-image`. It would be good to emberify this so that we can remove the dependency and further reduce our JS payload.

`gh-profile-image`'s file uploading requirements are pretty minimal and not too different to those introduced in #6651. It would be nice to abstract some of the shared details out to improve re-use in the future.

**Comment by schneidmaster** [comment]
Hey @kevinansfield is this issue already being worked on? Have been meaning to get back into contributing to Ghost, wouldn't mind taking it on 😄

**Comment by kevinansfield** [comment]
@schneidmaster it's not being worked on yet so definitely available to pick up if you want to work on it!

We now have three components in the new uploader style:

- `gh-image-uploader`
- `gh-image-uploader-with-preview`
- `gh-file-uploader`

What I would like to see is the common functionality pulled out and the re-used parts made into composable components. I think once we have those primitives to work with changing `gh-profile-image`  will be relatively straight forward and we can also replace `gh-file-upload` that's currently used on the labs page.

**Comment by schneidmaster** [comment]
Cool, I'll have a look in the next few days and see what I can do 👍

**Comment by schneidmaster** [comment]
Update -- I think I've got a good handle on this now (had to brush up on Ember and read a bunch of source). I'm going to refactor so that:

* `gh-file-uploader` is a basic component to upload a file to a given destination URL, with progress and success/failure/finish actions
* `gh-image-uploader` uses `gh-file-uploader` to accept uploads, allows "uploads" via a link, and shows a preview of the image (thus allowing removal of `gh-image-uploader-with-preview` -- there is no place where we are using `gh-image-uploader` without the preview so it seems unnecessary to have two components)
* `gh-profile-image` uses `gh-file-uploader` to accept uploads, and uses the Gravatar image for the user's email or falls back to the default Ghost user silhouette image if no Gravater image can be found
* `gh-file-upload` is removed and replaced by `gh-file-uploader`

**Comment by kevinansfield** [comment]
> there is no place where we are using gh-image-uploader without the preview so it seems unnecessary to have two components)

There are situations (such as in modals, where you'll see `gh-image-uploader` used) where having the preview inside the component causes problems when typing link text because as soon as a character is entered the component switches to a preview as it's value is updated externally. If you can workaround that then 👍
