### ISSUE TITLE
Ghost as NPM: Rewrite Router

### ISSUE THREAD

**Issue by kirkas** [TryGhost/Ghost#6677]
I'm using Ghost for my new blog. I use it as a [NPM Module](https://github.com/TryGhost/Ghost/wiki/Using-Ghost-as-an-npm-module).

My issue is that I want to change the way router works.

e.g: I want `blog.com/tag/something` to actually read as `blog.com/collection/something`.

Can I do that through `ghostServer.rootApp`?

Index.js:

    var ghost = require('ghost'),
        express = require('express'),
        path = require('path'),
        parentApp = express();
    
    ghost({
      config: path.join(__dirname, 'config.js')
    }).then(function (ghostServer) {
        parentApp.use(ghostServer.config.paths.subdir, ghostServer.rootApp);
        ghostServer.start(parentApp);
    });

Spec:

- Ghost Version: 0.7.8
- Node Version: v4.4.2
- NPM Version: 3.8.5
- Browser/OS: All
- Database: MySql

**Comment by JanSichula** [comment]
Hello @kirkas,

my plan is to implement exactly same modification as you have described for our new church blog. Now I was able to find a walk-through at https://andy.stanton.is/writing/about/custom-post-tag-paths-with-ghost/ which is targeted at somewhat old Ghost version 0.4.2. I did not have enough time to try to implement it yet. Also be aware that the routing code in 0.7.8 might have been refactored in various ways since April 2014 which is the date for that article. Should you succeed in your effort, please share about the steps and results with community here at this thread.

One Bible quote for a contemplation:

"For God so loved the world, that He gave His only begotten Son, that whoever believes in Him shall not perish, but have eternal life.” John 3:16

**Comment by ErisDS** [comment]
The linked blog post is out of date, this is actually much easier to do now. These strings now exist as simple configuration inside of Ghost, but is setup so that it cannot currently be overridden. This is a stop-gap as we haven't decided how to make this configuration available just yet.

You can change the word `tag` in this [configuration block](https://github.com/TryGhost/Ghost/blob/2386a69f9db78908ebd8f53c166fb7a25b58ad00/core/server/config/index.js#L188) and everything should *just work*. If you run into issues with it not being reflected everywhere let us know. You will need to reapply this change after each upgrade until such time as an official way to configure this is made available.

If you need more help or have additional questions about how Ghost works, please swing by our [slack team](https://ghost.org/slack) and post in the #help channel, where the community is on hand to answer questions.

*Note: Off-topic content was removed from this thread by me. This is a place where [everyone is welcome](https://ghost.org/about/guidelines/) to participate in discussions, but please keep discussions to the topic at hand.*

**Comment by kirkas** [comment]
Great, thanks for the tips!
