### ISSUE TITLE
Can close the ghost editor preview page, use the shortcut key (Alt+/) to switch?

### ISSUE THREAD

**Issue by jet10000** [TryGhost/Ghost#6751]
Can close the ghost editor preview page, use the shortcut key (Alt+/) to switch?

http://www.typora.io/

**Comment by ErisDS** [comment]
Sorry, @jet10000 it's not at all clear here what you mean. Are you reporting a bug or asking a question or requesting a feature?

 Depending on which one - here's what to do:
- to ask some questions and get some help with Ghost, please come visit the #help channel in our [slack](https://ghost.org/slack) team where the community is on hand to provide support
- to ask for a feature, you can make a request on our [wishlist](http://ideas.ghost.org), but please provide plenty of detail so that what you're asking for is clear!
- finally if you're raising a bug, please reply including all the details listed in the new issue template (hit the "new issue" button to see it again) and we'll reopen the issue
