### ISSUE TITLE
 cannot run in wd %s %s (wd=%s) ghost@0.7.9 npm install semver 

### ISSUE THREAD

**Issue by xiashali** [TryGhost/Ghost#6754]
> ghost@0.7.9~preinstall: cannot run in wd %s %s (wd=%s) ghost@0.7.9 npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()" /root/ghost

* Ghost Version:0.7.9
* Node Version:5.11.0
* Browser/OS: Arch Linux

**Comment by acburdine** [comment]
Hey @xiashali, sorry to hear you're having trouble!

Most likely this is caused by improper permissions when trying to run npm install. As you are installing Ghost in `/root/ghost` this means you have to have root permissions in order to run npm install.

If you have any further questions I'd suggest heading over to our [slack](https://ghost.org/slack) channel, where we're better able to provide assistance. :smile:

**Comment by xiashali** [comment]
I run by root user

**Comment by jumkey** [comment]
@xiashali 不要用root 或者加 `--unsafe-perm`参数
