### ISSUE TITLE
Missing Handlebars helper to preserve \n characters in a post's markdown field

### ISSUE THREAD

**Issue by pickled-plugins** [TryGhost/Ghost#6757]
Hello - the helper I'm describing below is useful to define initial state on single-page apps powered by Ghost. Wonder if you consider this feature useful, or if there is a way around it.

### Issue Summary

Missing Handlebars helper to include escaped Markdown that preserves "\n" characters as opposed to adding newlines.

### Steps to Reproduce

1. Write a blog post with the following markdown:
```
First paragraph.

Second paragraph.
```

2. Add the following in `post.hbs` (to be consumed by a client-side application as initial application state):

```html
{{#post}}
<script>
var postData = {
  markdown: "{{{markdown}}}"
};
</script>
{{/post}}
```

3. Receive the following result:

```html
<script>
var postData = {
  markdown: "First paragraph.

Second paragraph."
};
</script>
```

as opposed to:

```html
<script>
var postData = {
  markdown: "First paragraph.\n\nSecond paragraph."
};
</script>
```

The former version produces a JS error and doesn't allow the data to be used on the client as single-page application state.

### Technical details:

* Ghost Version: 0.7.9
* GhostPro hosted.

**Comment by acburdine** [comment]
Hey @pickled-plugins!

I don't think this is a bug given how Handlebars renders things, and as a practice we don't normally take feature requests in Github's issue tracker. Please see [ideas.ghost.org](http://ideas.ghost.org) for the wishlist. 😄 

However, in response to the feature request I would say that as an alternative you could use the Public API's `ghost-url` script, which allows you to call the API directly and should return the raw post data instead of having to render it into a JS script (which seems like a bit of a hack to me).

**Comment by pickled-plugins** [comment]
Hey @acburdine - thanks for the hints.

The point of the script tag would be to avoid an initial extra round-trip to the server when the page loads. If I use ghost.url, I'd need to make an additional HTTP request after the page HTML is loaded - [the Redux docs](http://redux.js.org/docs/recipes/ServerRendering.html) explain a little better what I'm looking for.

I'm already using ghost.url.api, and it works great. I'm looking for a solution that works in the server-side templates. Anyways, I'll give {{get}} a go and see if it works.
