### ISSUE TITLE
rss not work

### ISSUE THREAD

**Issue by Draveness** [TryGhost/Ghost#6774]
### Issue Summary

This is my blog http://draveness.me and I don't know why but my rss feed http://draveness.me/rss doesn't work. And i'm not good at html, css and js and sort of these thing. I really need to fix this. And I have already search this on google, but didn't find an answer. Thx for your time

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: Safari
* Database: MySQL

**Comment by mrvautin** [comment]
Seems to work for me. What do you mean by "doesnt work"?

![capture](https://cloud.githubusercontent.com/assets/299398/14948329/36930358-107e-11e6-96b5-bef778512fe2.PNG)

**Comment by Draveness** [comment]
![3e937827-1f28-4457-982c-c0319b368596](https://cloud.githubusercontent.com/assets/6493255/14950542/07f4458c-1085-11e6-92bc-2f7efed7a9d4.png)

I use reeder to test it and seems like it doesn't find a rss feeding. Thanks for your help

**Comment by Draveness** [comment]
![Uploading 15173D29-87B6-4D87-94C7-0B4CF1CE104F.png…]()

This is the error when I trying to open this page on Chrome

**Comment by mrvautin** [comment]
I dont have Reeder and cannot confirm. Your feed works in Chrome for me. 

I think the issue is not Ghost software related and more likely a browser/app configuration.

**Comment by Draveness** [comment]
👍 Anyway, Thanks for your help

**Comment by ErisDS** [comment]
@Draveness I see this error on your feed:
![](http://puu.sh/oFd2G.png)
0x9B is a control character, and isn't valid in RSS. Ideally these should be removed for you, and there is an open issue about it here: https://github.com/dylang/node-rss/issues/49, however these characters shouldn't really be in your content either. Did you perhaps copy and paste a section from somewhere else? 

It can be hard to track these control characters down as they are invisible, however it can be done by pasting content into a validator like https://validator.w3.org/feed/ until you find the character in question. Removing it from the post will then result in the RSS feed working correctly.

I realise this is less than ideal and am very keen to get some feedback on https://github.com/dylang/node-rss/issues/49 so that we can get this resolved properly.

**Comment by djyde** [comment]
I have this problem too. https://validator.w3.org/feed/check.cgi?url=lutaonan.com%2Frss

How should I do?

**Comment by ErisDS** [comment]
If you are seeing errors like this, it means you likely have a character in your post which is not permitted in RSS. Usually these are invisible control characters. It is hard to find and remove them because they are invisible, however the RSS validator will give you a clue where it might be.

This is also usually caused by copy and pasting content from elsewhere, so the author should have an idea which bit of content might be the problem and why. Once the character is located & removed the RSS feed will stop showing you the error.
