### ISSUE TITLE
[Feature] Option to toggle converting tabs to spaces

### ISSUE THREAD

**Issue by opeik** [TryGhost/Ghost#6813]
Hi, after some grepping around your codebase I _think_ this should be fairly simple to implement. From my brief testing, commenting out all calls to `_Detab()` in "core/built/assets/vendor.js" and "node_modules/showdown-ghost/src/showdown.js" will cause tabs to be left alone in both the live markdown editor and the published posts.

**Comment by ErisDS** [comment]
Hi there @opeik!

To request a feature for Ghost you can add your idea (or vote on a [similar one](http://ideas.ghost.org/forums/285309-wishlist?query=tabs)) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)

As a general rule, we don't add options to the admin panel for minor features. We pick a sensible default that suits our core user base. The tab key is used for navigating around the app and is an important accessibility feature, which is why we do not hijack it within the editor.

**Comment by opeik** [comment]
Hi, thanks for the response.

> The tab key is used for navigating around the app and is an important accessibility feature, which is why we do not hijack it within the editor.

Fair enough, but I was referring to pasting code into preformatted code blocks. I don't see how these things are related.

**Comment by ErisDS** [comment]
@opeik Sorry for the confusion, your meaning wasn't clear from what you wrote 😉  Nonetheless we still wouldn't add options for this kind of detail. There is a plan to overhaul the editor to be more configurable in the future, but it's not something we're going to be working on for a little while.

**Comment by opeik** [comment]
I look forward to it. 👌
