### ISSUE TITLE
[FR] hide preview

### ISSUE THREAD

**Issue by sakulstra** [TryGhost/Ghost#6825]
Hello there,
I currently use ghost for a blog where i have to write a lot of html inside posts. This get's really messy because I have only half the screen for writing and the other half contains a completely useless preview. So it would be nice to hide it - just like with the menu.

I would volunteer to implement this, if there's a chance to get merged in ;)
I never used ember before, so I probably need some help down the road.

Regards,
Lukas

**Comment by ErisDS** [comment]
Hi there @sakulstra, whilst I don't follow the logic that having HTML in the left pane renders the preview "completely useless" (the preview window will still show how your content will display, rather than the raw html) , I can see other reasons why this might be nice to add. 

To request this as a feature for Ghost you can vote on [this similar idea](http://ideas.ghost.org/forums/285309-wishlist/suggestions/9659289-hide-live-preview) over on our [wishlist](http://ideas.ghost.org). We use this list to help determine what goes into the roadmap and how to prioritise features. You can also access the wishlist any time from inside the Ghost admin:
![](http://puu.sh/jXKwm.png)

**Comment by sakulstra** [comment]
Hay @ErisDS "completely useless" was mispronounced, you're right - i meant that it isn't rendering with the front end css, so in my case it's at least "confusing" ;)

Nevertheless, I already visited the wish list and found this idea you mentioned above - instead of voting for it and waiting I wanted to implement it myself if there's a chance that it gets merged in, but I am currently just learning ember so I probably would need some help down the road.

Best regards,
Lukas

**Comment by disordinary** [comment]
A better option would be to fix the rendering on that pane to reflect the actual content.
