### ISSUE TITLE
I use squid proxy pass port  80 to 2368, but signin admin return 401 error

### ISSUE THREAD

**Issue by Chen-Michael** [TryGhost/Ghost#6828]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

i can use domain:2368 signin admin

but i can't use domain signin admin

### Steps to Reproduce

1. add rule "cache_peer 192.168.0.2 parent 2368 0 no-query oiginalserver name=web1" in to squid 
2. add rule "cache_peer_domain web1 XXXXX.com"
3. open browser enter domain signin admin
4. return 401 `error`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 0.7.9
* Node Version: 4.4.4
* Browser/OS: chrome windows 2008 RX
* Database: sqlite3

**Comment by ErisDS** [comment]
Hi @Chen-Michael, sorry to hear you're having trouble. This seems like an environment issue rather than a bug. I recommend reaching out in the #help channel on [slack](https://ghost.org/slack) to see if anyone in our community has experience with squid. If you don't have any joy, then I'd recommend trying a squid user group or switching to use nginx which is a more standard setup.
