### ISSUE TITLE
add previous page class on body

### ISSUE THREAD

**Issue by oscarmorrison** [TryGhost/Ghost#6867]
### Improvement Issue Summary
I propose to include the class of a previous page on the body tag.

Currently we add the current page template, and the tags on the body class: e.g
`<body class="post-template tag-getting-started">
`

I am proposing to add what the previous page(template) was on the body as well in the format
**previous-home-template**

`<body class="post-template previous-home-template tag-getting-started">
`

### Use Case
There are times when you want to style, css animations different based on the previous page. For example if you have a big navigation bar on the home page, and would like that to shrink when it goes to a post. You would want a different animation coming from the tags page for example.

**Comment by acburdine** [comment]
@oscarmorrison this sounds like an idea for the [wishlist](ideas.ghost.org), as we use Ghost for tracking bugs with the software, as well as feature work that is currently going on.

That being said, I feel like this is something better done in a theme, as Ghost would have to store what page the user has visited (in the backend?) and then render it the next time the page loads. The other thing (for your use case specifically) is that the css animations might not work the way you intend them to, specifically because ghost actually does a page refresh when you go from one page/post to another. 

I could be wrong about the CSS, but implementing something like this on the backend isn't trivial, and IMO is better done in a theme.
