### ISSUE TITLE
Post Scheduling: Admin UI v1

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6870]
From a user interface perspective, scheduling posts will be a very small and simple change to begin with.

In the post settings menu, there is a field for entering a date and time that you would like your post to be published. Currently, that date and time *must* be in the past.

To allow for post scheduling, the validation that enforces dates being in the past will need to be removed.  After this, there will be two different flows for publishing a post:

### Flow 1: Publish (the same as now):

![](https://camo.githubusercontent.com/41178c38c774749c505e552227ffce752000cbb2/68747470733a2f2f64326d787565667165616137736a2e636c6f756466726f6e742e6e65742f735f453532363841343639324436343046453939343634413241333641414141413642314630463239393842383445443637373836453442384634354230394638435f313435333430343636383936335f53637265656e25324253686f74253242323031362d30312d3231253242617425324231392e32362e34372e706e67)

Case: the user either leaves the date as is, or sets it to a date in the past

- whilst the post has a status of `draft`, the save button menu will read "Publish Now" as it does currently
- after hitting "publish now", the post is published immediately (changed status from `draft`, to `published`) and the button is updated to say "Update Post". 

### Flow 2: Schedule (new):

![](https://camo.githubusercontent.com/10880171035f08e8c9cbcd30ba90e03c069070da/68747470733a2f2f64326d787565667165616137736a2e636c6f756466726f6e742e6e65742f735f453532363841343639324436343046453939343634413241333641414141413642314630463239393842383445443637373836453442384634354230394638435f313435333430343636383937375f53637265656e25324253686f74253242323031362d30312d3231253242617425324231392e32372e33322e706e67)

![screen shot 2016-05-20 at 13 32 24](https://cloud.githubusercontent.com/assets/101513/15427792/58711a40-1e8f-11e6-84c4-a7527c8ac0ce.png)

Case: the user sets the date to a date in the future

- whilst the post has a status of `draft`, the save button menu item will read "Schedule Post"
- after hitting "Schedule Post" the post is "scheduled" (status changes from `draft` to `scheduled`)
- whist the post has a status of `scheduled`, the save button will read "Scheduled". The menu items will be "Update Post" and "Unschedule". 
   - Update post will save the post, keeping the scheduled time and status
   - Unschedule will save the post, setting the status back to draft
- once the post becomes `published` the menu will be the same as a normal published post

When the post has the status "scheduled" we also want to update the label on the PSM from:

![](http://puu.sh/oYH0h.png)

To 

![](http://puu.sh/oYH2X.png)

### Edge cases with time going past the publish date

Because time keeps going whilst we're editing, there are some edge cases that need to be handled.

With scheduling, we get two extra states we need to handle cleanly:

#### 1. a draft post that is about to be scheduled.

This is a post that has a `status` of "draft", but a `published_at` date in the future. If we keep the draft post in a draft state after setting the `published_at` date in the future, at some point the `published_at` date will no longer be in the future.

When this happens, the editor save button needs to update from saying "Schedule Post" to "Publish Now".

We don't currently have sockets or any automatic thing that will tell us to update this, however the autosave does go off in the background & the user can save manually. Therefore the button should be wired to update when the underlying model changes and this is the best we can do for now.

#### 2. a scheduled post that gets published

If a post has a `status` of "scheduled" and a `published_at` date in the future, then all is ok with the world. However, the publishing job can potentially run on the server in the background whilst the editor is open. If the post changes from `scheduled` to `published`, the button should be wired to change from saying "Scheduled" to saying "Update Post". Note, "Scheduled' is a red state, "Update Post" is a blue state.

**Comment by kevinansfield** [comment]
Following on from the discussion in #6861 - what is the plan for the situation where a post is being edited when it's due to be published? I imagine having a post go live whilst you're editing with no indication wouldn't be the best experience.

One option could be to display a countdown either next to or in the Publish button, although that does raise an edge-case of user's having incorrect clock times.

Or... I could be overthinking this and we don't need a prominent indication of a post going live whilst editing for v1! 😁

**Comment by ErisDS** [comment]
Only plan right now is what is described in the "1. a draft post that is about to be scheduled." section -> The button would update.

I guess that the toaster notification would also pop up at that point?

Beyond that, nothing for v1 😉

**Comment by kevinansfield** [comment]
> 1 - a draft post that is about to be scheduled.
> Therefore the button should be wired to update when the underlying model changes and this is the best we can do for now.

That should happen automatically through Ember.

It would also be possible to set a timeout when entering the editor or when the publish date is changed. When that timeout fires it updates the button to reflect that the "published at" time is no longer in the future. Alternatively, @AileenCGN's timezone PR has a rudimentary clock service that could be used to check/update the button status periodically.

> 2 - a scheduled post that gets published

This one is a little more tricky because the auto-save only runs for draft posts so we have no existing method to auto-update. Again, we could follow the timeout/clock service approach above to switch the button at the current "published at" time but that means there could be a temporary disconnect between UI state and server source-of-truth - maybe best case scenario until we have true web socket support? Alternative would be to poll the server but it would need to be outside of Ember Data so that we aren't changing the underlying data sources whilst the user is editing.

**Comment by kevinansfield** [comment]
> I guess that the toaster notification would also pop up at that point?

I feel like I'm being dumb here - what's the toaster notification?

**Comment by ErisDS** [comment]
![toaster](http://puu.sh/oYOUq.png)

Called a toaster notification after an old app called toast which added notifications for things to Windows/Mac? Although ours doesn't really pop up like toast...

**Comment by kevinansfield** [comment]
Ah ok, in which case, no that notification wouldn't pop up as the scheduled->published change is not happening as a result of an action in Ember - Ember wouldn't know anything about it as there's no websockets/polling or even autosave for scheduled posts so I think the timeout is probably the easiest route for now.

**Comment by AileenCGN** [comment]
@ErisDS & @kevinansfield: One question regarding the posts overview (content). Atm we're sorting them like this:

1. status: ASC
2. publishedAt: DESC
3. updatedAt: DESC
4. id: DESC

Having the status sorted ascending would implicate to show the scheduled posts **after** the published posts. I reckon, we'll change the order to:

1. status: **draft, scheduled, published** (2. - 4. stays the same)

**Comment by kevinansfield** [comment]
@AileenCGN I agree, I also think we could improve the client-side sorting code. Ember contains a [Comparable mixin](http://emberjs.com/api/classes/Ember.Comparable.html#method_compare) that could be used by the Post model, this would move the sorting logic from the posts controller into the post model where it's easier to re-use.

**Comment by AileenCGN** [comment]
@ErisDS, @kevinansfield I have a question:

>![image](https://cloud.githubusercontent.com/assets/8037602/15573504/cf2a0702-2347-11e6-8824-818a6a645809.png)

This scenario is the only one, where 'Scheduled' actually has no behaviour. What is expected, when the user clicks on it? If we continue the logic of all the functionality here, a click should in fact do the 'Update Post' and save any changes. Is that correct? If so, I suggest the 'Update Post' should be marked blue and not 'Unscheduled' as this only gets marked, when the user clicks on it and the save button changes to 'Unschedule'.

**Comment by AileenCGN** [comment]
Here' a little **update** on this spec, as we discussed a few things to be sightly different than originally described here.

## Flow:
Other than described above, we decided to keep the button design the same as for a draft or published post. This means:

### Starting from a draft:
User chooses a date/time in future:

![image](https://cloud.githubusercontent.com/assets/8037602/15825530/6cfa56ca-2c04-11e6-85cb-0de9eb9f0ba2.png)

Then the save button text itself doesn't change, but will have the option to 'Schedule Post` instead of 'Publish Now' which it was before:
![image](https://cloud.githubusercontent.com/assets/8037602/15825563/88c53ab4-2c04-11e6-93b1-fe3a32daacac.png)
After clicking on 'Schedule Post', the save button text changes to the same text and turns red:
![image](https://cloud.githubusercontent.com/assets/8037602/15825583/a5191938-2c04-11e6-9602-7dde438e01ef.png)

### Starting from a scheduled post:
The default save button text will be the same as for a published post, except, the drop down menu will now say 'Unschedule' instead of 'Unpublish':

![image](https://cloud.githubusercontent.com/assets/8037602/15825637/df005a3a-2c04-11e6-9703-d987bf212e38.png)

Clicking on 'Unpublish' will change the save button text to the same text and turn red, as it is about to change the state of the post:

![image](https://cloud.githubusercontent.com/assets/8037602/15825672/01a804ac-2c05-11e6-9ade-318ca805913f.png)

## Minimum time in future:
As we need a little buffer to process the scheduling, the user needs to choose a time at least 3 minutes in future. If the time is less, the user will get the message below (just as if the inserted date is not valid):

![image](https://cloud.githubusercontent.com/assets/8037602/15825761/50587e88-2c05-11e6-8ec4-781950fde2ed.png)

Saving will reset the date to now, unless the entered time is > 3 minutes from now.

## Edge cases:

>1. a draft post that is about to be scheduled.

> This is a post that has a status of "draft", but a published_at date in the future. If we keep the draft post in a draft state after setting the published_at date in the future, at some point the published_at date will no longer be in the future.

> When this happens, the editor save button needs to update from saying "Schedule Post" to "Publish Now".

This edge case is easy to handle, as it doesn't change the state of the post to 'scheduled'. I decided to use a computed property, which checks (with the help of the clock service) every second, if we already reached the estimated time to publish. If so, the CP `timeScheduled` will return false, and the save buttons change back to the regular 'draft' state.

>2. a scheduled post that gets published

>If a post has a status of "scheduled" and a published_at date in the future, then all is ok with the world. However, the publishing job can potentially run on the server in the background whilst the editor is open. If the post changes from scheduled to published, the button should be wired to change from saying "Scheduled" to saying "Update Post". Note, "Scheduled' is a red state, "Update Post" is a blue state.

This edge case is way more tricky, as the models will not be refreshed automatically, if they change the state on the server. My solution for that is (for this v1 of the scheduler UI) a notification:

### Countdown notification:
15 minutes before the estimated publish time, the user will see a countdown notification like this:

![image](https://cloud.githubusercontent.com/assets/8037602/15826109/91f8d3b4-2c06-11e6-91d0-092c116de4e0.png)

When we reached the publish time, the notification will disappear.

Some hickups remain:
1. The user makes very very last minute changes and tries to save, but they can't be processed anymore within the 3 minutes before the estimated publish time
2. There's no autosave, that saves the changes for the user
3. As soon as the post has the status 'scheduled' but we already reached the publish time, the buttons will change back to this: 

![image](https://cloud.githubusercontent.com/assets/8037602/15826824/55c6be58-2c09-11e6-8bb5-f703cebcef9c.png)

and the page has to be refreshed to update the model, because otherwise, Ember will try to update the model not synced data anymore. The server stored the model already as 'published', but for Ember it's still in the state 'scheduled'. A click on 'Update Post' will therefore cause and API error: 

![image](https://cloud.githubusercontent.com/assets/8037602/15826840/6af00172-2c09-11e6-89b7-d53a80b8209a.png)

A click on 'Publish Now' will work.

## Sorted order of posts in content:
The posts in the content overview needed to have a custom sort order (this needs to be the same on the server, see TryGhost/Ghost#6932).

Posts will now have the order of:

1. status: 1. scheduled, 2. draft, 3. published
2. published_at: 'DESC',
3. updated_at: 'DESC',
4. id: 'DESC'

## New status 'Scheduled' in posts overview:
Scheduled posts will show, for what time they are scheduled.

![image](https://cloud.githubusercontent.com/assets/8037602/15827127/90c2ff66-2c0a-11e6-9a26-fed1b6050d8b.png)

**Comment by ErisDS** [comment]
Some hickups remain:
1. The user makes very very last minute changes and tries to save, but they can't be processed anymore within the 3 minutes before the estimated publish time

Where did 3 minutes come from? On https://github.com/TryGhost/Ghost/pull/6861 we talked about reducing the 5minute window down to 1 or 2 minutes.. this window needs to be quite brief I think.

Also, I think we need to handle this case nicely with sensible messaging, so that the error message tells the user to unschedule if they need to update the post? 

2. There's no autosave, that saves the changes for the user

I think this is correct, that there should not be autosave on scheduled posts, but we'll see what users think!

3. As soon as the post has the status 'scheduled' but we already reached the publish time, the buttons will change back to this:

![](https://cloud.githubusercontent.com/assets/8037602/15826824/55c6be58-2c09-11e6-8bb5-f703cebcef9c.png)

This seems like a bug to me - the post is definitely not a draft at this point... I'm not sure what the right thing to do is - but I think it would likely be to have the same options as a published post at this point?

**Comment by AileenCGN** [comment]
>Where did 3 minutes come from? On #6861 we talked about reducing the 5minute window down to 1 or 2 minutes.. this window needs to be quite brief I think.

You're right, I think atm it's 2 minutes, might be 1 later. But is a limit of 3 minutes minimum ok to have for the input field, though? Just to avoid this last edge case (scheduled gets draft), because the user inputs the minimum future date of x minutes, makes some metadatadescription, tags and _flupp_ it's published.

Nice messaging for this error would be nice. What about having something like a 'last warning'. 2 minutes seems to be the limit of doing changes (that's when I'm getting API errors), so I suggest, having a slightly different notification like this:

![image](https://cloud.githubusercontent.com/assets/8037602/15848906/db75a092-2c8f-11e6-9bc1-5a4a979ba65c.png)

And the save button changes to 'Unschedule'?

>\3. As soon as the post has the status 'scheduled' but we already reached the publish time, the buttons will change back to this: 
>This seems like a bug to me - the post is definitely not a draft at this point... I'm not sure what the right thing to do is - but I think it would likely be to have the same options as a published post at this point?

I agree, this should be the options for a published post. But then again, 'Save Draft' or 'Update Post' wouldn't work unless the user refreshes the page...

**Comment by AileenCGN** [comment]
**Update:**
Regarding the edge cases, I think I found a solution and pushed the changes for that on my PR TryGhost/Ghost-Admin#25.

This occurs only, when the user is in the editor, while the post is scheduled:

1. We reach 15 minutes before the scheduled date: this notification will show it to the user:

![image](https://cloud.githubusercontent.com/assets/8037602/15867746/f0b13778-2ce4-11e6-821e-5136432ff3d2.png)

2. We reach 2 minutes before the scheduled date: the save button will switch to 'Unschedule' and will not show the dropdown anymore:

![image](https://cloud.githubusercontent.com/assets/8037602/15867836/4cac6fe8-2ce5-11e6-89f5-fa2e317eb145.png)

3. We finally reached the scheduled date and the server did his job and changed the status to `published`, but Ember doesn't know about it. I built a way, to pretend that we're dealing now with a published post and the user sees these buttons:

![image](https://cloud.githubusercontent.com/assets/8037602/15867889/95ee1d3c-2ce5-11e6-8d62-22bbb12e9941.png)

Changes, which were done since the user opened the post and didn't change anymore will be kept by clicking on 'Update Post'. The post is still published and the changes submitted. A click on 'Unpublish' will set the post back to a draft.

I hope, this is a satisfying solution? @ErisDS, @kevinansfield , @JohnONolan

**Comment by AileenCGN** [comment]
Little update regarding the notifications:

Between 15 and 2 minutes before publishing, the user will see this notification:

![image](https://cloud.githubusercontent.com/assets/8037602/15940150/03b5aaba-2e7b-11e6-80cc-6e80a6c8869b.png)

and two minutes before publishing, it will switch to this:

![image](https://cloud.githubusercontent.com/assets/8037602/15940168/117b393a-2e7b-11e6-9b70-59c86f200e88.png)

So the message stays the same, just the buttons change.

**Comment by AileenCGN** [comment]
There are still two situations, where we're getting an error message from the API:

1. The user sets a schedule date > 2 minutes from now, but then does some other stuff and waits up to 1 minute before the date. 
2. The user is in the editor and the scheduled post gets published within 1 minute. He clicks on 'Unpublish' (the only choice he has at that time), and then immediately - without changing the date more than 2 minutes up from now - clicks on 'Schedule Post' again.

In both cases the API would return a validation error which said `Expected published_at to be in the future.` 

I changed this specific message to one, I assume the user would understand better:

![image](https://cloud.githubusercontent.com/assets/8037602/15959190/cf0fcc76-2ef9-11e6-889c-831f7be7d4bd.png)

Please feel free to correct the wording, if it's not ok...

**Comment by kirrg001** [comment]
like 👍  i will update the message in my PR soon.

**Comment by AileenCGN** [comment]
Updated the API error notification to look like this (checked with @JohnONolan):

![image](https://cloud.githubusercontent.com/assets/8037602/15961507/58aa3af6-2f05-11e6-9db0-f8ca2cb15008.png)

**Comment by ErisDS** [comment]
@ail Should this be closed now?

**Comment by Ail** [comment]
no
Date: Tue, 14 Jun 2016 09:20:59 -0700

**Comment by AileenCGN** [comment]
@ErisDS Yes!

**Comment by Ail** [comment]
1. why?2. i hope some day i will be able to use it

Date: Tue, 14 Jun 2016 09:34:33 -0700
