### ISSUE TITLE
Missing new users in author drop-down

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [TryGhost/Ghost#6907]
### Issue Summary

New users (created during the same browsing session) are missing in the post author drop-downs in edition mode.
### Steps to Reproduce
1. Create and validate a new user
2. Create a new post
3. Open the author drop-drop down in the post configurations

You will see that the new author is missing.
Refreshing the page fixes the issue of course.
### Technical details:
- Ghost Version: 0.7.8
- Node Version: node:4.2-slim (from Docker image)
- Browser/OS: buildpack-deps:jessie-curl (from Docker image)
- Database: MySQL

**Comment by kevinansfield** [comment]
This is happening because we currently only fetch the authors once and the result is cached on the `post-settings-menu` controller: https://github.com/TryGhost/Ghost-Admin/blob/master/app/controllers/post-settings-menu.js#L42-L57

Short-term solution would be to re-query the authors every time we access the editor, long-term solution is again web sockets and probably a combination of exposing a live array via `store.peekAll` and a CP that filters the list.

**Comment by kevinansfield** [comment]
Closing as this was fixed via https://github.com/TryGhost/Ghost-Admin/pull/137 and https://github.com/TryGhost/Ghost-Admin/pull/577.
