### ISSUE TITLE
Default sort order for posts needs to consider status 'scheduled'

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#6932]
The orderDefaultOptions() for posts model return a sort order which needs to be updated in regards of the new scheduling feature (#6861). Status quo the order is

1. status: 'ASC',
2. published_at: 'DESC',
3. updated_at: 'DESC',
4. id: 'DESC'.

This worked out well so far, because we want to have posts with status 'draft' before posts with status 'published' and the usual alphabetical, ascending order (d before p) works fine. 

Now, as we expanded the posts to also have a status 'scheduled', these posts would always be last in order, if we'd remain the regular order.

**For usability reasons, 'scheduled' posts should be listed first. Then 'draft' and finally 'published'.**

-------

I suggest to return a custom sorting function (if needed), which returns the order like this:

**1. status: 1. scheduled, 2. draft, 3. published**
2. published_at: 'DESC',
3. updated_at: 'DESC',
4. id: 'DESC'

The comparison between a 'draft' and 'published' can stay the same, as the alphabetical order is valid here. Anytime a 'scheduled' post is compared with a different status, it should get the higher priority in the order. `published_at`, `updated_at` and `id` will remain unaffected. 

--------

**Reason, why we have to do this:**

> The API endpoint is paginated so we need the server to return the posts in the right order by default or have some way to instruct the server to return posts in the order that we want.

^ thanks @kevinansfield

**Comment by kirrg001** [comment]
I don’t think the server should implement a custom sort logic for this problem. Just imagine we add a sort filter to ember in the future, so the user can decide how to show the posts. Then you need additional sort logic anyway (you don't want to request the server to get a new order)

That’s why here is my suggestion:

We can change `status` to `DESC` in the server, then scheduled posts are always on top, drafts are on the bottom.

When receiving the result, switch draft and published posts by finding out the indices: (this code example is just an example and is not a full solution)

```
var result = [{status: 'scheduled'}, {status: 'scheduled'}, {status: 'published'}, {status: 'draft'}, {status: 'draft'}];
var draftIndex, publishedIndex;

result.forEach(function(model, index) {
	if (model.status === 'draft' && !draftIndex) { draftIndex = index };
	if (model.status === 'published' && !publishedIndex) { publishedIndex = index };
    });

result = result.slice(0, publishedIndex-1).concat(result.slice(draftIndex, result.length)).concat(result.slice(publishedIndex, draftIndex));
```

This logic could be a default sort module in ember.

**Comment by AileenCGN** [comment]
We already implemented the custom sort order in ember, but it seems to be the same on both sides, as I can read from the comments:
https://github.com/TryGhost/Ghost-Admin/blob/master/app/controllers/posts.js#L6

But maybe I'm wrong?
@kevinansfield @ErisDS

**Comment by kevinansfield** [comment]
The API endpoint is paginated so we need the server to return the posts in the right order by default or have some way to instruct the server to return posts in the order that we want.

**Comment by AileenCGN** [comment]
I just updated the issue description with this information.

**Comment by kirrg001** [comment]
I assume you have a variable in ember where all your posts are stored, so you can still order in ember, not based on the api result, based on an update of the list. (if you later have performance problems, you could reusing DOM elements)

**Comment by kevinansfield** [comment]
> I assume you have a variable in ember where all your posts are stored

The API is paginated so we will almost always have a partial store of posts on the client-side. If there's no way to control the order of data the server is giving us we would need to download every post in the database in order to sort it correctly.

For the client the API is the "database" and the same principles that would apply to interacting with a database directly on the server apply to the client interacting with the API.

Server-side you wouldn't pull everything out of the database into a variable because the ordering isn't what you want, you'd instruct the database to return the data in the order that you want so that you can use `LIMIT` and fetch the data in pages. The same needs to be possible with the API - right now we have a default order, in the future we might have custom ordering but the API will still need to support that custom ordering.

**Comment by kevinansfield** [comment]
The ideal solution would be a way to provide arbitrary ordering instructions to the API via query params however that potentially opens us up to abuse and denial of service attacks which I imagine is why the [existing order parameter](http://api.ghost.org/docs/order) is limited.

Until such time as the ordering is more flexible I think we need to have the API order match the client-side ordering.

In SQL the ORDER statement would be:

```sql
ORDER BY
    CASE WHEN status = 'scheduled' THEN 1
         WHEN status = 'draft' THEN 2
         ELSE 3 END ASC,
    published_at DESC,
    updated_at DESC,
    id DESC
```

However, I'm not sure how this would interact with other API options, for example if the `filter` parameter is used and the `status` field is not returned is that reflected in the database query (potentially breaking the order statement) or is the filtering done after the query but before generating the returned JSON?

**Comment by ErisDS** [comment]
The server side `orderDefaultOptions()` sets up the correct order for our API "default". It creates the correct order for returning all posts, and still returns published posts in chronological order, newest first, for when you're only looking at public data. 

The rules, e.g. that public posts should be returned in order of published_at with the newest first, and the rules set out in this issue where scheduled posts should be first are the business logic of our particular models, and so they make sense as being the defaults for the API to return. It makes very little sense to have a default that no one is actually using.

The API _can_ return posts in different orders if you specify an `order` parameter but this is currently limited. In order to implement this, we're going to need to use SQL case statements (as @kevinansfield has just added in his comment) - this is more complex than anything that the `order` parameter can currently convey, which is another reason for making it the default.

It may be that this adds overhead such that it makes sense to split between a "public default" and a "private default", but we'd need to test for performance issues to measure whether that's really worth resolving.

**Comment by ErisDS** [comment]
@kevinansfield I'm not sure about whether using `fields` to not include `status` in the result would cause a problem - if it does, that would be considered a bug. It's not insurmountable as we can manually add on extra fields to fetch and exclude them again from the result set.

**Comment by kirrg001** [comment]
@ErisDS Because of all this (thanks for summarize), i've suggested a ember client solution for the first version of scheduling.

**Comment by ErisDS** [comment]
IMO the API is our first concern. We deliberately build our API to "dogfood" and by finding and fixing problems with the API upfront we ensure that everyone else can also build meaningful clients. That is, if we have to workaround a problem with the API, then so does anyone else building a client.

In this case, I also don't think there is a workable client-side fix for this, as explained by @kevinansfield, in order to get the right order the ember client would always need to load all the posts. 
This may result in the UI loading slowly, jumping around, or other misbehaviour, as we have [seen](https://github.com/TryGhost/Ghost/issues/4788) in [the past](https://github.com/TryGhost/Ghost/issues/3008) when the client & server orders don't match.

**Comment by awendt** [comment]
My 2 cents about the description:

> For usability reasons, 'scheduled' posts should be listed first.
> Then 'draft' and finally 'published'.

I don't think this is good from a usability perspective: I'd rather see posts move down in a list from "draft" (top) to "scheduled" to "published" (bottom).

Think about it: If the UI showed scheduled first, the post starts in the middle of the list (assuming other posts are already scheduled), then moves up to scheduled, then all the way down to scheduled based on time.

I imagine this to be very confusing to users.

**Comment by kirrg001** [comment]
I will care about the ordering on the server side asap.
