### ISSUE TITLE
Tags lost order after exporting and importing

### ISSUE THREAD

**Issue by kirtan403** [TryGhost/Ghost#6967]
### Issue Summary

Exporting Data and Importing Data lost the tag sequence. Most of the time the sequence doesn't matter for tags. But I am using a first tag as category and from second, normal tags. So that makes it all fuzzy after exporting and importing it.

Note: Tags re-ordering works fine if you don't export-import.
### Steps to Reproduce
1. Export all data from http://websitename.com/ghost/settings/labs/
2. Delete all content from the same page
3. Import it again from the same page
### Technical details:
- Ghost Version: 0.8
- Node Version: 4.3.0
- Browser/OS: Chrome v51
- Database: SQLite

**Comment by ErisDS** [comment]
Hi @kirtan403, thanks for the bug report! I think we missed updating the importer after tag ordering was added. Our importer probably needs a bit of TLC.

**Comment by kirtan403** [comment]
It was just 20 posts for me. So I was able to do it again. But may take good amount time on large blog.

Hope to see the fix soon.

**Comment by ErisDS** [comment]
Just to confirm - this is fixed in 1.0.0 but not in LTS?

**Comment by kirrg001** [comment]
@ErisDS 

Yeah exactly. I left some importer bugs open, in case the community wants to pick them up. But they didn't get any attention.

I am going to close this issue, because we've overhauled the importer in Ghost 1.0. If you experience this problem, i would suggest to migrate to 1.0 👍 😬 

Alternatively, feel free to re-open and provide a quick fix for the LTS branch.
