### ISSUE TITLE
Labs: errors display as [object Object] and other error issues

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6974]
I've seen a couple of reports recently of errors being displayed as `[object Object]` in certain cases. I've managed to recreate two, both on the labs page. 

### Steps to reproduce

1. Start Ghost, and load up the labs page
2. Do something to create an error, easiest thing is to stop Ghost
3. Try deleting all your content -> see the notification error pop up and look like this:
![](http://puu.sh/pp3GS.png)
4. Now, try sending an email... same thing happens
5. Try an import - that correctly says "Import Failed" as a big red error alert across the top of the page
6. Try an export - nothing happens at all!

### Technical details:

* Ghost Version: 0.8.0 (current master)

**Comment by kevinansfield** [comment]
The core problem here is that the notifications error display methods aren't correctly dealing with error objects from `ember-ajax`. This is most noticeable when we don't get any response from the server (e.g. by killing the server as mentioned in this issue) as that means our custom error parsing gets bypassed.

I'm working on the above as well as a more general cleanup of our error handling although I think there will still be room for further improvements once we're past the imminent release. 

> Try an export - nothing happens at all!

This is actually a completely different class of error - the problem here is that we need to create an iframe and set it's `src` attribute to the export path so that a download is triggered. It's not entirely straight forward to do error handling in this case because we've handed over control to the browser. There are [some approaches](http://stackoverflow.com/questions/15273042/catch-error-if-iframe-src-fails-to-load-error-refused-to-display-http-ww) available that bind to the `onload` event in the `iframe` coupled with a timer which doesn't sound particularly useful for our case as (1) we're initiating a download rather than a page load and (2) it's reliant on a set timeout so we may inadvertently show an error to users if have slow connections or very large exports.
