### ISSUE TITLE
Permalinks preview won't reflect custom permalink setting

### ISSUE THREAD

**Issue by farmdawgnation** [TryGhost/Ghost#6978]
### Issue Summary

There have been a few issues around permalinks filed on the repository so far - and I came to the understanding that it is possible to change your permalink structure manually in the database. Since I'm migrating from Squarespace, I want to make links as close as possible to that environment - because I actually liked the URL structure I had there a lot - so that's what I did.

However, I noticed that the UI permalink preview won't reflect this change. For example, my permalink pattern is `/blog/:year/:month/:day/:slug`, but when I go to compose a new post and preview the permalink in the settings I see:

![screen shot 2016-06-11 at 9 49 54 pm](https://cloud.githubusercontent.com/assets/620189/15988441/d93f22b6-301e-11e6-8dfb-30f35b7bffc9.png)

I would expect it to properly simulate the actual URL format that would be used for this post.

### Steps to Reproduce

1. Customize permalink structure in the database.
2. Go to compose a new post and look at the screen where you customize the slug

### Technical details:

* Ghost Version: 0.8
* Node Version: v4.4.5 (using ghost docker container)
* Browser/OS: Chrome/OSX
* Database: sqlite

**Comment by ErisDS** [comment]
Hi @farmdawgnation thanks for the bug report! I appreciate it's a bit weird, but this is working as intended.

This is also the case if you use the standard  "dated permalink" structure in Ghost and is not because you're using a custom permalink structure. The permalink preview is designed to only show the slug because the slug is the only part of the URL which can change and also be predicted.

Until you actually publish the post, there's no possible way to know what the date parts of the URL will be. That in combination with the limited available space means it isn't really possible to display a preview of a dated permalink.

At some point in future we'll be looking to change the workflow of creating posts, to provide more preview information just before a post is published. When that work is done we will revisit this.
