### ISSUE TITLE
Shall we put sqlite3 into dev-dependencies?

### ISSUE THREAD

**Issue by palmtale** [TryGhost/Ghost#6980]
That's terrible to build sqlite3 npm module in some of the OS, such as Alpine. caused by the memcpy@CGLIB, They's give a patch to solve it , but not released. 

But!!!, Why I go to research that sqlite3 things? I don't care it . I would like to use mysql as my database, so this should be you ghost's issue!

This (Sqlite3)  is totally not force dependency. You've already support lots kind of data persistence engines, then each of their driver should be optional, OK?

**Comment by ErisDS** [comment]
@palmtale Sorry to hear you've been having trouble.

Sqlite3 is not a dev dependency - it is the default and recommended database to use with Ghost at present, which is why it is included by default. There is no need to compile it on any major OS.

Trying to support every possible combination of install for every possible kind of user on every possible environment is very challenging. The setup we have makes it easy for the majority of users to get going without needing to know too much by optimising for the most common environments. Users who go off the beaten path (such as yourself) are the users who have the technical chops to solve technical issues with the install. 

This may change in future, but not without significant work around documentation and the install process.
