### ISSUE TITLE
Subscribe page back link always links to home page

### ISSUE THREAD

**Issue by jonblack** [TryGhost/Ghost#6984]
The default subscriber page "back" link always links to the home page. I would expect it to link to the page the user was on before they clicked on the "subscribe" link.

* Ghost Version: 0.9.0beta1
* Node Version: v4.4.0
* Browser/OS: Linux/Firefox
* Database: MySQL

**Comment by kirrg001** [comment]
Thanks @jonblack 
I can confirm this behaviour.

**Comment by sakulstra** [comment]
`<a href="{{@blog.url}}" class="gh-flow-back"><i class="icon-arrow-left"></i> Back</a>` seems to be pretty static :)

@kirrg001: not sure if this is a valid solution, but one could simply use `onclick="javascript:history.go(-1)"`.  This will work in most cases.

When accessing `https://url/subscribe/` directly this will lead to a blank page (imo unimportant edge case).
When being referred from somewhere else this will direct to the referrers page (don't know if this is the wanted behavior - even if it does what "back" says). 

If javascript is disabled it will fall back to the current behavior.

If you want me to, I can do a pr with the described solution.

**Comment by sakulstra** [comment]
Ups, sry for the spam... first used `javascript:history.go(-1)` and then read, that this has some problems in older chrome versions and `window.history.go(-1)` is the official way to go.

**Comment by kevinansfield** [comment]
I think I see where the problem might be although I haven't tested it yet. [This line](https://github.com/TryGhost/Ghost/blob/master/core/server/apps/subscribers/index.js#L25) will the grab the value of the `.referrer` input and put it back into that input, there's a conditional there which is intended to fall back to `document.referrer` but it will never be reached as an empty string (which is why you'll get back from that selector) is truthy. I'm assuming the tests fake it by passing in `null` rather than an empty string which is why they are passing.
