### ISSUE TITLE
[Request] Markdown support for the Blog Description under General Settings

### ISSUE THREAD

**Issue by JamieSinn** [TryGhost/Ghost#7012]
Line breaks are especially annoying and hard to do when you don't have markdown's double newline. 

I'd personally write this if I had a bit more work with node, but I'm mostly a Java/PHP guy.

**Comment by kevinansfield** [comment]
The blog description is used for the meta description which is why there is no formatting and the text field has a character limit.

If you would like to have a full "about us" type description then I would suggest building it into your theme templates or creating a separate page. Alternatively if you would like to suggest it as a feature please use our [wishlist](https://ideas.ghost.org) so that we can track which ideas have traction.
