### ISSUE TITLE
Default url still showing on front and back end after configuring

### ISSUE THREAD

**Issue by MorbidEntree** [TryGhost/Ghost#7030]
### Issue Summary

After installing and configuring Ghost on DigitalOcean, along with my domain, it still uses the default url `http://my-ghost-blog.com/` instead of the one I set it to. This only happens on the urls in the lower left corner, in the sharing buttons, and in the back end.

### Steps to Reproduce

I'm not exactly sure what caused this, besides installing and configuring the software.

### Technical details:

* Ghost Version: 0.8
* Node Version: Unknown, whatever DigitalOcean uses.
* Browser/OS: Chrome
* Database: Unknown, whatever DigitalOcean uses.

**Comment by acburdine** [comment]
Hey @MorbidEntree, sorry to hear you're having trouble!

At first thought this sounds to me like you've configured the wrong section of your `config.js`. Make sure you've configured the `production` section and not the `development` one.

If you have trouble after that, please swing by our [slack](http://ghost.org/slack) channel and ask there. We can provide better support, and if it turns out to be an issue with Ghost we can reopen this issue.

Thanks! 😄
