### ISSUE TITLE
Saving data not working

### ISSUE THREAD

**Issue by philipthomasme** [TryGhost/Ghost#7050]
### Issue Summary

If I save settings or delete content/tags etc. the data is deleted but if I go back to the settings page, the old, already deleted data is shown again resulting in overwriting the new data if clicking "save" again.

### Example
I just deleted the “getting started” tag, go to “content” and back to “tags” and it will load the “/tags/getting-started” page and even shows the already deleted tag but as soon as i “hard-reload”, it will say 404 because the tag was deleted.
If i THEN click on tags again - so a soft load of data is performed, the tag shows up AGAIN.

Publishing posts is working but in the admin panel, a post will be shown as "draft" although it was published even after "hard-reloading" the page. After deleting cookies and logging in again, the post will be shown as published.

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 0.10.46
* Browser/OS: Chrome 51.0.2704.106 (Official Build) (64-bit) on Mac OS X

**Comment by strues** [comment]
I too am experiencing this. I thought there was an issue with permissions within my Docker container, but using a fresh install (without Docker) the issue continued. 

This occurs both in version 0.8.0 and the 0.9 beta for me.

Unfortunately there are not any console errors and the networking tab shows all 200s. Running Node 4.2 and Postgres.

**Comment by kevinansfield** [comment]
@strues are you running any kind of cache in front of ghost? The behaviour that @philipthomasme described matches what I would expect if there is a cache somewhere (external or possibly even the browser, although I've not seen a browser doing this directly before) that is caching the API responses

**Comment by ErisDS** [comment]
Is there any more information we can use to debug this? It's a pretty worrying issue but it does sound like a non-standard setup.

**Comment by kevinansfield** [comment]
Having the full response headers for the `200` requests after saving could be useful as they may indicate whether or not they are coming from a cache.

**Comment by kevinansfield** [comment]
We send the necessary HTTP 1.1 headers to prevent caching so it definitely seems like an odd issue. I see three possibilities:

1. There is a HTTP 1.0 only cache/proxy between the client and the API in which case the necessary `Pragma: no-cache` and `Expires: 0` headers are missing. However HTTP 1.1 was introduced in 1997 so it would need to be either very old or misconfigured
2. A cache/proxy between the client and the API is misconfigured to overly cache everything and ignore the HTTP headers
3. There's some browser config or setup that we don't know about that is causing the weird behaviour

What would also be useful is to verify that the content in the 200 requests after saving is showing old data rather than the newly saved data that's in the database.

**Comment by ErisDS** [comment]
This issue needs more information for us to be able to do anything with it and there has been no reply in more than a month. Going to close it for now, if more information is provided so that we can reproduce, we will reopen it 👍
