### ISSUE TITLE
Upgrde from 0.8.0 to 0.9.0-beta.x: SQLITE_ERROR: no such table: subscribers

### ISSUE THREAD

**Issue by adamcavendish** [TryGhost/Ghost#7069]
### Issue Summary

Upgrde from 0.8.0 to 0.9.0-beta.x: SQLITE_ERROR: no such table: subscribers

Upgrade steps: git pull

### Technical details:

* Ghost Version: 0.8.0 to 0.9.0-beta-2
* Node Version: v4.4.7
* Browser/OS: Ubuntu 16.04
* Database: SQLite

### Error Report:

Migrations: Database upgrade required from version 005 to 006
Migrations: Creating database backup
Migrations: Database backup written to: /files/Nutstore/blog/Ghost/content/data/modest-destiny.ghost.2016-07-04.json
Migrations: Ensuring default settings
Migrations: Running fixture updates
Migrations: Updating fixtures to 006
Migrations: Transforming dates to UTC: (could take a while)...
Migrations: Transforming dates to UTC: Updated datetime fields for Posts
Migrations: Transforming dates to UTC: Updated datetime fields for Users

ERROR: select "subscribers".* from "subscribers" - SQLITE_ERROR: no such table: subscribers 
 
 Error: SQLITE_ERROR: no such table: subscribers
    at Error (native)
From previous event:
    at Client._query (/files/Nutstore/blog/Ghost/node_modules/knex/lib/dialects/sqlite3/index.js:84:12)
    at Client.query (/files/Nutstore/blog/Ghost/node_modules/knex/lib/client.js:136:24)
    at /files/Nutstore/blog/Ghost/node_modules/knex/lib/transaction.js:225:21
From previous event:
    at Client.trxClient.query (/files/Nutstore/blog/Ghost/node_modules/knex/lib/transaction.js:222:26)
    at Runner.<anonymous> (/files/Nutstore/blog/Ghost/node_modules/knex/lib/runner.js:115:24)
From previous event:
    at /files/Nutstore/blog/Ghost/node_modules/knex/lib/runner.js:43:21
From previous event:
    at Runner.run (/files/Nutstore/blog/Ghost/node_modules/knex/lib/runner.js:29:20)
    at QueryBuilder.Target.then (/files/Nutstore/blog/Ghost/node_modules/knex/lib/interface.js:26:43)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by ErisDS** [comment]
Hi @adamcavendish,

You list your upgrade steps as "git pull" and say you went from 0.8.0 to 0.9.0-beta-2.

The subscribers table should have been created as part of the upgrade from 0.7.x to 0.8.0, so this suggests to me that you have been running master rather than the stable branch? If you're running master, you're not on a specific version, so you can end up running Ghost at half-way points in the middle of database migrations. 

To mitigate this, you'd need to run `FORCE_MIGRATION=true npm start`. This will force Ghost to try to re-run all of the database migrations. 

All of this is intended for development only. If you're running a site in production you should use the stable branch.

**Comment by adamcavendish** [comment]
@ErisDS  Thx, it fixed my issue. I'll never use master afterwards. I'm switching back to stable now.

**Comment by kskarthik** [comment]
@ErisDS I think i am facing similar issue with 0.80. :confused: 

![nodeghost](https://cloud.githubusercontent.com/assets/11899221/16951492/deb05d28-4de2-11e6-8d30-85ed05d12ad5.png)
