### ISSUE TITLE
Error when run 'npm start' when installing ghost

### ISSUE THREAD

**Issue by donnisnoni** [TryGhost/Ghost#7072]
I have some problem when i try to run
```sh
npm start
```
and

```sh
npm start --production
```
Please help me,, this is my npm-debug.log files
[npm-debug.txt](https://github.com/TryGhost/Ghost/files/346802/npm-debug.txt)

## Ghost Information
Version : 0.9.0-beta.2

Thanks.....

**Comment by acburdine** [comment]
Hey @donnisnoni, sorry to hear you're having trouble!

Because 0.9.0 is still in beta, it's likely there's some kinks in the startup process - would you mind taking a look at the [release post](https://github.com/tryghost/ghost/releases/0.9.0-beta.2) to see if any of the steps there fix it.

If not, please swing by our [slack channel](https://ghost.org/slack) and you can get more specialized help. If it turns out this is an actual issue, we can reopen this.

Thanks! :smile:

**Comment by dhonx** [comment]
Thanks @acburdine!!! It works now after 4 years 😂
