### ISSUE TITLE
urlPathForPost does not include subdirectory

### ISSUE THREAD

**Issue by PeerWell** [TryGhost/Ghost#7087]
When generating the URL for a post, it does not include the subdirectory. This effects the controller that pulls a single post and post.url does not match req.path.

// CASE: permalink is not valid anymore, we redirect him permanently to the correct one
if (post.url !== req.path) {
  return res.redirect(301, post.url);
}

**Comment by ErisDS** [comment]
@PeerWell Sorry to hear you're having trouble. When you raise an issue we provide a template which shows all the kinds of information that we need in order to track down an issue quickly and easily.

In particular, it includes the steps to reproduce & some details of your environment.

Can you please update your issue to include that info, so that we can find and fix the issue you're reporting? 

Thanks 👍

**Comment by ErisDS** [comment]
This issue needs more information for us to be able to do anything with it and there has been no reply in more than a month. Going to close it for now, if more information is provided so that we can reproduce, we will reopen it 👍
