### ISSUE TITLE
implement RTL support in editor as a standalone feature

### ISSUE THREAD

**Issue by danielkatz** [TryGhost/Ghost#7103]
As part of the ongoing effort to add i18n support at #5345, I want to propose implementing RTL support in the markdown editor as a standalone step towards the goal.

I'm not (yet) a contributor to this project, but from a brief look at the source code it looks (please correct me if i wrong) like, that it should be fairly straightforward to implement it, even without the full blown i18n support.

Just to be clear what i mean as RTL support: Is the ability to flow the content (or part of it) in both the markdown editor and the preview panel from the right. This alone (with a theme style), will allow authoring posts in RTL languages.

There are some considerations, the RTL setting can be on one of three levels:

1. Blog level (my vote, based on the fact that I haven't seen many mixed blogs)
2. Post level
3. Paragraph level overrides would be nice touch in any case, but i'm not sure if it even applicable to markdown idioms.

In any case, IMO, there must be an exception for code (inline and block) that are always LTR (though it would be an inconvenience for esoteric languages like [Mama](https://en.wikipedia.org/wiki/Mama_(software))).

If it would be acceptable as a standalone feature, i'd like to try to implement it and make a PR.
Please comment your thoughts on the matter.

**Comment by ErisDS** [comment]
Hi @danielkatz!  Thank you for your interest in working on this, however I don't think RTL is a viable project for Ghost core.

We ask that people request features via the [wishlist](http://ideas.ghost.org). RTL hasn't been raised on there so it's not a project I believe has traction. You'll also notice it isn't mentioned in our big list of [i18n problems](https://github.com/TryGhost/Ghost/issues/3801) that do need solving. 

The reason for that is introducing RTL support creates a huge amount of overhead (new fonts, exponential extra complexity in design & maintenance and so on), and therefore creates impediments in the software whilst only benefiting a small percentage of users. Knowing all this and how it has played out in other projects, we have always believed this needs to be implemented as some kind of app (plugin) rather than being in Ghost core.

As an additional note we intend to replace Ghost's editor entirely in the near future, something that we hope will open the door for extensions to implement features like this, but again it wouldn't be something we'd consider [adding to core](https://github.com/TryGhost/Ghost/wiki/What-makes-it-into-Ghost-core%3F).

**Comment by jegesh** [comment]
I have a quick fix I applied to my fork of the Ghost-Admin repo, which I needed to help my wife write her blog in Hebrew.  It's just a checkbox that switches the editor windows to RTL.  Should I make a pull request?

**Comment by EzimetYusup** [comment]
I think we need rtl!

**Comment by EzimetYusup** [comment]
it's such a waste if Ghost doesn't support rtl!

**Comment by kevinansfield** [comment]
@EzimetYusup feature requests should be opened on the [Ideas category](https://forum.ghost.org/c/Ideas/l/votes) on our forum where users can vote on them.

**Comment by EzimetYusup** [comment]
if there is no rtl feature that means u have already lost many users, it's kinda basic thing, all the users are ltr now, how possibly they can vote on rtl feature?

**Comment by EzimetYusup** [comment]
but any way I have created topic for that [vote here](https://forum.ghost.org/t/lets-add-rtl-feature-to-editor/1872) @jegesh @danielkatz

**Comment by mehdisadeghi** [comment]
@ErisDS I was just considering Ghost for my nephew knowing that it lacks RTL features. I was eager to make some patches that I came across this issue.

> We ask that people request features via the wishlist. RTL hasn't been raised on there so it's not a project I believe has traction. You'll also notice it isn't mentioned in our big list of i18n problems that do need solving.

Does this mean you won't even consider pull requests that solve this matter? In that case it would be very sad and exclusive policy, regardless of voting.

**Comment by javadbat** [comment]
why ? we need RTL support
