### ISSUE TITLE
Need to click submit button twice in "Invite user" modal with validation error

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7131]
### Issue Summary

If you have a validation error when inviting a user (through the team page) and then correct the email the first time you click on the "Send Invite" button the validation is cleared but the invite is not sent.
### Steps to Reproduce
1. Visit the Team page
2. Click "Invite People" button
3. Enter an invalid email address, e.g. "foo"
4. Click "Send" - note the inline validation
5. Enter a valid email address, e.g. "test@example.com"
6. Click "Send"
7. Note the inline validation message disappears but the invite hasn't been sent
8. Click "Send" again - invite is actually sent this time

I would expect the invite to be sent on the first button press when a valid e-mail address is present.
### Technical details:
- Ghost Version: master && LTS?

**Comment by dbalders** [comment]
@kevinansfield so, I did some testing, looks like the reason it doesn't take your click is because the focus out event happens first, which moves the button upwards and then the click didn't technically happen on the button. If you click at the very top of the button this works.

I see two ways to solve this, either remove the on focus out event and just have it validate on click (this would also solve a problem where when you close the modal, you see a flash of the error), or we give that error permanent space so the invite button never moves. 

I can do either of those or something else if you have a better solution.

What are your thoughts?

**Comment by Avasse** [comment]
Hi, i would like to work on this issue as my first PR, is anybody working on it ?

**Comment by kevinansfield** [comment]
@Avasse there is an old implementation attempt here https://github.com/TryGhost/Ghost-Admin/pull/170 however it would be preferable to find a solution that did not rely on a timeout.

**Comment by evexoio** [comment]
Can't reproduce this issue. I think its fixed, can we close this issue?

**Comment by m1guelpf** [comment]
@kevinansfield https://github.com/TryGhost/Ghost-Admin/pull/1020 was merged, can this be closed?

**Comment by ErisDS** [comment]
We're dropping LTS support on 31st December. The only fixes that will happen between now and then are any major security issues. Closing this as wontfix.
