### ISSUE TITLE
Bug: Editor broken in Edge browser

### ISSUE THREAD

**Issue by twisterghost** [TryGhost/Ghost#7149]
### Issue Summary

When attempting to access the content editor in the MS Edge browser, there is a javascript error in the console, and the editor never gets displayed.

### Steps to Reproduce

1. Access the content panel in the admin view
2. Click to edit a post, or click "New post"
3. See that there is nothing shown, and an error in the MS Edge console:

>SCRIPT5007: Unable to get property 'querySelectorAll' of undefined or null reference
ghost.min.js (1,14277)

Screenshot of the broken state:
![Content editor broken in MS Edge](https://s3-us-west-2.amazonaws.com/mjb-personal/ghost-edge-bug-screenshot.png)

### Technical details

* Ghost Version: 0.8.0 (via Digital Ocean)
* Client OS: Windows 10
* Server OS: Ubuntu 14.04
* Node Version: 4.4.4
* Browser: MS Edge
* Database: sqlite

**Comment by kevinansfield** [comment]
Hi @twisterghost, thanks for reporting the issue. We've confirmed it and located where the problem is in the codebase. Hopefully we'll have a fix out soon.

The problem arises in [this code](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-ed-preview.js#L55-L57) in the `gh-ed-preview` component. It turns out IE doesn't support the `.content` property on `<template>` elements 😞 We use `template.content` here to easily get a pre-built `documentFragment` that we can then work with in-memory.

After reviewing a few template element polyfills I think the solution will be to borrow their techniques to loop over all the elements in the generated HTML and build up a document fragment manually when `template.content` doesn't exist. Unfortunately this may come with a performance penalty so it will need some testing around that area because the `buildPreviewHTML` method is a hot code path that can be called at up to 30ms intervals.

**Comment by RicSwirrl** [comment]
I experience this is IE11 too.

**Comment by acburdine** [comment]
@RicSwirrl yeah, we found it there as well.
