### ISSUE TITLE
Upgrading 0.8 to 0.9

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Ghost#7158]
So I have tried to upgrade from Ghost 0.8 to 0.9 using the instruction shown your [website](http://support.ghost.org/how-to-upgrade). But it crashed.

![capture](https://cloud.githubusercontent.com/assets/7360286/17238653/95cc05d6-55b1-11e6-830b-6e12c5b46758.JPG)

Whats going on? I have no idea.

**Edit**

My NPM version is 

![capture1](https://cloud.githubusercontent.com/assets/7360286/17238682/e6b9cd0c-55b1-11e6-8a0f-bf765ec746ec.JPG)

**Comment by acburdine** [comment]
@akshaybabloo Sorry to hear that! Unfortunately this is caused by somewhat unexpected behavior in npm. The solution is to delete your `node_modules` folder, and run `npm install --production` again.

**Comment by crepererum** [comment]
I somehow remember that this was a problem before. Maybe [the official docs](http://support.ghost.org/how-to-upgrade) should be changed to tell users delete the `node_modules` folder in EVERY error case, not only when the `npm install --production` step fails. Or even better (which I think would avoid many future problems): ALWAYS delete it before doing the upgrade. This would increase upgrade times slightly, but I think it is worth it.

**Comment by acburdine** [comment]
@crepererum normally it's fine, the only time I recall this has been a problem was in the 0.9.0-beta2 release.

In the 0.9.0-beta.2 release, it was caused by a lodash dependency issue, explained in [this comment](https://github.com/TryGhost/Ghost/issues/6997#issuecomment-226190914).

In the main 0.9.0 release, the same problem is occuring, except it's with knex instead of bookshelf. A maintenance release will be issued sometime soon to fix the issue.

**Comment by mattlacey** [comment]
For the record this just happened to me while going from 0.8.0 to 0.9.0, and I found this by specifically searching for the lodash and ghost.

Seems like a step too many when including a note to try deleting the node_modules directory would resolve the situation for many.

**Comment by ErisDS** [comment]
@mattlacey sorry to hear you had this problem. Where did you expect to see the note? It is included in the [troubleshooting section of the upgrade guide](http://support.ghost.org/how-to-upgrade/#troubleshooting).

**Comment by mattlacey** [comment]
You know what, I spotted that right after! I think I missed it because I'd
scrolled down to just the command list after the first upgrade round (I was
going 0.7 -> 0.8 -> 0.9 -> 0.10.1) and then forgot about that.

I guess including it twice would be silly, maybe after the last step have
something like "If you encounter an issue refer to the troubleshooting
section above"?

**Comment by ErisDS** [comment]
This has been done 😉
