### ISSUE TITLE
Next/Previous posts appear not to be working in 0.9.0

### ISSUE THREAD

**Issue by jpsingleton** [TryGhost/Ghost#7179]
### Issue Summary

Next/Previous posts (read next at the bottom of posts) appear not to be working in 0.9.0 after upgrading from 0.8.0. Instead of Next/Previous I only see the most recent post.

I can't find any existing issues and the code in this area doesn't seem to have changed. The data looks fine still, as the correct published dates appear in the editor.

I had the usual npm node modules dependency hell when upgrading, with the main problem being sqlite. It wanted `node-v46-win32-ia32` but was installing `node-v11-win32-ia32`, so this could be related.

If I can't fix this then I'll probably revert to a backup of 0.8.0.

### Steps to Reproduce

1. Note correct behaviour of next/prev on a 0.8 blog
2. Make a backup (including db file) - very important
3. Upgrade to 0.9 (reinstall and fix modules a few times)
4. Note incorrect behaviour of next/prev on a 0.9 blog

I'd be interested if anyone else is experiencing this or if there is something unique to my setup that is causing the problem. For example, if a specific version of node is required (I know v4 is recommended but v0.10 is supported).

### Technical details:

* Ghost Version: 0.9.0
* Node Version: v0.10.29 - default value on Azure (unchanged from 0.8.0) - `WEBSITE_NODE_DEFAULT_VERSION` not set (`echo %WEBSITE_NODE_DEFAULT_VERSION%` just returns the literal string)
* Browser/OS: Firefox and Chrome on Windows (unchanged from 0.8.0)
* Database: Built-in embedded sqlite (unchanged from 0.8.0)

**Comment by ErisDS** [comment]
Hi @jpsingleton. I'm really sorry to hear you're having trouble with next/prev posts.

As you've correctly identified, there were no code changes in this area. If you take a look at http://demo.ghost.io, and go through the posts,  you can also clearly see the next/prev posts are working.

Therefore, this would appear to be an environment issue, rather than a bug in Ghost that we would be able to investigate and solve. I'd suggest deleting all dependencies, deleting the core folder and redoing the upgrade. If you need a hand tracking down the issue then there is always our [slack team](https://ghost.org/slack).

**Comment by donovanmuller** [comment]
@ErisDS I believe this might be a bug in the migration scripts to 0.9.
I had an existing blog on version 0.7.x and just updated to 0.9 using the same `$GHOST_CONTENT` directory. When running version 0.9 for the first time it migrated the current database schema (0.7.x) successfully but I just noticed that I had the exact problem @jpsingleton did.

@jpsingleton in case you didn't get past this, all you have to do is update any of your existing posts and the previous/next posts will work again. I'm assuming the update somehow brings the tables in sync again ¯\\_(ツ)_/¯

@ErisDS I assume this must be a migration script bug because I have another [demo blog](https://brage.switchbit.io/) which was on 0.8 but doesn't have much data and no uploads, so I just used the Labs feature to [export](http://support.ghost.org/import-and-export-my-ghost-blog-settings-and-data/) the blog data and then used the import function on a fresh install of 0.9 and that worked as expected with the prev/next links working. 

Only difference then was that the one blog was updated via schema upgrade scripts (@jpsingleton's error) and the other through the import labs feature (no problem)?

**Comment by jpsingleton** [comment]
I had a suspicion that it might be due to the DB migration scripts, so thanks for adding another data point. Messing up dates and time-zones is a pretty common problem, as it requires some thought to get it right.

It looks like this is a bug in Ghost then and it's not quite ready for serious use. I may go back to using WordPress until Ghost is at least v1 and the edge cases have been ironed out. For all its faults I never had a problem updating WordPress.

**Comment by jpsingleton** [comment]
I can confirm that re-saving all posts "resolves" this issue. Thanks for the tip @donovanmuller! 

This suggests to me that this is indeed a bug in Ghost (probably in the migration scripts - which I saw run), rather than an environmental problem. Disappointing that this was dismissed so quickly by @ErisDS rather than considering a full root-cause analysis.

**Comment by donovanmuller** [comment]
@ErisDS can this issue be reopened?

@jpsingleton have you tried the migration (like above) with 0.10.0?

**Comment by jpsingleton** [comment]
I haven't tried with 0.10.0 as I have too much on to go through the upgrade pain right now. Especially when the [release notes](https://dev.ghost.org/ghost-0-10-0/) mention breaking changes in a minor version bump. That's not really how [Semantic Versioning](http://semver.org/) should work but I can see why they wouldn't want to go for v1 as it's clearly not ready.

It's a shame as there is a [security bug fix](https://github.com/TryGhost/Ghost/pull/7247) for an [open redirection vulnerability](https://www.asp.net/mvc/overview/security/preventing-open-redirection-attacks), which would be nice to have in a 0.9.1 patch release. However, I tested this and my 0.9.0 install doesn't appear to vulnerable.

**Comment by ErisDS** [comment]
I apologise for misdiagnosing the problem, I interpreted the issue report as saying that next/previous posts weren't showing at all. It seems that this is actually the same problem as reported in #7248. 

Could you please share what timezone your servers were running in prior to the migration? 

As #7248 is already open, there's no need to reopen this. However, if we can tie this down as being migration related, we may need to open a separate issue to track the underlying problem.

**Comment by jpsingleton** [comment]
The blog timezone is GMT (so BST for the migration) but the server may be using UTC at the OS level. The other issue appears to be the same problem so happy for this to remain closed. The nature of the next/previous corruption does appear to be date related.

Don't worry, timezones are hard. I find storing everything as UTC (and naming it as such) helps, or even better using a datetime offset - which implicitly captures the timezone too.

Thanks for following up.
