### ISSUE TITLE
Ghost API: Access-Control-Allow-Origin Error with client_trusted_domains entry

### ISSUE THREAD

**Issue by rorymaddeninitiate** [TryGhost/Ghost#7244]
### Issue Summary

I am trying to access the Ghost blog api from an external site. I have setup two client trusted domains: localhost:8080 and my site address: https://uxdxconf.com. This site is hosted on github pages with a Cloudflare CDN providing the SSL. 

The access works fine from my local environment (localhost:8080) but it gets an Access-Control-Allow-Origin error when trying to access it from the live site. 

### Steps to Reproduce

1. Set up two client_trusted_domains entries with unique uuid's pointing to the local and live urls.
2. Send request from the local version - works
3. Send request from the live version - fails

### Technical details:

* Ghost Version: 0.7.9
* Node Version: v0.10.35 (Live), 5.10.1 (Local)
* Browser/OS: Chrome / OSX
* Database: MySQL

**Comment by ErisDS** [comment]
Hi @rorymaddeninitiate, I'm sorry to hear you're having trouble.
This is most certainly a configuration issue, rather than a bug in Ghost. It sounds like either your trusted domain entries are configured incorrectly or the way you're building the request is wrong.

A few things to check:

- do your trusted domains have protocols?
- do your trusted domains end with a slash? (They should not)
- are you using the ghost api url helper, and if not, can you check that the URL it generates for you matches the one you're using?

I'm going to close this issue as I don't believe there is a bug here, if you need more help debugging your configuration, our [slack](https://ghost.org/slack) channel is a more appropriate way to get support than GitHub issues.
