### ISSUE TITLE
Trying to invite a user with the same email as the current user results in an incorrect validation

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#7250]
### Issue Summary

Step 3 screen, attempting to invite using an existing email address (i.e. the one provided in Step 2) results in "Failed to send 1 invitation: <email>. Please check your email configuration, see http://support.ghost.org/mail for instructions"

Looking in the server log shows an "Error: User is already registered", so that's not the issue here.
### Steps to Reproduce
1. Setup blog with email address
2. Invite same email address
3. Invite completes and observe above error message in top alert

I believe this is a regression, and this was handled in the validation step before?
### Technical details:
- Ghost Version: [master](https://github.com/TryGhost/Ghost/commit/6c199afedf50ea3c3d1ebd7f5781d540b16f45f3)
- Node Version: latest 4.x
- Browser/OS: Chrome 52
- Database: SQLite

**Comment by acburdine** [comment]
@kevinansfield @kirrg001 wasn't sure if this is a blocker?

**Comment by ErisDS** [comment]
Not a blocker, pretty sure it's been like this for a while 😉

**Comment by AileenCGN** [comment]
When I use the email address, I registered with, plus two (valid) more email addresses, I have the following situation:

1. The button in step 3 tells me, that I'm about to invite 2 users, although 3 emails are entered. But this is completely correct, as one of them is used already.
2. After hitting the invite button, I get the same error as @acburdine for the used email PLUS (and that's what I think, is wrong)
3. The error message tells me, that it failed to invite **2** users and lists the first (already used email) and the second one I entered, but when I check the network response, I can see, that the invite for the second user was successful.

Also, in my terminal, I got this message: `Warning: Error sending email: Error: Message could not be sent
More info: Mail from command failed - 550 5.7.1  Mail from IP 197.162.254.169 was rejected due to listing in Spamhaus PBL. For details please see http://www.spamhaus.org/query/bl?ip=197.162.254.169 Please check your email settings and resend the invitation.`

**Comment by kevinansfield** [comment]
This has been fixed in 1.0 😄
