### ISSUE TITLE
Slug updates don't work as expected

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7255]
This happens for posts and for profile slugs.

#### In profile
I change only the slug and click save. ember sends only a GET request to `/ghost/api/v0.1/slugs/user/{name}`, then i have to press another time save, then it sends a PUT request.

#### In posts
The slug doesn't get updated at all.
I change the slug, press update post and ember sends the old slug.

Version: pre-release 0.10.0
Database: tested with sqlite

**Comment by kevinansfield** [comment]
> I change only the slug and click save. ember sends only a GET request to /ghost/api/v0.1/slugs/user/{name}, then i have to press another time save, then it sends a PUT request.

This is happening when you type in the slug field and then immediately click on the Save button - the focus-out event on the field is triggering and blocking the save. We had a similar problem in the Slack config page, fix is to keep a reference to in-process promises and chain them so that we perform the slug check and then the save in sequence.

> The slug doesn't get updated at all.
> I change the slug, press update post and ember sends the old slug.

The focus-out slug checking function is throwing an error which prevents the new slug from being registered, once that is fixed everything should be back to normal.

Fixes for both should be incoming shortly 😄

**Comment by kirrg001** [comment]
Thank you!

**Comment by acburdine** [comment]
Closed via TryGhost/Ghost-Admin#222
