### ISSUE TITLE
non-availability of RSS when password protection is on

### ISSUE THREAD

**Issue by guyzmo** [TryGhost/Ghost#7282]
### Issue Summary

When password protection is setup to make the blog private, the `rss` index generation is not working (directing to a 404).

### Steps to Reproduce

1. check 'Enable password protection` in `Settings`→`General`→`Make this blog private`
2. go to the RSS page, you'll get a `404`.

I believe this is an expected behaviour, though documentation should better reflect that.

Whether RSS is a *social feature* is not necessarily obvious, and often the main reason to put a blog as private is to test it before publishing.

An even better thing would be to have a `500 Service unavailable` like error, with a message stating *feature not available in private mode*.

### Technical details:

* Ghost Version: v0.9.0

**Comment by nuclearpengy** [comment]
on a semi related note, it would be pretty cool if the RSS feed could still work somehow if the user has the password. Not sure if that's something an RSS reader would/could support.

**Comment by nuclearpengy** [comment]
I think it's also a simple and effective method for setting up personal/family sites or even for internal work blogs.

**Comment by guyzmo** [comment]
@nuclearpengy it might, but it's the wrong tool, as it is providing a lower level of security for your privacy. Setting up a htaccess isn't that hard and much safer!

**Comment by acburdine** [comment]
@guyzmo the only issue with .htaccess is you wouldn't be able to login to the Ghost Admin using http basic auth (they both send data in the same request header).

I don't think this is an actual issue as RSS is by design disabled by the private blogging feature, however I'll leave it up to @ErisDS about the documentation part of this.

**Comment by guyzmo** [comment]
@acburdine well, if the private feature is a mean to setup private blogging scheme, then the same auth scheme as the admin interface should be used for "read only users", so at least it's compatible with tools around.

At the very least, have "Social features" a link, with the list of what's expected not to work and what's expected to work at a given version of Ghost with password protection on. ☺

**Comment by ErisDS** [comment]
If you'd like to raise or vote on feature requests, you can do so on http://ideas.ghost.org.

The private blogging feature is only intended to be used to create privacy for a blog. It is not secure and should not be used for security purposes.

When a blog is in private mode, RSS is disabled as it contains all of the content through a mechanism that wouldn't be useful to a blog in private mode. This is expected behaviour for this feature, rather than a bug.
