### ISSUE TITLE
better theme name consistency

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7313]
Uploading theme names like `abc (1).zip` results in a `{ themes: [null]}` response, which causes ember to not show the popup "Do you wanne activate this theme?" - instead it still shows the upload popup.

**The good thing is, that the theme table gets refreshed, it gets uploaded, you can activate the theme, use it and delete it, because we are reading available themes from disk.** - so its not a serious bug. Anyway we need to add a bit of consistency naming love.

The storage adapter right now does a character replacement, see https://github.com/TryGhost/Ghost/blob/master/core/server/storage/base.js#L48 and the `local-file-store` then returns the path to the file. In future thinking, if we want to allow having custom theme storage adapters, we maybe cannot rely on the same response of the `save` function. 

An option would be to call the storage adapter like this `getFileName(name)` and it normalises the name. Or we can normalise the name without the storage adapter in the upload logic. Anyway, if ember wants to detect an existing theme, it needs to either also normalise the name or the server returns a normalised name and the original uploaded name.

**Comment by kevinansfield** [comment]
> server returns a normalised name and the original uploaded name

That would be my preferred route - the server should be the source of truth especially with regards to normalisation so that the logic doesn't need to be duplicated across the server and any clients that use the API.

**Comment by kirrg001** [comment]
@kevinansfield yes agree 👍

**Comment by disordinary** [comment]
There is a problem with this proposed solution. If two themes have identical names (or the same theme is uploaded multiple times, potentially with upgrades) in that it creates a unique filename. So if I have (2).zip and I upload it twice I get -2-, and  -2--1 but a new method getFileName(name) will always resolve the first upload of that theme -2- and never subsequent ones.

**Comment by disordinary** [comment]
The submitted solution only accepts characters from the Latin alphabet + the **@** and **.** characters, this is for compatibility reasons.

If two themes are uploaded with names written in Kanji that have different characters but are of the same length then they will be treated as the same filename. 

For example, if I upload two themes with filenames in Cyrillic, `день.zip` and `ночь.zip` - literally themes called `day` and `night` then both will resolve to `----.zip` and therefore overwrite one and another. This is a tough one to solve with filename level as not all filesystems support Unicode. A better way to do it is to abstract the name of the theme from it's physical location (potentially storing it in UUID directories rather than directories named after the zip file, or use Ghosts existing functionality to append a number on the end of conflicting filenames) and use the pakage.json theme name and version information to see if a theme exists.
