### ISSUE TITLE
Bug: Theme Uploader/Update ignores small changes in files

### ISSUE THREAD

**Issue by tlseabra** [TryGhost/Ghost#7399]
### Issue Summary

I have been hacking away at Casper and trying to change some stuff inside the theme.
Yesterday I had a problem where I couldn't repeatedly change the height property of .main-header class (think big cover image at the home page). Today, by messing around with Chrome Developer tools, I found out that the screen.css file wasn't being updated as I uploaded changed themes.

I tried renaming the .css file to something like screen1.css and it then updated properly.

I tried to look for info regarding update-time limits or problems with file updating but couldn't find any solution. Have no idea if this problem persists with other themes.

### Steps to Reproduce

1. Change something in the screen.css file of a theme.
2. Upload the new .zip theme file using the theme uploader.
3. Again, change something in the .css file.
4. Again, upload the new theme using the theme uploader.
5. Realize this time no change was made.

This is a bug because the theme did not update properly.

### Technical details

* Ghost Version: Ghost PRO
* Client OS: Windows 10
* Server OS: 
* Node Version: 
* Browser:  Chrome
* Database:

**Comment by ErisDS** [comment]
Hi @tlseabra, sorry to hear you're having trouble. I think you're probably running into [this bug](https://github.com/TryGhost/Ghost/issues/7350), which was fixed in Ghost 0.11.0. However, not all Ghost(Pro) users have been upgraded to 0.11.0 yet due to the emergency maintenance we did on Friday.

You can check and confirm which version of Ghost you are running by viewing the about screen. This is accessible in the drop down menu next to your blog title:

![](https://puu.sh/rgxdA.png)

If your blog shows 0.11.0 now (we're finishing the upgrades) you should be able to re-try uploading your theme and find the bug is gone.
