### ISSUE TITLE
Scheduler fail

### ISSUE THREAD

**Issue by newbish** [TryGhost/Ghost#7435]
When the scheduler time elapses a call to the API is made but is using GET instead of PUT.

127.0.0.1 - - [23/Sep/2016:19:59:59 +0000] "GET /ghost/api/v0.1/schedules/posts/47?client_id=ghost-scheduler&client_secret=xxxxxxxx HTTP/1.0" 301 - "-" "node-superagent/2.2.0"
127.0.0.1 - - [23/Sep/2016:20:00:00 +0000] "GET /ghost/api/v0.1/schedules/posts/47/?client_id=ghost-scheduler&client_secret=xxxxxxxx HTTP/1.0" 200 - "-" "node-superagent/2.2.0"

**Comment by newbish** [comment]
So part of the issue is nginx is acting as a reverse proxy and uses a rule to redirect all traffic to HTTPS. Is there a way to instruct the API to only operate via HTTPS?

**Comment by kirrg001** [comment]
Hey @newbish Sorry to hear you are having trouble.
Maybe our documentation will help, see http://support.ghost.org/setup-ssl-self-hosted-ghost/.

If you still hit a problem, can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
