### ISSUE TITLE
Sitemap Generating only 1 Image by Default

### ISSUE THREAD

**Issue by uditgoenka** [TryGhost/Ghost#7442]
The sitemap post links that are being automatically generated by default shows only 1 Image while all the posts have got more than one image because of this, Google Webmaster is incorrectly indexing all the image. 

![image](https://cloud.githubusercontent.com/assets/1478769/18852755/89089512-845f-11e6-8db6-1442ed3265ed.png)

[https://gopbn.com/blog/sitemap-posts.xml](https://gopbn.com/blog/sitemap-posts.xml)

### Technical details:

* Ghost Version: 0.11

**Comment by ScottHelme** [comment]
I've confirmed this on my blog which is running 0.11.0 right now:

https://scotthelme.co.uk/sitemap-posts.xml

It also happens on hosted Ghost:

https://www.troyhunt.com/sitemap-posts.xml

**Comment by ScottHelme** [comment]
cc @troyhunt

**Comment by kevinansfield** [comment]
It's worth noting that the google site map reports are only reporting on the specific content that is in the site map, by listing 1 next to a page they are _not_ saying that's thats the only indexed Image but that it's seen 1 image in he site map. If google is showing the page as indexed then it's quite likely that they have indexed every image on the page as per their normal crawling algorithm - the site map is a guide to help google to find deeper pages than they may through a normal crawl rather than a way to specify every element on a site.

Right now the only structured data that ghost has for images is the "post image" selected in the post settings and so that is all that is added to the site map. We're currently working on a new editor that will store data in a more structured format as well as improved image management. Once those pieces are in place we'll be in a better position to add additional entries to the site map.

**Comment by uditgoenka** [comment]
@kevinansfield Until then, do we just need to wait?

**Comment by kevinansfield** [comment]
@uditgoenka for now yes, in the meantime I would suggest adding or voting on a feature request for better image sitemaps over on https://ideas.ghost.org so that we can gauge community desire for this feature.

Closing for now as this is in the feature-request arena rather than a bug.
