### ISSUE TITLE
config: it's not possible to override defaults via argv 

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7492]
`node index.js --url=my-url` won't override the default url.
Thanks @sebgie for reporting.

With current usage of `nconf`, somehow `file` is always stronger then `argv` - maybe it's caused by how nconf create's in memory stores in combination of how we are using `nconf`.

Will work on a solution for that.

Workaround could be for now:
`touch config.development.json`
`echo "{\"url\": \".....\"}" | config.development.json`

**Comment by vivekannan** [comment]
OK. Really weird. nconf looks through the different "stores" that it has (argv, env, files etc) for the given key (in this case `url`). The problem is, it returns the value found in the first store that has the given key.

When you configure the files as numbers (1, 2, 3, 4), they come before argv alphanumerically speaking. So the `url` in 1 (which is one of the config files) is returned. On the other hand when they are configured as ghost1, ghost2 etc, they come after `argv`. So `argv`'s url is returned. Not sure if this is the expected behaviour......

**Comment by kirrg001** [comment]
@vivekannan 
The alphanumeric assumption is an interesting fact and might explain the behaviour, but as you pointed out: this shouldn't be expected?

The good thing for now is: with `ghost1, ghost2..` keys, argv overrides work.

The PR is still open because we would like to figure out why. If you can find more, please share. Very appreciating your help. From next week on we will work again on Ghost 1.0 issues, bugs (config bugs etc.) and features.

**Comment by kirrg001** [comment]
Closing. I've added a reference into the configuration audit issue #7488 
This helps getting a better issue overview for our upcoming 1.0 releases.

Any further conversations, can still happen here.
