### ISSUE TITLE
npm WARN cannot run in wd ghost@0.11.2

### ISSUE THREAD

**Issue by ccccccmd** [TryGhost/Ghost#7575]
when i update ghost,
npm install --production

it  comes :
`npm WARN cannot run in wd ghost@0.11.2`

**Comment by kirrg001** [comment]
Hey @ccccccmd 
Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.

**Comment by jaydson** [comment]
Same issue here. Can't find any solution on Slack as well.

**Comment by ErisDS** [comment]
@jaydson I see on Slack you did get to a solution 😉 

wd = "working directory", as in the full error shared in slack, the message usually tells you which directory this is. This error is usually a permissions error telling you it can't run in the folder you're in. However, if the error is followed by "killed" it is because you ran out of memory. 

We ask people to use slack for support rather than GitHub, not least because this is our bug tracker, but also because half-shared error messages and "me too"'s require a lot of back-and-forth thats far easier in Slack.

We do have a troubleshooting guide: http://support.ghost.org/troubleshooting/
