### ISSUE TITLE
Theme upload seems to be broken

### ISSUE THREAD

**Issue by msamoylov** [TryGhost/Ghost#7596]
### Issue Summary

I'm trying to upload a theme and getting an error: `_.where is not a function`.

### Steps to Reproduce

1. Navigate to **/ghost/settings/general/uploadtheme/**
2. Try uploading a theme.

**/ghost/api/v0.1/themes/upload/** is throwing the server error with:

```
{
    "errors": [
        {
            "message": "_.where is not a function",
            "errorType": "InternalServerError"
        }
    ]
}
```

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 4.6.0
* Browser/OS: Safari 10.0/macOS Sierra
* Database: PostgreSQL 9.5.4

**Comment by acburdine** [comment]
Hey @msamoylov, this is a known issue - however it's not with Ghost. The issue is that your node_modules have become slightly out-of-whack due to some long-standing issues with npm.

The fix is pretty simple:
- `rm -rf node_modules`
- `npm cache clean`
- `npm install --production`

That should fix the issue. If it doesn't, please head over to our [slack channel](https://ghost.org/slack) for further help 😄 If it turns out that this is actually a bug within Ghost, this issue can be reopened.
