### ISSUE TITLE
No datepicker in Post Settings

### ISSUE THREAD

**Issue by evil-shrike** [TryGhost/Ghost#7603]
### Date picker is not working in Post settings

I expect that there should be a date picker for "Publish date" field in Post settings but it's just a plane text input.

### Steps to Reproduce

1. Open any post
2. Enter into edit mode
3. Open post settings
4. a date in "Publish date" field can only be edited as text (in very awkward format: "20 Oct 16")

I expect that there should be a date picker but it's just a plane input.

### Technical details:

* Ghost Version: 0.11.2
* Node Version: 6.9.1
* Browser/OS: Chrome/Windows
* Database: sqlite3

**Comment by kevinansfield** [comment]
Hi @evil-shrike, glad to hear that you're trying Ghost out and sorry to see that you've found something that you don't quite like. Unfortunately this issue falls under the feature request category rather than a bug/on-going development so Github isn't the best place for it, if you can take a moment to add/up-vote the requested feature on http://ideas.ghost.org then you'll be able to help prioritise what is worked on.

For further reference there is discussion around potential date pickers and other input types on this issue https://github.com/TryGhost/Ghost/issues/5777

**Comment by evil-shrike** [comment]
Ok, I see, no datepicker is being used yet. 
Then it'd make sense to format dates in inputs in more universal format, like: "2016-10-20 19:42".
