### ISSUE TITLE
Update v0.11.2 and Deployment Issues

### ISSUE THREAD

**Issue by EnFlight** [TryGhost/Ghost#7607]
### Issue Summary

I am updating ghost.js from 0.7 to 0.11. When I run the app locally the updates are seen. When I push to github so it'll deploy to heroku, the changes are not seen.

This is not an issue with a .gitignore file. Are there any issues with updating because I am running ghost using Heroku vs. when I run the app locally?

### Steps to Reproduce

1. Use ghost.js with heroku and S3
2. Go through the update directions via http://support.ghost.org/how-to-upgrade/
3. Update the files in ghost folder
4. Push to github
5. Merge Pull Request
6. Deploy to Heroku
7. Run app using Heroku

### Technical details:

* Ghost Version: 0.7 to 0.11.2
* Node Version: 0.12.14
* Browser/OS: Chrome/Mac
* Database: S3/Heroku/Github

**Comment by carloscuesta** [comment]
I'm running Ghost @ 0.11.2 at Heroku and had no problems @EnFlight.

Taking a look at your [repository package.json](https://github.com/EnFlight/enflight.design/blob/master/package.json#L14) I'm seeing that you're using `ghost@0.7.8`. Update this with the last version `0.11.2` to install it when deploying the blog to heroku.

Also I recommend you to use the [Ghost recommended](http://support.ghost.org/supported-node-versions/) node version `>=4.2 <5.*`

**Comment by kevinansfield** [comment]
Hi @EnFlight, sorry to hear you are having trouble upgrading. Unfortunately this sounds like an environment issue rather than a bug in Ghost so I'll have to close this issue as we only use Github for bug tracking and on-going development. If you head over to our [Slack team](https://ghost.org/slack/) and ask in the #help channel the community is usually very good at finding where the problem may be and pointing you in the right direction 😃
