### ISSUE TITLE
Knex-Migrator should exit with non-zero error code if start fails

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost#7615]
### Issue Summary

The new knex-migrator logs an error to the console if the database has not been initialized; however, it exits with an error code of 0, which is rather unhelpful for processes that are listening to it. (For example, Ghost-CLI).

It should probably exit with a non-zero error code which will let consuming process managers know that something is wrong.
### Steps to reproduce:
1. Clone 👻 (or install with the CLI 😉)

``` sh
> node index.js
ERROR: Please run knex-migrator init
> echo $?
0
```
### Technical details:
- Ghost Version: 1.0.0-alpha.5
- Node Version: 4.6.0
- Browser/OS: N/A
- Database: N/A

**Comment by kirrg001** [comment]
> The new knex-migrator logs an error to the console if the database has not been initialized; 

In case of using knex-migrator JS API, knex-migrator does not log the error to stdout. Ghost is doing that. Knex-migrator just returns an error. 

Ghost-CLI is using knex-migrator JS API and it can exit the process depending on the response of knex-migrator. The error contains a self-explained error code. Because Ghost-CLI handles the database health checks as first instance, it can handle a process exit. It should not happen that Ghost throws a database error, because Ghost-CLI checks the database health before.

---

Anyway: Ghost exits by default with exit code 0 - that is true, see https://github.com/TryGhost/Ghost/blob/master/index.js#L21 - that happens for every error which occurs. So as far as i understand, this request is a general request to Ghost changing this behaviour?But this is not really related to knex-migrator?

**Comment by kirrg001** [comment]
Closing. Fixed via https://github.com/TryGhost/Ghost/commit/b3f09347e45361f87bd97076d2b57e590459bf0f#diff-168726dbe96b3ce427e7fedce31bb0bcR35
