### ISSUE TITLE
global and local installation of knex-migrator need to be compatible

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#7669]
It can happen that your global installation does not support the version Ghost has installed locally. And then the database management won't work as expected. 

Steps to reproduce:
- Install global version 0.1.2
- Install local version 0.0.7
- knex-migrator init - works
- npm start -> still throws an error

To avoid getting problems: use for global and local the same versions.

**Comment by acburdine** [comment]
@kirrg001 something that might be good to take a look at is how Ember-CLI solves the exact same problem. Basically the bin file checks if there's an ember-cli instance in the current directory and loads that if there is rather than the global one.

Their code is here: https://github.com/ember-cli/ember-cli/blob/master/bin/ember

I'm fairly certain it could be adapter to work for this lib.

**Comment by kirrg001** [comment]
@acburdine Thanks!

**Comment by kirrg001** [comment]
see https://github.com/TryGhost/knex-migrator/pull/20

**Comment by kirrg001** [comment]
This is fixed, tested and released. Closing.
