### ISSUE TITLE
GhostAuth 422 RedirectUri Mismatch

### ISSUE THREAD

**Issue by spamguy** [TryGhost/Ghost#7684]
### Issue Summary

I am setting up a local instance of Ghost on my DigitalOcean droplet. I attempted to sign in through Ghost's OAuth2. The popup window generated nothing but the text '422 ValidationError / Redirect URI Mismatch / ID:'. (The ID is empty.) I expected to receive a token and the popup to close quietly.

### Steps to Reproduce

1. The cURL of the authentication request is:

```
curl 'http://devauth.ghost.org:8080/oauth2/authorize?response_type=code&client_id=581c231231cfd62d292b641c&redirect_uri=https%3A%2F%2Fblog.dipl.io%2Fghost%2F&state=hfRj0OGvXTTQFsVo&type=setup' -H 'Pragma: no-cache' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: no-cache' -H 'Cookie: __cfduid=d14b362cadf2aab8a7fa5ab3d103061141478043577; ajs_anonymous_id=%22a0c2f79d-2a6b-4d3e-9f74-3a9ca716e5eb%22; intercom-id-5bzvblx6=f5d6b06d-1e06-49ce-8f62-22c7f014e93c; ajs_user_id=null; ajs_group_id=null; ghost-auth=eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNTgxZDgwZGYzMWNmZDYyZDI5MmI2NDU5In0sImFjY2Vzc3Rva2VuIjoiUVF0V1dDMWp0MWlBR1RzS2J2WWFvN1FXWlJ2aHZwREcifQ==; ghost-auth.sig=AckalTHe3uxtmzrptGUZYMkHi20' -H 'Connection: keep-alive' --compressed
```

### Technical details:

* Ghost Version: 1.0.0-alpha-7
* Node Version: v6.7.0
* Browser/OS: Mac Chrome
* Database: PostgreSQL
* SSL: valid Let's Encrypt certificate used

**Comment by kirrg001** [comment]
Hey @spamguy 👋

I assume that your registered public client id does no longer exists on our dev auth server. We already had this case last week with a different developer. The solution to this is to reset your database and try again. If you still hit a problem, can you please swing by our [slack channel](https://ghost.org/slack/)?If this turns out to be an actual issue with Ghost this issue can be reopened. Thanks!

Are you aware of the fact that you are using an alpha version of Ghost? (`1.0.0-alpha-7`).
The alpha versions are for development only!
So if you would like to setup a production blog on your droplet, i recommend using the latest LTS version. See https://ghost.org/developers/

Are you aware of the fact that we dropped PostgreSQL support?
You can read here why: https://dev.ghost.org/dropping-support-for-postgresql/

**Comment by spamguy** [comment]
Node v6 support is a must due to another app on the environment using it. Plus, I'm fine with the tinkering and reporting back.

I wasn't aware of the blog post about PostgreSQL, though. Bummer. If I decide to switch to MySQL I will report back.
