### ISSUE TITLE
.json file import failed

### ISSUE THREAD

**Issue by curlymario** [TryGhost/Ghost#7738]
First of all, I'm new to github so please forgive me if I'm doing anything wrong by opening this issue.

### Issue Summary
I have just set up three ghost blogs up and running on the same Digital Ocean server on the same domain with different subdirectories (/en /ru /journal).
All three are version 0.11.3
When I'm trying to import .json file from one ghost blog to another it sais “Import Failed”. That's it, just “failed” no further details.

### Steps to Reproduce

1. I downloaded .json file from /ru blog
2. Set up /journal blog with the same user name, email and password
3. Tried to upload this .json
4. Fail

I thought maybe I shouldn't create the same user, so
1. I once again downloaded .json file from /ru blog
2. Set up /en blog with different user name and email
3. Uploaded new .json
4 Fail

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 4.6.0
* Browser/OS: DigitalOcean Ubuntu 14.04
* Database: huh? default probably, I don't remember setting up any databases

**Comment by kirrg001** [comment]
Hey @curlymario Sorry to hear you are having trouble. It's hard to say why your database import failed without seeing the server log or without providing your JSON file to us.

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
