### ISSUE TITLE
README.md. Section "Developer Install". Step "install bower" missed.

### ISSUE THREAD

**Issue by ringill** [TryGhost/Ghost#7770]
### Issue Summary

Miss step in README.md. Section "Developer Install". Step "install bower" missed.

### Steps to Reproduce

1. Follow step by step "Developer install" in README.md upon "grunt init" command.
2. On "grunt init" throws error:
```bash
Running "shell:bower-install" (shell) task
Verifying property shell.bower-install exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal, execOptions={"env":null}
Command: bower install
"bower" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
Warning: Command failed: bower install
"bower" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
 Use --force to continue.

Aborted due to warnings.
Warning: Failed running "grunt init --verbose" in "core/client". Use --force to continue.

Aborted due to warnings.
```
### Technical details:

* Ghost Version: commit dc605580839162595813d066a2e64b53c462bbef on master branch
* Node Version: 6.9.1
* Browser/OS: command line in windows 10 x64
* Database:

**Comment by kevinansfield** [comment]
Hi @ringill, thanks for trying out Ghost! `master` is currently in an alpha state and under heavy development [in the run-up to 1.0](https://dev.ghost.org/lts/) and so not fully documented yet. The `grunt` tasks have actually been deprecated and replaced with `gulp` tasks in master.

I'm going to close this issue as the `grunt` tasks aren't supported int the version you are running, if you have the same problem using the `stable` branch please open a new issue, thanks 😄 

If you are looking to run a site or develop themes rather than develop the core software I would recommend checking out the stable branch or downloading the latest release, you'll have a much smoother experience.
