### ISSUE TITLE
undefined module of 'versioning' during migration from 0.7.6 to 0.11.3

### ISSUE THREAD

**Issue by 1919yuan** [TryGhost/Ghost#7775]
### Issue Summary

I downloaded ghost v0.11.3 and was trying to copy the files and overwrite my existing installation of 0.7.6.
After `npm install`, when I run `npm start --production`, it errors out saying
"canMigrateFromVersion" is not found in undefined.

After looking at the code, I found that if I change the line

    versioning = require('../schema').versioning,

in core/server/data/migration/update.js to

    versioning = require('..schema/versioning')

then the code can continue running. I had to do the same kind of syntax modification a few other places to finally make the database migration code work, and run ghost 0.11.3.

I'm running Ghost on Debian Testing distribution with Linux kernel version 4.6.0.1 with node v4.2.1, not sure whether the Testing distribution is problematic here, but from the code change to make the migration work, I don't think it's related to kernel version as long as the node version I'm running is supported.

### Steps to Reproduce

Just install 0.7.6, put in some post and overwrite with 0.11.3.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect the upgrade would succeed without me changing the js code.

### Technical details:

* Ghost Version: 0.7.6 -> 0.11.3
* Node Version: 4.2.1
* Browser/OS: Debian Stetch Testing 
* Database: Sqlite 3

**Comment by kirrg001** [comment]
Hey @1919yuan Sorry to hear you are having trouble.
You have updated from `0.7.6` and this version contains a `schema.js` file.
See https://github.com/TryGhost/Ghost/tree/0.7.6/core/server/data

It looks to me this file is still left in your file tree. And this file does not contain an object called `versioning`. That's why your fix worked. Glad you figured out a solution to update to `0.11.3` successfully. 

I assume something went wrong when you deleted the old files (see http://support.ghost.org/how-to-upgrade/#3.-delete-the-old-files)

If you have further questions can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? Thanks 👍
