### ISSUE TITLE
Add additional variable for count of words

### ISSUE THREAD

**Issue by ivanursul** [TryGhost/Ghost#7776]
I need to know how much words do I have in my article. Can you add such variable ? Or is there a way I can do that using handlebar handlers ?

**Comment by eashish93** [comment]
You can count that via `get` helper function in javascript. The thing you have to do is to fetch the current post, then using `array.split(' ')` method count the no of words.

**Comment by kevinansfield** [comment]
Hi @ivanursul, word count is something that is potentially subjective - eg, the count may work differently depending on the post's language or if words should only be counted in a particular section of a post. As such I don't think it's a great candidate for a core feature.

There are a couple of ways this could be achieved without it being added into core:
1. calculate the word-count client-side with JS, if the full post is already displayed then you can use JS to count the words or if you are listing posts then it's possible to use the public API to fetch the post content and count the words that you are interested in
2. add a custom handlebars helper/app - we don't have an official story for custom helpers or apps yet but it is possible, this tutorial seems to cover things well (although I haven't tried it personally) https://github.com/google/caja/issues/2014. Please do head over to our [slack channel](https://slack.ghost.org) if you need any help 😄 Once 1.0 is released we'll be focusing on a well-supported method for apps and other customisations.

If you believe that this is still a good candidate for being added to core please add it on our [public wishlist](https://ideas.ghost.org) - other users can vote for ideas and we can use that to gauge the need/desire for new features

Hope that helps in some way 😄 I'm going to close this as it's a feature request rather than a bug and we try to keep Github solely for bug tracking and on-going development work.
