### ISSUE TITLE
ghost.url.api as an independent NPM module

### ISSUE THREAD

**Issue by andrewmclagan** [TryGhost/Ghost#7785]
### Issue Summary

Access the `ghost.url.api` utility as an independent npm module to consume data ghost as a headless blog / CMS within another website.

----

is this possible?

**Comment by oliverbenns** [comment]
+1

**Comment by andrewmclagan** [comment]
@oliverbenns Im also looking at integrating with redux, how has this gone for you / your team? We are considering either ghost or wordpress as a headless driver for blog and page content. 

Do you have any recommendations or pitfalls we should be aware of? :-)

**Comment by oliverbenns** [comment]
Right now we're only going to be getting latest posts. But after Googling and not finding much it's got me tinkering some more, hoping to create a repo sometime next week. I can't see many issues right now, but it's early stages at the moment.

**Comment by ErisDS** [comment]
I have to say, I didn't really understand what this issue meant at first. I think I'm starting to get what the request is now - you're looking for a util you can include inside of a module system in order to construct urls for posts using the same pretty syntax that Ghost has elsewhere?

The existing tool was a quick utility we put together to help people get past the main hurdles of using the API - that is constructing URLs properly for the API and not hitting up against cross origin and cross protocol issues. It's not the final version, and this utility is definitely going to need to move & get an overhaul before the public API comes out of beta.

Despite the tool being there, I've already had countless issues passed to me via various channels, all people telling us the API doesn't work, only to find they aren't using the tool and they've constructed a URL wrong. 

Therefore, I think it's primary function is pretty valuable, if only we could get developers to use it!

Unfortunately, the nicest functionality we have with ghost-url.js cannot physically be replicated as an external module. If you take a look at the source served by a Ghost blog, you'll see that the correct URL for the API is injected by the Ghost server - i.e. it's not a reusable script, but custom to every blog.

That's why we recommend requiring the script direct from the blog you're trying to talk to - it's then preconfigured.

I think the idea of an external toolkit is great, however I don't think it's something we'd want to invest in until we take the public API out of beta and settle on what the toolset needs to look like.

**Comment by oliverbenns** [comment]
Yeah that's fair enough. On the other hand, sometimes the api's response isn't entirely useful, I've mistyped the url a couple of times (like missing a trailing slash on request post/user/tag id) and instead of returning a 404 it returns a CORS error.

The only thing that the script seems to depend on is the url. It's possible that you just create a wrapper and pass it in as an argument (e.g. `createApiHelper(host, apiVersion)`), but yeah sure if there hasn't been much demand for it then maybe it's not a priority.

**Comment by ErisDS** [comment]
The issue with trailing slashes & CORS is tracked over in https://github.com/TryGhost/Ghost/issues/7839 :)

> The only thing that the script seems to depend on is the url.

What I'm trying to say is that figuring out the correct api base url is one of the hardest parts of using our API, and therefore, that's exactly why we added this utility ;) 
Sure, it has other useful features, like getting the trailing slashes right, and neatly adding query params, however IMO auto-including the base url is the nicest feature 😁 .

**Comment by ErisDS** [comment]
Gonna close this for now. I'm very keen to see people build community tools and also to let us know what they find or would find useful.

We need to revisit the way this tool works in the near future, so feedback will be taken on board and factored into that project :)

**Comment by oliverbenns** [comment]
@andrewmclagan A little late, but this might be of use to hook Ghost up to a redux build: https://github.com/oliverbenns/redux-ghost
