### ISSUE TITLE
Can you use Ghost without a Ghost.org account? 

### ISSUE THREAD

**Issue by anthonydelgado** [TryGhost/Ghost#7803]
Anyone familiar with the "Ghost" CMS know if there is a straightforward way of using it without relying on their oAuth for authentication?

**Comment by kevinansfield** [comment]
Hey @anthonydelgado, it sounds like you're trying to run the `master` branch which is currently in alpha state and under heavy development and therefore not documented yet.

It's definitely possible to run without using the central OAuth system in the same way that the current stable branch does authentication, however if you are looking to run a site or develop themes rather than develop the core software I would recommend checking out the `stable` branch or [downloading the latest release](https://ghost.org/developers/).

I'm going to close this issue as we use github solely for bug tracking and feature development. If you require installation help or other support please come say hello on [our slack team](https://slack.ghost.org) 😄

**Comment by anthonydelgado** [comment]
cool. will do. Thanks Kevin!
