### ISSUE TITLE
Update Readme add Knex Init

### ISSUE THREAD

**Issue by oscarmorrison** [TryGhost/Ghost#7827]
### Issue Summary

Update readme instructions to include 
`knex-migrator init`

### Steps to Reproduce
1. checkout fresh repo
2. go through readme dev instructions for setup
I then get an error 

I was able to get around this error by running:
`knex-migrator init`
<img width="665" alt="screen shot 2017-01-08 at 2 16 35 pm" src="https://cloud.githubusercontent.com/assets/1651212/21752830/5653875e-d5ad-11e6-9658-26937f625a1b.png">

**Comment by kevinansfield** [comment]
Hey @oscarmorrison, the `master` branch is currently in ["alpha" status](http://support.ghost.org/v1-0-alpha/) so there is a lot of documentation and some tooling that is out of date and there's not much point updating it at the moment as it's all subject to change. Once we near the 1.0 release we will be updating all of the documentation with the final tooling and recommended install/setup procedures.

If you are trying to install the current stable version in order to run ghost or develop themes etc please checkout the `stable` branch (latest release) or the `lts` branch (what will become the next maintenance release)
