### ISSUE TITLE
CORS middleware should be processed before redirects

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7839]
### Issue Summary

If a user attempts to use the public API via browser JS and forgets to add a trailing-slash they will receive a redirect response with no CORS headers causing the request to fail.

Although it's preferable to always hit the trailing-slash endpoints the CORS error message is misleading as it suggests the whitelisted domain setup is incorrect rather than the requested URL being incorrect.

### Technical details:

Now that the API app is better separated from the blog app I think we should register the CORS middleware before any other middleware so that the `maintenance` and `prettyURLs` middleware 
won't cause unexpected errors.

We also have the `checkSSL` middleware however I'm not sure if we should be returning CORS headers for those redirects, I think it's safer to block a non-secure request that should be secure rather than letting it redirect?

**Comment by ErisDS** [comment]
> I think it's safer to block a non-secure request that should be secure rather than letting it redirect

There's a config that lets the user determine whether they want secure requests to redirect or not, although it's one of the messy config values that ideally needs revisiting in Ghost 1.0 as part of the [audit](#7488) issue. 

The checkSSL middleware only redirects if it is allowed to, or otherwise blocks the request. CORS should probably be done before this as well to prevent the same issue?
