### ISSUE TITLE
500 error on Setup

### ISSUE THREAD

**Issue by dpawson905** [TryGhost/Ghost#7870]
I am trying to set up Ghost on my server using Plesk Onyx.  I have NodeJS setup and all of the directories are correct and I can go to my domain and the main page loads but when I try to go into setup I get a 500 error and I cant figure out what is causing this to happen.  I have included the console screenshot from Chrome.  Any help would be appreciated.  

Thanks

* Ghost Version: 0.11.4
* Node Version:  6.9.1
* Browser/OS: Chrome/Windows 10

![capture](https://cloud.githubusercontent.com/assets/20251795/22183610/ff9d1cde-e08f-11e6-96af-d04f8be563fd.PNG)

**Comment by kevinansfield** [comment]
Hi @dpawson905, sorry to hear you're having trouble getting set up. Unfortunately we only use GitHub for bug tracking and on-going development rather than support requests. If you need help getting Ghost installed and configured please head over to our [slack channel](https://slack.ghost.org) where the community is more than happy to help 😄 

As a starting off point I would suggest you look into the cause of the `net::ERR_TOO_MANY_REDIRECTS` error - it sounds like there may be something in your proxy/ghost setup that isn't configured correctly.
