### ISSUE TITLE
Mailgun mail returns Error: connect ETIMEDOUT 52.0.63.157:587

### ISSUE THREAD

**Issue by nodesocket** [TryGhost/Ghost#7915]
Configured Mailgun with the following in `config.json`:

````
mail: {
    transport: 'SMTP',
    options: {
        service: 'Mailgun',
            auth: {
                user: 'postmaster@mailgun.mydomain.com',
                pass: process.env.MAILGUN_PASSWORD
            }
        }
},
````

When I try to send an e-mail _(e.g. forgot password or test in admin)_, the request `500` errors with:

    {"errors":[{"message":"Error: connect ETIMEDOUT 52.0.63.157:587","errorType":"EmailError"}]}

Doing a whois on `52.0.63.157` returns this is an AWS ip address. Quite strange.

* Ghost Version: 0.11.4
* Node Version: 6.9.4
* Browser/OS: Ubuntu 16.04 LTS
* Database: sqlite3

**Comment by wan-qy** [comment]
>user: 'postmaster@mailgun.mydomain.com',
 pass: process.env.MAILGUN_PASSWORD

That's wrong.
For example, you hava a domain mail.dm.net, and username is "xxx",password is "yyy", you shou do like that
```
user: 'xxx@mail.dm.net',
pass: process.env.MAILGUN_PASSWORD
```
and
```
export MAILGUN_PASSWORD=yyy
```

**Comment by nodesocket** [comment]
I'm confused, I am using the `Default SMTP Login` listed in Mailgun with `Default Password`. I just changed to `postmaster@mailgun.mydomain.com` to protect my actual domain. Replace `mydomain.com` with my actual domain. Am I still doing something incorrect?

Do I need to open any firewall rules for this? Certainly seems like it, since the request is timing out.

**Comment by kirrg001** [comment]
Hey @nodesocket Sorry to hear you are having trouble.

I'm going to close this issue as we use github solely for bug tracking and feature development. 
Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? If this turns out to be an actual issue with Ghost this issue can be reopened. Thanks!

**Comment by mgilbir** [comment]
As I ended up here with the same problem and for the sake of documentation, I got help on the slack channel and it turned out to be that my host is blocking the default SMTP ports.

You can telnet out to port 587 and see if you can connect. If not, you may want to try an alternative port as Mailgun SMTP is also available on 2525.

**Comment by burningTyger** [comment]
For the sake of documentation let me note that scaleway blocks outgoing smtp ports too. Took me an hour to pinpoint.
