### ISSUE TITLE
Subdirectory install, assets not loaded

### ISSUE THREAD

**Issue by maxpv** [TryGhost/Ghost#7952]
Freshly installing Ghost (last build, official documentation followed) configured in a subdirectory of a subdomain :`my.site.io/blog/` leads to unloaded assets on the front page. This means that .Js and .CSS files are being searched at `my.site.io/assetsroot`.

The same goes on with the generated link of an article : `my.site.io/post-url` instead of `my.site.io/blog/post-url`.

It looks like `production.url` is not being used entirely.

Here is my nginx configuration file :

```
server { 
listen 80; 
server_name my.site.io www.my.site.io; 

location ^~ /blog { 
proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Host $http_host; proxy_set_header X-NginX-Proxy true; proxy_pass http://127.0.0.1:2368; proxy_redirect off; 
} 
} 
```

Ghost has been started through with `NODE_ENV=production; forever start index.js`

**Comment by kirrg001** [comment]
Hey @maxpv Sorry to hear you are having trouble.

Did you follow [how to install ghost in a subdirectory](https://www.ghostforbeginners.com/how-to-install-ghost-in-a-subdirectory/)?
Can you please swing by our [slack channel](https://slack.ghost.org) and ask in the #help channel?

This doesn't look like a bug to me right now. I'm going to close this issue as we use github solely for bug tracking and feature development.  If this turns out to be an actual issue with Ghost this issue can be reopened 👍
