### ISSUE TITLE
Navigation values exist, yet 0 iterations in foreach on Navigation

### ISSUE THREAD

**Issue by Cahl-Dee** [TryGhost/Ghost#7988]
### Issue Summary
Navigation helper is not returning any values when attempting to iterate over it with a foreach. Meanwhile, I can confirm that {{#if @blog.navigation}} evaluates true.

### Steps to Reproduce

1. Create ghost/content/themes/[theme]/partials/navigation.hbs with:
```
{{!-- Navigation --}}
<ul class="nav navbar-nav navbar-right doYouReadMe {{#if @blog.navigation}}weHaveNav{{/if}}">
    {{#foreach navigation}}
        <a href="{{url absolute="true"}}">{{label}}</a>
    {{/foreach}}
</ul>
```
2. Restart ghost 
3. Load page and inspect with dev tools to see the following:
```
<ul class="nav navbar-nav navbar-right doYouReadMe weHaveNav">
    ::before
    ::after
</ul>
```

While loading the "Navigation" page in the admin area, my Nav items load without any issues. Checking the databse, the Nav items appear to be formatted properly:
```
mysql> select settings.key, settings.value from settings where settings.key = 'navigation';
+------------+--------------------------------------------------------------------------------------------------------------+
| key        | value                                                                                                        |
+------------+--------------------------------------------------------------------------------------------------------------+
| navigation | [{"label":"home","url":"/"},{"label":"about","url":"/about/"},{"label":"google","url":"https://google.com"}] |
+------------+--------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### Technical details:

* Ghost Version: 0.11.4 - installed via zip in early January
* Node Version: 4.2.6
* Browser/OS: tested in Chrome 56.0, Firefox 49.0 and Edge 38 / Windows 10
* Database: mysql 5.5.41
* OS: Ubuntu 12.04.5 LTS
* Theme: [Omikron 1.4](https://themeforest.net/item/omikron-minimal-responsive-bootstrap-ghost-theme/6138330) (paid, ask if code snippets needed)

**Comment by kevinansfield** [comment]
Hey @Cahl-Dee! Sorry to hear you are having trouble with your theme. From your report it sounds like you are conflating two separate things, you are checking for the existence of navigation data using `@blog.navigation` and then trying to iterate over the `{{navigation}}` helper rather than the `@blog.navigation` data.

`{{navigation}}` is a [built-in helper](http://themes.ghost.org/docs/navigation) that outputs the full navigation bar HTML for you. If instead you want to loop over each of the navigation items yourself you would need to do this:

```
{{#foreach @blog.navigation}}
  <a href="{{url absolute="true"}}">{{label}}</a>
{{/foreach}}
```

I'm going to close this issue as we use Github for bug-tracking and feature development only. If you need any further help please head over to our [Slack team](https://slack.ghost.org), thanks 😄

**Comment by Cahl-Dee** [comment]
Thanks again for our chat in Slack, @kevinansfield 

Want to keep everyone updated here. The issue was that, in my template, I was calling the navigation incorrectly.

In order to preserve the correct context within navigation.hbs, you need to be sure that you are calling it via:
`{{navigation}}`

My problem was that I was calling it **incorrectly** as:
`{{> navigation}}`

**Comment by grevory** [comment]
@Cahl-Dee For someone new to both Handlebars and Ghost what exactly does that mean in context to your original issue, which is the issue I am having. I have no idea where `{{navigation}}` goes in this template.
