### ISSUE TITLE
Dependency 'validator' do not support isNull

### ISSUE THREAD

**Issue by michael34435** [TryGhost/Ghost#7996]
### Issue Summary

Dependency 'validator' do not support isNull and it throw undefined error in `core/server/data/validation/index.js:188`

### Steps to Reproduce

1. Enter to admin panel
2. Go to general
3. UPLOAD THEME

### Technical details:

* Ghost Version: 0.11.4
* Node Version: 6.9.1
* Browser/OS: debian
* Database: sqlite3

**Comment by kirrg001** [comment]
Hey @michael34435 Sorry to hear you are having trouble.

`isNull` is not used in `0.11.4`, see https://github.com/TryGhost/Ghost/pull/7823.
Uploading themes works 100% on `0.11.4`.
I assume when you have updated Ghost to `0.11.4`, something went wrong?

Could you re-follow our [how to update Ghost guide](http://support.ghost.org/how-to-upgrade/)?
If you still need help, can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened.
