### ISSUE TITLE
Handle invite gracefully when logged in

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8028]
If you are logged in and you click an invite link, you are getting a 500 error in Ghost-Admin. It's complaining that the route is not available.

![jajaja](https://cloud.githubusercontent.com/assets/1160712/23126287/41ea4f7e-f776-11e6-8e34-70de50286bc1.png)

Steps to reproduce:
1. Setup a blog
2. Invite an email you have access to
3. Click on the invite link
4. Ensure you are still logged in with the owner user
5. You will see a 500 error.

Ghost: master only

**Comment by ErisDS** [comment]
I'm seeing what I think is a slightly different version of this.

When logged out, and attempting to accept an invite, I'm getting an error 

![](https://puu.sh/vhQJA.gif)

I'm not sure if this is related to the 503 error or not, but the error text is

> TypeError: Cannot read property 'htmlSafe' of undefined

**Comment by ErisDS** [comment]
It seems the above was due to the same case - where I was logged into ghost.org with a user that was already a member of the blog.

I.e. I did the following

- logged in as the owner user
- invited a second account
- logged out of Ghost
- tried to accept the invite of the second account whilst still logged in as the owner on ghost.org

**Comment by kevinansfield** [comment]
Note that this only seems to be an issue for Ghost OAuth - when using password auth you get a warning:

![screen shot 2017-04-26 at 14 02 47](https://cloud.githubusercontent.com/assets/415/25435769/10b6c356-2a89-11e7-9c77-52a089a06ff9.png)
