### ISSUE TITLE
Menu button Ghost-Admin

### ISSUE THREAD

**Issue by roramirez** [TryGhost/Ghost#8134]
I'm  not sure if this can be here. I tried found on Ghost-Admin but the feature issues is not available.

On the last update from the master branch master 6933a751bc6921f26c6230500801474724e2e9e3  the menu button have a weird style. Also,  the master from Ghost-Admin is present too.

I tested on Firefox and Chrome and look the same.

![screenshot at 2017-03-12 19-23-07](https://cloud.githubusercontent.com/assets/2161075/23836582/57c55332-0759-11e7-9d9b-310f32eab5da.png)

**Comment by acburdine** [comment]
@roramirez This is already a known issue - and it occurs because there's still some broken styling where buttons are concerned 😄 The styling for Ghost 1.0 is still a bit of a WIP.

As to future issues with Ghost-Admin, issues are to be submitted here instead of in that repo, so that there's a central place. (essentially, you opened the issue in the right place 😉)

**Comment by kevinansfield** [comment]
Hey @roramirez, this issue is already being tracked as part of the 1.0 UI overhaul https://github.com/TryGhost/Ghost/issues/8021 (the split button publishing flow is going away).

Expect quite a few UI issues at the moment, we're still in alpha ;-) Keep an eye on our dev blog https://dev.ghost.org - we'll be releasing betas soon and will be definitely be looking for more feedback from that point 😄
