### ISSUE TITLE
editor card selection

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#8194]
Currently there is a blank line on either side of a card which the cursor can navigate into, this is actually a part of the card and aids in selection. By design it should be inline on either side of it.

When in either one of these blank lines you cannot type, all you can do is navigate to and from that line and delete the card that it's attached to.

Because the inclination is to want to type when you see a cursor (and expect it to work) we want to make this a bit more usable.

Idea 1) when the cursor is located inside one of these lines select the card itself and remove the range from the DOM.
idea 2) when a user types when the cursor is in one of these lines create a paragraph either above or below the card for the user to type into.

**Comment by ErisDS** [comment]
My findings from 8243

I've had a bit a play with the editor and found a few cases where the card menu / interactions didn't behave as I expected. I've collected them together into one issue, but let me know if I should do this differently. 

**1. Initial card has no add menu**

I already mentioned in #8191 that I can't use tab to get to the editor. Therefore I'm either using the mouse to click or the down arrow.

When I get my cursor to the editor, I can type, but I do not get the card + menu. If I type a character and delete it, or just hit backspace, then the + appears and then jumps down really far!

**2. Extra paragraph added above image card**

If I use the + menu on a brand new empty line to add an image card, it gets added *after* the empty paragraph, instead of inline.

This doesn't happen if I drag an image onto the editor. It also doesn't happen if I add an embed card.

I tested this on the previous version of the card selection and had the same problem - it was not the old empty para above and below the cards. It's an extra additional paragraph, or rather the one I'm on doesn't get removed. As far as I can tell this doesn't happen for any other card.

**3. No way to delete markdown card**

There's a cancel and a save button, but no delete.

**4. No way to get cursor after a non-text card**

Once you add an image, ember or markdown card etc - any non-text card, it is no longer possible to get the cursor to go after it, to add a new text card.

**5. Console error & cards stop working**

There is a case where I can no longer add cards and I get the following error in the console:

![](https://puu.sh/v3JPJ.png)

I don't know what the reproduction case is for this at the moment, it happens after I've added and removed a few cards, when I try to add a new card. 

**6. Unknown error and cursor not working**

Not sure how I got this one, only saw it once.

![](https://puu.sh/v3KvX.png)

This was an editor that had a text card and a markdown card. I saw this error appear twice whilst clicking around. I wasn't able to insert my cursor back into the text card with my mouse anymore.

**7. Markdown text appears in text card**

I also managed to achieve this by pressing the delete button at an opportune moment

![](https://puu.sh/v3KCs.png)


**Note:** Issues 6 & 7 I have only reproduced one time. Issue 5 I get fairly regularly. I will continue to play with the editor over the next few days to try to narrow down reproduction cases for each bug.

**Question:**

I prefer the new selection over the older version. Not sure what the full plan is, however if I hit backspace or delete with the card selected (I think hard selected - double border), that no longer works at all (before it did it without any obvious selection, which is not good either, obviously :D). Is that the intentional? Or will we get it back. I don't know why, but clearly from using some other product I expect the first press of backspace when I'm after the card to hard-select, and the second one to actually delete? This is more of a suggestion than anything.

- [ ] 1. Initial card has no add menu
- [ ] 2. Extra paragraph added above image card
- [ ] 3. No way to delete markdown card
- [ ] 4. No way to get cursor after a non-text card
- [ ] 5. Console error & cards stop working
- [ ] 6. Unknown error and cursor not working
- [ ] 7. Markdown text appears in text card

## Technical Details

Ghost-Admin: f5fc35f
Browser: Chrome 56

**Comment by JohnONolan** [comment]
Oh good - I was going to write "cant do card selection" but then hannah wrote an actual useful report

**Comment by disordinary** [comment]
Yeah, I was asked to merge the progress even though it wasn't completed.

I've copied the checklist from Hannah below as I can't uncheck her ones.
- [ ]    1. Initial card has no add menu
- [ ]    2. Extra paragraph added above image card
- [ ]    3. No way to delete markdown card
- [ ]    4. No way to get cursor after a non-text card
- [ ]    5. Console error & cards stop working
- [ ]    6. Unknown error and cursor not working
- [ ]    7. Markdown text appears in text card

**Comment by disordinary** [comment]
Numbers 12 and 26 above are both a bug in Safari where you can't get the location of a collapsed range. One solution is to create a new expanded range and measure that, however that isn't always possible (for instance if the paragraph that the cursor is in is empty). I've put in place a workaround for 12 for now and I'll dig around for a proper solution when I've gone through more pressing issues.

**Comment by disordinary** [comment]
Issue 29 is related to issue 1, I wrote a workaround for 1 but a fix for 29 will need to be done in mobiledoc itself and will take some time.

**Comment by disordinary** [comment]
#25 is working in edge but not IE 11.

**Comment by disordinary** [comment]
Closed in favor of:
https://github.com/TryGhost/Ghost/issues/8313
https://github.com/TryGhost/Ghost/issues/8312
https://github.com/TryGhost/Ghost/issues/8311
https://github.com/TryGhost/Ghost/issues/8310
