### ISSUE TITLE
[alpha.17] Incorrect Ghost version

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8228]
### Issue Summary

`ghost -v` shows incorrect version

### Steps to Reproduce

1. Install Ghost alpha.17
2. Run `ghost -v`

### Technical details:

Ghost Version: alpha.17
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB
Browser: Comodo Dragon

### Log
```
root@ghost:/var/www/ghost# ls -ld current
lrwxrwxrwx 1 root root 38 Mar 23 01:49 current -> /var/www/ghost/versions/1.0.0-alpha.17
root@ghost:/var/www/ghost# ghost -v
1.0.0-alpha.12
```

**Comment by kevinansfield** [comment]
`ghost -v` is showing the version of the `ghost` command (https://github.com/tryghost/ghost-cli latest is `alpha.15`, you might want to run `npm install -g ghost-cli` to update 😉) not the version of Ghost which could be multiple versions across multiple installs on one machine.

Closing as this is expected behaviour 😄

**Comment by PaszaVonPomiot** [comment]
@kevinansfield Okay, good to know. Maybe we could update usage info for `ghost` command:
`    -v, --version      output the version number`
to
`    -v, --version      output the ghost-cli version number`
