### ISSUE TITLE
[alpha.18] Give contributors some love

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8270]
### Issue Summary

Some missing img assets:
```
ERROR [2017-04-04 18:20:33] "GET /ghost/assets/img/contributors/sebgie.png" 404 115ms
ERROR [2017-04-04 18:20:33] "GET /ghost/assets/img/contributors/mixonic.png" 404 119ms
ERROR [2017-04-04 18:20:33] "GET /ghost/assets/img/contributors/tgriesser.png" 404 122ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found. 
```

### Steps to Reproduce

1. Open "About Ghost" page

### Technical details:

Ghost Version: alpha.18
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29
Browser: Comodo Dragon

### And...
Cheers from Poland!

**Comment by kirrg001** [comment]
Hey @PaszaVonPomiot  👋 Thanks for your report. 

I am not able to reproduce this.
@kevinansfield ?

**Comment by kevinansfield** [comment]
I can confirm, the .png assets were hashed by the ember build but it doesn't look like the image references in the template were automatically updated.

```
...
-rwxr-xr-x  1 kevinansfield  staff   1.6K  4 Apr 12:47 kevinkucharczyk.jpeg
-rwxr-xr-x  1 kevinansfield  staff   1.3K  4 Apr 12:47 kirrg001.jpeg
-rw-r--r--  1 kevinansfield  staff   3.8K  4 Apr 12:47 mixonic-1ff87736dd02cfa080ae109b45131aa6.png
-rwxr-xr-x  1 kevinansfield  staff   1.5K  4 Apr 12:47 rwjblue.jpeg
-rw-r--r--  1 kevinansfield  staff   3.6K  4 Apr 12:47 sebgie-0fb02df00ee7834dbcc8beba84aec81e.png
-rw-r--r--  1 kevinansfield  staff   3.8K  4 Apr 12:47 tgriesser-d871cbf74a871c0fb6d855e76a893f7e.png
```

I'll change the asset rewrite config to include `.jpeg` assets (I think it's expecting `.jpg` at the moment) and modify the template so that it's not using the `{{gh-path}}` helper that is breaking the asset rewrite build step.
