### ISSUE TITLE
New->Edit transition refactor

### ISSUE THREAD

**Issue by disordinary** [TryGhost/Ghost#8287]
General overview of required changes outlined in https://github.com/TryGhost/Ghost/issues/8287#issuecomment-292184700

Issues that should be fixed when this lands:
- [ ] https://github.com/TryGhost/Ghost/issues/8750 Split-screen mode lost on new->edit transition

---

Currently ghost-admin doesn't create a post until the user makes a change in the editor. This causes the editor to reload which in turn resets the cursor position among other things.  

We unsuccessfully try and mask this by moving the cursor to the end of the content.

This:
1. Causes a visible jump in the cursor.
2. It doesn't actually successfully jump to the end so the user ends up with mangled words.
3. If a user opens the `/` menu it just flickers visible as the page is reloaded.
4. There's a few bugs which only appear on the new page and not the edit page for some reason:
    1. The title placeholder text appears over the body rather than the title
    2. The '+' menu doesn't appear on the first blank paragraph.

**Comment by kevinansfield** [comment]
I've been thinking about this for a while and we went through my plans to eliminate it on Slack a while back https://ghost.slack.com/archives/C09JM0TCK/p1489655198744663

The outline of the refactor discussed there:
- add an explicit `editor` route/controller/template triad
- remove the editor base route/controller mixins and move their logic into the top-level editor route/controller
- remove the new/edit controllers and move the `editor/edit.hbs` template to `editor.hbs`
- the new/edit routes will now be very basic, they'll create or fetch the post model and update the parent `editor` route's controller
- the editor rendering is now controlled by the top-level route so switching from new->edit child routes won't force a re-render, the editor controller's `model` won't be replaced as the reference will stay the same so components won't be re-rendered either
- we'd no longer be able to use Ember's standard loading route to display a spinner whilst the post is fetched in the edit route but we should be able to work around that by using the `edit` route's `model` hook to update properties in the `editor` controller (during the new->edit transition that hook won't be called because we can pass the existing model in)

**Comment by disordinary** [comment]
That sounds good, I should have work arounds for most of the bugs but there is no solution to the actual physical reloading of the editor with the current setup.

Other options which may be simpler are:
1. Reload on title OR editor change.
2. Reload when the user navigates from the title to the editor and the title has changed OR the editor has changed.
3. Don't reload at all until the user explicitly saves the document.
