### ISSUE TITLE
Support DigitalOcean's smallest droplet size in their one-click app install

### ISSUE THREAD

**Issue by folz** [TryGhost/Ghost#8295]
### Issue Summary

Ghost's DigitalOcean one-click app doesn't support the $5/mo droplet size (error: "This size doesn't have enough disk space to support the image you selected").

### Steps to Reproduce

1. Open the "One-click apps" tab at https://cloud.digitalocean.com/droplets/new
2. Select "Ghost 0.11.7" in the "Choose an Image" selection.
3. Scroll down to "Choose a size" and attempt to select the $5/mo droplet.

**What did I expect to happen:**

I would be able to select the $5/mo droplet because Ghost has an advertised size of 4mb, which is smaller than the 20gb in disk space provided by the $5/mo droplet.

**What actually happened:**

I received the error message "This size doesn't have enough disk space to support the image you selected" -- the droplet has 20gb in disk space provided.

The smallest droplet I can select is the $10/mo droplet, with 30gb in disk space provided.

### Technical details:

* Ghost Version: N/A
* Node Version: N/A
* Browser/OS: Firefox on Linux, but probably N/A
* Database: N/A

**Comment by ErisDS** [comment]
Hi @folz, I'm afraid you'd need to raise this with DO - we don't control the images they provide.

Nonetheless, I'd guess the reason they don't allow Ghost installs on the $5 is due to the lack of memory, rather than disk space. When doing an upgrade, you'd have to add swap space & I'm sure they get a lot of support requests.

In short - DO are telling you what they recommend, trying to downsize is going against their recommendations. Feel free to bring it up with them, but I would agree the $10 droplet is more suitable.

**Comment by folz** [comment]
For sure, thanks for the quick response! I'll take it up with them.

**Comment by MartynKeigher** [comment]
@folz ... I have Ghost running on a $5 droplet. Follow this guide: https://github.com/joepierce/ghost-on-digitalocean-512M by @joepierce 

Granted... while I'm not complaining about an extra $5 a month... I do want you to know that it _is_ possible!! :)

**Comment by aalster** [comment]
@MartynKeigher link is not available. Could you share your solution?

**Comment by ErisDS** [comment]
To provide an update here, we now control the DO image and the choice to not support the smallest droplet is deliberate. Although Ghost can run on the smallest droplet, it often fails with obscure memory errors when attempting to update. 

It's possible to work around that with swap and advanced knowledge, but the point of the one-click installer is to create a Ghost install that can be managed by pretty much anyone and therefore allowing creating Ghost instances on the smallest size doesn't fit that mission.

I'm going to lock this topic so that this remains the de-facto answer, if anyone wants to discuss this further, the [forum](https://forum.ghost.org) is a better place for it.
