### ISSUE TITLE
Code injection not sanitized correctly

### ISSUE THREAD

**Issue by cmchap** [TryGhost/Ghost#8317]
### Issue Summary

The code in the Code Injection page is not correctly sanitized.

### Steps to Reproduce

1. Put a dollar sign followed by a single quote `$'` within a `<script>` tag in either the Blog Header or Blog Footer fields. For example:
```HTML
<!-- Some HTML here -->
<script>
var test = '$';
console.log(test)
</script>
<!-- Some other HTML here -->
```
2. Save the changes you made on the Code Injection screen
3. Refresh any page on your Ghost blog
4. Look at the source code at the end of the `<head>` or `<body>` tags (wherever you put the `$'`)

### Expected Result

I expect the characters `$` and `'` to be treated just like they would be everywhere else in javascript. So the above example should print the string `$` to the console. Instead, the `$'` string is replaced with something else, which makes the variable `test` invalid, so nothing gets logged to the console. No error is raised in the console.  

### Observed Result

If you put the above example in the Blog Header, the `$'` string is replaced by the the closing head tag, and the entire body of the page, and the closing HTML tag. Then the *actual* closing head tag, body, and closing HTML tag are appended after that. It ends up looking like this:

```HTML
 <!-- Some HTML here -->
<script>
var test = '
</head>
<body>
<!-- ENTIRE BODY CONTENT OF YOUR GHOST BLOG PAGE HERE -->
</body>
</html>
;
console.log(test)
</script>
<!-- Some other HTML here -->
</head>
<body>
<!-- ENTIRE BODY CONTENT OF YOUR GHOST BLOG PAGE HERE -->
</body>
</html>
```

If you put the  above example in the Blog Footer, the `$'` string is replaced by two newlines, the closing body tag, and the closing HTML tag. It ends up looking like this:
```HTML
<!-- Some HTML here -->
<script>
var test = '

</body>
</html>
;
console.log(test)
</script>
<!-- Some other HTML here -->
```

I'm guessing it's some escaping issue when jQuery is used to do the code injection. 

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 4.8.1
* Browser/OS: Chrome Version 57.0.2987.133 (64-bit) on Mac OSX 10.11.6
* Database: sqlite3

**Comment by ErisDS** [comment]
This issue occurs both on LTS and on master, however we have only ever had one report.

I'm not 100% sure what the underlying cause is, however it is an extreme edge case, where the only impacted strings I can find are either:
-  `'$'` (single quote, dollar, single quote).
-  `'abc$'` (single quote, one-or-more chars, dollar, single quote).

If the single quotes are swapped for double quotes, the problem does not occur. E.g. `var test = "$";`
If any chars are placed after the dollar sign, the problem goes away again E.g. `var test = '$test';`

As double quotes are valid JavaScript and a simple workaround for this case, I'm going to close this issue. If we get more reports, we can investigate further.
