### ISSUE TITLE
Japanese text issue on the new WYSIWYG editor

### ISSUE THREAD

**Issue by mach** [TryGhost/Ghost#8319]
### Issue Summary

On Ghost Alpha's new text editor, Japanese text can't be typed correctly with Japanese IME (input method).

![untitled](https://cloud.githubusercontent.com/assets/82702/24944278/6743d564-1f95-11e7-80c8-eeedab8bbb7a.gif)

### Steps to Reproduce

1. Select Japanese IME (either Apple's JapaneseIM or [Google's Japanese IME](https://www.google.co.jp/ime/))
2. Type "watasi" 
3. Press Enter key

### Expected Result

At step 2: "watasi" should be converted to "わたし"
At step 3: "わたし" should be converted to "私"

###  Actual Result

At step 2: "watasi" is converted to "wあたし"
At step 3: "wあたし" is converted to "w"

### Technical details:

* Ghost Version:  1.0.0-alpha.19
* Node Version: v6.10.2
* Browser/OS: Google Chrome / macOS Sierra
* Database: MySQL 5.7.17

**Comment by disordinary** [comment]
Thanks @mach,

I just installed the Japanese keyboard on macOS and tried a few different options but couldn't replicate the issue. As a non Japanese speaker I have no idea what I'm doing though, perhaps we could chat in the Ghost Slack team (https://slack.ghost.org/) or organise a hangout?

**Comment by mach** [comment]
Hi @disordinary, thank you for following up.
I understand this issue is not easy to tackle by a non Japanese speaker..

Let me briefly explain about Japanese Input Method (IME):

1. Japanese has three different alphabets (1. Hiragana, 2. Katakana, 3. Kanji)
2. IME first converts English string (e.g. “watasi”) to Hiragana string (e.g. “わたし”) automatically
3. At this point, the string “わたし” is not confirmed yet or still in editing mode (as you can see the underline below the string)
4. When you press Space key, you can convert the Hiragana string “watasi” to other alphabets like  “私”
5. Finally, when you press Enter key, the string is confirmed

You can test above things in any textfield; TextEdit, Medium, etc.

The issue of Ghost Editor is:

- When you start typing Japanese string (which start with a consonant like “w”) in the body area, “w” is somehow confirmed BEFORE you press Space or Enter key
- That means, a word like “watasi” is divided into “w” & “atasi”, which is meaningless
- Besides, when you press Enter key to start a new line, the string “atashi” is disappeared

Please let me know if you need any help. I'm excited to see Ghost 1.0 😄

**Comment by ErisDS** [comment]
Hey @mach,

Thanks for the detailed bug report! I wasn't able to locate/add the Japanese IME keyboard on my mac at first, but I do have Chinese Simplified Pinyin, which I believe is a similar concept (although one conversion not two) and I was able to reproduce the error with my limited memory of how to ask how someone is in Mandarin 😁 
†
It seems to be a problem, specifically with the first character in the text card, after that. For example if I put english "Test" and then start typing it appears to work.

Now that I reproduced it that way, I experimented with the Japanese keyboard, installed that & selected Hiragana and got a similar although slightly different behaviour.

@disordinary If you choose Chinese - Pinyin Simplified and start typing the characters `ni` you should see this. Try just `ni` and you get this:

![](https://puu.sh/vhHZW.png)

Put any other character first and then type `ni` and you get a menu of options:

![](https://puu.sh/vhI1t.png)

This is slightly easier to reproduce/demonstrate in Chinese because this gives a pop over menu, whereas hiragana auto-converts as you type.

**Comment by disordinary** [comment]
Great, thanks Hannah.

This is an upstream issue in mobiledoc-kit, so I'll raise the issue there as well.

**Comment by disordinary** [comment]
Can we confirm that this only occurs in an empty paragraph?

**Comment by ITJesse** [comment]
I cannot use any other input method except English when I edit article on my iPad.
All input methods behave the same as English.But the hand write works well.
I don't know if it is a bug of Safari but I can only see it happen on the editor of Ghost.

Version of Ghost is 1.0.0
Version of iOS is 10.3.3

**Comment by ITJesse** [comment]
![img_0493](https://user-images.githubusercontent.com/3601376/28496032-4ac74cf8-6f9b-11e7-8627-a8f56ee08614.jpg)

**Comment by timeswind** [comment]
Having trouble with Chinese input methods too
