### ISSUE TITLE
Slash-menu positioning bug in Safari

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8323]
### Issue Summary

![screen shot 2017-04-12 at 15 25 53](https://cloud.githubusercontent.com/assets/415/24962688/8ce199e2-1f94-11e7-9b6c-d5c9ef103d42.png)

### Steps to Reproduce

1. Open the editor, type `/` in an empty paragraph

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/60ca9e8aced21cca5779c7264534adfa6ac955f0
* Browser/OS: Safari 10.1

**Comment by disordinary** [comment]
Thanks @kevinansfield ,

This is a bug in Safari and Safari mobile where it won't give the position of a range which is collapsed. In this case the editor tries to figure out where to place the menu based on the paragraph that the cursor is in.

It's not ideal, the only reasonable workaround that I can think of is to create a new one character range where possible and measure that. 

Ironically this bug makes the automatic scrolling to match the cursor location feel nicer in Safari as it jumps paragraph by paragraph rather than line by line. 😄
