### ISSUE TITLE
Any chance to interage TXTPEN?

### ISSUE THREAD

**Issue by rickyhan** [TryGhost/Ghost#8325]
txtpen is the only service that provides highlighting and in-text commenting similar to Medium. I think adding txtpen in the official documentation will benefit new Jekyll users and bring web annotation to more people.

Thanks in advance.
Ricky

**Comment by kirrg001** [comment]
Hi @rickyhan 👋

I'm going to close this issue as we use github solely for bug tracking and feature development.
If you'd like to request a new feature/idea for Ghost please head over to https://ideas.ghost.org.
Otherwise, if you have any questions please come say hello on [our slack channel](https://slack.ghost.org) 😊
