### ISSUE TITLE
Emoji not supported as tags

### ISSUE THREAD

**Issue by guillermovs** [TryGhost/Ghost#8329]
### Ghost does not support Emoji tags
Certainly low priority, but it would be great to be able to use emoji as tags 👍
I have updated the database charset to `utf8mb4`, but ghost seems to be escaping emojis and throwing a `422 Unprocessable Entity` error.

I've looked around `/api`, but can't find the right places where the filters get validated. If anyone knows where, here's an exhaustive regex for validating Emoji. 

### Regex for parsing Emoji (*)
`(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])`

* Regex source: https://medium.com/@thekevinscott/emojis-in-javascript-f693d0eb79fb

### Reproducing the error

1. Update DB charset `utf8mb4`
2. Name a tag as an emoji directly on the DB table (e.g. 😂  or urlencoded `%F0%9F%98%82`)
3. Go to localhost:port/tag/😂

You should get: `QUERY ERROR: UNRECOGNIZED TEXT "'" IN FILTER AT CHAR 6 TAGS:`

**Comment by kirrg001** [comment]
Hey @guillermovs 👋 Thanks for your report!

Ghost uses ascii characters in the url only. We [unidecode any slugs](https://github.com/TryGhost/Ghost/blob/lts/core/server/utils/index.js#L64) in the [model](https://github.com/TryGhost/Ghost/blob/lts/core/server/models/base/index.js#L556) at the moment. That's why emojis for tags won't work. 

See https://github.com/TryGhost/Ghost/issues/1285 and https://github.com/TryGhost/Ghost/pull/1408/files.

I'm closing this issue as in my opinion there are too many edge cases where a none decoded slug can cause problems. We can re-open if there are good arguments to remove decoding slugs for tags. 

Come and say hello in our [slack community](https://slack.ghost.org).
