### ISSUE TITLE
Unsecure image links when RSS accessed from HTTPS

### ISSUE THREAD

**Issue by sovietspaceship** [TryGhost/Ghost#8372]
Probable regression from PR #5189.

> When the RSS is accessed over SSL, the title feed links appropriately to https. However, the links to the posts and images still points to http.

**Comment by kirrg001** [comment]
Hey @sovietspaceship 👋
Sorry to hear you are having trouble.

Are you experiencing this on Ghost alpha or on `0.11.x`?

**Comment by kirrg001** [comment]
@sovietspaceship Hey again. I just wondered, could you please share your url configuration from your `config.js`? And could you please share your rss feed? Thanks!

**Comment by kirrg001** [comment]
Re-open, because we have to investigate/understand this again.

The fix, which was suggested makes in my opinion 100% sense, but i fear that the fix was not really understood from our side, plus it looks like there are other wrong secure flag handlings, [see](https://github.com/TryGhost/Ghost/blob/lts/core/server/config/url.js#L183).

This is low priority right now, that's why we would like to spend time next month again.

We have to keep in mind, that we already merged [this](https://github.com/TryGhost/Ghost/commit/e0660940445fe8af463d58ad180a48992ea27bb6) into master (no big deal, but might be that we want to revert it)

**Comment by ErisDS** [comment]
I don't think we're going to fix this in LTS now, closing.
