### ISSUE TITLE
Sticky insert card button

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8380]
### Issue Summary

In certain circumstances the insert-card `+` button can get stuck, where it doesn't disappear even when other cards are selected and can appear in the wrong location.

### Steps to Reproduce

1. Add a card to a post and exit the card's edit mode
2. Click below the card and then click the `+` button
3. Click on the previously added card
4. Note that the `+` button is still visible
5. Click the edit button on the card
6. Note that the `+` button appears beside the card
7. Click below the edit card frame
8. Note that the `+` button is now floating outside the bottom of the document

After going through these steps there is still some odd behaviour such as clicking in the title not causing the `+` button to disappear.

![sticky-plus-button](https://cloud.githubusercontent.com/assets/415/25341304/4f268228-2900-11e7-84e4-8526c8b59049.gif)

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/097f37ea02641632f194b597eea66ad96fea1853
* Browser/OS: Chrome/MacOS

**Comment by disordinary** [comment]
Cross browser handling of Ranges can be tough, there's a reason why a lot of web apps are Chrome only.

Right now it's listening for mobiledoc to fire a `cursorDidChange` event and removes the plus if the cursor is not in the document or if the location of the cursor is in a block that has content.

Mobiledoc itself figures out if the cursor has moved by polling the selection object on the window.  But, we also need to take into account that the editor may lose the cursor because the `+` button has been clicked and the card-selection menu is open (in which case we want the `+` button to stay in place.

Either Mobiledoc isn't firing a `cursorDidChange` event in this scenario or more likely the logic behind hiding the `+` button after opening the card menu with the `+` is faulty.
