### ISSUE TITLE
Odd paste/undo behaviour in editor title

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8386]
### Issue Summary

There seems to be a few issues with the title since adding the HTML stripping. When pasting, the cursor position stays at the beginning of the input and a subsequent undo doesn't work, after manually removing the text and pasting again the undo now adds the old text back without removing the new text.

![title-paste-undo](https://cloud.githubusercontent.com/assets/415/25377326/123fe968-299f-11e7-9a19-b1ee5fdc7958.gif)

### Steps to Reproduce

1. Copy some text (I used text with style attached - not sure if this makes a difference)
2. Paste text into the title input
3. Note that the cursor is at the beginning of the line
4. Press <kbd>Command+Z</kbd>
5. Note that the text hasn't been removed
6. Manually select and delete the text
7. Paste the text again
8. Press <kbd>Command+Z</kbd> again, may need to press twice
9. Note that the old text has now been added to the end of the current text

### Technical details:

* Ghost Version: https://github.com/TryGhost/Ghost-Admin/commit/9eda16e60ae569187a8e167636e16e5b75988fda
* Browser/OS: Chrome/MacOS

**Comment by kevinansfield** [comment]
@disordinary I'm wondering if we should be handling the `paste` event to extract the innerText of the pasted content and only using the `MutationObserver` as a fall back for rarer methods of users managing to inject HTML into the title?

**Comment by disordinary** [comment]
That makes sense, perhaps we get rid of the mutation observer altogether then and just handle the `change` and `paste` events.

It's odd that I don't see a flash but I know why it's there. In the tests doing find('').html() would create an infinite loop if you modified the content underneath it so I placed the stripping code in the next run loop.

I think we're still going to break undo if we strip changes on paste.  If we go to the point where we have to write our own undo queue we might as well just use a second mobiledoc editor just for the title, I didn't want to do that because I felt it would be too heavy.

**Comment by disordinary** [comment]
Summarising the conversation that we had in slack.

IE 11 doesn't fire an `input` event on change at all so we can't rely on that.

The best solution is to keep the mutation observer to observe changes but to include a new paste event handler to strip out HTML.

Using `document.execCommand('insertHTML...` in all modern browsers and the `range.pasteHTML` in IE 11 we should be able to paste the contents of the clipboard in plaintext into the title and retain the browsers in built undo queue.
