### ISSUE TITLE
Tests failing on gitlab ci and local 

### ISSUE THREAD

**Issue by jmwenda** [TryGhost/Ghost#8393]
### Technical details:

* Ghost Version: 0.11.8
* Node Version: v6.9.0
* Browser/OS:  Ubuntu LTS 

Keep having this problem on both docker based CI and local environment. When one runs  'npm test' the test do perform as the should but as the terminal fails leading to also testing runners also failing. The warning produced is shown below. Seems the --verbose when running npm test trips the entire test.

Warning: stderr maxBuffer exceeded Use --force to continue.
Aborted due to warnings.
Warning: Failed running "grunt init --verbose" in "core/client". Use --force to continue.
Aborted due to warnings.

**Comment by ErisDS** [comment]
Hi @jmwenda, thanks for dropping by!

For us, the tests are there to ensure quality whilst we add new features. We require them to work on our local environments and on Travis, which they do. The error you're seeing would appear to be to do with there being too much output for your environment, and --verbose means there would be even more output than normal.

I don't think there's anything for us to do or fix here, however if you have a PR to fix an underlying issue here we'd be happy to review it.

**Comment by jmwenda** [comment]
@ErisDS  Thanks, how would you advise to run the tests on a local env?
