### ISSUE TITLE
Editor performance

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#8395]
This is a hold-all issue to collect reports of poor or inconsistent editor performance.

I've noticed that there is sometimes quite a bit of delay whilst typing with the editor not being able to keep up with my typing speed (which isn't _that_ fast) with blocks of text jumping into view rather than seeing each character as I type. This was with very little in the editor, only two small paragraphs with a small markdown card between them.

**Comment by disordinary** [comment]
There's a bug in mobiledoc where it re-renders unnecessarily which can slow things down but that's mainly within a single long paragraph, my guess is that it's because it's firing the onChange event on every keypress which is in turn saving the document.

A solution will be to throttle these events so that they occur on a timer, say every 200 ms.
