### ISSUE TITLE
Menu jumps when selecting content

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8404]
When i try to select content (SHIFT+key up/down), the menu jumps around. 
Especially when i am on an empty line and press SHIFT+key down and SHIFT+key up. It jumps from left to right.

![menujumps](https://cloud.githubusercontent.com/assets/1160712/25429449/56c67608-2a79-11e7-805f-3618e101e455.gif)

### Steps to Reproduce

See video.

### Technical details:

* Ghost Version: master
* Browser/OS: Chrome/MacOS

**Comment by kevinansfield** [comment]
I think this is because multi-line selections are always full-width, it's the fact that only the text gets a background colour that's making it seem confusing? Eg, you can see the jumping menu behaviour more clearly here because the full-width selection is visible:

![menu-jump](https://cloud.githubusercontent.com/assets/415/25430618/3923ccd0-2a75-11e7-803b-a660a39eb07c.gif)
