### ISSUE TITLE
Add Rocket.Chat integration as alternative to Slack

### ISSUE THREAD

**Issue by k0nsl** [TryGhost/Ghost#8430]
I have for sometime now seen this feature:
![selection_018](https://cloud.githubusercontent.com/assets/2517921/25564997/683180d8-2dbf-11e7-946a-76cf55273cf1.jpg)

...which allows « newly published posts to a channel in Slack. »

That is great for people who use Slack. But there's a growing number of people who are switching to alternative solutions such as [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/). I'm one of those.
This feature should be more or less 99,99% compatible with Rocket.Chat, but unfortunately there's no way to test since the application does URL validation and only allows input where the domain matches Slack.
I suppose it would be possible to hack at the core and remove this, then test. But maybe somebody know of a better solution? I'd love to see this feature support Rocket.Chat as well.

Thanks for providing a great blogging platform.

**Comment by kirrg001** [comment]
Hey @k0nsl 👋

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened. 

Furthermore, we have a [wishlist](http://ideas.ghost.org/forums/285309-wishlist) for future ideas.
