### ISSUE TITLE
footnotes do not link

### ISSUE THREAD

**Issue by enguerran** [TryGhost/Ghost#8438]
### Issue Summary

On Chromium or Firefox, footnotes links are displaying an error in the JavaScript console.

### Steps to Reproduce

1. Go to https://blog.ticabri.com/2017/05/03/pollution-internet/#fnref:1
1. Open the browser devtools
1. Click on the small 1 to go to the footnote
1. See the error coming from jquery and foot-scripts

![](https://i.imgur.com/0cpAX9g.png)

### Technical details:

Last docker image with:

* Ghost Version: 0.11.8
* Theme:  Ghostium - 2.2.1

**Comment by kevinansfield** [comment]
Hey @enguerran 👋 Sorry to hear you are having issues. The error you are seeing is coming from your theme's javascript rather than Ghost itself - we have no control/ability to fix it, I would suggest you contact the author of your theme so that can fix it, alternatively swing by our [Slack channel](https://slack.ghost.org) to see if anyone there is able to help you fix your theme yourself.
