### ISSUE TITLE
Where to change the Preview link?

### ISSUE THREAD

**Issue by CentrixDE** [TryGhost/Ghost#8445]
Hello,

I'm currently using ghost through a docker container with the default setup. I changed the productive and the developer links to my main blog (xy.com). The only thing which doesn't change is the preview URL which stays at "localhost:2368" which is not very comfortable to change every single time.

### Steps to Reproduce

1. Install ghost with the default settings
2. Change the URL to your main-URL

Maybe it should be changed in the admin ui?

### Technical details:

* Ghost Version: 0.11.8

**Comment by kirrg001** [comment]
Hey @CentrixDE 👋

This doesn't look like a bug to me.

Did you change the url in your `config.js`? See [Ghost configuration options](http://support.ghost.org/config/#configuration-options). All url's are generated, so if you set `xy.com` as your Ghost url, the preview link should be `xy.com/p/uuid`.

Can you please swing by our [slack channel](https://ghost.org/slack/) if you need further help? If this turns out to be an actual issue with Ghost this issue can be reopened. Thanks so much!
