### ISSUE TITLE
ghost lifecycle warning

### ISSUE THREAD

**Issue by nebulousdog** [TryGhost/Ghost#8471]
following [these instructions](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ghost-on-ubuntu-16-04), get the following..

```
$ sudo npm install --production
npm WARN lifecycle ghost@0.11.8~preinstall: cannot run in wd %s %s (wd=%s) ghost@0.11.8 node core/server/utils/npm/preinstall.js /var/www/ghost
```

**Comment by kirrg001** [comment]
Hey @nebulousdog!

If you use the Github search you will find a couple of related reports:

https://github.com/TryGhost/Ghost/issues?q=is%3Aissue+cannot+run+in+wd+is%3Aclosed

Can you please swing by our [slack channel](https://ghost.org/slack/) and ask for help there? We can provide better support there than in the Github issue tracker, and if this turns out to be an actual issue with Ghost this issue can be reopened. Thanks 🙂

**Comment by nebulousdog** [comment]
it looks like those are duplicates with no answers because you close everything :man_shrugging:
