### ISSUE TITLE
Filter with Chinese character doesn't work properly

### ISSUE THREAD

**Issue by neesonqk** [TryGhost/Ghost#8477]
### Issue Summary

While following this instruction, everything works well if tags are pure English words only, however, any Chinese character will break the filter with no query result checked out at all.

```
{{#get "posts" limit="5" filter="tags:['测试']+id:-{{id}}" include="tags"}}
{{/get}}
```

### Steps to Reproduce

1. create '测试' this Chinese tag. (you can use this tag as other pure English tags normally but filter)
2. create a `get` query with a filter of `测试`.

### Technical details:

* Ghost Version: 0.11.9
* Node Version: 4.2.6
* Browser/OS:  MacOS Chrome
* Database: MySQL with utf-8 charset
* Config.js: database charset: utf8

**Comment by neesonqk** [comment]
This probably was caused by my database settings problems.

**Comment by AileenCGN** [comment]
Hey there @neesonqk! 

Sorry to hear that you're having trouble! The filter in the `{{get}}` helper works with slugs. That means in your certain case you'll have to use it like this:

```
{{#get "posts" limit="5" filter="tags:['ce-shi']" include="tags"}}
{{/get}}
```

This way, it worked just fine for me! If you have further question, please pass by in our [Slack community](https://slack.ghost.org) where you'll find a bunch of people helping you out faster and in more depth if needed.

Closing this, as it's not an issue. If it turns out to be one, we can still reopen it.

**Comment by neesonqk** [comment]
@AileenCGN thanks!

It indeed works with slugs, however, in my case, one post contains multiple tags, there are mix with Chinese & English, I'd like to `get` all related posts which contain any tag from the main post, so the best way to implement is via slugs as you suggested, I'm able to get main post tags by `{{post.tags}}` or `{{tags}}`, but since `tags` is an array, so how do I pass over all slugs from the tags into a filter?

I've tried 

```html
{{#get "posts" limit="5" filter="tags:[{{#foreach tags}} {{slug}} {{/foreach}}]" include="tags"}}
{{/get}}
```

with no luck.

**Comment by AileenCGN** [comment]
Hey @neesonqk! We use GitHub solely for bug and issue tracking. Please swing over to our our [Slack community ](https://slack.ghost.org) if you need help or advise. Thank you 🤗
