### ISSUE TITLE
Sitemap issue, author is undefined

### ISSUE THREAD

**Issue by rolandsaven** [TryGhost/Ghost#8494]
I have an issue with the automatically generated sitemap. I changed the `permalinks` entry in the database to `/:author/:slug/`. This works fine but I have noticed that the author is undefined in the the generated sitemap. Please see attached.

![screenshot 2017-05-30 15 51 23](https://cloud.githubusercontent.com/assets/5774580/26589585/4cc36138-4550-11e7-9cf2-6d06b658a7a4.png)

* Ghost Version: 0.11.7
* Node Version: 4.8.3

Thanks

**Comment by kirrg001** [comment]
Hey @rolandsaven 👋

Thanks for your report and sorry you are having trouble.

I can confirm this bug. The post sitemap generator doesn't load the author and this results in `undefined`, because the user reference `post.author` is not resolved. 

See https://github.com/TryGhost/Ghost/blob/lts/core/server/data/xml/sitemap/post-generator.js#L26.

`include: author` is missing ^
