### ISSUE TITLE
Error if I type # 3 times in the editor

### ISSUE THREAD

**Issue by lunarbase** [TryGhost/Ghost#8499]
### Steps to Reproduce

I am trying to create a level 3 title, so I type # 3 times in the editor area

I see the following error: 

> <missing conversion parameter: amount, source unit, destination unit>

### Technical details:

* Version: 0.11.9
* Node Version: 
* Browser/OS: Safari Version 10.1 (12603.1.30.0.34)
* Database: MySQL 5.6.34

**Comment by kevinansfield** [comment]
Hey @lunarbase, I'm sorry but I've been unable to replicate this at all and there's not enough information here to move forwards.

I'm going to close this issue for now because the error message you're seeing isn't generated by Ghost or any of it's dependencies which suggests it's something specific to your setup. If you can provide more information or can show this is an issue in Ghost rather than with your setup we can re-open. Additional information would be things like:

- details of where are you seeing the error (screenshots are most useful)
- details of any errors seen in the web inspector console (right click, choose "Inspect", click the "Console" tab)
- details of any failing network requests or the responses from save requests (can be seen in the "Network" tab of web inspector

You've also mentioned on Slack that you are using Softaculous which is a setup we don't recommend nor support, seeing as you are also having other issues with API requests I would start by contacting support@softaculous.com.
