### ISSUE TITLE
blog post fotos not showing up in summary in latest developer version

### ISSUE THREAD

**Issue by awb99** [TryGhost/Ghost#8522]
### Issue Summary

Latest developer version does not show any blog fotos in the summary view.

### Steps to Reproduce

Glone git repo, build it, and run it and then start a new blog.

### Technical details:

* Ghost Version: 1.0.0-alpha.20
* Node Version: v6.10.3 on debian jessie
* Browser/OS:  firefox, chrome, chromium on linux
* Database:  default setting of ghost.

**Comment by kevinansfield** [comment]
Hey @awb99, I'm afraid I'm not really following what you mean, are you able to provide screenshots? It would also help if your reproduction steps listed what you expect to see and where (see https://github.com/TryGhost/Ghost/issues/8409 for an example) - you mention "blog fotos" but don't mention what they are or how you added them in your reproduction steps.

Note that the latest developer release is [alpha.21](https://github.com/TryGhost/Ghost/releases/tag/1.0.0-alpha.21) which has a major change to the editor compared to alpha.20.

**Comment by forteco** [comment]
https://mega.nz/#!bVwQ1T5Q!DC0gGZ3R3fRplB9IFQZ_l7Bb8nHBHThGGtDjLfRByCo
this is the video.

**Comment by kevinansfield** [comment]
Hi @forteco, this looks like it's a theme issue rather than a bug in Ghost as the behaviour is not reproducible using valid theme syntax. I would suggest reviewing the breaking changes in the alpha/beta cycle, there's a quick overview with links to docs in the [1.0.0 beta.1 blog post](https://dev.ghost.org/1-0-0-beta/#10themes).

If after you have updated your theme you are still seeing the incorrect behaviour we can re-open the issue. I would also suggest swinging by our [slack community](https://slack.ghost.org) where you can get help with theme problems 😄.
