### ISSUE TITLE
Previous and next posts not rendered for welcome posts

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#8562]
### Issue Summary

After populating the db with the new welcome posts fixtures, no previous or next posts at the bottom of each post is rendered. The reason for that might be for the `published_at` date not being populated within the fixtures.

### Steps to Reproduce

1. Fresh install of Ghost beta (fresh db init) to see the new welcome posts fixtures
2. Click on any post
3. See, that there's no 'read next' section at the bottom
4. Add a new post
5. See that the section appears, but with wrong content

### Expected behaviour

Click on the first welcome post, see the second one in 'Read next' section.
Click on the second welcome post, see the previous and the next one. And so on...

### Technical details:

* Ghost Version: 1.0 beta-1
* Node Version: 4.5
* Database: sqlite/MySQL

**Comment by kevinansfield** [comment]
> The reason for that might be for the published_at date not being populated within the fixtures.

The `published_at` field is being populated (it's generated automatically by the post model) but because fixtures are created so quickly and we only store time with a resolution of seconds all posts have the same `published_at` value which means the prev/next queries do not find any posts with earlier/later `published_at` values.

I believe the fix will be to specify a `published_at` field for the posts in the fixtures so that we can distribute them in time to allow the prev/next queries to function.
