### ISSUE TITLE
Incompatible with ROCKSDB

### ISSUE THREAD

**Issue by azilber** [TryGhost/Ghost#8577]
### Issue Summary

Install using ghost-cli with RocksDB set as the default database type causes error:
 ✔ Validating config
[2017-06-14 03:34:13] INFO Creating table: posts
An error occurred.
Message: 'alter table `posts` add unique `posts_slug_unique`(`slug`) - ER_UNKNOWN_ERROR: Unsupported collation on string indexed column ghost_production.posts.id Use binary collation (latin1_bin, binary, utf8_bin).'

### Steps to Reproduce

1. Install MariaDB 10.2.x (or higher) with the RocksDB engine set as default:
[mariadb]
plugin-load-add=ha_rocksdb.so
default_storage_engine   = RocksDB
ignore_db_dirs=.rocksdb

2. Run ghost install

### Technical details:

Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-alpha.18
    Environment: production
    Command: 'ghost install'
DB: 10.2.6-MariaDB-10.2.6+maria~jessie-log mariadb.org binary distribution
OS: Devuan (Debian Jessie based)
Ghost Version: 1.0.0-beta.1

**Comment by kirrg001** [comment]
Hey @azilber 👋

Sorry to hear you are having trouble.

From the [MyRocks/RocksDB limitation](https://github.com/facebook/mysql-5.6/wiki/MyRocks-limitations):
`"*_bin" (e.g. latin1_bin) or binary collation should be used on CHAR/VARCHAR indexed columns.`

Ghost uses [string/uuid's for table identifiers](https://github.com/TryGhost/Ghost/blob/master/core/server/data/schema/schema.js#L3). So it uses varchar indexed columns. And MyRocks requires you to use binary collation because of that. So i guess it's a configuration problem.

I am going to close this issue, as we do not support MyRocks/RocksDB.
But please let us know here if you were able to fix your issue. 

Thanks 👍
