### ISSUE TITLE
Rename ghost-url.js to ghost-sdk.js

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8605]
It would be really good to rename the file which is injected into `{{ghost_head}}` - currently `ghost-url.js` to something that makes a bit more sense, like `ghost-sdk.js`.

- [ ] rename the file 🎊 and change all connected code occurrences e.g. app routing

**Comment by jloh** [comment]
It would be good (IMO) if this file was not included by default in '{{ghost_head}}'. Quite a few themes use it in the back end but don't use it on the front end at all. It just ends up being another file for the browser to download and not end up using. It especially sucks for themes that try and go js free and use the '{{get}}` helper in the background but have to have this on the front end.

Maybe like how posts per page is now a theme setting this "show ghost js" could be a theme setting as well?

**Comment by ErisDS** [comment]
We originally opted not to rename this, because we felt it was too much of a change for a beta. 

What we totally forgot was that we had _already_ effectively renamed it, because we moved it from `/shared/` to `/public/` :woman_facepalming: 

In addition, after migrating you will also need to update your client id and secret. This is because of https://github.com/TryGhost/Ghost/issues/8719, which we do hope to improve in a future version.

Still, we've broken the Public API for anyone pulling data on a 3rd party site, and as we've broken it one time, we might as well finish renaming things.

So, we're now going to make the remaining update to `ghost-sdk.js` and then do a further bugfix release. We'll then write documentation and add notes about this to all the migration guides. This should mean everyone only needs to do this one time, which is better than two.
