### ISSUE TITLE
Can't upload images after reauthenticating

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8615]
Ghost 1.0-beta1, on production:

1. Write a post
2. Manually terminate session
3. Re-authenticate via modal
4. Upload an image to the post content

Expected behaviour: Image uploads

Actual behaviour: nothing happens, nothing in network tab, nothing in console, have to do a full refresh of the app to get it working again.

(Annoying edge-case, definitely not a blocker)

**Comment by ErisDS** [comment]
I have a sneaking suspicion that this may hint at what got you logged out in the first place, e.g. something is not getting updated properly when a token is swapped.

**Comment by kevinansfield** [comment]
Haven't been able to reproduce with the steps here so far on beta.1 dev/production or master. It's _possible_ it could be related to #8616 but you'd still get output in the network tab and console 🤔

One thing that wasn't mentioned in the issue was whether the image upload was initiated via drag/drop or via the image toolbar button.

**Comment by JohnONolan** [comment]
Closing until someone can reproduce or this comes up again
