### ISSUE TITLE
Error handling for 4xx - In particular: trackback requests

### ISSUE THREAD

**Issue by AviateX14** [TryGhost/Ghost#8634]
### Issue Summary

Running Ghost 1.0 beta (with the CLI) on Debian 9 with Nginx proxying to it. The problem is, someone, presumably still living in the 1990's, has linked to my blog (I'm guessing from their wordpress), and as such, I get requests every few hours to each one of my posts in the style of: POST blog.domain.com/post-name/trackback. The error log grows, and my HIDS system spams me with emails:

```
OSSEC HIDS Notification.
2017 Jun 26 11:43:11

Received From: servername->/var/log/syslog
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Jun 26 10:43:11 servername nodejs[10317]: #033[31mERROR#033[39m [2017-06-26 09:43:11] "POST /keyboards-compared-part-one/trackback/" 404 17ms
```

It would be nice to either have trackback requests handled, or for a more gentle fail of post requests. Any interim solution to save my inbox would be greatly appreciated.

### Steps to Reproduce

1. Install ghost
2. Do a POST request to and post url + /trackback

### Technical details:

* Ghost Version: 1.0
* Node Version: 4.8.3
* Browser/OS: Debian 9
* Database: MySQL

**Comment by PaszaVonPomiot** [comment]
@AviateX14 have you tried [this](http://john.cuppi.net/blocking-wordpress-pingback-ddos-attacks-with-nginx-and-apache/) solution? It should block it on nginx level.

**Comment by AviateX14** [comment]
User agent wouldn't work, it comes in from a Chrome-esque UA. I could to a 403 on anything that matches ~/trackback - but I'd rather it was handled more elegantly.

**Comment by ErisDS** [comment]
Seems to me that your email notification has done exactly what is intended - it's flagged up to you an issue specific to your blog, that you need to resolve.

Ghost isn't causing the problem - it's correctly logging errors for 404s that are happening, and in turn this is getting flagged up to you.

This is great for you, but not something that Ghost needs to handle - it has in fact done it's job already.

As @PaszaVonPomiot has suggested, the next thing to do would be to customise your nginx config to ignore these requests at the server level. This is the correct solution, because sending this traffic to Ghost for it to do a bunch of work that it cannot do makes no sense. Much better to drop these requests at the nginx-level. Means less work for your server & for your Ghost instance
 👍
