### ISSUE TITLE
Unable to click New Post while editing current post

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#8636]
### Issue Summary

While editing a new post, after the autosave triggers, you're unable to click on New Post from the admin menu on the left.

### Steps to Reproduce

1. Click New Post
2. Enter a title
3. Click into the editor and wait for autosave
4. Click on New Post

**Expected behaviour:** To be directed to New Post with current post saved
**What happens:** You cannot leave the original post page

### Technical details:

* Ghost Version: LTS
* Browser/OS: Chrome v 58.0.3029.110 / OS X El Capitan v 10.11.6

**Comment by kevinansfield** [comment]
This appears to be an autosave bug introduced in a recent LTS release - when the autosave is triggered by the title losing focus the transition from new->edit is not happening meaning you're still on the `editor.new` route so clicking the "New post" link does nothing because you're already on the page it's linking to.

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost-Admin/pull/783.
