### ISSUE TITLE
User status not preserved after import

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8651]
### Issue Summary

In exported content user status is not preserved. So if you export suspended users then after the import user will not be suspended.

### Steps to Reproduce

1. Suspend one team member account
2. "Export your content"
3. "Delete all content" (btw. there's a typo in warning message)
4. "Import content" (description of this option indicates that it will only import posts so this could be clarified)
5. Check team menu where user is in "active" status

### Technical details:

* Ghost Version: beta2
* Node Version: 6
* Browser/OS: chrome
* Database: mariadb

**Comment by kirrg001** [comment]
Hey @PaszaVonPomiot!

Thanks for your report. The behaviour you describe is true. All exported users are getting imported as locked users, because they have to reset the password.

What we could do here is to check if the exported user status is `inactive`, see https://github.com/TryGhost/Ghost/blob/master/core/server/data/importer/importers/data/users.js#L44. By this only active users can reset their passwords. 

I would rate this issue as low priority, because the blog owner can manually suspend the user in the admin panel again. PR is welcome!
