### ISSUE TITLE
413 Entity Too Large errors swallowed silently for image and import uploads

### ISSUE THREAD

**Issue by jgreenemi** [TryGhost/Ghost#8660]
### Issue Summary

In the Settings -> General menu, uploading a Publication Cover image fails silently when it receives a HTTP 413 Payload Too Large response from the server. The only indication that there is an issue is that the image thumbnail does not appear.

### Steps to Reproduce

1. Under Settings -> General, click "Upload image" for Publication Cover.
2. Select and upload an image that is 2MB+. (I'm unfamiliar just what the limit is.)
3. The progress bar animation completes, but the thumbnail for the image does not appear, and no error message is given to indicate a problem.

I expect that there would be a message to indicate that an error occurred during the upload, as well as giving details what file size limit there is.

### Technical details:

* Ghost Version: 1.0.0-beta.2
* Node Version: v4.5.0
* Browser/OS: Opera 46.0.2597.26314, Windows 7
* Database: SQLite3

**Comment by kevinansfield** [comment]
Hey @jgreenemi 👋 I'll look into this, we definitely had error messages for other errors so I'm not sure why the 413 error would slip through 🤔

> Select and upload an image that is 2MB+. (I'm unfamiliar just what the limit is.)

Ghost doesn't set an upload limit, you'll need to check your nginx configuration as the limit is likely to be set there.

**Comment by ErisDS** [comment]
Worth noting here that blogs installed through the cli using our recommended setup will automatically have their max upload size set to 50mb, which should mean this bug is much rarer than if you have nginx setup with its 1mb default.

**Comment by PaszaVonPomiot** [comment]
Hi, I suspect that many users that don't use standard stack will have this and other issues simply because they won't know what exatly are the settings that ghost-cli will set. I think it would be very useful to just list in the docs all the parameters that are set by ghost-cli for nginx (including ssl settings), system user (including sudo) and database user. Then I guess less issue reports would appear.

**Comment by kevinansfield** [comment]
Confirmed that this is also the case when uploading imports where the only error shown is "Import failed" and that a number of users have run into this problem due to nginx's default 1MB upload limit.

We should add tests for all upload points simulating 413 errors to make sure that the underlying error is surfaced correctly.
