### ISSUE TITLE
Markdown Editor small bug

### ISSUE THREAD

**Issue by blagoeres** [TryGhost/Ghost#8695]
When writing inside of fenced code block comment gets rendered as heading. This should not happen inside code block. Rendering is correct on the frontend.

![bug](https://user-images.githubusercontent.com/15614178/28230289-920dc436-68e6-11e7-95d1-c3679d0c92f5.gif)

### Technical details:

* Ghost: 1.0.0rc
* Node: 6.11.1
* Database: MySQL

**Comment by kevinansfield** [comment]
Hey @blagoeres, thank's for reporting. The problem is that the underlying Codemirror editor is not in "gfm" markdown mode so it's not seeing the fenced code block as a code block (if you indent by 4 chars instead as per standard markdown you'll see better behaviour).

Thankfully, this should be a quick fix.

**Comment by PaszaVonPomiot** [comment]
Yeah I was about to report this :)
