### ISSUE TITLE
internal error message displayed in alert

### ISSUE THREAD

**Issue by wassimseif** [TryGhost/Ghost#8714]
### Issue Summary
If i have a featured post and i'm in the editor. i don't want the post to be featured anymore, i want it to be page instead. i tried to deselect 'Feature this Post' and select 'Turn this post into a page' and pressed the update button to publish it again i got the error in the screenshot attached.
<img width="1634" alt="screen shot 2017-07-20 at 12 58 06 pm" src="https://user-images.githubusercontent.com/7282773/28412018-82a33efe-6d4b-11e7-9430-a9df54fbe25a.png">

### Steps to Reproduce

1. Feature a post 
2. publish it
3. Edit the post 
4. remove the post from featured 
5. select to make it a page
6. try to publish again 
7. Weird error message and changes are not applied 

### Technical details:

* Ghost Version: 1.0 rc1
* Node Version: 6.5.0
* Browser/OS: chrome , macos 10.12.5
* Database: RDS MySQL

**Comment by kevinansfield** [comment]
I'm unable to cause an error using the steps you've provided (from the Slack convo it sounds like the network error may have been due to your setup) but the bug where an internal message is shown in an alert definitely shouldn't be there.

Anyone looking at this I would suggest setting up an acceptance test that triggers a validation error (I've tested offline and I see `Server was unreachable` which is fine) when publishing and inspecting the alert text.

**Comment by ErisDS** [comment]
Closing due to age & lack of traction
