### ISSUE TITLE
No space between words in Chinese and Japanese. Word count function cannot work correctly on it.

### ISSUE THREAD

**Issue by cliier** [TryGhost/Ghost#8726]
The above problem has not been solved."Word count function cannot work correctly on it."
Ghost Version:1.0.0-rc.3
ghost-cli Version: 1.0.0-alpha.16
Node Version:v6.9.0
OS: centos 7
![_20170721132058](https://user-images.githubusercontent.com/13637933/28450104-b28f23fe-6e17-11e7-89bb-be603c96b59a.png)

**Comment by weizeng** [comment]
solved this issue?

**Comment by kevinansfield** [comment]
If you are using languages that do not have spaces between words then it's recommended to set a custom excerpt on posts so that you can control how much text is displayed. There's more details on custom excerpts here https://blog.ghost.org/custom-excerpts/

The behaviour of the `{{excerpt words="20"}}` helper and word count attribute is unlikely to change.

**Comment by weizeng** [comment]
@kevinansfield  thank u ,solved my issue.   excerpt worked.
https://10106.wang/

**Comment by cliier** [comment]
@kevinansfield cool
