### ISSUE TITLE
Save Post Error! Error info: "ROLLBACK; - This socket has been ended by the other party"

### ISSUE THREAD

**Issue by cnwanq** [TryGhost/Ghost#8745]
### Issue Summary

Hi, I want to create an article, this article more words, and then I save it failed：
failed ms: `ROLLBACK; - This socket has been ended by the other party`

### Technical details:

* Ghost Version: 0.11.10
* Node Version: v6.11.0
* Browser/OS: centos7
* Database: 10.1.25-MariaDB

**Comment by acburdine** [comment]
@cnwanq From the research I did, it appears this is a bug with https://github.com/tgreisser/knex rather than Ghost itself. What's happening is the database is closing the connection unexpectedly, and knex isn't trying to reconnect.

Going to close this for now, however if we find that there's something more Ghost can do to handle this sort of error then we can reopen it 😄
