### ISSUE TITLE
Author permissions and Invite system

### ISSUE THREAD

**Issue by gomesphoto** [TryGhost/Ghost#8746]
### Issue Summary

Currently an Editor or Admin is able to invite users as Authors to write on a Ghost blog, but is not able to create new Authors and post on their behalf. I understand the reasoning behind this but it would be great to have the option attribute posts to Authors without having to give them permissions to the blog.

Alternatively the permissions of the Author would be reduced to simply creating drafts but it would require an Editor or Admin to publish them. For blogs with multiple authors this requires more management from the Editor over the Authors since they can edit and publish new posts and modify old ones.

I would like to suggest this change over Authors publishing posts as an improvement for User Permissions in Ghost.

**Comment by acburdine** [comment]
You could work around this by inviting an author with a fake email address, then manually setting the "Author" of the post to said author using the Post Settings Menu.

As far as preventing authors from publishing, this is a feature that has been often requested in Ghost. Going to close this issue though, as feature requests should be submitted through ideas.ghost.org rather than Github 😄

**Comment by bhardin** [comment]
If anyone is looking for this specific request, it is here: http://ideas.ghost.org/forums/285309-wishlist/suggestions/7193351-contributor-author-account
