### ISSUE TITLE
MESSAGE: The currently active theme "casper" is missing.

### ISSUE THREAD

**Issue by CavanLife** [TryGhost/Ghost#8787]
### Issue Summary

MESSAGE: The currently active theme "casper" is missing.

### Steps to Reproduce

1. download the lastest Ghost source code
2. npm install --production
3. npm start
4. errorInfo: 
MESSAGE: The currently active theme "casper" is missing.

### Technical details:

* Ghost Version: v1.0.2
* Node Version: v8.1.4
* Browser/OS: chrome
* Database: sqlite3.0

**Comment by ErisDS** [comment]
Hi @CavanLife, from what you've said it sounds like you opted to download a "source code" zip, rather than the official pre-built Ghost-1.1.0.zip that lives above it.

![](https://puu.sh/wXJh6.png)

Source code is the pure source - it's the same as cloning the repo, only you won't get any submodules unless you add them yourself. You'd then also need to run all the build steps.

I assume you meant to download the built code :)

**Comment by ErisDS** [comment]
Also worth noting, the recommended install mechanism is with Ghost CLI: https://docs.ghost.org/docs/getting-started-guide

**Comment by Hekman** [comment]
Run into the same problems. Appears that Node version 8+ is not supported. I downgraded to an prior version and it worked

See https://docs.ghost.org/docs/supported-node-versions for more

**Comment by CavanLife** [comment]
Yeah！Thanks for you! @Hekman @ErisDS 

I resloved the issue with downgraded the node version to 6.9.4. it works well.

**Comment by rcmangnale** [comment]
How can I Install the Liebling theme instead of Casper in local?
