### ISSUE TITLE
Markdown issue

### ISSUE THREAD

**Issue by Luen** [TryGhost/Ghost#8801]
### Issue Summary

Markdown doesn't work in this case:
`Although there isn't any creeks or waterholes, the environment_, and of course the hike,_ is spectacular.`

### Steps to Reproduce

1. Copy and paste "Although there isn't any creeks or waterholes, the environment_, and of course the hike,_ is spectacular." into a new story.
2. Publish and view post.

If I change it to "waterholes, _and of course the hike_, is" it works

### Technical details:

* Ghost Version: 1.2 (installed via CLI)
* Node Version: 6
* Browser/OS: Chrome/Windows 10 (Server Ubuntu 16)
* Database: MySQL

**Comment by kevinansfield** [comment]
@Lucen this is expected behaviour (see the [CommonMark spec](http://spec.commonmark.org/0.27/#emphasis-and-strong-emphasis)). Opening intra-word emphasis characters cannot be followed by punctuation (in your case you're starting intra-word emphasis because you've left no space after the `t`). Either of the following will work:

`Although there isn't any creeks or waterholes, the environment, *and of course the hike,* is spectacular.` 

Although there isn't any creeks or waterholes, the environment, *and of course the hike,* is spectacular.

`Although there isn't any creeks or waterholes, the environment, *and of course the hike*, is spectacular.`

Although there isn't any creeks or waterholes, the environment, *and of course the hike*, is spectacular.
