### ISSUE TITLE
Ghost not starting when custom storage module is used

### ISSUE THREAD

**Issue by robincsamuel** [TryGhost/Ghost#8847]
### Issue Summary
✖ Starting Ghost
A GhostError occurred.

Message: An error occurred.
Stack: Error: An error occurred.
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:55:35)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Debug Information:
    Node Version: v6.9.0
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost start --development -V'

### Steps to Reproduce

1. setup a new ghost instance
2. Add folder `adapters/storage` under `content` directory
3. New file in storage `hello.js`, for storage class `hello`
4. Update config 

```
"storage": {
      "active": "hello",
      "hello": {
          "key": "99"
      }
  }
```

### Technical details:

  OS: mac seirra
  Node Version: v6.9.0
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost start --development -V'

**Comment by ErisDS** [comment]
Hi @robincsamuel, chances are that you're getting an error because your storage adapter is invalid. I would try using `ghost run` rather than starting with a process manager so that you can see the output from Ghost. Alternatively, check the log files in content/logs.

If this does turn out to be an issue, please re-raise whatever the underlying bug is either here if it is to do with storage, or on the [Ghost-CLI](https://github.com/TryGhost/Ghost-CLI) repo if it is a problem with the ghost commands.

**Comment by robincsamuel** [comment]
Ah okay! I got confused a bit with CLI.

I did `ghost install local` and then added storage module under `content/adapters/storage`. But it didn't work. Seems fine when I downloaded ghost.

Updated storage [Ghost google drive](https://github.com/robincsamuel/ghost-google-drive) to work with the latest version of ghost.
