### ISSUE TITLE
Datepicker bug

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8891]
Live demo.ghost.io production site shows "1432" as the current year when opening datepicker

![image](https://user-images.githubusercontent.com/120485/29265601-8978bef6-80d9-11e7-8278-c9c0f622a3ae.png)

**Comment by kevinansfield** [comment]
@JohnONolan I believe this is because the current post `published_at` is set to that date (demo.ghost.io has historic posts) .

What should the behaviour be for the "schedule it now" option when the post has an existing publish date? Should it default to "now" if the date is in the past?

**Comment by JohnONolan** [comment]
> default to "now" if the date is in the past?

Definitely

**Comment by kevinansfield** [comment]
We already default to "now + 5mins" as soon as the "schedule it later" option is selected.

Looking into it a bit further the issue is that the popup calendar month view does not jump immediately even though the date has been changed. I think this is a bug in the calendar component because as soon as you click the >> button it jumps to "now + 1 month" because the selection in the calendar is correct, it's just that it's displaying the wrong month.

![datepicker-bug](https://user-images.githubusercontent.com/415/30543021-62f7b2ee-9c79-11e7-8b70-e88450375d44.gif)

There are two things that can be done here:
1. Fix the bug in `power-datepicker` so that the correct month view is shown when the selected date is updated
2. Update `gh-publishmenu-draft` so that the date/time picker always defaults to now+5mins
