### ISSUE TITLE
Chrome's Spell Checker is not working

### ISSUE THREAD

**Issue by Luen** [TryGhost/Ghost#8897]
### Issue Summary

Chrome's spell check no longer works in the version 1 of Ghost. Is this a bug? Is it on your list to make ghost work with browser spell checkers?
I do know that you have your own spell checker built in but I prefer getting suggestions when right clicking the word. THanks

### Steps to Reproduce

1. Misspell a word
2. Note there is no browser spell checker to correct the spelling mistakes

### Technical details:

* Ghost Version: 1.3.0
* Browser/OS: Chrome

**Comment by kevinansfield** [comment]
No bug, it's a known downside to the technology used in the new markdown editor - see https://github.com/TryGhost/Ghost/issues/8566 for some additional discussion.

We're still working on bringing the full Mobiledoc editor into Ghost which will have native spellcheck but the CodeMirror based markdown editor won't get native spellcheck unless the issue is solved [in that project](https://github.com/codemirror/CodeMirror/search?q=spellcheck&type=Issues&utf8=✓).

**Comment by FrankV01** [comment]
[This post in 2015](https://blog.ghost.org/ghost-spellcheck/) says that spell checking should be working in newer versions. (Unless you've intentionally withheld this from the open source version...)

At this point, should in browser spell checking be working or not for personal, open source installations of Ghost? For reference, I'm currently running 1.21.2 and it doesn't work.

**Comment by kevinansfield** [comment]
In browser spell-check will not work with the current markdown editor that was introduced in Ghost 1.0. We're in the process of building a new rich-text editor which does have native spellcheck, see https://github.com/TryGhost/Ghost/issues/9311

**Comment by kevinansfield** [comment]
> personal, open source installations of Ghost?

Also, for clarification, there is only one version of Ghost and that is the open source version that's available to everyone. There is no "paid-for", "enterprise", or any other closed source version of Ghost.
