### ISSUE TITLE
Update app development page?

### ISSUE THREAD

**Issue by siolfyr** [TryGhost/Ghost#8906]
Following the [app development page](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs), I got this error:

"code":"MODULE_NOT_FOUND"

Is this wiki page super out of date?  Should there be a hello world app or something?  I want to get playing with Ghost, but do not have enough motivation to work around bugs, at least until I get the dopamine from building a working app or theme.

**Comment by acburdine** [comment]
Yes, the app wiki page is out of date - the reason the wiki is still in existence is because of the various feature specs that are still there. As far as app development goes - there's no guarantee that it works for Ghost 1.0.

If you're willing to figure out a way to make it work in the short term then we can update the wiki page; however, apps are not officially supported in Ghost as of yet.

Going to close this though as it isn't really a bug, and future work in the app space will have separate feature issues.
