### ISSUE TITLE
Subscriber table css issue in darkmode

### ISSUE THREAD

**Issue by timscha** [TryGhost/Ghost#8919]
### Issue Summary

Just a small css issue. The arrow for the subscription date is black and not switched to white colour, when Nightmode is enabled

![screenshot 7](https://user-images.githubusercontent.com/4650393/29456889-055e5558-8418-11e7-9bb4-9efd0614b766.png)

### Technical details:

* Ghost Version: 1.6.2

**Comment by vikaspotluri123** [comment]
This issue won't be fixed for now, as the subscribers area will be overhauled soon, it's currently a beta feature, and the fix takes more time than it's worth. For more info, check out [this thread](https://ghost.slack.com/archives/C09JM0TCK/p1503126352000039) in [Slack](https://slack.ghost.org)

**Comment by whmii** [comment]
@kevinansfield should this issue be closed?

**Comment by kevinansfield** [comment]
Yeah, I think this can be closed for now. The Subscribers feature is in beta and is due for an overhaul as mentioned above - the fix is more complicated than it's worth at the moment.

That said if anyone has any bright ideas for overriding a color set in an SVG that's used via `background: url(arrow.svg)` feel free to comment or submit a PR 😄
