### ISSUE TITLE
Internal tags are used as primary_tag and displayed to users

### ISSUE THREAD

**Issue by simontabor** [TryGhost/Ghost#8920]
### Issue Summary

If a post has an internal tag associated with it (and it's the first tag), that is set as the primary_tag and then displayed to the user by Casper. https://github.com/TryGhost/Ghost/blob/cafabff89e3dec2e57d5c91234fa0c6e73dadc84/core/server/models/post.js#L513 and then used as if it's publicly visible here: https://github.com/TryGhost/Casper/blob/8d17e9a452bb426142c0005a493ba726a93b7cc5/post.hbs#L23-L25

### Steps to Reproduce

1. Create an internal tag
2. Associate it with a post as the first/only tag
3. View the post, the internal tag is used as the primary tag and displayed to the user ![screen shot 2017-08-18 at 16 27 15](https://user-images.githubusercontent.com/1441031/29465753-43ccd0f2-8432-11e7-96c8-3054b05d3ec2.png)
4. Click on the tag link, it's a 404 error (correct behaviour)

I can see potential use-cases for primary_tag to be the first tag in any situation, but internal tags should never be displayed to the end user.

### Technical details:

* Ghost Version: 1.6.2
* Node Version: 6.11.1
* Browser/OS: All
* Database: All

**Comment by ErisDS** [comment]
This is a good point. We were using `tags.[0]`, so we added the `primary_tag` as an alias, buuut you're right, this case should be run through the visibility filter first.

For what it's worth, Casper has been designed to be used with sites that add tags to all their posts, so I think there may be some argument that if you only use internal tags, that perhaps Casper isn't for you 😉 

The fix for this is pretty straightforward, p sure I can get it in before the next release.

**Comment by ErisDS** [comment]
For clarity, the fix for this disables primary tag functionality for any post that has an internal tag as the first tag.

The logic for a primary tag is: a primary tag is the first tag associated with a post, _if_ that tag is public.
