### ISSUE TITLE
Error while trying to insert emojis to a post

### ISSUE THREAD

**Issue by pandres95** [TryGhost/Ghost#8921]
### Issue Summary

When inserting emojis to a post and saving, it throws an error bar, making impossible to save, and in Ghost Editor while editing a long post is specially conflictive, because the close button disappears and I need to restart the browser.

### Steps to Reproduce

1. Create a new post, or edit an existing one.
2. Insert a face emoji, like (😂, 😆, 😛, 😱, 🤣, etc).
3. Save.

## Expected behaviour

To successfully save the article.

## Actual behaviour

An error bar appears with a message like this one.

```sql
insert into `posts` (`author_id`, `codeinjection_foot`, `codeinjection_head`, `created_at`, `created_by`, `featured`, `html`, `id`, `mobiledoc`, `page`, `plaintext`, `slug`, `status`, `title`, `updated_at`, `updated_by`, `uuid`) values ('1', '', '', '2017-08-18 03:53:56', '1', false, '<div class=\"kg-card-markdown\"><p>😆</p>\n</div>', '599664d43baaac00018e45d9', '{\"version\":\"0.3.1\",\"markups\":[],\"atoms\":[],\"cards\":[[\"card-markdown\",{\"cardName\":\"card-markdown\",\"markdown\":\"😆\"}]],\"sections\":[[10,0]]}', false, '😆', 'untitled', 'draft', '(Untitled)', '2017-08-18 03:53:56', '1', 'e98e0a4f-3b78-4faf-8f7c-9e8f2ab5122c') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x86</...' for column 'html' at row 1
```

### Technical details:

* Ghost Version: 1.6.1
* Node Version: 6.11.2
* Browser/OS: Chrome 60.0.3112.90/macOS Sierra 10.12.6, Ghost Desktop 1.3.0/macOS Sierra 10.12.6
* Database: MySQL 5.7.19

**Comment by pandres95** [comment]
I found a similar [issue](https://stackoverflow.com/questions/13653712/java-sql-sqlexception-incorrect-string-value-xf0-x9f-x91-xbd-xf0-x9f) and tried to apply it. However, didn't work.

**Comment by kevinansfield** [comment]
@pandres95 I'm unable to replicate this issue in MySQL or SQLite.

Do you know which encoding your database is using? I believe you'll need to be using `utf8mb4`.

There are a number of similar issues open on StackOverflow such as https://stackoverflow.com/questions/35125933/mysql-utf8mb4-errors-when-saving-emojis. It would be helpful to know what OS you have installed Ghost on and how you installed - e.g., did you use Ghost-CLI and have it set up MySQL for you or have you gone for a manual setup?

**Comment by kirrg001** [comment]
I am also not able to reproduce this and i doubt this is caused by Ghost. Ghost is using `utf8mb4` encoding to support more than 3 bytes per character, read more [here](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html). This is how Ghost is able to support any kinds of emojis. I suggest to double check with which charset your database was created and what kind of collation your tables have.

If you need further support, could you please swing by our [slack channel](https://slack.ghost.org) and ask in the `#help` channel? We can provide better support there.

If this turns out to be an actual issue with Ghost this issue can be reopened. Thanks!
