### ISSUE TITLE
Broken references to casper.ghost.org in fixtures

### ISSUE THREAD

**Issue by YoranBrondsema** [TryGhost/Ghost#8925]
### Issue Summary

[Privacy Badger](https://www.eff.org/privacybadger) is a useful tool by the EFF that blocks trackers. As I was setting up my blog with Ghost, I noticed that none of the images of the default posts in Casper were showing.

![Images not loading](https://user-images.githubusercontent.com/1374412/29494037-8abbe770-85a2-11e7-9472-526abde1b24a.png)

It turns out that it's due to Privacy Badger blocking the casper.ghost.org domain:

![Privacy Badger](https://user-images.githubusercontent.com/1374412/29494049-c8c0cafe-85a2-11e7-8b0e-f1491fb3652f.png)

Of course, turning off Privacy Badger for the site resolves the issue. However, since Ghost does not have any bad intentions, I don't see why it wouldn't be allowed by Privacy Badger. From what I read, the domain needs respond in a correct way to a Do Not Track message in order not to be blocked. The [website](https://www.eff.org/privacybadger) has a more detailed explanation.

### Steps to Reproduce

1. Install a fresh copy of Ghost on a self-hosted server.
2. Install [Privacy Badger](https://www.eff.org/privacybadger)
3. Go to the homepage of your blog and the images won't be visible.

### Technical details:

* Ghost Version: 1.6.2
* Node Version: 6.11.2
* Browser/OS: Ubuntu 16.04
* Database: MySQL 14.14

**Comment by JohnONolan** [comment]
Wow, I have no idea wtf this is. casper.ghost.org is not a domain we use - it's pointing at github pages, but just 404's - however there are multiple references to it in our fixtures:

![image](https://user-images.githubusercontent.com/120485/29629294-4ff80842-8806-11e7-8222-ec0217888c57.png)

Either way - it's a false positive in PrivacyBadger - because it's not a tracker, but it's also a bug in Ghost, cause these references are broken.

**Comment by YoranBrondsema** [comment]
@JohnONolan For me `https://casper.ghost.org` does give a 404 but the resources, such as `https://casper.ghost.org/v1.0.0/images/welcome.jpg` does resolve correctly.

**Comment by kevinansfield** [comment]
@JohnONolan the references aren't broken, they point to Ghost's [gh-pages branch](https://github.com/TryGhost/Ghost/tree/gh-pages) - if they were broken the images for default posts in every Ghost install would 404.

They are needed because knex-migrator/the fixtures in Ghost do not have the ability to push files into the user's `content` directory which is what would be necessary so we decided to use external resources for the default posts, the PR for this [is here](https://github.com/TryGhost/Ghost/pull/8548)

**Comment by kevinansfield** [comment]
I think what's happening here is similar to [what happened with Discourse](https://meta.discourse.org/t/discourse-cdns-are-blocked-by-privacy-badger/17127/27).

If you've previously visited ghost.org, especially if you've logged in to my.ghost.org, all requests to *.ghost.org domains will have cookies attached to them, including casper.ghost.org - PrivacyBadger then uses it's heuristics to determine that casper.ghost.org is a CDN used for tracking visitors (it only serves images which wouldn't normally have cookies and there's no root page on the domain) and so it  blocks the whole domain.

I've just installed Privacy Badger to test - when visiting my local dev blog on ghost.blog it does detect that casper.ghost.org is a potential tracker but it hasn't blocked the domain or even blocked cookies. I'll keep it running to see if the heuristics do eventually block the images.

Potential fixes:
1. move the default images to a non ghost.org domain so that "CDN" requests aren't burdened with our *.ghost.org cookies (interestingly streams.ghost.org has the same cookie problem but Privacy Badger doesn't detect it, possibly because it's not looking for .mov files?)
2. find a method for our fixtures to be able to copy files when inserting the welcome posts so that images are local to the blog - this will mean bundling the images in the release zip and npm module, not sure if we care about that but we have had drives in the past to reduce the size of those

**Comment by kevinansfield** [comment]
> I've just installed Privacy Badger to test - when visiting my local dev blog on ghost.blog it does detect that casper.ghost.org is a potential tracker but it hasn't blocked the domain or even blocked cookies. I'll keep it running to see if the heuristics do eventually block the images.

Ha, immediately after posting this I visited https://demo.ghost.io and after the loading the first image from casper.ghost.org Privacy Badger immediately blocked all other images on casper.ghost.org from loading.

**Comment by ErisDS** [comment]
This is a very specific problem, where Privacy Badger is blocking those URLs. Similar things would happen if you tried to install Ghost behind a firewall, or if you run Ghost when disconnected from the internet.

The assets loaded from casper.ghost.org are a set of fixture images used in the example blog posts. They aren't required for the correct functioning of Ghost, and the expectation is that one of the first things you'd do after starting a new blog is delete the dummy "Ghost" user and all of its content.

I'm going to close this issue as there's nothing for us to do or fix here.
