### ISSUE TITLE
Admin Search not able to bring back results when some chars are in story titles - e.g. (, ), [, ]

### ISSUE THREAD

**Issue by erikstern-r7** [TryGhost/Ghost#8959]
### Issue Summary

When trying to search for a post in the ghost admin of our site, we often have post titles that contain chars like: (, ), [, ] and others that when pasted into the search box return no results message. Would like to be able to search without having to remove these chars to bring back the correct post in the type-ahead.

### Steps to Reproduce

1. Be logged into admin on Mac Safari, FF or Chrome.
2. Do a search for a post with a title containing: `(`, `)`, `[`, `]` (or i am sure there are others that you might want to check).
3. Search type-ahead brings back "No results found".
4. If you edit the title to remove these chars in question, the story/post is found. 

### Technical details:

* Ghost Version: currently on 1.7 and others even before 1.0 this has been a bug that we have noticed 
* Browser/OS: Mac Safari, FF & Chrome.

**Comment by kevinansfield** [comment]
The problem arises because we are using the search string directly in a regex:
<img width="546" alt="screen shot 2017-08-31 at 16 14 18" src="https://user-images.githubusercontent.com/415/29930857-85d563e4-8e67-11e7-9b50-615f7a2d563f.png">

It works if you treat the search box as a regex search, e.g. by typing `\[`. Regex is quite useful for power searching but I'm not sure it's particularly obvious that's how the search works 😁

**Comment by erikstern-r7** [comment]
@kevinansfield, i think this is great for power-users and i never new this was possible, but our audience that would be using this search box is probably not going to know RegEx. It might make sense to make this a setting that could be enable. Just a thought.

**Comment by kevinansfield** [comment]
Sorry if I wasn't clear, my intention was to remove the regex search completely... "we should probably treat the search query as a literal string 😁"

The ability to use regex in the search box was an accident rather than intentional. Although it's may be useful for power users it's not Ghost's philosophy to have flags or settings for these sorts of things so the fix for this is to remove the regex search.
