### ISSUE TITLE
Docker Ghost redirect to localhost:2368

### ISSUE THREAD

**Issue by MLescaudron** [TryGhost/Ghost#8966]
I can't use ghost with docker on domain name or ip != localhost

Everything work, but the home link redirect to localhost:2368 and email invation too.

```
docker run -d --name some-ghost -p 3001:2368 -v /path/to/ghost/blog:/var/lib/ghost/content ghost:1.8.1-alpine
```

**Comment by acburdine** [comment]
@MLescaudron this is not an issue with Ghost itself - this has to do with the ghost docker image (which is over at [this repo](https://github.com/docker-library/ghost/)).

However, this is actually solvable, as you can provide environment variables to the ghost instance in order to configure it, see [the docs](https://docs.ghost.org/v1/docs/config#section-running-ghost-with-config-env-variables). In your specific case, to run ghost's docker with a different url you would use: 
```sh
docker run -d --name ghost -p 3001:2368 -e url=http://my-ghost-url.com -v /path/to/ghost/blog:/var/lib/ghost/content ghost:1.8.1-alpine
```

Closing because this is neither a bug nor an issue related to Ghost itself.

**Comment by hedefalk** [comment]
Actually, this didn't universally help. Maybe it's just casper theme that's broken? Posts and stuff work, most nav work, but only the upper left thing is borked:

![image](https://user-images.githubusercontent.com/116520/35628256-9f0e9824-069b-11e8-93ec-8180de21a447.png)


![image](https://user-images.githubusercontent.com/116520/35628214-7b8684ac-069b-11e8-97d9-aa1dff3c5579.png)

**Comment by hedefalk** [comment]
Nah, casper seems to use a reasonable named variable at least:

https://github.com/TryGhost/Casper/blob/bfaae0f7ba5c4b9d70d9f37b65ea765257aa5486/partials/site-nav.hbs#L5

Nowhere in the settings can I change this and I do have set the env "url" correctly.

**Comment by hedefalk** [comment]
Scrap all my comments. Turns out I misunderstood docker-compose. It doesn't re-read config on restart.

```
viktor@i7:/var/lib/ghost$ sudo docker-compose restart
Restarting blog ... done
```

vs

```
viktor@i7:/var/lib/ghost$ sudo docker-compose stop
Stopping blog ... done
viktor@i7:/var/lib/ghost$ sudo docker-compose up -d
Recreating blog
```

**Comment by DwijadasDey** [comment]
Map a ghost config file from your host to the container [root dir of ghost] using volume. The URL parameter in your config file will reflect your domain name instead of localhost.

````
$ vi /home/ghost/config/config.production.json
{
  "url": "http://SUBDOMAIN.DOMAIN.TLD/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
$ ghost restart

````

**Comment by DwijadasDey** [comment]
@Bellusterra , If you have created the Ghost container using docker run command then you can map the config file from your host machine to  container using -v option like the following:

# docker run -p 80:2368 -v PATH_IN_HOST_MACHINE/config.production.json: PATH_IN_CONTAINER/config.production.json ...

To get the location of the file `config.production.json` inside container run, `docker exec <containerid> /bin/bash` and then find the location of the file config.production.json which is your PATH_IN_CONTAINER (Most probably it will be inside /var/lib/ghost). Be sure to edit the parameter `url` in the config file from your host machine.

**Comment by mossmoss** [comment]
I was stumped by the localhost:2368 issue running Ghost within Rancher and Docker. I could register a user and access the blog, but was unable to upload images. I think I was able to resolve taking a clue from this [comment](https://github.com/TryGhost/Ghost/issues/8966#issuecomment-326746476) -- I cloned the Ghost container in Rancher, and there you can set the "url" environment variable, I set it to the IP address that was working for Ghost (instead of I presume the default of localhost) and things seem to be working better now.

**Comment by nendonerd** [comment]
setting docker-compose environment as url=\<your site\> works, but mind that it's <b>CASE-SENSITIVE</b>, only 'url' works but not 'URL'
```
services:
    ghost:
        environment:
            - url=https://xxx.xxx
```

**Comment by Bellusterra** [comment]
@DwijadasDey Thank you for your response. I had a difficult time finding the file you described, I think now it was because I was not in the container itself, so what you suggested may have very well worked for me, so thank you... I ended up when starting the docker container just adding the “-e url=https://my.website.com” to the list of variables which as @nendonerd also suggested is the same as using docker compose file and adding it under the environment variable there. Thank you both for your help.
