### ISSUE TITLE
type enter in title, cursor go to body editor

### ISSUE THREAD

**Issue by nasa9084** [TryGhost/Ghost#8970]
### Issue Summary

in Japanese, enter key is used for Kana-to-Kanji conversion finalize in addition to insert a new line.
when I type some title in Japanese and type enter to finalize conversion, the cursor go to post body editor.

### Steps to Reproduce

1. type some title in Japanese
2. convert to Kanji
3. type enter for conversion finalize
4. the cursor go to post body editor

### Technical details:

* Ghost Version: 1.8.1
* Node Version: v6.11.2(according to https://hub.docker.com/_/ghost/)
* Browser/OS: firefox 55.0.3 on MacOS
* Database: SQLite

running on docker container on Rancher.

**Comment by kevinansfield** [comment]
Pressing `<kbd>Enter</kbd>` to move from the title to the body is the expected behaviour.

Do you know if there's anything specific about the kana-to-kanji conversion that is detectable via JS?

**Comment by nasa9084** [comment]
> Pressing Enter to move from the title to the body is the expected behaviour.

I thought it...😥

> Do you know if there's anything specific about the kana-to-kanji conversion that is detectable via JS?

I don't know...
If i know and I can write JS well, I will fix it and send PR.

So I'd like to make a suggestion.
Can you make a toggle config for `Enter` binds to move cursor or not?

**Comment by kevinansfield** [comment]
It sounds like it may be possible to switch the <kbd>Enter</kbd> key detection to the `keydown` event according to the discussions here:

https://stackoverflow.com/questions/22705698/distinguishing-between-enter-keypress-for-japanese-kanji-suggestion-and-other
https://meta.stackexchange.com/questions/66646/confirming-context-menu-entries-via-enter-when-entering-comments-triggers-commen/217498#217498

I haven't tested it but that's a good place for anyone who wants to tackle this to start.

> Can you make a toggle config for Enter binds to move cursor or not?

No, we have a policy not have configs for anything like this because if we start doing that it never ends then there's a million and one config options which are impossible to support, debug, and develop around because there are so many possible variations.

**Comment by nasa9084** [comment]
this problem is solved with 2.0 new editor.
thanks.
