### ISSUE TITLE
Links that have space are broken

### ISSUE THREAD

**Issue by cristiandley** [TryGhost/Ghost#8991]
### Issue Summary

Migrated from Ghost 0.7.x to Ghost 1.0 > 1.8 after that... and Links that are like

`[LINK](http://mycoool.link/That Opens A Pdf.pdf)` is broken now, they look like this:

![link](https://user-images.githubusercontent.com/1873659/30213081-ddb54e6e-947d-11e7-968d-06794e3cbf67.png)

### Technical details:

* Ghost Version: 1.8
* Node Version: 6.9.5
* Browser/OS: Chrome
* Database: MySql 5

**Comment by kevinansfield** [comment]
@cristiandley this is a result of a more spec-conformant markdown parser. URLs in links should be urlencoded, so `[LINK](http://mycoool.link/That Opens A Pdf.pdf)` should be written as `[LINK](http://mycoool.link/That%20Opens%20A%20Pdf.pdf)`.

The first space inside the `( )` brackets is used to delineate the end of the url so that it's possible to add titles to links. eg. `[link text](https://mysite.com/some%20file.pdf "title shown on hover")`. You can see the full spec for links in markdown here http://spec.commonmark.org/0.28/#links

I've added a note to the "Markdown breaking changes" section of the [Migrating to 1.0.0](https://docs.ghost.org/docs/migrating-to-ghost-1-0-0) guide.

**Comment by cristiandley** [comment]
@kevinansfield is there an easy way to give this a solution ? i have more than 1000 posts.

**Comment by cristiandley** [comment]
A friend of mine did this snippet ... i just felt the need to share:

```JavaScript
const transformLinks = require("transform-markdown-links");
const Promise = require("bluebird");
const _ = require("lodash");
const models = require('./core/server/models');
const db = require('./core/server/data/db');
const ctx = {context: {internal: true}};

models.init();

return models.Post.findAll(ctx)
    .then(function (allPosts) {
        return Promise.each(allPosts.models, function (post) {
            if (post.get('slug') == '') {
                return Promise.resolve();
            }

            let mobiledoc = JSON.parse(post.get('mobiledoc'));

            mobiledoc.cards[0][1].markdown = transformLinks(mobiledoc.cards[0][1].markdown, (link, text) =>
                    encodeURI(link.toString().trim().replace(/\s{2,}/g, " "))
            );

            return models.Post.edit({
                mobiledoc: JSON.stringify(mobiledoc)
            }, _.merge({id: post.id}, ctx));
        });
    })
    .finally(function () {
        console.log("jop");
        db.knex.destroy();
    });
```
