### ISSUE TITLE
Update notification issues

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9006]
Ghost 1.8.4 - can't dismiss update notifications. And isn't this the wrong update notification? Also these are getting really annoying now. Every single time I open Ghost there's a new one, it's worse than Spotify.

I don't know what to do in the medium/long term - but in the short term could we at least disable update notifications for patch updates? We would just need to bump minor for security issues obviously

![image](https://user-images.githubusercontent.com/120485/30361057-be0081a8-9809-11e7-8770-2ba5e5084675.png)

**Comment by letsjustfixit** [comment]
It would be awesome if the releases would be labelled &/ categorized somehow.
Eg
- feature update
- maintenance release (bugfixes)
- security update

Which would make it easier to realize the urgency of a specific update..

**Comment by kirrg001** [comment]
> And isn't this the wrong update notification? 

As soon as the [PR](#8871) for LTS get's an approval, we port the changes over to 1.0. And then we consume notifications from the service, the message will change and we can control which notification is dismissible. 

> Every single time I open Ghost there's a new one, it's worse than Spotify.

Can you explain where? If you are on the latest Ghost version, you shouldn't see any update notification. Maybe your master is not up-to-date?

>  but in the short term could we at least disable update notifications for patch updates?

Yeah can do that for tomorrow's release 👍 

---

The refactoring for notifications was not yet released, see the open issue #5071 and https://github.com/TryGhost/Ghost/releases.

**Comment by dm17** [comment]
Ditto on the annoyance. Don't want to update to 5x if I have the latest 4x because I have a lot of sites to manually upgrade, and ghost doesn't upgrade very easily. I have to 1) migrate from sqlite to mysql 2) do a "full reinstall" of ghost - https://ghost.org/docs/reinstall/
Having to do a full reinstall seems like some anti-patterns are in play when the software is technically fully "reinstalled" by running the 5x rather than 4x docker image.
