### ISSUE TITLE
How to create custom helpers in ghost v1.7.1 

### ISSUE THREAD

**Issue by vivekmengu016** [TryGhost/Ghost#9007]
I wanted to create a helper in ghost to lower case the text.

I used the same in old ghost version it worked fine but with new version it throws an error saying "Helper not found on ghost dashboard"

How do i solve this, there is no proper documentation for ghost theme development... :( 
Why so many releases with small small fixes

**Comment by AileenCGN** [comment]
Hey @vivekmengu016 👋 

There is a #themes channel in [slack](https://ghost.org/slack) where you can get help from the community for questions like this. Please provide as much information as possible when you ask in the channel, so people are able to assist and help you. You can also find a pretty detailed [documentation](http://themes.ghost.org/) for themes to get more information.

Closing this as it is not an issue with Ghost.

**Comment by yamsellem** [comment]
@AileenCGN using slack for this kind of purpose seems painful to me.

I have the same issue @vivekmengu016 has (and I have it from the first day: the use of custom handlebars helpers in a theme).

I don't event see how one can do a blog without one custom helper: it help so much!

Browsing the history of slack to find the answer @vivekmengu016 got 17 days ago is almost impossible, and it's just 17 days.

I've always use github issue for question, because, with the time, it build a great documentation for an open source project. Anyone can search there if the doc is missing something, and it helps a lot.

**Comment by yamsellem** [comment]
I'm still encountering the issue, can you please document somewhere how to use custom handlebars  helper in ghost, of say if this is impossible for the moment?

Thanks.

**Comment by AileenCGN** [comment]
This is not an issue, it's a feature request. The usage of custom helpers is currently not possible with Ghost. 

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our [slack](https://slack.ghost.org/) community - https://slack.ghost.org. Furthermore, you can find our theme documentation [here](https://themes.ghost.org).

**Comment by yamsellem** [comment]
Thanks @AileenCGN for making that clear.
I've already chatted in slack about that a couple of week ago, and the idea was left in reflexion by someone of the team, I presume. May I open a feature request about it?

For info, I'm blocked with Ghost 0.11.11 because of that: it was possible to use custom helpers then, now is seems that a mechanism in Ghost prevent to do so.

**Comment by ErisDS** [comment]
@yamsellem In Ghost 0.11.11 it was only possible with a hack - it was never supported and it is still not. The restructuring in 1.0 means the hack has gone away.

If you need a helper that Ghost does not provide - we ask that you propose it in the #themes channel in Slack, so that we can collect together information on what helpers developers would find useful and potentially add them to core, as we did with the reading time helper recently.

We will be creating a way to add custom helpers in future with apps - it's already tracked on our internal feature board.

**Comment by yamsellem** [comment]
@ErisDS I cannot propose the helper I need to the team because its only dedicated to the website I work on.

On some post, we are using something like (_in the post content_):
`==Espèces : Bar, Lieu, Dorades, Homard, Tourteau==`

To generate something like that:
![species](https://user-images.githubusercontent.com/606754/34640663-172933a4-f2f7-11e7-9c7c-4f850647390a.png)

Then, with a helper, the `{{hmtl}}` is printed without this <mark>.
And with another helper, this <mark> is transformed into a piece of HTML with the dedicated images and added after the `{{html}}`.

This helps greatly to build a post not only made of paragraph, images and titles, but also made of components. This can be also used to offer a grid display of the post (_ex. the content on one column and a part of it as metadata in a block on its right_).

Maybe I missing something here, but being able to offer a rich post template (_with grid content, in one word_) is very helpful to build a website. Maybe Ghost is not targeting this king of use for now, or it offers something I've missed, if so, I would greatly appreciate any help on the matter.
