### ISSUE TITLE
iOS Admin panel: Can't input Chinese and Japanese

### ISSUE THREAD

**Issue by ITJesse** [TryGhost/Ghost#9017]
### Issue Summary

iOS Admin panel: Can't input Chinese and Japanese

### Steps to Reproduce

1. Open the Ghost Admin.
2. Create a new story.
3. Input something with Chinese input method.

### Technical details:

* Ghost Version: v1.8.6
* Node Version: v6.11.3
* Browser/OS: iOS 11
* Database: MariaDB

For more info please see this issue I created in the repo of mobiledoc-kit.
https://github.com/bustle/mobiledoc-kit/issues/583

**Comment by kevinansfield** [comment]
@ITJesse this is an issue for [CodeMirror](https://github.com/codemirror/CodeMirror) which is the editor that Ghost's markdown editor is using rather than `mobiledoc-kit`.

It sounds like [they are already aware](https://github.com/codemirror/CodeMirror/issues/3137) of this problem? As this issue doesn't contain any actionable reproduction steps and it really belongs in a different project I'm going to close for now.
