### ISSUE TITLE
Excerpt Mode: Paragraph

### ISSUE THREAD

**Issue by karai17** [TryGhost/Ghost#9019]
Currently there are only two ways of getting excerpt text: by word count, and by character count. While these are both useful, it is not always desirable to pull fragmented paragraphs. I think it would be very handy to be able to pull whole paragraphs at a time.

**Comment by kevinansfield** [comment]
@karai17 the `{{excerpt}}` helper is intentionally limited as it's meant for extracting short pieces of text to use in post lists where large bodies of text won't fit in the theme design.

If you need to use full paragraphs or you are using a language where character/word/paragraph counts don't work it's recommended to add [custom excerpts](https://blog.ghost.org/custom-excerpts/) to your posts so that you have complete control over what's displayed.
