### ISSUE TITLE
Enhancement: list tags for Stories in admin

### ISSUE THREAD

**Issue by thorsten-panknin** [TryGhost/Ghost#9027]
### Issue Summary

No tags listed for stories in admin. The info would be practical, at least for me, but it's missing.

### Steps to Reproduce

1. Log in to Ghost admin
2. Click on "Stories"
3. Look at Story list to the right -- no tags

### Technical details:

* Ghost Version: 1.8.6
* Node Version: 6.11.1
* Browser/OS: Firefox on Windows 10
* Database: mysql

**Comment by kevinansfield** [comment]
Hey @thorsten-panknin 👋 Thanks for your input! The tags were intentionally kept off the stories screen because it can become very noisy to display them and it was seen as not being particularly useful for most users for the majority of the time.

That said we're always interested to hear concrete use cases that the UI fails on. Would you care to elaborate on why you need tags to be visible on the stories list which isn't already covered by the tags dropdown filter?

We only use GitHub for bug tracking so I'll close this because it's a feature request but we have noted it on our internal feature tracker so we can gauge how often it comes up 😄

**Comment by thorsten-panknin** [comment]
Hey @kevinansfield,

thanks for your reponse! I'll add this stuff to other channels in the future, my apologies.

I see assigned tags as metadata equal to author and publish date. If I assigned tags, why would I _not_ want them be listed? (I could imagine a "last edited" entry, too, as an aside), Having to open up a Story for that seems to be an unneccessary step for me.

Assuming that most people assign, say, a handful of tags, I don't see why that would be noisy on a desktop display or maybe even on a tablet display.
