### ISSUE TITLE
Update Notification Problem

### ISSUE THREAD

**Issue by MertcanGokgoz** [TryGhost/Ghost#9040]
### Issue Summary

App is up-to-date but notification has come every page

### Steps to Reproduce

1. Login admin area
2. I saw the notification :)

and i check 2 times server side `ghost update`

```
root@main:/var/www/ghost# ghost update
✔️ Checking for latest Ghost version
All up to date!
root@main:/var/www/ghost#
```

### Technical details:

* Ghost Version: 1.9.0
* Node Version: 6.11.3
* Browser/OS: Chrome 61.0.3163.91
* Database: mysql

Screenshot

![update](https://user-images.githubusercontent.com/8042604/30744147-6a0769fc-9fa9-11e7-9cd3-8b819aafda92.PNG)

**Comment by letsjustfixit** [comment]
Suggestion: 
  - if migration is needed already it could dismiss the upgrade notification..

**Comment by MaluNoPeleke** [comment]
Same problem on my server with current 1.9.0.
I always update with my script including database migration: https://www.peleke.de/ghost-1-0-aktualisierung-bei-uberspace/

**Comment by mmornati** [comment]
The problem seems related to permissions.
Here you are the full log about the problem:
`blog                                 | NAME: NoPermissionError
blog                                 | MESSAGE: You do not have permission to dismiss this notification.
blog                                 |
blog                                 | level:normal
blog                                 |
blog                                 | NoPermissionError: You do not have permission to dismiss this notification.
blog                                 |     at new NoPermissionError (/ghost/blog/versions/1.9.0/node_modules/ghost-ignition/lib/errors/index.js:108:23)
blog                                 |     at destroyNotification (/ghost/blog/versions/1.9.0/core/server/api/notifications.js:165:21)
blog                                 |     at runTask (/ghost/blog/versions/1.9.0/core/server/utils/pipeline.js:16:24)
blog                                 |     at /ghost/blog/versions/1.9.0/core/server/utils/pipeline.js:26:20
blog                                 |     at tryCatcher (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
blog                                 |     at Object.gotValue (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/reduce.js:157:18)
blog                                 |     at Object.gotAccum (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/reduce.js:144:25)
blog                                 |     at Object.tryCatcher (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
blog                                 |     at Promise._settlePromiseFromHandler (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:512:31)
blog                                 |     at Promise._settlePromise (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
blog                                 |     at Promise._settlePromise0 (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
blog                                 |     at Promise._settlePromises (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
blog                                 |     at Promise._fulfill (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)
blog                                 |     at Promise._resolveCallback (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:432:57)
blog                                 |     at Promise._settlePromiseFromHandler (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:524:17)
blog                                 |     at Promise._settlePromise (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
blog                                 |     at Promise._settlePromise0 (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
blog                                 |     at Promise._settlePromises (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
blog                                 |     at Promise._fulfill (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)
blog                                 |     at Promise._resolveCallback (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:432:57)
blog                                 |     at Promise._settlePromiseFromHandler (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:524:17)
blog                                 |     at Promise._settlePromise (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
blog                                 |     at Promise._settlePromise0 (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
blog                                 |     at Promise._settlePromises (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
blog                                 |     at Promise._fulfill (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)
blog                                 |     at Promise._resolveCallback (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:432:57)
blog                                 |     at Promise._settlePromiseFromHandler (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:524:17)
blog                                 |     at Promise._settlePromise (/ghost/blog/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)`

**Comment by moebis** [comment]
So how do we dismiss this message. I chown ghost:ghost -R /var/www/ghost and reran "ghost update"

**Comment by letsjustfixit** [comment]
I think adding the ID of your notification to the following entry should work
```select settings.key,settings.value from settings where settings.key="seen_notifications";```
i mean something like this would your notification added to the value array
```update settings set  settings.value="[]" where settings.key="seen_notifications";```

**Comment by tobiasboyd** [comment]
After upgrading my install to 1.9.1, the update notification banner went away, but it hasn't shown up even when new releases drop - I have manually run `ghost update` to get 1.10 and 1.11, but never saw a banner alerting me they had been released... is that expected behavior until this fix ships?

**Comment by letsjustfixit** [comment]
Heyo,
@Toby thats a side effect of this:
https://github.com/TryGhost/Ghost/pull/9009
(Changed showing update notifications for minor/major only )
Cheers
