### ISSUE TITLE
Permissions improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9043]
This is basically a brain dump of notes on our permissions system. I'm currently working towards introducing attribute based permissions to solve #8602 and other problems. 

As part of that work, I've reviewed the code, cleaned it up a little, and am working towards ensuring we have 100% test coverage, so that refactoring is possible.

Once I get a bit further through this, I'll write up some details of my thoughts on the more long-term items, so that the context isn't lost.

High Priority:
- [x] Split public-related and context code into logical components
- [x] Ensure we have 100% test coverage
- [x] Introduce attribute-based permissions #9025

Cleanups / refactors to make the code more manageable:
- [x] Move remaining code out of index.js
- [x] refactor the odd way of exporting
- [x] rename "effective" -> "providers"
- [ ] use modern JS classes
- [ ] don't use enumerable:false for the action types
- [ ] optimisations e.g. caching, or only building needed objects

Moving towards making permissions a dependency:
- [ ] refactor so that hard-coded Ghost-specific logic is configuration
- [ ] simplify/abstract out the concept of "context" so that it's easier to add new ones
- [ ] maybe think about this a bit like passport? providers & mechanisms 🤔 

Long term features:

- [ ] can external and public contexts be merged?
- [ ] consider reopening / recreating the missing pieces of https://github.com/TryGhost/Ghost/issues/5614
- [ ] bring more of the "public" permissions logic into the permissions layer
- [ ] Add proper permissions for clients (e.g. a new context / effective permission layer)
- [ ] Maybe look at using JSON-based policies or other ways of describing permissions
- [ ] More specific error messages for attribute-based permissions [ref](https://github.com/TryGhost/Ghost/pull/9067#discussion_r141283509)

Note: bookshelf ref material https://github.com/sequiturs/bookshelf-advanced-serialization

**Comment by allouis** [comment]
Copied from #10080


# Permissions Issue

The permissions service in ghost is not as good as it could be.

One of the biggest issues is that it has a lot of work offloaded to the model layer in `permissible` functions, this makes the logic for permissions scattered and hard to determine/audit from a single place. But there are some smaller issues we can tackle to help make fixin that easier.

## What could be done

### Nested loops

Due to the permissions service being quite complex, it is quite hard to see what is going on and reason about it. This is in part due to the API the permissions service provides e.g. `canThis(context).edit.posts(model, unsafeAttrs)` It need to do numerous loops to build up the data structure, only for it to be used once and thrown away.

If we were to make a change to the `canThis` api along the lines of:

```javascript
canThis(context, 'edit', 'post', model, unsafeAttrs);
```

I think it would result in huge improvement of readability and mantianablity of the module.

### External context

As the permissions service has grown it has become necessary to add permissions to unauthenticated requests, we've done this via an `external` property on the `context` - this has now split permissions outside of the permissions service. If we were able to bring those permissions back into the permission service, we can again make it more maintaniable, and easier to make future changes.

I think the solution here is to add an `Unauthenticated` or `Anonymous` role. To begin with we would just give this role permissions for `add` and `edit` actions on the `subscriber` object.

### Owner permissions

We also have scattered through the permissible functions, references and check to the Owner role, this again moves permission logic outside of where it belongs.

To address this we should probably give the Owner role all permissions

(There would still need to be checks to ensure the owner could not remove their role or delete themselves)

### App context

We have an app context, that has further complicated the permissions service, as we have to check the permissions of the user AND the app. From initial searching - I don't believe the functionality is used anywhere in ghost, nor has it been documented.

Can we delete it?

**Comment by ErisDS** [comment]
Right now the permissions system is holding up. However, we know we will definitely need to revisit all of this in the near future. Tagged `feature` `later` & closed.
