### ISSUE TITLE
Ghost Public API is inaccessible

### ISSUE THREAD

**Issue by iharsuvorau** [TryGhost/Ghost#9047]
### Issue Summary
Can't access the API of the ghost from the docker `ghost:latest` container https://hub.docker.com/_/ghost/. The site is running fine at 192.168.99.100:9091. In settings *Public API* is on be default. 

Tried to query with curl:

 request | response
---------|-------
http://192.168.99.100:9091/ghost/api/posts/?client_id=client&client_secret=secret | returns 302 with `Location` header pointing at `http://192.168.99.100:9091/ghost/#/api/posts/?client_id=client&client_secret=secret` 
http://192.168.99.100:9091/ghost/api/v1.7.0/posts/?client_id=client&client_secret=secret | with the same result
http://192.168.99.100:9091/ghost/api/v1.8.7/posts/?client_id=client&client_secret=secret | the same
http://192.168.99.100:9091/ghost/api/posts/ | the same

Requesting any URL with `../#/..` returns 200 OK but actually it's a 404 error HTML page.

Browser, OS:
* Chrome at macOS Sierra 10.12.6

Ghost:
* Version 1.8.7
* Environment production
* Database sqlite3

### Steps to Reproduce

1. docker run -p 9091:2368 --name ghost -d -e url=http://192.168.99.100:9091 ghost:latest
2. curl -v "http://192.168.99.100:9091/ghost/api/posts/

### Expect:

* expect the server to return 404 instead of 200 accessing an invalid URL
* a successful or failed response from `/ghost/api/posts/` or `/ghost/api/<version>/posts/`, or a redirect to a valid page but not the redirect to an invalid page

**Comment by kevinansfield** [comment]
Hey @iharsuvorau 👋

All of the API URLs you've referenced as trying are incorrect. The API only lives on one URL:

http(s)://yoursite.com/ghost/api/v0.1/*

`v0.1` is the only API version. Unfortunately it looks like our doc hosting platform at https://api.ghost.org is now outputting incorrect URLs - I'll look into that as I can see why there would be confusion.

For reference it's recommended that you use the [`ghost.url.api()`](https://themes.ghost.org/v1.0.0/docs/ghost-url-api) helper where possible - if you use that then the correct URLs will be generated for you.

--- 

All the other behaviour you mention is correct.

`yoursite.com/ghost/*` will redirect to the admin screen at `yoursite.com/ghost/#/$1` - the server will then render the admin SPA's basic HTML page and the SPA takes over the routing. In all of the examples you gave above the admin app will transition to a 404 error because it won't recognise the incorrect URLs

**Comment by kevinansfield** [comment]
https://api.ghost.org reference URLs have been fixed
