### ISSUE TITLE
[Ghost Admin] Misleading color variable names

### ISSUE THREAD

**Issue by ifvictr** [TryGhost/Ghost#9055]
In https://github.com/TryGhost/Ghost-Admin/blob/master/app/styles/app-dark.css#L63-L67, you can see that the darkest grey color is assigned to `lightgrey`, and the lightest grey color is assigned to `darkgrey`.

**Comment by kevinansfield** [comment]
Hey @ifvictr, that's intentional. `app-dark.css` is the CSS for Night Shift mode, it contains overrides and sits on top of the regular CSS. The variable names you mention are used throughout all of the CSS files, in order to be a "dark" mode the values attached to the variables need to be reversed in `app-dark.css` compared to the default "light" CSS values.
