### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by cc17** [TryGhost/Ghost#9170]
### Issue Summary
when i use docker-compose to start my app,i found the navigator link not right,it has hard code,fix the port on 2386. But my host has used nginx,and port is 80 now.so it cant work.

### Steps to Reproduce

1. This is the first step

create a docker-compose.yml like this:
```bash
version: "3.1"

networks:
  ghost:

services:
  ghost-app:
    image: hub.c.163.com/library/ghost:latest
    restart: always
    networks:
      - ghost
    ports:
      - 2386:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost

    
  nginx-ghost:
    build: nginx
    networks:
      - ghost
    depends_on:
      - ghost-app
    ports:
      - "80:80"
  
  db:
    image: "hub.c.163.com/library/mysql"
    networks:
      - ghost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - $PWD/data:/var/libmysql
    ports:
      - "3306:3306"
```
then input this code to the command:
```bash
docker-compose up -d
```
2. and,the service is work. We can visite the website,like this:
http://localhost

3.right click the website,and choose "view the code",you will find:
https://img.alicdn.com/tfs/TB1jnFLmaagSKJjy0FgXXcRqFXa-1100-271.png
thx.

**Comment by AileenCGN** [comment]
Hi @cc17 👋 

We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.
