### ISSUE TITLE
Why just an Hour for caching these files?

### ISSUE THREAD

**Issue by fabianmarcus** [TryGhost/Ghost#9175]
https://github.com/TryGhost/Ghost/blob/d943fc7cc94c12a640164d3104673114fc33c305/core/server/blog/app.js#L51

**Comment by fabianmarcus** [comment]
Hi @ErisDS ,

even though you found my question not as important to answer it, it is a serious one. There isn't a direct possibility to configure the cache duration, isn't it?

Pagespeed Insights wants a longer one. It would be nice if a user could configure this directly via the config file. Or is this already possible?

Best regards 
Fabian

**Comment by kevinansfield** [comment]
@fabianmarcus your issue was closed because you ignored our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md) that GitHub highlights for you and also ignored the default issue text that is meant to guide you to the right place.

GitHub is our office - we use it solely for bug tracking and feature development. Noise on GitHub takes up a lot of our (very small) development teams time, when the well-highlighted rules are ignored and there's less time spent writing a reasonable/researched question than it would take a developer to answer/point you to the right place the issue will just be closed.

**Comment by fabianmarcus** [comment]
Ah, ok, sorry about this. I will just ask my questions in your slack channel and take a look at your guidelines.
