### ISSUE TITLE
Updating (casper) shouldn't wipe out disqus comment section

### ISSUE THREAD

**Issue by wcchristian** [TryGhost/Ghost#9177]
### Issue Summary

When updating ghost, I find that the disqus enable code in post.hbs gets disabled again if there is an update to casper. This constantly forces me to go back(I forget to re-enable nearly every time that I upgrade 😉 ) and re-enable.

I propose we wrap the disqus code in an If check and allow the user to imput their disqus info in the admin UI. This way when casper updates, it won't be disabled. It would just again be the if check and if enabled, disqus code would be run.

I would be willing to work on this.

### Steps to Reproduce

1. Enable Disqus
2. Update Ghost (With casper update)
3. Note that disqus is now disabled.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I consider this to be a new feature.

### Technical details:

* Ghost Version: latest (will update this later when I can access my server) 
* Node Version: latest (will update this later when I can access my server)
* Browser/OS: viewing on: chrome/mac running ghost on: ubuntu server 16.04
* Database: sqlite

**Comment by wcchristian** [comment]
Again, provided the ghost team thinks that this is a good idea, I would love to contribute.

**Comment by vikaspotluri123** [comment]
Ghost doesn't have an official commenting engine recommendation (for example, the help center also has a guide for Facebook). Disqus is one of the easier systems to set up, so it's included in the comments of casper as an example of _how_ you would integrate a commenting engine.

That being said, the Casper theme is the default theme, so if there are any bugs, they _must_ be pushed out to everyone, including people who have made changes to it. Therefore, even though you're making a minimal modification to the theme, you should use it as a custom theme (upload it under a different name) since you made modifications to it.

On a side note, this seems more like an issue for the [Casper](https://github.com/TryGhost/Casper) repo, since the issue is specific to it 😄

**Comment by wcchristian** [comment]
Ahh, good point! I will do so. I didn't know where to put this since I figured the solution would be changing a few of the repos 😄 . 

Otherwise, is there any plan of allowing custom UI in the admin area so that if I did implement this in a custom theme I could add a switch or something to the management UI? I suppose this would be adding variables to ghost to be accessible in the hbs files of the theme.

Thanks for the response! Closing this issue....

**Comment by vikaspotluri123** [comment]
As of now, the only thing that _might_ support something like that is apps, but I'm not sure if the admin interface would support inserting things like that.

Another possibility is adding support for theme options. I know it was in the research stage a few weeks ago, and I'm not sure what has happened to it since then. As far as I am aware, the only current theme option that's available is `posts_per_page`

**Comment by wcchristian** [comment]
I'm definitely interested in theme options if that's a possibility.
