### ISSUE TITLE
Page not loading http2

### ISSUE THREAD

**Issue by Arkwin** [TryGhost/Ghost#9191]
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Http requests work fine, http2 requests don't load anything

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Load the blog with an http2 request (not sure if it's part of it, but I'm also using ssl)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.16.0
* Node Version: latest
* Browser/OS: mostly Microsoft ones 
* Database: whatever the ghost install config said to use

**Comment by kirrg001** [comment]
Hi @Arkwin!

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org. We can always re-open if it turns out to be a problem with Ghost.
