### ISSUE TITLE
Post without tags (for {{post.tags}}) creates error

### ISSUE THREAD

**Issue by Kuzoin** [TryGhost/Ghost#9258]
Problem with Get Helper and `{{post.tags}}`

`{{#get "posts" limit="3" filter="tags:[{{post.tags}}]+id:-{{post.id}}" include="tags,author"}}`

### Steps to Reproduce

1. Create a new post without any tags
2. Publish the post
3. Navigate to the post in the frontend
4. See the error in the server logs

When I use `{{#primary_tag}}` solution is https://github.com/TryGhost/Casper/issues/382
What is the solution for `{{post.tags}}`?

### Error Log
```
Error: Query Error: unexpected character in filter at char 6
tags:[]+id:-597a5f603c1f29
------^
```

### Technical details:

* Ghost Version: 1.17.3
* Node Version: v8.9.0
* Browser/OS: Safari/ macOS 10.13.1
* Database: sqlite3

**Comment by AileenCGN** [comment]
Hi @Kuzoin 👋 

We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. 

What you are describing as a wrong usage of the `filter` rather than an issue with the post not having a tag. The correct usage would be this:

`{{#get "posts" filter="tags:{{tags.[0].slug}}+id:-{{id}}" limit="3" include="tags,author"}}`

We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

**Comment by ErisDS** [comment]
I have raised a bug in GQL for this to try to address it, we have seen the same problem in Casper: https://github.com/TryGhost/Casper/issues/382

The filter `filter="tags:[{{post.tags}}]+id:-{{post.id}}" ` is correct  - it's used / recommended in the docs here: https://themes.ghost.org/docs/recent-featured-sidebar.

However, if you have posts which have no tags, then the filter will be `tags:[]` and unfortunately there is no handling in the filtering for empty groups.

The solution for now is to wrap the filter in an if statement to guard against this case (as we do in Casper).

```
{{#if posts.tags}}
{{#get "posts" limit="3" filter="tags:[{{post.tags}}]+id:-{{post.id}}" include="tags,author"}}
{{/get}}
{{/if}}
```

**Comment by Kuzoin** [comment]
@ErisDS Finally I used:

```
{{#if tags.[0]}}
{{#get "posts" limit="3" filter="tags:[{{tags[*].slug}}]+id:-{{id}}" include="tags,author"}}
{{/get}}
{{/if}}
```

Regards!

**Comment by sunknudsen** [comment]
Hey @ErisDS,

I just encountered issue in edition theme.

```
Error: Query Error: unexpected character in filter at char 7
    at Child.applyDefaultAndCustomFilters (/home/sun/sunknudsen-ghost/versions/4.33.0/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:66:23)
(tags:[]+id:-61ed65f8a9e00b
-------^
```

I see your issue is still open on https://github.com/NexesJS/NQL-Lang/issues/3.

Adding tag to all posts fixes issue, but feels like a hack.

Is there an official workaround?

Thanks!
