### ISSUE TITLE
Post scheduling not publishing posts at the scheduled time

### ISSUE THREAD

**Issue by daneverson** [TryGhost/Ghost#9287]
### Issue Summary

I am running a self-hosted Ghost installation on Ubuntu 16.04, on a DigitalOcean droplet, inside a Docker container, using the standard [alpine Ghost image](https://hub.docker.com/_/ghost/). I had written a post and scheduled it to publish in the future. When I checked a day after the publish date to ensure it had become visible, it had not. This is not a timezone issue as the post was scheduled to publish about 36 hours ago at the time that I checked.

### Steps to Reproduce

1. Create a new post
2. Schedule it to publish in the future
3. Check at scheduled time to see post published on live site
4. Post is not published

In the list view of stories, the story was still marked with a green badge, "scheduled", and said in green text that it "will go live on <date>", as expected, however this date was in the past, and the expected result would be that the story say "Published" and not "scheduled" at this point.

### Technical details:

* Ghost Version: 1.17
* Node Version: 6.11.5
* Browser/OS: Firefox / MacOS
* Database: SQLite

**Comment by kirrg001** [comment]
Hey!

Sorry to hear you are having trouble, but i can't reproduce.

Please swing by our [slack channel](https://slack.ghost.org) to figure out why post scheduling does not work for you.

Maybe [this link](https://derekswingley.com/2016/09/10/troubleshooting-ghost-post-scheduling-failures/) helps you.

We can re-open this issue if it turns out to be a bug in Ghost.
