### ISSUE TITLE
Pressing Ctrl/Cmd + S inside the tag component triggers a file dialog

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9298]
Whilst editing tags, if you want to save the post you might use the shortcut ctrl / cmd + s. This used to work, but currently triggers a file dialog.

### Steps to Reproduce

1. Open the "PSM" (click the cog in the top right corner of the editor)
2. Click into the tag component
3. Use the ctrl / cmd + s keyboard shortcut

Ghost shouldn't trigger file dialogs for saving, ctrl / cmd + s should trigger a save of the content.

### Technical details:

* Ghost Version: 1.18.0
* Browser/OS: Chrome

**Comment by kirrg001** [comment]
Can confirm. 

@AileenCGN Could you please take a look? It's not super critical, but maybe there is an easy fix available for tomorrow's release.

**Comment by ErisDS** [comment]
Don't sweat this one too much - it needs fixing but is defo not urgent - I assume it's been this way since the new tag component went out.

**Comment by AileenCGN** [comment]
I wasn't able to find a quick fix to get it ready for this release. Will continue looking for a fix until Thursday.

**Comment by kevinansfield** [comment]
@AileenCGN the problem arises [here](https://github.com/TryGhost/Ghost-Admin/blob/master/app/components/gh-token-input.js#L64-L78) where we remove the default key scope because it was preventing certain characters from being typed.

I would first test commenting that code out to see if there are any problems you can see. If there aren't then we can either temporarily leave that code commented or in the `gh-psm-tags-input` component we can pass in an `onfocus` action that sets the key scope back to `default`. If there are still problems with typing then we could pass in the save action to `gh-psm-tags-input` and attach it to Cmd+S on the token input key scope.

**Comment by AileenCGN** [comment]
@kevinansfield This didn't seem to work for me... :(

**Comment by kevinansfield** [comment]
@AileenCGN no problem, I'll have a quick look now. Think I've got a solution in mind

**Comment by kevinansfield** [comment]
The keymaster scope isn't the problem 😞 `Ctrl/Cmd+S` is registered with the scope `all` so it should still be triggered (also tested adding to the `gh-token-input` scope with no luck), instead it looks like something is stopping the keydown event from propagating 🤔
