### ISSUE TITLE
Remove all reliance on incremental IDs

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9299]
In Ghost 1.0 we set out to get rid of incremental IDs. We didn't quite achieve it, as the migrations table still uses it, and I believe there is still some hardcoded expectations around the Ghost owner ID.

Regarding incremental IDs in the migrations table I raised an issue on knex migrator: https://github.com/TryGhost/knex-migrator/issues/91

We need to also try to get rid of reliance on IDs inside of Ghost itself.

This issue needs more detail really - raising it as a starting point.

- [ ] Everything should depend on the owner role and not on the owner ID being 1
  - [x] go over codebase and remove all reliances of owner id 1
  - [x] ensure created_by is not 1
  - [x] external user id is 0 O_O
  - [ ] ensure importing/exporting works as expected e.g. you import id 1
  - [x] generate an ObjectId for the owner
  - [ ] migration script
  - [ ] add a sanitise check in the model layer and compare incoming data types
  - [x] deny /:id/ -> /1/
- [ ] knex-migrator should accept a custom table definition https://github.com/TryGhost/knex-migrator/issues/91

**Comment by kirrg001** [comment]
> I believe there is still some hardcoded expectations around the Ghost owner ID.

Yeah, we had multiple places where we relied on the owner ID being 1, which allows us to **not** query the database, that's why it was very hard to get rid of this pattern. Not sure how hard/easy it is to get rid of this because of permissions (for example [here](https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/index.js#L305)), the importer and tests. **Everything should depend on the `owner` role and not on the owner ID being 1.**

> as the migrations table still uses it

As you pointed out in the [raised issue](https://github.com/TryGhost/knex-migrator/issues/91), it would be good to tell the migrator to use a different ID value and type. Did we ran into any problems with having incremental ID's in this table?

**Comment by kirrg001** [comment]
>  Everything should depend on the owner role and not on the owner ID being 1

FYI: https://github.com/TryGhost/Ghost/issues/9548#issuecomment-378888362

If we start with this, it would be great:
- to get rid of all usages of owner being 1 (!) - in tests, in the code base (e.g. internalUser)
- add a sanitise check in the model layer and compare incoming data types (fn `sanitizeData`)
- generate an ObjectId for the owner
- if we have to figure out if a user is an owner, please use `isOwnerUser` - check is based on the role and not on the id
- probably a 2-3 day task
