### ISSUE TITLE
Can't start ghost

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#9309]
### Issue Summary

Can't start ghost after I updated it

### Steps to Reproduce

1. Update it to latest version
2. Run `ghost start`, it will get the error
### Technical details:

* Ghost Version: latest
* Node Version: v6.9.0
* Browser/OS: macOS High Serria
* Database: sqlite

### More infos
```
Debug Information:
    Node Version: v6.9.0
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost start'
Message: An error occurred.
Stack: Error: An error occurred.
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:55:35)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by AileenCGN** [comment]
Hi @hzb 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

I'm closing this issue here, as it - if it turns out to be an issue - needs to be opened in the [Ghost-CLI](https://github.com/TryGhost/Ghost-cli/) repository, but kindly ask you to first seek help in the above mentioned Slack community.

**Comment by ErisDS** [comment]
@hzb don't normally do this in GitHub, but this sounds like a variation of https://docs.ghost.org/docs/troubleshooting#section-task-execute-is-not-a-function

Essentially, you need to update Ghost-CLI before you can update Ghost.

**Comment by hzb** [comment]
@ErisDS Thanks, can I ask how to update Ghost-CLI? I google it, but I can't find the answer.

**Comment by ErisDS** [comment]
@hzb the link I provided has a link to the upgrade docs.

**Comment by hzb** [comment]
@ErisDS got it, thank you.

**Comment by hzb** [comment]
@ErisDS BTW, can i submit issues or bugs here in Github repo?

**Comment by ErisDS** [comment]
GitHub is for reporting bugs, yes :)
