### ISSUE TITLE
Add reading time to the ghost api

### ISSUE THREAD

**Issue by godofredoninja** [TryGhost/Ghost#9310]
**First I would like to thank you for the excellent work you are doing with the ghost.**

### Issue Summary
I will be brief and precise

— I think it is necessary to add `reading_time` to the ghost [API](https://api.ghost.org/docs/posts)

**Comment by AileenCGN** [comment]
Hi @godofredoninja 👋 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work, but always happy to chat about future ideas over on our  [slack](https://slack.ghost.org/) community - https://slack.ghost.org.

**Comment by kirrg001** [comment]
@godofredoninja In fact it would be great if the API would be able to e.g. return the reading time, but this is not so easy to solve, because the API returns JSON, which returns model data and handlebars helpers like `{{reading_time}}` is additional (computed) data for the frontend, which is right now independent from the JSON API. 

So before we are able to return additional data via the API, we have to come up with a full concept here. So we have to ask ourself the questions: How can we access helper data via the API? Do we want to offer this feature? Also, if Ghost wants to return [full json api](http://jsonapi.org/) format, we have to consider how both tasks can be combined.
