### ISSUE TITLE
Failed at the ghost@0.11.3 start script 'node index'

### ISSUE THREAD

**Issue by jainashish0902** [TryGhost/Ghost#9316]
Issue Summary:
Failed at the ghost@0.11.3 start script. This is most likely a problem with the ghost package,
 not with npm itself. This is probably not a problem with npm. There is likely additional logging output above.
![issue](https://user-images.githubusercontent.com/34434759/33819696-c6a0ceb8-de71-11e7-9570-aa39b1d56684.PNG)

### Steps to Reproduce

1. run npm install --development cmd.
2. another commabd npm start --development in cmd & check the status.

#Even update the latest version of node.js with npm package. 

### Technical details:

* Ghost Version: 0.11.3
* Node Version: v 6.9.5 , npm: 3.10.10
* Browser/OS: Win 10
* Database:

**Comment by AileenCGN** [comment]
Hi @jainashish0902 

We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org, especially here: https://docs.ghost.org/v0.11/docs/installing-ghost-on-windows
