### ISSUE TITLE
if published_at evaluates as true when unpublished

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#9322]
Apologies if this is not a bug, just something I've always found weird in Ghost!

I use the `{{ if published_at }}` helper to prevent the printing of some things on preview templates (comments, analytics etc) and if I unpublish a post (after accidentally publishing it) the if clause still evaluates as true.

## Steps to Reproduce

 1. Use the `{{ if published_at}}` helper somewhere in the post template
 1. Publish a post
 1. Unpublish post
 1. See `{{ if published_at}}` is still evaluated as true

## Technical details:

 * Ghost Version: Ghost Pro

**Comment by kirrg001** [comment]
Hey @jloh!

Thanks for reaching out. `published_at` is not a helper, it's a property of the post model. And it doesn't get unset, because the publish date is freely editable. Eg. if I set a `published_at` in the past on a draft I don't want it to disappear or be reset when I publish. 

So using `published_at` won't work to hide things. You would have to e.g. check if the post's status is draft, but therefor i think you would need to use JS, because Ghost doesn't offer a helper ([similar to this issue](https://github.com/TryGhost/Ghost/issues/5966)). I would suggest to continue with the discussion in [slack](https://slack.ghost.org).
