### ISSUE TITLE
Post scheduling not working

### ISSUE THREAD

**Issue by foggy1** [TryGhost/Ghost#9359]
### Issue Summary

I schedule a post, it says it was set live, and it was not.

### Steps to Reproduce

1. Schedule a post.
2. Check to see if it shows up on my site.
3. It doesn't.

In the dashboard, it uses the correct language, saying that a post "was set live" in the past tense and at the correct time. Additionally, I checked my timezone in the dashboard, and it is correct (it displays the correct local time). Despite saying that things were published at the correct time, they just... aren't really published.

### Technical details:

* Ghost Version: 1.19.0
* Node Version: 6.11.5
* Browser/OS: Ubuntu 16.04
* Database: Ver 14.14 Distrib 5.7.20

**Comment by kirrg001** [comment]
Hey @foggy1!

If the post was published at the correct time, but it's not visible on your blog, it could be that the page cache was not invalidated. 

Please swing by our [slack channel](https://slack.ghost.org/) community - https://slack.ghost.org and ask in the **#help** channel. We can always re-open the issue if it turns out to be a bug in Ghost.
