### ISSUE TITLE
Inlined images are not inlined in the article

### ISSUE THREAD

**Issue by andreygrehov** [TryGhost/Ghost#9360]
### Issue Summary

I inline formulas as images. It works great in the editor's preview screen, but when I open post in the Preview mode (via the Preview link in the Post Settings), Ghost places all the inline images as separate elements.

This is how it looks in the Side-by-Side preview screen:

<img width="628" alt="screen shot 2017-12-29 at 5 48 52 pm" src="https://user-images.githubusercontent.com/409722/34451002-6326cf98-ece7-11e7-8609-5849a68b6c8e.png">

And here is the same piece of content in the Preview mode:

<img width="824" alt="screen shot 2017-12-29 at 5 49 39 pm" src="https://user-images.githubusercontent.com/409722/34451008-79525760-ece7-11e7-8308-0a07b6969f42.png">

1. Is it possible to explicitly tell Ghost that I want an image to be inlined?
2. I suppose we don't want the behavior between Preview and Side-by-Side Preview be different.

### Technical details:

* Ghost Version: 1.19.0
* Node Version: 6.11.5
* Browser/OS: Chrome 63.0.3239.84, macOS Sierra 10.12.6
* Database: mysql

This is a default DigitalOcean installation.

**Comment by kevinansfield** [comment]
Hey @andreygrehov 👋 This is a theming issue rather than a bug in Ghost, the behaviour between the preview and the fully rendered post will always be different because the rendered version behaviour is determined via your theme.

You will need to adjust the styles in your theme to work for your use case. If you need any help pop over to our [Slack channel](https://slack.ghost.org). I'm closing this as there's no bug and we don't offer support via Github.

**Comment by andreygrehov** [comment]
@kevinansfield gotcha. Makes sense. Thank you. I haven't made any changes to the default installation. That said, is **casper** a default Ghost theme or it's simply the way DigitalOcean pre-packed Ghost for its customers?

**Comment by kevinansfield** [comment]
@andreygrehov [Casper](https://github.com/TryGhost/Casper) is the default theme
