### ISSUE TITLE
No field is visible for inserting the header code

### ISSUE THREAD

**Issue by NOCELL** [TryGhost/Ghost#9395]
### No field is visible for inserting the header code

When I open the panel, I can not insert the code in the header field
![fve4upnrncg](https://user-images.githubusercontent.com/22259080/34909751-bb5884ec-f8d9-11e7-8bc5-79bae19e3bb9.jpg)

### Steps to Reproduce

1. Open Ghost admin's menu
2. Click on "Code Injection"
3. Click no first field

### Technical details:

Ghost 1.4.2
NodeJS 6.12.3
Google Chrome 59, Ubuntu 16 
MySQL  Ver 14.14 Distrib 5.7.20, for Linux (x86_64)

**Comment by kevinansfield** [comment]
Hi @NOCELL 👋 Sorry to hear you're having trouble. Could you upgrade to the latest Ghost version and re-test? You say you're using v1.4.2, latest is v.1.20.0.

This also sounds like an environment issue, I can see that you have JS errors in the Console tab which will probably indicate that the CodeMirror scripts weren't able to load (later Ghost versions have a fallback for this case too). I'm going to close this issue because we use GitHub solely for bug tracking and on-going feature development, if you need support please use our [Slack channel](https://slack.ghost.org), if it becomes apparent through community support that this is a bug in Ghost it can be re-opened.
