### ISSUE TITLE
Syntax error blocking initial setup after fresh install

### ISSUE THREAD

**Issue by pablotrinidad** [TryGhost/Ghost#9396]
### Issue Summary

After a fresh install following the [production guide](/var/www/ghost/versions/1.20.0), the `/ghost` or `/admin` URL hangs on the loading spinner.
![spinner](https://user-images.githubusercontent.com/5308050/34910598-3ae15092-f87e-11e7-9880-e9994f12e08a.png)

Console prompts that 2 *syntax errors* occurred on the `vendor.min` and `ghost.min`, apparently its missing some semicolons 🤔
![syntax-errors](https://user-images.githubusercontent.com/5308050/34910613-8165e5c8-f87e-11e7-9838-225e068f8849.png)

### Steps to Reproduce

I followed the production installation guide, I haven't changed any specific configuration.

### Technical details:

* Ghost Version: **1.20.0**
* Node Version: **v8.9.4**
* Browser/OS: **Mozila Firefox**
* Database: **MySQL**

**Comment by acburdine** [comment]
@pablotrinidad See the docs [here](https://docs.ghost.org/v1/docs/troubleshooting#section-ghost-admin-not-loading) -> if you're using Cloudflare this is most likely the issue.

Going to close because it's most likely related to Cloudflare. However, if it turns out not to be the issue, then we can reopen this.

**Comment by pablotrinidad** [comment]
That was it, thank you so much! and sorry for not being able to find it by myself
