### ISSUE TITLE
“Post settings” pane shows wrong value in Post URL if isDatedPermalinks is enabled

### ISSUE THREAD

**Issue by chris-morgan** [TryGhost/Ghost#9439]
### Issue Summary

The URL preview shown in the post settings pane does not take isDatedPermalinks into account, producing an incorrect URL if it is enabled.

### Steps to Reproduce

1. Enable isDatedPermalinks in the site settings.
2. Go to a post in the admin, any post.
3. Open the post settings sidebar.
4. Observe the URL shown below the Post URL text box (selector: `.settings-menu .ghost-url-preview`), and how it shows something like `localhost:2368/welcome/` instead of `localhost:2368/2018/02/02/welcome/`.

### Technical details:

* Ghost Version: 1.20.3

This is because [the gh-post-settings-menu component is only passing the slug to gh-url-preview]( https://github.com/TryGhost/Ghost-Admin/blob/ac16e6504c443b428b90e7f7491e99e071addfe3/app/templates/components/gh-post-settings-menu.hbs#L44); something more complex will need to be done to make it correct.

**Comment by kevinansfield** [comment]
This is by design. There's a limited amount of space available for the preview and it's intended to show the relationship between the "slug" input and the URL, not as a direct indication of what the final URL will be because that can be affected by a number of variables.

If the full permalink url is shown then for many sites they will only ever see the permalink section, eg: `my-long-domain-name.co.uk/2018/02/12/start-...`

There are a number of big changes coming to how sites can be structured that will have an affect on the URL, we'll be reviewing all URL previews as part of that work.
