### ISSUE TITLE
knex-migrator init gets error "is not a function"

### ISSUE THREAD

**Issue by camilla-m** [TryGhost/Ghost#9456]
Hello everybody :)

I'm setting knex to run with Ghost and when I run _knex-migrator init_ command I get this error:

> $ knex-migrator init                                                            
> [2018-02-14 23:04:40] INFO Creating table: posts
> [2018-02-14 23:04:40] INFO Creating table: users
> [2018-02-14 23:04:40] INFO Creating table: roles
> [2018-02-14 23:04:40] INFO Creating table: roles_users
> [2018-02-14 23:04:40] INFO Creating table: permissions
> [2018-02-14 23:04:40] INFO Creating table: permissions_users
> [2018-02-14 23:04:40] INFO Creating table: permissions_roles
> [2018-02-14 23:04:40] INFO Creating table: permissions_apps
> [2018-02-14 23:04:40] INFO Creating table: settings
> [2018-02-14 23:04:40] INFO Creating table: tags
> [2018-02-14 23:04:40] INFO Creating table: posts_tags
> [2018-02-14 23:04:40] INFO Creating table: apps
> [2018-02-14 23:04:40] INFO Creating table: app_settings
> [2018-02-14 23:04:41] INFO Creating table: app_fields
> [2018-02-14 23:04:41] INFO Creating table: clients
> [2018-02-14 23:04:41] INFO Creating table: client_trusted_domains
> [2018-02-14 23:04:41] INFO Creating table: accesstokens
> [2018-02-14 23:04:41] INFO Creating table: refreshtokens
> [2018-02-14 23:04:41] INFO Creating table: subscribers
> [2018-02-14 23:04:41] INFO Creating table: invites
> [2018-02-14 23:04:41] INFO Creating table: brute
> [2018-02-14 23:04:41] INFO Creating table: webhooks
> [2018-02-14 23:04:41] INFO Model: Post
> [2018-02-14 23:04:42] ERROR
> 
> **NAME: MigrationScriptError
> MESSAGE: this.builder.queryContext is not a function**

Even if I update ghost for the latest version it's still happening. What can I do? :(

**Comment by kirrg001** [comment]
Hi @camilla-m!

We're sorry to hear you're having problems, but please do not use our GitHub repo for help. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). Furthermore please do not ignore our [issue template](https://github.com/TryGhost/Ghost/blob/master/.github/ISSUE_TEMPLATE.md).

Please swing by our [slack](https://slack.ghost.org/) community - https://slack.ghost.org. 

We can always re-open this issue in the [target repository](https://github.com/TryGhost/knex-migrator) if it turns out it's a bug.
