### ISSUE TITLE
Scheduled email notifications 

### ISSUE THREAD

**Issue by turalus** [TryGhost/Ghost#9461]
I know that it's a bit offtopic but, I was waiting long time for scheduled email notifications using subscribers list. 

Is there any roadmap about when it will be released or any workaround about sending emails to subscribers?

**Comment by acburdine** [comment]
@turalus as detailed [here](https://blog.ghost.org/zapier-x-ghost/) there is now a Zapier integration within Ghost itself, that you can use to do two things:

- Send new subscribers to some sort of mailing list (e.g. Mailchimp)
- Notify said mailing list (e.g. Mailchimp) when a new post is published.

Using those two things, you can easily set up auto subscription notifications.

Going to close this as we use Github issues for bugs and ongoing work, not for feature requests. Please drop by our [slack channel](https://slack.ghost.org) if you have any further questions. Thanks!

**Comment by rawsh** [comment]
@turalus #6913

**Comment by rawsh** [comment]
@acburdine zapier is a paid product. If I wanted to use a paid product I would use mailgun. I don't. 

I want to use the __server I'm paying for already__ to send emails out.

**Comment by cotko** [comment]
Just to sum up my experience if anybody finds himself in this place in the future as well:

I came across quite a few similar comments like acburdine's above *just use mailchimp/mailgun zaps to easily set this up*, so I thought this won't take long.

I tried using **mailchimp**, [there is also an excellent guide with screen shots](https://medium.com/@angel_71919/integrating-ghost-with-mailchimp-ca9410655eee) the only problem is that if you follow this guide, you'll end up with *draft* campaigns where you'd need to login to mailchimp up to 15min after a new blog post (that much time is needed for the zappier to pick up the new post) and then manually activate the campaign so that subscribers get the emails. The reason is that the guide tells you to select the *create campaign* mailchimp action.

- I then tried to use other action, *send campaign*. This one requires you to already have a campaign for a new blog post, which you don't. So there is an option to choose additional *create campaign* step before this one. Everything works ok and can be set up, right to the end, where I tried to activate the zap and was notified by zappier that zaps with 3+ steps require a paid account. I'll only have a small blog with probably a few subscribers and am already paying for the domain and hosting so additional costs are not welcome.
- After that I tried to add additional zap besides the one which just created the campaign, which would include *mailchimp + mailchimp* where first one picks up new cmpaigns and second activates them. It seemed possible, but I could not figure out how to pick up draft campaigns, no matter what I tried to do, so this also turned out to not be an option.

With mailchimp out of the picture, I tried **mailgun**. After setting everything up and verifying the domain, it turned out that a paid plan is needed, only sandbox apis can be used for free. So this was also a waste of time.

Looking for the email related zaps, I then found the **mailjet** and it seemed like it'd be possible to use that one. The setup was practically the same as for the mailchimp and suprisingly everything actually did work, with a free account (having up to 200 mails per day / 6000 per month, which should be fine for my needs).

**Comment by kevinansfield** [comment]
Mailchimp also has an [rss to email](https://mailchimp.com/features/rss-to-email/) feature which may be preferable in certain situations. Ghost<->Zapier<->Mailchimp can be used to synchronise list members with MailChimp set up to send e-mails when you publish posts.

**Comment by rawsh** [comment]
@cotko mailgun is paid but the way it works is that you don't pay if you stay below a certain number of emails sent and even then it's just a few cents. Are you sending 10000 emails?

**Comment by joeldeteves** [comment]
Actually @rawsh Zapier offers a "free" version that is good for up to 5 Zaps. I didn't know about it either but it's actually hidden under their pricing section under "more plans":

![image](https://user-images.githubusercontent.com/33190570/38552268-7c2e0dac-3c70-11e8-9bc2-cda27da233c0.png)

I tested it with mailchimp and it works great, which is good because I prefer to use my existing lists.

**Comment by rawsh** [comment]
@joeldeteves true, but there is no in between for that and the 20$ a month plan. If you use zaps to both subscribe people and send rss you can go over a 100 easily and you'll have to spend that 20$ each month for something that should be built into ghost

**Comment by rawsh** [comment]
I agree, I think an official app for ghost that integrated Amazon Mail service, Mailgun and Mailchimp would be great.

**Comment by jerry-git** [comment]
This is a rather old issue but for those who are battling with zapier + mailchimp, it's possible to create a zap (with a free plan) that creates a campaign and then sends it. Workflow is basically: 1) New Story trigger (Ghost) 2) Create Campaign action (Mailchimp) 3) Send Campaign action (Mailchimp). Here's [how to do the step 3](https://zapier.com/help/mailchimp/#how-to-create-and-send-a-campaign) which is missing from this otherwise complete [step-by-step guide](https://medium.com/@angeldominguez/integrating-ghost-with-mailchimp-ca9410655eee).

**Comment by rawsh** [comment]
@jerry-git thanks for the info jerry. 

[What I'm using now for anyone interested (mailgun free account + custom webhook + custom subscribe page template)](https://github.com/devpytech/devpygrunt)
