### ISSUE TITLE
Make page in metatitle translatable?

### ISSUE THREAD

**Issue by mantebridts** [TryGhost/Ghost#9466]
When using pagination on the blog index, the title in the browser show the current page you're on. This is great, but it is not translatable (to dutch, in my case). 

I don't know how, but it has something to do with the "common.i18n.t" function I guess? Am I right?
 Can someone help me explain the use of it and how I can make this string translatable?

It's about this line: https://github.com/TryGhost/Ghost/blob/415ff2cf2040a04e4ac8c01eac553c0b1a9b2523/core/server/data/meta/title.js#L15

Kind regards, Mante

**Comment by kirrg001** [comment]
Hey @mantebridts 👋

There is an open pull request for this missing string, [see](https://github.com/TryGhost/Ghost/pull/9385). The PR was already reviewed, but the contributor never came back. Any helper is very welcome.

**Comment by juan-g** [comment]
Something similar to `{{plural}}` and `{{reading_time}}` helpers -with explicit default texts- could be
``` 
<title>{{meta_title page=(t "Page %")}}</title>
```
instead of
``` 
<title>{{meta_title}}</title>
```
in the theme's _default.hbs_ template, with a string placeholder in _core/server/data/meta/title.js_ and replacement logic in _core/server/helpers/meta_title.js_ .

That's just a possible idea for anyone willing to work on this, since for example I'm always in a hurry these months. :wink:

**Comment by mantebridts** [comment]
Allright, I think I get it. I will try to make a fix! :)

**Comment by mantebridts** [comment]
I think I made a PR that should do the trick. It works here, I follow the instructions and ran the tests... 😊
I hope I did everything right, first-time-contributer here, just tell me when I did something wrong. 😅

https://github.com/TryGhost/Ghost/pull/9468

**Comment by heyakyra** [comment]
Is there no way to do this for navigation labels & site data currently? #11444
