### ISSUE TITLE
Installation is fine, but do not run after stopping

### ISSUE THREAD

**Issue by CordlessWool** [TryGhost/Ghost#9479]
### Issue Summary

I try to use ghost-cli on ubuntu. After installation it runs fine but after I want to start it later or stop and start it again it runs in an error. It says that my home directory is not readable for every user. Ok could be but it runs fine after installation, so why is it not run able later?

### Steps to Reproduce

1. Install in home directory
2. stop and start server after installation

Could be shown a warning, but should start.

### Technical details:

* Ghost Version: 1.21.3
* Node Version: 8.9.4

**Comment by AileenCGN** [comment]
Hi @CordlessWool 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

If it turns out to be an issue indeed, please use the [Ghost CLI](https://github.com/TryGhost/Ghost-CLI/issues) repo to submit an issue with as much information as possible (log files etc.).
