### ISSUE TITLE
Ghost is auto-linking something that's not a link.

### ISSUE THREAD

**Issue by queued37** [TryGhost/Ghost#9481]
### Issue Summary

Ghost is auto-linking something that's not a link. It is supposed to be resolved by #9084 as a fix of #8987, but some strange behavior still remains.

### Steps to Reproduce

Ghost is still auto-linking something that doesn't contain a protocol. For example, when I write Sublime Text binary's path `"/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"`, the `Text.app/Contents/SharedSupport/bin/subl` part is automatically converted to a link. This is quite unexpected behavior. It can probably be a bug of linkify-it, but I'm not sure.

### Technical details:

* Ghost Version: v1.21.3
* Node Version: v6.12.3
* Browser/OS: Chrome/Ubuntu
* Database: MySQL

**Comment by kevinansfield** [comment]
Hey @queued37 👋 I'm not able to reproduce this. I can see in the markdown editor that the `Text.app/Contents/SharedSupport/bin/subl` text does get highlighted differently (this is CodeMirror's markdown syntax highlighting rather than anything to do with our markdown parser) but in both the side-by-side preview and the actual published post there's no link.

**Comment by queued37** [comment]
Thanks for your reply! After some investigation I realized my blog theme was using some javascript auto-linking library. I'm closing this issue.
