### ISSUE TITLE
Failed to send email. Reason: getaddrinfo EAI_AGAIN smtp.mailgun.org:587

### ISSUE THREAD

**Issue by CordlessWool** [TryGhost/Ghost#9492]
### Issue Summary

I set up ghost via docker container and proxy request via nginx. To sending email I try to configure ghost via environment varibles 

--env mail__transport=SMTP \
--env mail__options__service=Mailgun \
--env mail__options__auth__user=postmaster@mg.domain.tld \
--env mail__options__auth__pass=password \

like explained in the wiki. Mailgun is running on own domain and tested via curl and api request. 
If I try to send me a mail, via test mail or forgot password I get the error message "Failed to send email. Reason: getaddrinfo EAI_AGAIN smtp.mailgun.org:587"

### Steps to Reproduce

1. Setup docker container (with --env) alpine or normal, makes no different 
2. Click forgot on start screen to test email sending

### Technical details:

* Ghost Version: 1.21.3
* Node Version:  ---
* Browser/OS: docker alpine/ docker debian
* Database: sqlite

**Comment by AileenCGN** [comment]
Hi @CordlessWool 

We're sorry to hear you're having problems, but ask that you do not use our GitHub repo for support. Please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [slack](https://slack.ghost.org/) community - https://slack.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

If it turns out to be an issue with Ghost, we can always reopen this issue.

**Comment by CordlessWool** [comment]
Hi, 

this should not be a support request. For me this is an issue, but if you don't want to get feedback and reporting issues... it's ok, so do not have to waste my time...

**Comment by jwillmer** [comment]
@aileen this is the first search result you get for this issue. Maybe it would be good to add some helpful links or even the fix?
