### ISSUE TITLE
ol.posts-list p not updating

### ISSUE THREAD

**Issue by CriticalRespawn** [TryGhost/Ghost#9512]
I've discovered an issue where the post excerpt that shows on the "Your Stories" page in the Ghost Admin does not update in certain circumstances. The steps below should allow you to replicate it. 

1. Login to Ghost Admin and create a new post. Set the post content to **1234**. What you set it to doesn't matter, but this is easier to keep track.
2. Publish the post and then un-publish it straight away.
3. Visit "Your Stories", you should see your new post with **1234*** in `<p></p>` underneath the title.
4. Go back into the post, edit the post content to **12345**.
5. Publish the post and then un-publish the it straight away.
6. Visit "Your Stories", you should still see **1234**.
7. Click into the post, the post body should be **12345**, which is correct because you previously set it to this.

So it looks like the post excerpt saves initially, but if you set the post to a draft, it no longer updates. If you then Publish the post, it doesn't update.

**Comment by kevinansfield** [comment]
@kirrg001 I think that this is a server-side issue - Ghost-Admin sends a `plaintext` value when saving the post but it contains the last value the server provided because it doesn't update it automatically (it's supposed to be generated server-side), Ghost is then taking the value provided via the API and saving it to the database instead of re-generating it from the `mobiledoc` field.

**Comment by kevinansfield** [comment]
Currently Ghost-Admin avoids sending the `html` value for the same reason. I can add `plaintext` to the attributes that get stripped out when saving in Ghost-Admin but we probably want to add protection at the API level to ensure attributes for auto-generated fields don't get persisted.
