### ISSUE TITLE
Improve usability of unsaved changes dialog

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/Ghost#9514]
### Issue Summary

There are cases when the Ghost editor can get to an unsaved state (see 'Steps to reproduce'). These cases are handled with a popup dialog asking the user if they want to leave the editor without saving the changes. It also asks the user to save the changes but there are no instructions for it:

<img width="669" alt="screen shot 2018-03-19 at 14 46 21" src="https://user-images.githubusercontent.com/353959/37600454-a7d5a306-2b87-11e8-860d-7e0fb81d9dc5.png">

### Steps to Reproduce

1. Create a new post
2. Add or remove tags for the post - don't make any changes in the post body, otherwise the system automatically saves.
3. Click on e.g. 'Stories' (or any other link) in the navigation sidebar

While it's possible to save the post by hitting CMD+S or Ctrl+S, it's not communicated properly.

**Comment by peterzimon** [comment]
### Design
The following use cases are treated differently:

1. Post state: draft
If the post is in 'draft' state then everything should be auto-saved. Tag changes (added, removed tags) should be saved on close of the Post Settings Menu (sidebar)

2. Post state: published
If the post is published the following dialog should appear if there are unpublished changes in the post (or its settings) and the user wants to navigate away from the editor:

![post - published](https://user-images.githubusercontent.com/353959/37643104-c3134dd8-2c1f-11e8-8cd3-78d884c637ec.png)

3. Post state: scheduled
When the post is scheduled to be published then a slightly different version of the previous popup should appear (on the same user action):

![post - scheduled](https://user-images.githubusercontent.com/353959/37643168-fa73e60c-2c1f-11e8-86a0-df26834ea30e.png)

**Comment by kevinansfield** [comment]
Not stale

**Comment by MrMovl** [comment]
We are testing ghost internally right now, and some of our team are very unsure about the way documents are saved. Having an autosave hint on the top confuses people, because it is argued that changes aren't really saved, when one leaves the editor and clicks `Leave`.

> While it's possible to save the post by hitting CMD+S or Ctrl+S, it's not communicated properly.

And I agree with this. Honestly, the easiest solution (and the one preferred by my team) seems to be an (optional) `Save` button in the top, left corner. Though I do like @peterzimon design idea and see it as an improvement, it might only be part of the solution.

**Comment by kevinansfield** [comment]
Not stale
