### ISSUE TITLE
'config.example.js': No such file or directory

### ISSUE THREAD

**Issue by IcyW** [TryGhost/Ghost#9535]
After cloning the Ghost from github, I found 'config.example.js' missing.
Actually it was there just few minutes ago when I tried to install Ghost the first time.

### Technical details:
* Ghost Version: The lastest
* Node Version: v6.13.1
* Browser/OS: Ubuntu 16.04

**Comment by kevinansfield** [comment]
Hey @IcyW 👋  `config.example.js` has not existed since Ghost 1.0. If you need help with an installation please first read the [docs](https://docs.ghost.org/docs/getting-started-guide) and if you're still having issues please swing by our [Slack channel](https://slack.ghost.org) which is where you can get community support - we use GitHub solely for bug tracking and on-going feature work, any install/help/support requests will be closed.

**Comment by IcyW** [comment]
@kevinansfield Thank you for your responding!
