### ISSUE TITLE
Improve performance when importing a huge CSV of subscribers

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9544]
### Issue Summary

When importing a very large number of subscribers, the server does not respond anymore. Feels like it's freezing. I've tested a CSV file with 27k subscribers.

Subscribers is a beta feature and we never did any performance testing.
We are happy about any help.

### Steps to Reproduce

1. Generate a huge CSV with email addresses
2. Import the CSV in the subscribers page

### Technical details:

* Ghost Version: 1.22
* Node Version: any
* Browser/OS: any
* Database: any

**Comment by vivekannan** [comment]
Hey, can I get a link to the CSV? I tried generating one, but boy is it hard. :|

**Comment by vivekannan** [comment]
So essentially, the parsing completes pretty quickly and asynchronous as one would expect it to. However, the processing of the rows is [completely synchronous](https://github.com/TryGhost/Ghost/blob/master/core/server/lib/fs/read-csv.js#L22) and can run for very long time for large imports and will lock the entire event loop. 

Best way to deal with such imports is to move the row processing logic inside the `data` event listener it self so that everything happens  asynchronously.

Shall I make a PR?

**Comment by kirrg001** [comment]
@vivekannan Thanks for investigating 👍 

> As Promise.all is used

Yeah this is possible. We experienced something similar with [our importer](https://github.com/TryGhost/Ghost/commit/29e143fa9a56ae0c178288ea1c4923079673dc0b#diff-f41262b74e0c309d6ef623f67e2dd79e).

>  guess the ideal way to handle this would be with chunked bulk inserts.

Yeah, but currently Bookshelf does not support bulk inserts.

---

The first goal here should be:
- if the import of a huge amount of subscribers takes long, that is acceptable
- if the import of a huge amount of subscribers breaks or freezes Ghost, that is not acceptable

Next step:
- speed up import of subscribers

**Comment by kirrg001** [comment]
`Promise.reduce` is fine in general, because it runs sequentially, but you are not making use of `total` in your example. So i am not sure why you are using reduce at all? 🤔 

I think if you import 50k subscribers and each subscriber get's inserted sequentially, you will run into a browser/webserver timeout, which is not really nice, but maybe unavoidable if you import such a large set of data.

Short term fix could be:
- use `Promise.map` and configure the concurrency option

Long Term:
- run large database executions in background and return a finished state (polling)

**Comment by sharathm** [comment]
@kirrg001 

> but you are not making use of total in your example. So i am not sure why you are using reduce at all?
The total is un-used. I agree, was just trying it out. 
The reason I used reduce was so that I could inspect each promise and track the fulfillments and rejections, instead of doing it once all promises are completed with `Promise.all[]`.

> I think if you import 50k subscribers and each subscriber get's inserted sequentially, you will run into a browser/webserver timeout, which is not really nice, but maybe unavoidable if you import such a large set of data.

For something like a uploader, would it be better to break the process up into two steps.
1. Let the files process, and return a list of valid / duplicate and rejected entries. This can be shown in a popup perhaps?
2. Then once the user hits `Confirm`, we can use a single Bookshefl/knex transaction to insert the subscribers to the database.  The other advantage this gives is that since we are using knex, a single connection would be used for all inserts, this keeping overall performance good.

**Comment by kirrg001** [comment]
> Then once the user hits Confirm, we can use a single Bookshefl/knex transaction to insert the subscribers to the database. The other advantage this gives is that since we are using a transaction, a single connection would be used for all inserts, thus keeping overall performance good.

I agree, the subscriber queries can run in a single transaction, but that won't solve the performance problem described in this issue? The problem is that we run all the queries in parallel - memory grows fast and the application will crash at some point, because node doesn't release memory, because of I/O interactions.

**Comment by kirrg001** [comment]
As the [upcoming members feature](https://github.com/TryGhost/Ghost/issues/10213) will and should replace subscribers, i think there is no longer the need to fix this bug. If you encounter this problem, i'd suggest to import many smaller CSV files.
