### ISSUE TITLE
Trailing slashes on post URLs breaks anchor links

### ISSUE THREAD

**Issue by benwoodward** [TryGhost/Ghost#9556]
Example:

Adding trailing slashes breaks anchor links:

`<a href="#example">Example headline</a>` => `ghostblog.com/post-url/#example` (should be: `ghostblog.com/post-url#example`)

This means that all the links generated by a table-of-contents generator like https://github.com/SixArm/markdown-toc-generator will not work.

**Comment by kevinansfield** [comment]
Hey @benwoodward 👋 Could you explain a bit more how is this an issue?

https://ghostblog.com/post-url/#example is a perfectly valid anchor link and is the _expected_ anchor link for a URL with a trailing slash. If it didn't have the trailing slash then it would be linking to a completely different URL and won't be expected to work.

Anchor links in the content specified as `<a href="#example">example</a>` on a URL such as https://ghostblog.com/post-url/ will automatically resolve to https://ghostblog.com/post-url/#example in the browser because it's a relative URL.

Closing for now as the current behaviour is valid and shouldn't be breaking anything unless you have a tool that is generating invalid absolute links.

**Comment by SupremeTechnopriest** [comment]
I think the issue here is that `https://example.com/page/#anchor` does not scroll to the element whereas `https://example.com/page#anchor` will.  I'm running into the same issue. It resolves to the correct page, but does not bring scroll to the content on the page.
