### ISSUE TITLE
The casper theme looks ugly for Chinese charaters.

### ISSUE THREAD

**Issue by jaggerwang** [TryGhost/Ghost#9577]
### Issue Summary

**The serif font for Chinese character looks not well, and it is too big. It will look much better if using sans-serif font.**

![image](https://user-images.githubusercontent.com/1255011/38850728-3e597162-4245-11e8-9252-2cb157398793.png)

**Image is wider than the content. Is this for purposes?**

![image](https://user-images.githubusercontent.com/1255011/38850736-48e8805a-4245-11e8-8ac5-051dc7cbbad3.png)

**Code block is not full width with the content. I'm using `Prism.js` to format code. Is this for purposes too?**

![image](https://user-images.githubusercontent.com/1255011/38850745-53828df8-4245-11e8-84fb-3f7dffde7285.png)

### Steps to Reproduce

1. View my blog [post](https://blog.jaggerwang.net/vs-code-develop-debug-python-program/) to see the effect.

### Technical details:

* Ghost Version: 1.21
* Node Version: 9.0
* Browser/OS: Chrome
* Database: SQLite

**Comment by kevinansfield** [comment]
Hi @jaggerwang 👋 Ghost's default theme [Casper](https://github.com/tryghost/ghost) is optimised for latin based languages so this isn't considered a bug. Themes are designed to be edited to match your requirements rather than being perfect for every requirement out of the box.

We have [extensive documentation](https://themes.ghost.org) for modifying themes to your liking as well as a [marketplace](https://marketplace.ghost.org) of other themes that may be a better starting point. If you need any help modifying your theme please head over to [our forum](https://forum.ghost.org) where you can get community support 😄
