### ISSUE TITLE
Transferring ownership doesn't change the owner ID

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9583]
According to https://github.com/TryGhost/Ghost/issues/9299, the owner should always be User ID 1. As I understand it, several parts of the code depend on this - not just on initial setup, but also in the importer.

However, if you transfer ownership of your blog, the old owner is ID 1, and the new owner keeps their Object Id.

### Steps to Reproduce

1. Create a blog with an additional admin user
2. Look at the ids, see the owner is 1, and the admin has an Object ID
3. Transfer ownership to the admin
4. Check the ids again, the old owner is still ID 1.

I have no idea if this has ramifications, but it matters in the context of https://github.com/TryGhost/Ghost/issues/9299 and [placeholder].

### Technical details:

* Ghost Version: 1.22.2
* Node Version: 8
* Database: Sqlite3 / MySQL

**Comment by kirrg001** [comment]
Confirmed. This is a bug. I can't really tell if it can cause ramifications without looking/testing deeper.

This is what i will do on Monday the 23rd of March:
- ensure the code base won't rely on the owner ID being 1 (relates to https://github.com/TryGhost/Ghost/issues/9299#issuecomment-379001882)
- then we can close this issue, because we can rely on the owner role 100%
- then we should probably migrate the owner user to ensure consistency
