### ISSUE TITLE
Ghost editor

### ISSUE THREAD

**Issue by huydh** [TryGhost/Ghost#9615]
Hi everyone,

The Ghost editor is so great. Its writer experience is just unmatched. Since it's open source, I'm just wondering if it is appropriate to extract the code for use in different purpose (general editing, code editing)? If yes, how can I locate the part needed to recreate that editor?

Glad if anyone could shed some light. I'm new to Ember.

Thanks,
Huy

**Comment by rkalis** [comment]
Hi @huydh,

If you mean the markdown editor, Ghost uses [simplemde](https://simplemde.com/), an open source markdown editor for javascript applications. You can embed it in any of your own projects, or edit it for other functionality since it is open source

**Comment by kevinansfield** [comment]
Hey @huydh, @rkalis 👋 This discussion is much better suited for our [forum](https://forum.ghost.org). I'm going to close this because we use Github solely for bug reports and on-going feature development, if you want to continue the discussion please open a new topic on the [forum](https://forum.ghost.org) 😄
