### ISSUE TITLE
ALT-C, ALT-L, ALT-E problems 

### ISSUE THREAD

**Issue by byisk** [TryGhost/Ghost#9618]
Hi,

yosz [made an issue](https://github.com/TryGhost/Ghost/issues/1529) in 2013. It was closed but not fixed.

We use ALT key in Polish for characters such as ć, ą, ź etc.

Ghost's shortcuts are pain in the ass for Polish Ghost's users:

- Alt-C puts code block instead of 'ć' character 
- Alt-L creates a numbered list instead of 'ł' character
- ALT-E switches to team members management instead of 'ę' character.
- ALT-S turns on the spellcheck instead of 'ś' character.

Do you plan to fix this? There could be a simple switch to turn off these shortcuts, for example.

**Comment by conwid** [comment]
Not just for Polish users, I'm guessing every Eastern-European language user/keyboard layout user has the same problem. For my Hungarian layout, ALT-C would be &, but obviously I cannot use it for the same reason and it is a pain for me to.
But I also like the shortcuts :) So in the long run, I'd say I wouldn't want to disable ALT-C (especially since for me ALT+38 gives the exact same character), but rather configure it to be something else.

**Comment by kevinansfield** [comment]
> Alt-C puts code block instead of 'ć' character
> Alt-L creates a numbered list instead of 'ł' character

These are an [upstream issue](https://github.com/sparksuite/simplemde-markdown-editor/issues/616) as described in the [related+closed issue here](https://github.com/TryGhost/Ghost/issues/8687).

With the [new editor](https://github.com/TryGhost/Ghost/issues/9311) that's in development they will no longer be an issue unless you're using the markdown card.

> ALT-S turns on the spellcheck instead of 'ś' character.

Similarly this will be fixed with the new editor unless you're using the markdown card.

> ALT-E switches to team members management instead of 'ę' character.

Unfortunately this stems from the keyboard manager we currently use. There's an [upstream issue](https://github.com/madrobby/keymaster/issues/158) to add support but it hasn't had any traction.

Most of these issues will be resolved with the new editor or will require a large overhaul of our shortcut handling, as such I'm going to close this for now. As always we're open to PRs that address this issue.

**Comment by mordka** [comment]
@kevinansfield  Would you accept a PR switching all the shortcuts off via toggle button?

**Comment by kevinansfield** [comment]
@mordka the issue needs to be fixed in CodeMirror, all of the markdown related shortcuts are registered in SimpleMDE using CodeMirror's `extraKeys` [keyMap config](http://codemirror.net/doc/manual.html#keymaps).

> ALT-E switches to team members management instead of 'ę' character 

Looking at this again I don't know where this is coming from, we don't have any shortcuts registered to switch to the team screen.
