### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by akashnimare** [TryGhost/Ghost#9638]
### Technical details:

* Ghost Version: 1.22.8
* Ghost-cli: 1.7.3
* npm: 5.6.0
* python: 2.7.12
* Node Version: 8.9.4
* Browser/OS: Ubuntu 16.04 EC2 AWS

I'm trying to setup a blog on my ec2 instance using [this](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ghost-on-ubuntu-16-04) tutorial.

Error logs -
<details>
✔ Setting up Systemd
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.9.4
    Ghost-CLI Version: 1.7.3
    Environment: production
    Command: 'ghost install'

Additional log info available in: /home/user/.ghost/logs/ghost-cli-debug-2018-05-15T20_26_18_686Z.log
</details>

I have tried removing, reinstalling everything (node, python, ghost, mysql etc) nothing seems to work 😞 
(everything works as expected if I use the docker method)

**Comment by AileenCGN** [comment]
Hey @akashnimare  👋 

We ask that you please do not use GitHub for help or support, the default issue template pointed you to our [forum](https://forum.ghost.org) for this type of question 😄 We use GitHub solely for bug-tracking and on-going feature development so we try to keep it noise free.

Many questions can be answered by reviewing our docs for [self-hosters](https://docs.ghost.org), our [theme API](https://themes.ghost.org), or our [public API](https://api.ghost.org). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

If this turns out to be a bug indeed, please open and issue on the correct [Ghost-CLI ](https://github.com/TryGhost/Ghost-CLI) repository, providing all information you'll be asked for.

FYI: Many projects have their own support guidelines and GitHub will highlight them for you, or the project owners will use issue templates to point you in the right direction, please read them before opening issues

**Comment by akashnimare** [comment]
Oh, damn! I was in a rush, reopen the same there.
