### ISSUE TITLE
Message: System stack checks failed with message: 'Linux version is not Ubuntu 16'

### ISSUE THREAD

**Issue by acodercat** [TryGhost/Ghost#9639]
I want use centos 7.4
Message: System stack checks failed with message: 'Linux version is not Ubuntu 16'

### Issue Summary

Message: System stack checks failed with message: 'Linux version is not Ubuntu 16'

### Technical details:

* Ghost Version:  1.7.3
* Node Version: v6.9.5
* Browser/OS:
* Database:

**Comment by AileenCGN** [comment]
Hi @acodercat 

We're sorry to hear you're having problems, however this looks like a problem with how you're using Ghost rather than a bug. We only keep Github issues open for bugs and in-progress feature work, please read our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). You can always use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org.

**Comment by allamiro** [comment]
is there a plan to support CentOS ?
