### ISSUE TITLE
Email subscription with double-opt-in

### ISSUE THREAD

**Issue by johndoe75** [TryGhost/Ghost#9642]
According the new GDPR regulation in Europe, it's strictly required by law, that all users subscribing to an email list, require to double-opt-in per notification mail.  I did not find a chance to enable double opt in with Ghost, so for now, I have disabled email subscription.  But I'd like to re-enable this soon to stay in contact with my readers.

Is it planned to enable double opt in for email subscriptions?

**Comment by kevinansfield** [comment]
The entire feature is due to be re-imagined as part of the memberships & subscriptions work (https://forum.ghost.org/t/memberships-subscriptions/377). It's only ever been implemented as a partial beta feature so far (that's why you have to turn it on in labs) and is not designed to be a full subscription system but rather to be tied in with an existing mailing list provider via Zapier integrations.

If you use Zapier to sync your Ghost subscribers list with your mailing list (eg. via MailChimp) then you can enable double opt-in in there.
