### ISSUE TITLE
Problems creating new user

### ISSUE THREAD

**Issue by JoseCed** [TryGhost/Ghost#9648]
Hi, I made the installation of ghost through the apps in Digital ocean, reason why when I go to my terminal to run ghost setup it tells me that first I have to create a user, I'm going to the documentation to create a new user and I get to this one point

```mv /root/.ghost/config/home/<user>/.ghost/config```

and here is the problem I can not move a file that does not exist.

The question is, should that file have been created by default or should I create it?

regards

**Comment by acburdine** [comment]
@JoseCed that documentation is a bit out of date - the DigitalOcean ghost app has since been updated, making some of those steps likely unnecessary.

Going to close this though as we don't use Github for help or support - please visit our [forum](https://forum.ghost.org) if you have any further issues 😄
