### ISSUE TITLE
Koeing editor filled with bugs to a level that made me quit using Ghost till fixed

### ISSUE THREAD

**Issue by ScarletWolf275** [TryGhost/Ghost#9679]
The Koeing editor seemed like a great tool which would improve writing but it has actually destroyed it all together for me. I write two sentences, try to edit the first, won't let me. Apparently, there's a bug which won't let you edit anything you've written without erasing to the point you want to fix. So what you write is a one-way ticket unless you are willing to rewrite all over again. Next, I try to add an image. Uploaded, ok, add a caption fine. Let's add another image. I click the image card, it inserts one, I upload an image and once it uploads, it creates ANOTHER new 3rd card. I delete the 3rd card and move on to add a caption for the 2nd card, let's say I'm captioning it Heroku, it doubles it... so it becomes HHeerrookkuu. Not only that, but it single-types it to the one above. So in 2nd it's now Hheerrookkuu and in the 1st, it adds it as if they're somehow connected so it's now Heroku. Everything is glitchy and bugged and unusable.

Images:
http://prntscr.com/jt1act
http://prntscr.com/jt1bq9
You can see that in the 2nd image caption, everything is doubled up, while it's typing the exact same thing (just not in doubles) for the 1st caption...

**Comment by ScarletWolf275** [comment]
Oh, and once you're in a story, either writing one or editing, you can't go back. You have to go to the admin homepage all over again by typing it...

**Comment by pascalandy** [comment]
The Ghost team put in place a format to report a bug which you decided to bypass. While you are right that Koeing editor is buggy, this not the way to report stuff. If you need to ventilate, I suggest Reddit instead of Github issues.

And to your points why not continue running 1.22.8 ?

**Comment by ScarletWolf275** [comment]
I'm sorry if this sounded rude. That last part of the title was just to explain the level of frustration, it wasn't me venting. And no, I have not been presented with that template selector. It just showed me the text area to write with no template in it. It was weird since I've made an issue here in the past

**Comment by kevinansfield** [comment]
Hey @ScarletWolf275 👋 All Koenig feedback should be reported to the [Koenig Beta forum topic](https://forum.ghost.org/t/koenig-editor-beta-release/1284). Please read the instructions there for how to report issues. Be sure to include the requested information such as DevTools console errors, browser version etc, otherwise it's impossible to do anything with the limited details you've provided in this issue.

> that made me quit using Ghost till fixed

No-one is forcing you to use the Koenig beta 😉 If it doesn't work for you, report the issues in the [forum topic](https://forum.ghost.org/t/koenig-editor-beta-release/1284) and disable the labs flag again.
