### ISSUE TITLE
`{{url}}` helper shows incorrect url when subdirectory equals post slug

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9687]
### Issue Summary

If you create a post called `/test/`. And you switch to a subdirectory called `/test/`. Then the post should live at `/test/test/`, but the `{{url}}` helper displays `/test/`. 

I am pretty sure it's caused by the deduplicate sub dir helper function, [see](https://github.com/TryGhost/Ghost/blob/1.24.3/core/server/services/url/utils.js#L57).

This bug must exist for a while (since we introduced this function).

### To Reproduce

1. Create post with slug "test" (without subdirectory)
2. Switch to subdirectory /test/
3. Serve your blog and see that the post url is /test/

### Solution

Write a test to proof this bug. Come up with an idea how to protect against this use case.

### Technical details:

* Ghost Version: latest

**Comment by tiendq** [comment]
What is this step really? Sorry, I'm still new to Ghost :)

> 2. Switch to subdirectory /test/

**Comment by kirrg001** [comment]
@tiendq https://docs.ghost.org/docs/config#section-subpath - url configuration in your config file.

**Comment by PranavRudra** [comment]
Hey! So I'm new to Ghost but I really want to help out with this issue. 

I was trying to reproduce the problematic behavior but I just can't figure out what you mean by slug. Is that another name for a post's tag or is it some other meta information that's included whenever you publish a post?

**Comment by kirrg001** [comment]
@PranavRudra The slug is the url of a post. If you create a post and open the PSM, you will see an input field on top, which reflects the post slug.

There is already an open [PR](https://github.com/TryGhost/Ghost/pull/9690) for this. But many thanks for your help!

**Comment by allouis** [comment]
@kirrg001 pull #9690 looks stale - I'm gonna pick this up :small_airplane:

**Comment by allouis** [comment]
From what I can tell, this issue will only occur if you create the slug, and _then_ switch your subdirectory to the same name. If you try to create a slug the same name as the current subdirectory then the api returns with `-post` appended. So that's good because it means this is fairly edge case.

As for a solution I propose a two step fix to the `deduplicateSubDir` function.

1. AFAIK slugs always appear at then _end_ of a url? in that case we should be able to make a regex that only deduplicates the subDir if it is in the middle of a url e.g. /subdir/subdir/thing and not /subdir/subdir. That will fix for this usecase, but still maintain the protection of someone using `joinUrl` with arguments such as `'http://host.tld/subdir', '/subdir/some-page'`

2. As slugs cannot contain a `/` character, if the `subDir` contains a `/` (it's >= two levels deep) then we deduplicate as usual and skip the previous logic

**Comment by allouis** [comment]
Thanks for the info @kirrg001 

> In theory you can define what you want as permalink structure e.g. /{slug}/{year}/.

This throws the whole approach off then :crab: :crab: 

Yeah you're right - refactoring code so we no longer need to call `deduplicateSubDir` is probably best!

We could maybe replace usages with it in createUrl etc...

from:
```js
url = deduplicateSubDir(url);
return url;
```

to:
```js
var dedupedUrl = deduplicateSubDir(url);
if (dedupedUrl !== url) {
  // warn about usage
}
return dedupedUrl;
```

Which should help give us an idea about how widespread the issue is, not sure how you feel about deprecation style warnings like that tho :shrimp:

**Comment by kirrg001** [comment]
Similar report: https://github.com/TryGhost/Ghost/issues/10309

**Comment by Ajphil** [comment]
What is the term slug that u have mentioned
