### ISSUE TITLE
maintenance.enabled doesn't seem to do anything

### ISSUE THREAD

**Issue by riverar** [TryGhost/Ghost#9728]
Ghost-CLI version: 1.8.1
Ghost Version (at /var/www/ghost): 1.24.6
Node: v6.14.3
Database client: mysql

1. `ghost config maintenance.enabled true`
2. Refresh blog, note nothing happened
3. `ghost restart`
4. Refresh blog, note nothing happened

Am I missing something here? Configuration docs indicate this key still exists. https://docs.ghost.org/docs/config

**Comment by kirrg001** [comment]
Hey!

Good catch. The maintenance variable is configured in our [overrides file](https://github.com/TryGhost/Ghost/blob/1.24.8/core/server/config/overrides.json#L61), it always falls back to false. Funny, it's there for exactly 2 years now 😜It should be configured in `defaults.json`. 

Fix is welcome 🙏🏽

**Comment by ErisDS** [comment]
> The maintenance variable is configured in our overrides file

Isn't this because the feature was deprecated?

**Comment by kirrg001** [comment]
@ErisDS I wasn't able to find a note about it. In LTS we were using the maintenance mode to force db migrations in the background, because the logic was part of Ghost core. We had a clear use case.

But as @riverar said, it's still in [our docs](https://docs.ghost.org/docs/config#section-maintenance-mode). Either we made a mistake in the config files or we forgot to remove it from our docs. 

@riverar What was the reason you wanted to enable the maintenance mode for your blog frontend/site? We are always interested in use cases :)

**Comment by riverar** [comment]
I wanted to take the site down while I iterated on my theme, without incurring a search engine cache hit. But it's not clear if it applied to /admin, so probably not a valid use case.

**Comment by kirrg001** [comment]
>But it's not clear if it applied to /admin

It does currently apply to the admin section.

**Comment by kirrg001** [comment]
@riverar You probably want to make your blog private?

https://blog.ghost.org/private-blogs/

**Comment by riverar** [comment]
That would get cached by search engines, and potentially impact search results, when my intention was to be temporary. 😢 (I did end up using this feature.)

**Comment by NathanBeddoeWebDev** [comment]
Would you guys mind if I have a go at this?

**Comment by kirrg001** [comment]
I have updated the docs for now.

If somebody has an use case for which he needs to be able to configure the maintenance mode, please raise a topic in our [forum](https://forum.ghost.org).

Closing for now.
