### ISSUE TITLE
Unable to view typing tools in Markdown

### ISSUE THREAD

**Issue by shaunkuan** [TryGhost/Ghost#9730]
In the create post section, I am unable to view the toolbar at the bottom. I have tried using different browsers - safari, Chrome etc and also gave the desktop app a shot, to no avail. Any advice?

<img width="1143" alt="screen shot 2018-07-12 at 12 13 03 am" src="https://user-images.githubusercontent.com/41122781/42585599-a6ee063c-8568-11e8-9356-d993840bcf12.png">

**Comment by kevinansfield** [comment]
Hey @shaunkuan 👋 This is most likely because the font-awesome request is failing for some reason, maybe a browser extension or some sort of firewall on your network? You will likely see an error in the DevTools console if you open that (right-click and select "Inspect element").

Closing this issue as it's environment-specific rather than a bug in Ghost. Please move any further discussion to [our forum](https://forum.ghost.org) 🙂
