### ISSUE TITLE
iOS Typing new story doesn't work with shaped based swype keyboards

### ISSUE THREAD

**Issue by dabbers** [TryGhost/Ghost#9738]
### Issue Summary
Using iOS in Safari (or Edge or anything) typing only works with 1 letter at a time. Using any shape keyboards causes the content to not include any extra letters than the first letter. Shape keyboard meaning you drag your fingers to draw the words instead of pecking each letter individually.

I'm using SwiftKey keyboard on iOS 11.4 (iPhone 8+)

### To Reproduce

1. Create a new content
2. Using SiftKey keyboard, drag your finger around to write a word (Hello).
3. Only the H is registered.

This behavior makes it incredibly difficult to type properly. 

### Technical details:

* Ghost Version: 1.24.7
* Node Version: -
* Browser/OS: Safari, Edge iOS 11.4 (iPhone 8+)
* Database: ?

**Comment by kevinansfield** [comment]
@dabbers custom keyboards that inject words rather than characters are not supported on mobile, it's a known limitation with [CodeMirror](https://github.com/codemirror/CodeMirror) that powers the markdown editor. You should have more luck with the [new Koenig editor](https://forum.ghost.org/t/koenig-editor-beta-release/1284) but mobile support is not a focus right now so the experience may not be perfect.
