### ISSUE TITLE
ID names of HTML elements (headings) are missing special characters

### ISSUE THREAD

**Issue by freddy8787** [TryGhost/Ghost#9740]
Ghost generated ID names strip some special characters. This is not exact bug, but space for improvements.

Example: in Slovak language i have the heading "Špecifikácia" and ID is generated as id="pecifikcia". Special characters are removed, but much better is to replace this characters, like id="specifikacia".
If i use it in URL it is more readable for users.

Also the spaces are stripped and i think better behaviour is to replace space for dash.

Another example: `<h2 id="nkupnproces">Nákupný proces</h2>`
Better solution: `<h2 id="nakupny-proces">Nákupný proces</h2>`

Ghost Version: 1.22.4

**Comment by kevinansfield** [comment]
@freddy8787 the heading IDs are like this for backwards compatibility reasons, if we change it then suddenly everyone's deep-links can stop working any time a post is updated.

With the [new editor](https://forum.ghost.org/t/koenig-editor-beta-release/1284) the ID behaviour has been improved to use `-` rather than removing spaces for rich-text headings, if however you're using the Markdown card then the old behaviour will still be present for said backwards-compatibility.

**Comment by meleu** [comment]
@freddy8787 
I've posted a "feature request" in the forums that, if implemented, can probably solve this issue.
You can check it here:
https://forum.ghost.org/t/extended-markdown-card-in-the-editor/11146

**Comment by adamkudrna** [comment]
Hello, I'd like to reopen the discussion here because I have the exactly same problem. I'm Czech and just like in Slovak, my language uses a lot of accents like `á`, `ě`, `ř`, etc.

My heading IDs look like this:

Source text: [`Rozšíření předávaného obsahu s @forward`](https://frontend.garden/co-jsou-sass-moduly-a-jak-use-a-forward-zlepsi-vas-kod/#roz-en-p-ed-van-ho-obsahu-s-forward)
Expected result: `#rozsireni-predavaneho-obsahu-s-forward`
Actual result: `#roz-en-p-ed-van-ho-obsahu-s-forward`

Current algorithm makes my IDs very messy—and I really wish my links to be readable. I love Ghost but this is a big dark stain on my otherwise excellent experience with it.

I understand the backwards-compatibility reason, but I don't believe a bad decision in past should bother everyone till the end of days of Ghost.

So I'd like to suggest **implementing the fix as an opt-in feature**, eg. through the Labs admin page. This way it only affects Ghost sites whose owners _want_ to have nice heading IDs—like @freddy8787 or me. The [translation table](https://github.com/visionappscz/bootstrap-ui/blob/master/src/js/slugger.js#L13) should be quite simple:

```js
const from = 'ãàáäâåčçďẽèéëêìíïîñõòóöôřšťùúüûýž·/_,:;';
const to   = 'aaaaaaccdeeeeeiiiinooooorstuuuuyz------';
```

**Comment by meleu** [comment]
> I love Ghost but this is a big dark stain on my otherwise excellent experience with it.

that's my feeling too. :(

**Comment by adamkudrna** [comment]
@matthanley ❤️

**Comment by adamkudrna** [comment]
@kevinansfield Wow, can't wait to try it out! Thank you, Kevin.
