### ISSUE TITLE
Preview URLs are being indexed by search engines

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9749]
Originally raised on the forum: https://forum.ghost.org/t/preview-article-links-ranking-in-google-possible-to-add-no-index-tag/2123

### To Reproduce

I'm not sure what the reproduction case for this is, in terms of how Google is finding the urls. It could be to do with Disqus and Google Analytics loading on the preview pages? These pages should definitely not be appearing in the sitemap (and they aren't).

Either way, we should prevent indexing on these pages. 

### Technical details:

* Ghost Version: 1.24

**Comment by vikaspotluri123** [comment]
Given robots.txt is only applicable for the domain root (i.e. `your.domain/robots.txt`) and not subdirectories (i.e. `your.domain/blog/robots.txt`) would the fix also require the preview url to have the meta noindex tag?

**Comment by jloh** [comment]
`robots.txt` applies to anything on the FQDN (ie even `your.domain/blog/`).

Using the meta tag or `X-Robots-Tag` http header is the best bet (https://developers.google.com/search/reference/robots_meta_tag):

```html
<meta name="robots" content="noindex" />
```

**Comment by vikaspotluri123** [comment]
> robots.txt applies to anything on the FQDN (ie even your.domain/blog/).

I think there's a communication issue - What I meant is `your.domain/blog/robots.txt` isn't a valid location for a robots.txt file since it's not in the domain root (i.e. `your.domain/robots.txt`). Since Ghost can be installed in a subdirectory (i.e `/blog/`), the Ghost robots.txt file might not always be used, so we would have to revert to something else, like the meta tag 👍

**Comment by ws-lancelot** [comment]
Because the preview links live on the ghost domain it's not possible for customers to add anything to them or their robots.txt (to my knowledge). I'd imagine this is a widespread problem effecting many customers. Do we know when a there might be a solution for this?

**Comment by vikaspotluri123** [comment]
@ws-lancelot can't give an ETA because I'm not sure what the plan is, but I would like to reiterate (in case you weren't aware) preview URLs will not be found unless you explicitly link to them - Search engines only index pages that are linked to.

For example, all of your posts, tags, pages and authors are indexed because Ghost links to them via the robots.txt sitemap, but your preview links aren't in that sitemap.

If you have a post that says

`Calling all beta testers: check out my new layout at https://super.blog/p/{id}`, then the indexer will find the link and add its index becuase it works!

**Comment by ws-lancelot** [comment]
Other people are linking to the staging site and as a result it's probably crawled regularly. We can try keep links on our own site at bay but have less control over other sites.
