### ISSUE TITLE
Lots of expired access tokens prevent server from starting

### ISSUE THREAD

**Issue by rik** [TryGhost/Ghost#9798]
### Issue Summary
When re-starting a server with a lot of expired access tokens, trying to destroy all of them can prevent the server from starting. We ran into knex timeout issues or memory issues.

### To Reproduce

1. Generate a lot of expired access tokens (we had around 38680).
1. Restart your server

### Expected results
Server smoothly comes online.

### Actual results
Server takes a loooooong time or crashes.

### Details from our debugging session
We saw one DELETE SQL query per token. We believe those were all wrap in a transaction so when the server crashes, the transaction is rolled back. And next attempt at starting up the server will probably fail again.

https://github.com/TryGhost/Ghost/blob/master/core/server/services/auth/oauth.js#L129 is where those queries are ran at startup. I'd suggest running that in a scheduled task or turn it into one query.

### Technical details:

* Ghost Version: 0.11.12
* Node Version: 6.14

**Comment by rik** [comment]
The knux error message we were seeing was `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`.

This might be the root cause for https://github.com/TryGhost/Ghost/issues/7346 or https://forum.ghost.org/t/back-with-the-ghost-sites-failing-to-load-following-an-aws-rds-maintenance-backup-window/1983

**Comment by rik** [comment]
@kirrg001 I've noticed the "needs info" tag. What kind of info would you like me to provide?

**Comment by kirrg001** [comment]
Hey @rik - there is nothing you can do right now - thanks for asking :)  

I need to find some time to reproduce this - probably beginning of next week!

**Comment by allouis** [comment]
Hey @rik :wave:

I've tried to reproduce this locally using both SQLite & MySQL and 50000 expired access tokens, but it's not causing any issues for me.

I noticed you're running ghost 0.11.12 - Could you please update to the latest and let us know if you're still having the issue? Thanks!

**Comment by rik** [comment]
We currently have no plans to migrate to 1.0 as we need to schedule some time to do that and 0.11 seems to still be the LTS version.

That being said, the underlying code seems to be the same in both versions so it should behave in a similar way.
https://github.com/TryGhost/Ghost/blob/lts/core/server/models/base/token.js#L33
https://github.com/TryGhost/Ghost/blob/master/core/server/models/base/token.js#L33

**Comment by rik** [comment]
We've seen this bug in production where the DB is not on the same system as the application, introducing a lot of latency. I suspect trying to reproduce locally where latency is less than 1ms is not representative in this case.

Could we please re-open to try and reproduce in a system where app and DB are separated?

**Comment by andrefecto** [comment]
Having this issue using Ghost behind an nginx reverse proxy. I know the proxy isn't the issue because as soon as I told the proxy to wait longer for a response from the upstream client (ghost) I was able to see the knex timeout 500 error. Only fix is to restart the container which I assume clears all the hanging connections. I think what was causing all the hanging connection is I use Google Stackdriver Uptime monitoring to alert when the site is down. If the site goes down (which it does every day for a restart) Stackdriver will try to access the site looking for a response (pretty quickly, about once a minute). This action is what I think was filling the connection pool. I am running Ghost 3.7.0 with sqlite3. Any help on getting this to not happen would be great because I would like to have uptime monitoring on my site.

**Comment by kevinansfield** [comment]
@andrefecto sounds like you have a different issue to the one you're replying to (tokens are not used in 3.7.0). I'd suggest posting on [our forum](https://forum.ghost.org) where you can get community support for self-hosted install issues 🙂
