### ISSUE TITLE
AMP post absolute URL is not so

### ISSUE THREAD

**Issue by tucoinfo** [TryGhost/Ghost#9859]
Hello, I'm running 1.24.8 and I don't see anything related in more recent Release Notes nor Issues.

Ghost is installed in a subfolder https://mywebsite.com/blog/
Add a link to an absolute URL like `[somewhere](/somepage.html)` in some post
Non-AMP version renders correctly https://mywebsite.com/somepage.html
On the AMP version it renders relative like https://mywebsite.com/blog/somepage.html (404)

Anyone else noticed this behaviour?

**Comment by gargol** [comment]
Hey :wave: @tucoinfo the latest version is at [2.1.1](https://github.com/TryGhost/Ghost/releases/tag/2.1.1) (1.24.8 is full version behind that). Did you try reproducing this issue in our latest version or in latest of your major [1.25.5](https://github.com/TryGhost/Ghost/releases/tag/1.25.5)?

**Comment by tucoinfo** [comment]
Have done so.
Clean dev install of v1.25.5 (Casper v2.4.2): same AMP issue
Clean dev install of v2.1.2 (Casper v2.6.2): same AMP issue

**Comment by tucoinfo** [comment]
Further to the above the discrepancy seems to be in `Service.utils.makeAbsoluteUrls` where '/' is considered relative to siteUrl as opposed to the website root folder.

I'm not in the business of sparking RFC discussions and will hard code my main site links. However I do think it is worth noting that AMP and non-AMP just don't give the same expected result.

**Comment by gargol** [comment]
@tucoinfo thanks for the info, I'll look into it!

**Comment by gargol** [comment]
@tucoinfo are you running the Ghost instance behind an http server like Apache or Nginx? How does your configuration look like to support this structure:
> subfolder https://mywebsite.com/blog/

**Comment by tucoinfo** [comment]
Hi @gargol both the out of the box localhost development and the production server have `"url": "https://mywebsite.com/blog/"` configured. Nothing special otherwise.

Production is nGinx with a basic location in the main site's server block. Ghost works fine otherwise.

```
location ^~ /blog/ {
            alias    /pathname/mywebsite.com/ghost/;

            add_header X-XSS-Protection "1; mode=block";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-Content-Type-Options nosniff;

            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass       http://127.0.0.1:2368;
}
```

**Comment by gargol** [comment]
Was trying to reproduce this issue on the local environment today with no luck. But while testing different configurations found some strange behavior in the way URLs are generated for APM and non-AMP pages.
Had a blog set up locally running behind `http://ghost.local/blog` with nginx configuration that @tucoinfo provided above. In config.development.js have change `url` to following:
```
"url": "http://ghost.local/blog",
```
The default post `Organising your content` was set with this link to Apps & Integrations:
![admin_url](https://user-images.githubusercontent.com/675397/45630780-b1c46180-ba99-11e8-9a18-634ef2023e8e.png)

When visiting this post in regular mode under http://ghost.local/blog/organising-content/ the url (probably correctly) was pointing to unexisting page http://ghost.local/apps-integrations/:
![regular_wrong_url](https://user-images.githubusercontent.com/675397/45630854-e3d5c380-ba99-11e8-94d2-64dafb793cc6.png)

But the AMP version was modifying this URL http://ghost.local/blog/apps-integrations/:
![amp_correct_url](https://user-images.githubusercontent.com/675397/45630887-f5b76680-ba99-11e8-885d-4eefbf54f70d.png)

The main difference between how this post is fetched is for AMP pages and regular fetch is following. For AMP `makeAbsoluteUrls` is always executed: https://github.com/TryGhost/Ghost/blob/master/core/server/apps/amp/lib/helpers/amp_content.js#L127
and for regulart posts even though  `absolute_url` option is present here: https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L42 it's never being passed into query itself https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L60 , thus `makeAbsoluteUrls` https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L460 doesn't get called.

@kirrg001 could you please provide more context for this behavior?

**Comment by kirrg001** [comment]
> Was trying to reproduce this issue on the local environment today with no luck

If you were not able to reproduce, i'd suggest to close this issue? I cannot find clear steps of how to reproduce this report. 

> When visiting this post in regular mode under http://ghost.local/blog/organising-content/ the url (probably correctly) was pointing to unexisting page http://ghost.local/apps-integrations/:

In this case it's just "lucky" that the url is correct for the amp page. Imagine you setup your blog on a subdirectory and you change the permalink structure from `/:slug/` to `/:year/:slug/`, the amp page won't output the correct absolute post url, because the links are **hardcoded** in the html/mobiledoc content.

> But the AMP version was modifying this URL http://ghost.local/blog/apps-integrations/:

Yeah. AMP is a **generated** page. AMP makes absolute urls because of image optimisations, [see](https://github.com/TryGhost/Ghost/commit/93ee19f36e6e18bee3f298976b26f2f6e4761178). Same reasoning as above.

> and for regulart posts even though absolute_url option is present here: https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L42 it's never being passed 

`absolute_urls` was an **optional** feature added [here](https://github.com/TryGhost/Ghost/commit/c9b8ddde4be0c757dece3b6f2485481b319c3bcb). You will only receive absolute urls when you tell Ghost. 

I hope that answers your question, if not we can continue in slack 🙂I guess your questions is not really related to this issue or maybe it is (?) and it's just not described good to enough?

**Comment by gargol** [comment]
@kirrg001 thanks for the explanation :star: Yeah, my questions were related to the observations that I've made during code exploration. It all makes sense to me now. 

@tucoinfo wasn't able to reproduce your bug unfortunatelly. Could you maybe provide a step by step guide on reproducing the bug. Maybe I'm just missing some step when trying to replicate it locally. Thanks!

**Comment by tucoinfo** [comment]
@gargol I've done another fresh install:

```
>npm install -g ghost-cli@latest
>ghost version
Ghost-CLI version: 1.9.4
>ghost install local
...Ghost was installed successfully!
>ghost version
Ghost-CLI version: 1.9.4
Ghost version: 2.1.3 (at F:\eclipse-workspace\cdlrv3_ghost2)
>ghost config "url" "http://localhost:2368/blog/"
Found a development config but not a production config, running in development mode instead
Successfully set 'url' to 'http://localhost:2368/blog/'
>ghost restart
```
Visit http://localhost:2368/blog/ghost/ and set user.
Edit post Welcome to Ghost, select "getting started", CTRL+K, enter forward slash, publish, copy link locations.
Non-AMP version link is http://localhost:2368/
AMP version link is http://localhost:2368/blog/

**Comment by kirrg001** [comment]
@gargol

**Comment by gargol** [comment]
Added reminder to go through this next Monday. Sorry for delay @tucoinfo

**Comment by gargol** [comment]
@tucoinfo, after analyzing the last example I came to the conclusion that this is a bit weird but expected behavior. The reason behind why regular post point's to http://localhost:2368/ and the AMP one to http://localhost:2368/blog/ is that amp page has to always use absolute URLs (as explained [above](https://github.com/TryGhost/Ghost/issues/9859#issuecomment-422073327)). The absolute URL in a blog configured with `http://localhost:2368/blog/` value will always start with `/blog/` so there's no way to point to `http://localhost:2368/` from the post other than using the url itself. 

As a side note, once currently worked on [API v2](https://github.com/TryGhost/Ghost/issues/9866) is out, all urls will be returned as absolute by default (same behavior as for AMP at the moment).

Closing the issue for now. Let me know if there's anything more to clarify, happy to help :smiley:
