### ISSUE TITLE
Relative links 404 after changing custom routes

### ISSUE THREAD

**Issue by nickpunt** [TryGhost/Ghost#9873]
### Issue Summary
If a user ever changes routes (say going from `/` to `/blog/`), all existing posts that link to other internal posts via relative link (e.g. `/my-post-from-last-year/`) will 404. 

There are two use cases this affects:

1. **Updating a site with new routes** - Any existing sites that move their content to different routes are affected. For instance, a user with an existing blog available at `/` may want to move their posts under `/blog/`, or users may want to change a regular post (`/a-review-i-wrote`) into a special type of post (`/reviews/a-review-i-wrote`). This makes the CMS more brittle to ways sites can evolve.

2. **Creating a fresh Ghost blog with custom routes** - The default posts created when Ghost is initialized use relative URLs (e.g. `/apps-integrations/`). When adding custom routes (e.g. making posts appear under `/blog/`), these resolve to 404s. This can be super confusing when setting up and troubleshooting custom routes, which is already a confusing process. 

For example, one default post links to `/apps-integrations/`, which the Koenig editor interprets as the following, despite routes for that page being to `/blog/`:

<img width="678" alt="screen shot 2018-09-13 at 9 03 11 pm" src="https://user-images.githubusercontent.com/88428/45529268-1f6e4600-b799-11e8-932f-bf511df01ed0.png">

### To Reproduce

1. Setup a new ghost blog
2. Update routes to have blog posts appear under `/blog/`
3. View blog's default content and click links that go from one blog post to another

Expectation: links will route to the appropriate place based on type of link.
Actual: 404

### Technical details:

* Ghost Version: 2.1.2 (development mode)
* Node Version: 8.11.3
* Browser/OS: Safari, MacOS High Sierra 
* Database: default

**Comment by kirrg001** [comment]
IMO expected behaviour. 

Ghost cannot iterate over all posts and update links, because it has no persistent information what the url structure was before moving posts to a new location. Even if Ghost would remember this information, i don't think this is a task Ghost should take over 🤔 

If you are using links in a blog post and you change where these linked posts live, then you have to setup redirects. Therefor you could use [our redirects feature](https://docs.ghost.org/docs/redirects). It's very similar to: if you link an external url and the url changes, the target external blog should setup redirects?

We are open for thoughts or suggestions - if you think Ghost should solve this or if you would like to discuss/talk about this, feel free to raise a topic [in our forum.](https://forum.ghost.org/) 🙂
