### ISSUE TITLE
PSM scroll broken

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9925]
On latest Pro, in Safari:

- Open an existing short post or start a new post
  - the problem is only apparent when the primary scrollable area is shorter than the PSM
- Open the PSM
- Try to scroll down
- [Nothing happens]

Then resize the viewport, try again, and now it scrolls as normal

No errors in console

**Comment by kevinansfield** [comment]
@JohnONolan is this reproducible for you with every post? I can't reproduce at all so far

**Comment by kevinansfield** [comment]
Managed to reproduce - it's only apparent when the post length is shorter than the window height. Updated the reproduction steps

**Comment by lunaticmonk** [comment]
@kevinansfield @JohnONolan What is the expected behaviour here? I did not get the reproduction step saying "Nothing happens". Does it mean that the blog post after opening the PSM should be able to scroll down? or the PSM should scroll down itself?

**Comment by eunicode** [comment]
I'm also interested in contributing, but can't reproduce this, perhaps because I'm on a laptop with dimensions where the PSM is always longer than the browser viewport (or alternatively, the viewport is always shorter than the PSM).

Or, like lunaticmonk said, is the problem that we should still be able to scroll down the _blog post_ even if the PSM is open?

**Comment by kevinansfield** [comment]
The problem is that the post settings menu isn’t scrollable. Reproduction isn’t consistent, I found that it was necessary to have a window that was shorter than the default height of the PSM for the problem to present itself. Again the problem inly presents itself in Safari rather than Chrome or Firefox.

**Comment by eunicode** [comment]
@kevinansfield I'm sorry, perhaps I'm missing something here. I am on Safari, and my window is shorter than the default height of the post settings menu. However, the post settings menu scrolls just fine for me. I have included a link of a [screen recording](http://recordit.co/RK8UHQwmCN) displaying my experience.

**Comment by rafaelmagu** [comment]
I can reproduce this problem every time I open a new post or edit an existing post after upgrading to the latest 2.x (from 1.x) a couple of weeks ago. As soon as the viewport is resized, scrolling starts working. The cutoff for the PSM panel on my screen is the top of the Meta Data card.

**Comment by tjgriffi** [comment]
Good evening, Is this issue currently being tackled  Because if not I'd like to give it a go. @JohnONolan @eunicode

**Comment by eunicode** [comment]
@tjgriffi I'm not working on this, so please feel free to give it a go!

**Comment by kscott5** [comment]
Hello all, 

don't forget your individual device resolution or the effects of CSS viewport. @eunicode.

It helps with a screen capture or video today.
